---
permalink: sm-storage/access-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, access volumes 
summary: アクセスボリュームは、ストレージアレイの工場出荷時に設定されたボリュームで、ホストI/O接続を介したストレージアレイおよびホストとの通信に使用されます。アクセスボリュームには論理ユニット番号（LUN）が必要です。 
---
= アクセスボリューム
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アクセスボリュームは、ストレージアレイの工場出荷時に設定されたボリュームで、ホストI/O接続を介したストレージアレイおよびホストとの通信に使用されます。アクセスボリュームには論理ユニット番号（LUN）が必要です。

アクセスボリュームは次の2つのケースで使用されます。

* *ホストの自動作成*- Host Context Agent（HCA）ユーティリティで、ホストの自動作成でホスト情報（名前、ポート、ホストタイプ）をSystem Managerにプッシュするために使用されます。
* *インバンド管理*--インバンド接続でストレージアレイを管理するために使用されるアクセスボリューム。これは、ストレージアレイをコマンドラインインターフェイス（CLI）で管理する場合にのみ可能です。
+
[NOTE]
====
インバンド管理は、EF600またはEF300ストレージシステムに対しては使用できません。

====


アクセスボリュームは、ホストに初めてボリュームを割り当てるときに自動的に作成されます。たとえば、Volume_1とVolume_2をホストに割り当てた場合、その割り当ての結果を表示すると、3つのボリューム（Volume_1、Volume_2、およびAccess）が表示されます。

ホストを自動的に作成しない場合やCLIを使用してストレージアレイをインバンドで管理しない場合は、アクセスボリュームが不要であるため、アクセスボリュームを削除してLUNを解放できます。この処理を実行すると、ボリュームとLUNの割り当てが解除されるだけでなく、ホストへのインバンド管理接続もすべて削除されます。
