---
permalink: sm-storage/add-member-volumes-to-a-snapshot-consistency-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, add, member, volume, snapshot consistency group 
summary: 既存のSnapshot整合性グループに新しいメンバーボリュームを追加できます。新しいメンバーボリュームを追加する場合、そのメンバーボリュームの容量もリザーブする必要があります。 
---
= Snapshot整合性グループにメンバーボリュームを追加します
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
既存のSnapshot整合性グループに新しいメンバーボリュームを追加できます。新しいメンバーボリュームを追加する場合、そのメンバーボリュームの容量もリザーブする必要があります。

.作業を開始する前に
* メンバーボリュームが最適lである必要があります。
* Snapshot整合性グループのボリューム数が、許容される最大ボリューム数（設定で定義）を下回っている必要があります。
* 各リザーブ容量ボリュームのData Assurance（DA）とセキュリティの設定が、関連付けられているメンバーボリュームと同じである必要があります。


.このタスクについて
Snapshot整合性グループには、標準ボリュームまたはシンボリュームを追加できます。ベースボリュームはプールまたはボリュームグループのどちらかに配置できます。

.手順
. メニューを選択します。Storage [Snapshots]。
. スナップショット・コンシステンシ・グループ*タブを選択します
+
ストレージアレイに関連付けられているすべてのSnapshot整合性グループが表示されます。

. 変更するSnapshot整合性グループを選択し、*メンバーの追加*をクリックします。
+
メンバーの追加（Add Members）ダイアログボックスが表示されます。

. 追加するメンバーボリュームを選択し、*次へ*をクリックします。
+
Reserve Capacityステップが表示されます。ボリューム候補表には、指定したリザーブ容量に対応する候補だけが表示されます。

. スピンボックスを使用して、メンバーボリュームにリザーブ容量を割り当てます。次のいずれかを実行します。
+
** *デフォルト設定を受け入れます。*
+
メンバーボリュームのリザーブ容量を割り当てる推奨されるオプションであり、デフォルトの設定でリザーブ容量を割り当てます。

** *データストレージのニーズに合わせて独自の設定でリザーブ容量を割り当てることができます。*
+
デフォルトのリザーブ容量設定を変更した場合は、*候補の更新*をクリックして、指定したリザーブ容量の候補リストを更新します。

+
次のガイドラインに従ってリザーブ容量を割り当てます。

+
*** リザーブ容量のデフォルト設定はベースボリュームの容量の40%で、通常はこの容量で十分です。
*** 必要な容量は、ボリュームに対するI/O書き込みの頻度とサイズ、およびSnapshotイメージを収集する数と期間によって異なります。




. [完了]をクリックして、メンバーボリュームを追加します。

