---
permalink: sm-storage/assign-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, assign volumes 
summary: I/O処理に使用できるように、ボリュームをホストまたはホストクラスタに割り当てる必要があります。これにより、ストレージアレイ内の1つ以上のボリュームへのアクセスがホストまたはホストクラスタに許可されます。 
---
= ホストにボリュームを割り当てます
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I/O処理に使用できるように、ボリュームをホストまたはホストクラスタに割り当てる必要があります。これにより、ストレージアレイ内の1つ以上のボリュームへのアクセスがホストまたはホストクラスタに許可されます。

.このタスクについて
ホストにボリュームを割り当てる際は、次のガイドラインに注意してください。

* ボリュームは一度に 1 つのホストまたはホストクラスタにのみ割り当てることができます。
* 割り当てられたボリュームは、ストレージアレイのコントローラ間で共有されます。
* あるホストまたはホストクラスタからボリュームへのアクセスに、同じ論理ユニット番号（LUN）を複数回使用することはできません。一意のLUNを使用する必要があります。
* 新しいボリュームグループでは、すべてのボリュームが作成されて初期化されるまでホストに割り当てると、ボリュームの初期化時間が短縮されます。ボリュームグループに関連付けられているボリュームをマッピングすると、_ALL_VOLUMESを使用すると、初期化の速度が遅くなります。初期化の進捗状況は、ホーム[処理実行中]メニューから確認できます。


次の場合、ボリュームの割り当ては失敗します。

* すべてのボリュームが割り当てられている。
* ボリュームはすでに別のホストまたはホストクラスタに割り当てられています。


次の場合、ボリュームを割り当てることはできません。

* 有効なホストまたはホストクラスタが存在しません。
* ホストポート識別子がホストに対して定義されていない。
* すべてのボリューム割り当てが定義されている。


このタスクでは、未割り当てのボリュームはすべて表示されますが、ホストがData Assurance（DA）対応かどうかで処理は次のように異なります。

* DA 対応ホストの場合は、 DA 有効、 DA 無効のどちらのボリュームでも選択できます。
* DA 対応でないホストで DA が有効なボリュームを選択した場合、ボリュームをホストに割り当てる前にボリュームの DA を自動的に無効にする必要があるという警告が表示されます。


.手順
. メニューから「 Storage [Hosts] 」を選択します。
. ボリュームを割り当てるホストまたはホストクラスタを選択し、 * ボリュームの割り当て * をクリックします。
+
ダイアログボックスに割り当て可能なすべてのボリュームが表示されます。任意の列をソートしたり、 * Filter * ボックスに何かを入力すると、特定のボリュームを簡単に見つけることができます。

. 割り当てる各ボリュームの横にあるチェックボックスを選択するか、テーブルヘッダーにあるチェックボックスを選択してすべてのボリュームを選択します。
. [*Assign*] をクリックして、操作を完了します。


.結果
ホストまたはホストクラスタへのボリュームの割り当てが完了すると、次の処理が実行されます。

* 割り当てられたボリュームに次に使用可能な LUN 番号が受信されます。ホストはこの LUN 番号を使用してボリュームにアクセスします。
* ホストに関連付けられているボリュームの一覧にユーザが指定したボリューム名が表示されます。該当する場合、ホストに関連付けられているボリュームの一覧には、工場出荷時に設定されたアクセスボリュームも表示されます。

