---
permalink: sm-storage/automatic-versus-manual-pool-creation.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, automatic, manual, pool 
summary: プールを自動または手動で作成して物理ストレージをグループ化し、必要に応じて動的に割り当てることができます。プールの作成時に物理ドライブを追加できます。 
---
= プールの自動作成と手動作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
プールを自動または手動で作成して物理ストレージをグループ化し、必要に応じて動的に割り当てることができます。プールの作成時に物理ドライブを追加できます。



== 自動作成

System Managerがストレージアレイ内に未割り当て容量を検出すると、プールの自動作成が開始されます。未割り当て容量が検出されると、System Managerは1つ以上のプールを作成するか、既存のプールに未割り当て容量を追加するか、またはその両方を実行するように求めます。

プールの自動作成は、次のいずれかの条件に該当する場合に実行されます。

* プールがストレージアレイに存在せず、新しいプールの作成に十分なドライブがない。
* 少なくとも1つのプールを含むストレージアレイに新しいドライブが追加される。


プール内の各ドライブは、タイプ（HDDまたはSSD）が同じで容量が同等である必要があります。次のタスクを実行するように求められます。

* タイプが十分な数のドライブがある場合は、単一のプールを作成する。
* 未割り当て容量が異なるドライブタイプで構成されている場合は、複数のプールを作成する。
* ストレージアレイにすでにプールが定義されている場合は、既存のプールにドライブを追加し、同じタイプの新しいドライブをプールに追加する。
* タイプの異なる複数のドライブを追加した場合は、ドライブタイプが同じドライブを既存のプールに追加し、別のドライブタイプのドライブを使用して別のプールを作成する。




== 手動作成

最適な構成を自動作成で判断できない場合は、プールを手動で作成できます。この状況は、次のいずれかの理由で発生する可能性があります。

* 新しいドライブが複数のプールに追加される可能性があります。
* 1つ以上の新しいプールの候補で、シェルフ損失の保護またはドロワー損失の保護を使用できる。
* 1つ以上の現在のプールの候補で、シェルフ損失の保護またはドロワー損失の保護のステータスを維持できない。


ストレージアレイ上に複数のアプリケーションがあり、同じドライブリソースにアクセスしないようにする場合に、プールを手動で作成することもできます。この場合、1つ以上のアプリケーション用に小規模なプールを手動で作成することを検討してください。データを分散するための多数のボリュームを含む大規模なプールにワークロードを割り当てるのではなく、1~2個のボリュームだけを割り当てることができます。特定のアプリケーションのワークロード専用の個別のプールを手動で作成すると、ストレージアレイの処理をより迅速に実行でき、競合が軽減されます。
