---
permalink: sm-storage/automatic-versus-manual-host-creation.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, automatic, manual, host, 
summary: ホストの作成は、ストレージアレイが接続されているホストを認識して、ボリュームへのI/Oアクセスを許可するために必要な手順の1つです。ホストは自動的に作成することも手動で作成することもできます。 
---
= ホストの自動作成と手動作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ホストの作成は、ストレージアレイが接続されているホストを認識して、ボリュームへのI/Oアクセスを許可するために必要な手順の1つです。ホストは自動的に作成することも手動で作成することもできます。



== 自動作成

（NVMe-oFではなく）SCSIベースのホストの自動作成は、Host Context Agent（HCA）によって開始されます。HCA は、ストレージアレイに接続されている各ホストにインストール可能なユーティリティです。HCA がインストールされている各ホストは、 I/O パスを経由してストレージアレイコントローラにホストの設定情報をプッシュします。コントローラは、ホスト情報に基づいてホストと関連するホストポートを自動的に作成し、ホストタイプを設定します。必要に応じて、System Managerを使用してホスト設定に加えた変更を行うことができます。

HCAの自動検出が実行されると、ホストは自動的にホストページに次の属性とともに表示されます。

* ホストのシステム名から取得されたホスト名。
* ホストに関連付けられたホストポート識別子。
* ホストのホストオペレーティングシステムタイプ。


ホストはスタンドアロンホストとして作成されます。 HCA では、ホストクラスタの作成やホストクラスタへの追加が自動的に行われることはありません。



== 手動作成

次のいずれかの理由でホストを手動で作成することが必要になる場合があります。

. ホストにHCAユーティリティをインストールしないように選択した。
. ストレージアレイコントローラによって検出されたホストポート識別子がホストに正しく関連付けられていることを確認する。


ホストの手動作成時には、ホストポート識別子をリストから選択するか、または手動で入力して関連付けます。ホストの作成後、ボリュームへのアクセスを共有する場合は、ボリュームをホストに割り当てたり、ホストクラスタに追加したりできます。
