---
permalink: sm-storage/cancel-snapshot-image-rollback.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, cancel, snapshot, image, rollback 
summary: 実行中のアクティブなロールバック（データのアクティブなコピー）、（リソースの開始を待機している保留キューで）保留中のロールバック、またはエラーが原因で一時停止されたロールバックをキャンセルできます。 
---
= Snapshotイメージのロールバックをキャンセルします
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
実行中のアクティブなロールバック（データのアクティブなコピー）、（リソースの開始を待機している保留キューで）保留中のロールバック、またはエラーが原因で一時停止されたロールバックをキャンセルできます。

.このタスクについて
実行中のロールバック処理をキャンセルすると、ベースボリュームが使用できない状態に戻り、「失敗」と表示されます。そのため、ベースボリュームの内容をリストアするためのリカバリオプションがある場合にのみロールバック処理をキャンセルすることを検討してください。

[NOTE]
====
Snapshotグループに含まれている1つ以上のSnapshotイメージが自動的にパージされた場合は、ロールバック処理に使用されるSnapshotイメージを今後のロールバックで使用できなくなる可能性があります。

====
.手順
. メニューを選択します。Storage [Snapshots]。
. スナップショットイメージ*タブをクリックします。
. アクティブまたは一時停止中のロールバックを選択し、メニューからロールバック[キャンセル]を選択します。
+
[ロールバックのキャンセルの確認]ダイアログボックスが表示されます。

. 「 * はい * 」をクリックして確定します。


.結果
System Managerがロールバック処理を停止します。ベースボリュームは使用可能ですが、含まれているデータの整合性が確保されない、またはデータが維持されない場合があります

.完了後
ロールバック処理をキャンセルしたら、次のいずれかの操作を実行する必要があります。

* ベースボリュームの内容を再初期化します。
* 新しいロールバック処理を実行し、ロールバックのキャンセル処理で使用されたのと同じSnapshotイメージまたは別のSnapshotイメージを使用してベースボリュームをリストアします。

