---
permalink: sm-storage/capacity-for-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, capacity, volumes, 
summary: ストレージアレイ内のドライブは、データに対して物理ストレージ容量を提供します。データの格納を開始する前に、プールまたはボリュームグループと呼ばれる論理コンポーネントに割り当て容量を設定する必要があります。これらのストレージオブジェクトを使用して、ストレージアレイのデータを設定、格納、メンテナンス、および保持できます。 
---
= ボリュームの容量の割り当て方法
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイ内のドライブは、データに対して物理ストレージ容量を提供します。データの格納を開始する前に、プールまたはボリュームグループと呼ばれる論理コンポーネントに割り当て容量を設定する必要があります。これらのストレージオブジェクトを使用して、ストレージアレイのデータを設定、格納、メンテナンス、および保持できます。



== 容量を使用したボリュームの作成と拡張

プールまたはボリュームグループ内の未割り当て容量または空き容量からボリュームを作成できます。

* 未割り当て容量からボリュームを作成する場合は、プールまたはボリュームグループとボリュームを同時に作成できます。
* 空き容量からボリュームを作成する場合は、既存のプールまたはボリュームグループに追加のボリュームを作成します。


ボリュームの容量を拡張したら、それに応じてファイルシステムのサイズを手動で拡張する必要があります。方法は、使用しているファイルシステムによって異なります。詳細については、ホストオペレーティングシステムのドキュメントを参照してください。



== シックボリュームとシンボリュームの容量タイプ

シックボリュームまたはシンボリュームのどちらかを作成できます。レポート容量と割り当て容量はシックボリュームでは同じですが、シンボリュームでは異なります。

* シックボリュームの場合、ボリュームのレポート容量は割り当て済みの物理ストレージ容量と同じになります。物理ストレージ容量全体が存在している必要があります。物理的に割り当てられるスペースは、ホストに報告されるスペースと同じです。
+
通常は、シックボリュームのレポート容量を、ボリュームが拡張すると予想される最大容量に設定します。シックボリュームは、予測可能な高パフォーマンスをアプリケーションに提供します。これは主に、すべてのユーザ容量が作成時に予約され、割り当てられているためです。

* シンボリュームの場合、ホストに報告される容量がレポート容量で、データの書き込み用に現在割り当てられているドライブスペースが割り当て容量となります。
+
レポート容量は、ストレージアレイ上の割り当て容量よりも大きくなる場合があります。現在使用可能な資産に関係なく、シンボリュームの拡張に合わせてサイズを設定できます。



[NOTE]
====
SANtricity System Managerには、シンボリュームを作成するオプションはありません。シンボリュームを作成する場合は、コマンドラインインターフェイス（CLI）を使用します。

====


== シックボリュームの容量制限

シックボリュームの最小容量は1MiBであり、最大容量はプールまたはボリュームグループ内のドライブの数と容量で決まります。

シックボリュームのレポート容量を拡張する際は、次のガイドラインに注意してください。

* 小数点以下3桁まで指定できます（例：65.375GiB）。
* ボリュームグループで使用可能な最大値以下の容量を指定してください。
+
ボリュームを作成する場合は、セグメントサイズの動的（DSS）変更のための追加容量が事前に割り当てられます。DSS変更は、ボリュームのセグメントサイズを変更できるソフトウェアの機能です。

* 一部のホストオペレーティングシステムでは、2TiBを超えるボリュームがサポートされます（最大レポート容量はホストオペレーティングシステムで決定されます）。実際には、一部のホストオペレーティングシステムでサポートされるのは最大128TiBのボリュームです。詳細については、ホストオペレーティングシステムのドキュメントを参照してください。




== シンボリュームの容量制限

レポート容量が多く、割り当て容量が比較的少ないシンボリュームを作成できます。これは、ストレージの利用率や効率性に効果的です。シンボリュームを使用すると、アプリケーションの実行を中断することなく、アプリケーションのニーズの変化に応じて割り当て容量を拡張できるため、ストレージ管理が簡易化され、ストレージ利用率が向上します。

シンボリュームには、レポート容量と割り当て容量に加えて、書き込み済み容量も含まれています。書き込み済み容量は、シンボリュームに割り当てられたリザーブ容量のうちの書き込み済みの容量です。

次の表に、シンボリュームの容量制限を示します。

[cols="3*"]
|===
| 容量のタイプ | 最小サイズ | 最大サイズ 


 a| 
報告済み
 a| 
32MiB
 a| 
256TiB です



 a| 
割り当て済み
 a| 
4MiB
 a| 
64TiB

|===
シンボリュームの場合、最大レポート容量の256TiBに達していると容量を拡張できません。シンボリュームのリザーブ容量が最大レポート容量よりも大きいサイズに設定されていることを確認してください。

割り当て容量は、割り当て容量の制限に基づいて自動的に拡張されます。割り当て容量の制限により、シンボリュームの自動拡張をレポート容量までに制限できます。書き込まれるデータの量が割り当て容量に近付いたときは、割り当て容量の制限を変更することができます。

割り当て容量の制限を変更するには、メニューを選択します。Storage [Volumes]> Thin Volume Monitoringタブ> Change Limit]

System Managerでは、シンボリュームの作成時にフル容量を割り当てないため、プールの空き容量が不足する可能性があります。スペース不足の場合は、シンボリュームについてだけでなく、プールの容量を必要とする他の処理（SnapshotイメージやSnapshotボリュームなど）についてもプールへの書き込みがブロックされる可能性があります。ただし、プールからの読み取り処理は引き続き実行できます。この状況が発生すると、アラートしきい値の警告が表示されます。
