---
permalink: sm-storage/capacity-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, capacity terms 
summary: ストレージアレイに関連する容量の用語を次に示します。 
---
= 容量に関する用語
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイに関連する容量の用語を次に示します。



== ストレージオブジェクト

次の用語は、ストレージアレイを利用できるさまざまなタイプのストレージオブジェクトを示しています。

[cols="25h,~"]
|===
| ストレージオブジェクト | 説明 


 a| 
ホスト
 a| 
ホストは、ストレージアレイ上のボリュームにI/Oを送信するサーバです。



 a| 
LUN
 a| 
Logical Unit Number（LUN；論理ユニット番号）は、ホストがボリュームへのアクセスに使用する番号で、アドレススペースに割り当てられます。ボリュームは、LUNの形式でホストに容量として提示されます。

各ホストには独自のLUNアドレススペースがあります。したがって、同じLUNを複数のホストで使用して、異なるボリュームにアクセスできます。



 a| 
ミラー整合性グループ
 a| 
ミラー整合性グループは、1つ以上のミラーペアのコンテナです。非同期ミラーリング処理では、ミラー整合性グループを作成する必要があります。



 a| 
ミラーボリュームペア
 a| 
ミラーペアは、プライマリボリュームとセカンダリボリュームの2つのボリュームで構成されます。



 a| 
プール
 a| 
プールは、論理的にグループ化された一連のドライブです。プールを使用して、ホストにアクセス可能な 1 つ以上のボリュームを作成することができます。（ボリュームはプールまたはボリュームグループから作成します）。



 a| 
Snapshot整合性グループ
 a| 
Snapshot整合性グループは、Snapshotイメージが作成されるときに1つのエンティティとして扱われるボリュームの集まりです。各ボリュームのSnapshotイメージが作成されますが、すべてのイメージが同じ時点で作成されます。



 a| 
Snapshotグループ
 a| 
Snapshotグループは、1つのベースボリュームのSnapshotイメージの集まりです。



 a| 
Snapshotボリューム
 a| 
Snapshotボリュームを使用すると、ホストはSnapshotイメージのデータにアクセスできます。Snapshotボリュームには独自のリザーブ容量があり、元のSnapshotイメージに影響を与えることなくベースボリュームへの変更が保存されます。



 a| 
ボリューム
 a| 
ボリュームは、アプリケーション、データベース、およびファイルシステムがデータを格納するコンテナです。ホストがストレージアレイのストレージにアクセスするために作成される論理コンポーネントです。



 a| 
ボリュームグループ
 a| 
ボリュームグループは、同じ特性を持つボリュームのコンテナです。ボリュームグループごとに容量とRAIDレベルが定義されています。ボリュームグループを使用して、ホストにアクセス可能な1つ以上のボリュームを作成することができます。（ボリュームはボリュームグループまたはプールから作成します）。

|===


== ストレージ容量

次の用語は、ストレージアレイで使用されるさまざまなタイプの容量を示しています。

[cols="25h,~"]
|===
| 容量タイプ | 説明 


 a| 
割り当て容量
 a| 
割り当て容量は、プールまたはボリュームグループ内のドライブから割り当てられた物理容量です。

割り当て容量は、ボリュームの作成やコピーサービス処理に使用します。



 a| 
空き容量
 a| 
空き容量は、ボリュームの作成処理やコピーサービス処理、およびストレージオブジェクトにまだ割り当てられていないプールまたはボリュームグループ内の使用可能な容量です。



 a| 
プールまたはボリュームグループの容量
 a| 
プール、ボリューム、またはボリュームグループの容量は、ストレージアレイ内の容量のうち、プールまたはボリュームグループに割り当てられている容量です。この容量は、ボリュームの作成、およびコピーサービス処理とストレージオブジェクトのさまざまな容量ニーズに対応するために使用されます。



 a| 
プールの使用不可容量
 a| 
プールの使用不可容量は、ドライブサイズの不一致が原因で使用できないプール内のスペースです。



 a| 
予約済み容量
 a| 
予約済み容量は、ドライブ障害に備えてプール内に確保されている容量（ドライブ数）です。



 a| 
レポート容量
 a| 
レポート容量は、ホストに報告され、ホストからアクセスできる容量です。



 a| 
リザーブ容量
 a| 
リザーブ容量は、コピーサービス処理やストレージオブジェクトに使用される物理割り当て容量です。ホストから直接読み取ることはできません。



 a| 
SSD キャッシュ
 a| 
[NOTE]
====
この機能は、EF600またはEF300ストレージシステムでは使用できません。

====
SSDキャッシュは、ストレージアレイ内で論理的にグループ化したソリッドステートディスク（SSD）ドライブのセットです。SSDキャッシュ機能では、アクセス頻度が特に高いデータ（「ホット」データ）を低レイテンシのSSDドライブにキャッシュすることでアプリケーションワークロードを動的に高速化します。



 a| 
未割り当て容量
 a| 
未割り当て容量は、ストレージアレイ内のスペースのうち、プールまたはボリュームグループに「割り当てられていない」スペースです。



 a| 
書き込み済み容量
 a| 
書き込み済み容量は、シンボリュームに割り当てられたリザーブ容量のうちの書き込み済みの容量です。

|===