---
permalink: sm-storage/change-host-port-identifiers-for-a-host.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, host port, identifiers, host 
summary: ホストポート識別子のユーザラベルを変更する場合、ホストに新しいホストポート識別子を追加する場合、またはホストからホストポート識別子を削除する場合は、ホストポート識別子を変更します。 
---
= ホストのホストポート識別子を変更する
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ホストポート識別子のユーザラベルを変更する場合、ホストに新しいホストポート識別子を追加する場合、またはホストからホストポート識別子を削除する場合は、ホストポート識別子を変更します。

.このタスクについて
ホストポート識別子を変更する際は、次のガイドラインに注意してください。

* *-ホストポートを追加すると、ストレージアレイに接続するために作成したホストにホストポート識別子が関連付けられます。ポート情報は、ホストバスアダプタ（HBA）ユーティリティを使用して手動で入力できます。
* *編集*--ホストポートを編集して'ホストポートを別のホストに移動(関連付け)することができますホストバスアダプタまたはiSCSIイニシエータを別のホストに移動した場合は、ホストポートを新しいホストに移動（関連付ける）する必要があります。
* *削除*--ホストポートを削除して'ホストからホストポートを削除(関連付けを解除)することができます


.手順
. メニューから「 Storage [Hosts] 」を選択します。
. ポートを関連付けるホストを選択し、 * 表示 / 設定の編集 * をクリックします。
+
ホストクラスタのホストにポートを追加する場合は、ホストクラスタを展開して目的のホストを選択します。ホストクラスタレベルでポートを追加することはできません。

+
ダイアログボックスが開き、現在のホスト設定が表示されます。

. [ ホストポート *] タブをクリックします。
+
ダイアログボックスに現在のホストポート識別子が表示されます。

. ホストポート識別子の設定を必要に応じて変更します。
+
[cols="25h,~"]
|===
| 設定 | 説明 


 a| 
ホストポート
 a| 
次のいずれかのオプションを選択できます。

** *追加-- Addを使用して'新しいホストポート識別子をホストに関連付けますホストポート識別子名の長さは、ホストインターフェイスのテクノロジによって決まります。Fibre ChannelとInfiniBandのホストポート識別子名は、16文字にする必要があります。iSCSI のホストポート識別子名は最大 223 文字です。ポートは一意である必要があります。すでに設定されているポート番号は使用できません。
** *Delete *-- Deleteを使用して、ホストポート識別子を削除(関連付けを解除)します。Deleteオプションを使用しても、ホストポートは物理的には削除されません。このオプションを選択すると、ホストポートとホストの間の関連付けが削除されます。ホストバスアダプタまたは iSCSI イニシエータを削除しないかぎり、ホストポートは引き続きコントローラで認識されます。
+
[NOTE]
====
ホストポート識別子を削除すると、そのホストとの関連付けが解除されます。また、ホストはホストに割り当てられているボリュームにこのホストポート識別子経由でアクセスできなくなります。

====




 a| 
ラベル
 a| 
ポートラベル名を変更するには、* Edit *アイコン（鉛筆）をクリックします。ポートラベル名は一意である必要があります。すでに設定されているラベル名は使用できません。



 a| 
CHAPシークレット
 a| 
iSCSIホストにのみ表示されます。イニシエータ（iSCSIホスト）のCHAPシークレットを設定または変更できます。

System Managerは、チャレンジハンドシェイク認証プロトコル（CHAP）方式を使用します。CHAPは初回のリンク確立時にターゲットとイニシエータのIDを検証します。認証は、CHAPシークレットと呼ばれる共有セキュリティキーに基づいて行われます。

|===
. [ 保存（ Save ） ] をクリックします。

