---
permalink: sm-storage/change-the-reserved-capacity-settings-for-a-snapshot-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, reserved capacity, settings, snapshot, group 
summary: Snapshotグループの設定では、グループ名、自動削除設定、許可されるSnapshotイメージの最大数、System Managerがリザーブ容量のアラート通知を送信する割合、またはリザーブ容量が最大使用率に達したときに使用するポリシーを変更できます。 
---
= SANtricity System Managerでスナップショットグループの予約容量設定を変更する
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Snapshotグループの設定を変更して、グループの名前、自動削除設定、許可されるSnapshotイメージの最大数、SANtricity System Managerがリザーブ容量のアラート通知を送信する割合、またはリザーブ容量が最大使用率に達したときに使用するポリシーを変更できます。

Snapshotグループの作成時に、グループに含まれるすべてのSnapshotイメージのデータを格納するためのリザーブ容量が作成されます。

.手順
. 左側のパネルから、メニュー：Storage[Pools and volume groups]を選択します。
. 予約容量*タブをクリックします。
. 編集するスナップショット グループを選択し、メニューをクリックします：省略記号アイコン[設定の編集]。
+
「スナップショット グループ設定の編集」ウィンドウが表示されます。

. Snapshotグループの設定を適宜変更します。
+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 説明 


 a| 
* Snapshotグループの設定*



 a| 
名前
 a| 
Snapshotグループの名前。Snapshotグループの名前は必ず指定する必要があります。



 a| 
スナップショット画像の自動削除
 a| 
グループ内のSnapshotイメージの総数をユーザ定義の最大数以下に抑えるための設定。このオプションを有効にすると、グループで許可されているSnapshotイメージの最大数に準拠するために、System Managerは新しいSnapshotが作成されるたびに最も古いSnapshotイメージを自動的に削除します。



 a| 
Snapshotイメージの上限
 a| 
Snapshotグループに許可されるSnapshotイメージの最大数。ユーザが設定できます。



 a| 
*リザーブ容量の設定*



 a| 
アラートの送信しきい値
 a| 
このスピンボックスを使用して、Snapshotグループのリザーブ容量が残り少なくなったときにSystem Managerからアラート通知を送信する割合を調整します。

Snapshotグループのリザーブ容量が指定したしきい値を超えるとSystem Managerからアラートが送信されるため、前もってリザーブ容量を増やしたり不要なオブジェクトを削除したりできます。



 a| 
リザーブ容量がフルになったときの処理です
 a| 
次のいずれかのポリシーを選択できます。

** *最も古いSnapshotイメージをパージする*- System ManagerはSnapshotグループ内の最も古いSnapshotイメージを自動的にパージし、そのSnapshotイメージのリザーブ容量を解放してグループ内で再利用します。
** *ベースボリュームへの書き込みを拒否*--リザーブ容量の割合が定義された上限に達すると、System Managerはリザーブ容量へのアクセスをトリガーしたベースボリュームに対するI/O書き込み要求をすべて拒否します。


|===
====
. [保存]をクリックして'スナップショット・グループの設定に変更を適用します

