---
permalink: sm-storage/change-host-port-identifiers-for-a-host.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, host port, identifiers, host 
summary: ホストポート識別子のユーザラベルを変更する場合、ホストに新しいホストポート識別子を追加する場合、またはホストからホストポート識別子を削除する場合は、ホストポート識別子を変更します。 
---
= SANtricity System Managerでホストのホストポート識別子を変更する
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ホストポート識別子のユーザラベルを変更する場合、ホストに新しいホストポート識別子を追加する場合、またはホストからホストポート識別子を削除する場合は、ホストポート識別子を変更します。

.このタスクについて
ホストポート識別子を変更する際は、次のガイドラインに注意してください。

* *-ホストポートを追加すると、ストレージアレイに接続するために作成したホストにホストポート識別子が関連付けられます。ポート情報は、ホストバスアダプタ（HBA）ユーティリティを使用して手動で入力できます。
* *編集*--ホストポートを編集して'ホストポートを別のホストに移動(関連付け)することができますホストバスアダプタまたはiSCSIイニシエータを別のホストに移動した場合は、ホストポートを新しいホストに移動（関連付ける）する必要があります。
* *削除*--ホストポートを削除して'ホストからホストポートを削除(関連付けを解除)することができます


.手順
. 左側のパネルから、menu:Storage[Hosts]を選択します。
. ポートを関連付けるホストを選択し、menu:ellipsis icon[Edit Settings]をクリックします。
+
ホスト クラスタ内のホストにポートを追加する場合は、目的のホストを選択します。ホスト クラスタ レベルでポートを追加することはできません。

+
現在のホスト設定を示す「ホスト設定の編集」画面が表示されます。

. ホストポート識別子の設定を必要に応じて変更します。
+
[cols="25h,~"]
|===
| 設定 | 説明 


 a| 
ホストポート
 a| 
次のいずれかのオプションを選択できます。

** *ホストポートの追加* -- *ホストポートの追加*をクリックして、ホストに新しいホストポート識別子を関連付けます。ホストポート識別子名の長さは、ホスト インターフェイステクノロジーによって決まります。Fibre ChannelおよびInfinibandのホストポート識別子名は16文字である必要があります。iSCSIホストポート識別子名は最大223文字までです。ポートは一意である必要があります。既に設定されているポート番号は使用できません。
** *削除（Xアイコン）* -- *X*アイコンをクリックして、ホストポート識別子を削除（関連付けを解除）します。削除オプションでは、ホストポートが物理的に削除されるわけではありません。このオプションは、ホストポートとホスト間の関連付けを解除します。ホストバスアダプタまたはiSCSIイニシエータを取り外しない限り、ホストポートはコントローラによって認識されたままになります。
+
[NOTE]
====
ホストポート識別子を削除すると、そのホストとの関連付けが解除されます。また、ホストはホストに割り当てられているボリュームにこのホストポート識別子経由でアクセスできなくなります。

====




 a| 
名前
 a| 
必要に応じて、ポートのラベル名を変更できます。ポートラベル名は一意である必要があります。すでに設定されているラベル名は使用できません。



 a| 
CHAPシークレット
 a| 
iSCSIホストにのみ表示されます。イニシエータ（iSCSIホスト）のCHAPシークレットを設定または変更できます。

System Managerは、チャレンジハンドシェイク認証プロトコル（CHAP）方式を使用します。CHAPは初回のリンク確立時にターゲットとイニシエータのIDを検証します。認証は、CHAPシークレットと呼ばれる共有セキュリティキーに基づいて行われます。

|===
. [ 保存（ Save ） ] をクリックします。

