---
permalink: sm-storage/change-settings-for-a-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, settings, volume 
summary: ボリュームの名前、ホストの割り当て、セグメントサイズ、変更の優先順位、キャッシュなど、ボリュームの設定を変更できます。 など。 
---
= SANtricity System Managerでボリュームの設定を変更する
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリュームの名前、ホストの割り当て、セグメントサイズ、変更の優先順位、キャッシュなど、ボリュームの設定を変更できます。 など。

.作業を開始する前に
変更するボリュームのステータスは「最適」である必要があります。


NOTE: ボリューム設定の変更の実行中は、一部の処理を使用できない可能性があります

.手順
. 左側のパネルから、menu:Storage[Volumes]を選択します。
. 変更するボリュームを選択し、menu:ellipsis icon[Edit Settings]をクリックします。
+
「ボリューム設定の編集」ウィンドウが表示され、選択したボリュームの設定が表示されます。

. 必要に応じてボリューム設定を構成します。
+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 説明 


 a| 
名前
 a| 
ボリュームの名前が表示されます。現在の名前が適切でない場合はボリュームの名前を変更します。



 a| 
ホスト
 a| 
ボリュームの割り当てが表示されます。I/O処理でボリュームにアクセスできるように、ボリュームをホストまたはホストクラスタに割り当てます。これにより、ストレージアレイ内の特定のボリューム、または複数のボリュームへのアクセスがホストまたはホストクラスタに許可されます。

** *割り当て先*--選択したボリュームにアクセスできるホストまたはホストクラスタを指定します
** * lun *：ホストがボリュームへのアクセスに使用するアドレス・スペースに割り当てられる番号ボリュームは、LUNの形式でホストに容量として提示されます。各ホストには独自のLUNアドレススペースがあります。したがって、同じLUNを複数のホストで使用して、異なるボリュームにアクセスできます。
+

NOTE: NVMeインターフェイスの場合、この列にはネームスペースIDが表示されます。ネームスペースは、ブロックアクセス用にフォーマットされたNVMストレージです。SCSIの論理ユニットに相当し、ストレージアレイではボリュームに関連します。ネームスペースIDは、NVMeコントローラのネームスペースの一意の識別子です。1~255の値を設定できます。SCSIの論理ユニット番号（LUN）に相当します。





 a| 
セグメントサイジング
 a| 
セグメントのサイジングに関する設定が表示されます。これは、ボリュームグループのボリュームについてのみ表示されます。セグメントサイズを変更することでパフォーマンスを最適化することができます。

*許容される変更後のセグメントサイズ*-許容される変更後のセグメントサイズがSystem Managerで判別されます。現在のセグメントサイズの変更後のサイズとして適切でないものは、ドロップダウンリストに表示されません。通常、許容される変更後のサイズは、現在のセグメントサイズの倍または半分です。たとえば、ボリュームの現在のセグメントサイズが 32KiB であれば、ボリュームの新しいセグメントサイズとして 16KiB または 64KiB が許容されます。

* SSDキャッシュが有効なボリューム*- SSDキャッシュが有効なボリュームでは、セグメントサイズを4KiBに指定することができます。4KiB のセグメントサイズを選択するのは、 SSD キャッシュが有効なボリュームで小さいブロックの I/O 処理を実行する（ I/O ブロックサイズが 16KiB 以下の場合など）場合のみにしてください。SSD キャッシュが有効なボリュームで大きいブロックのシーケンシャル処理を実行する場合は、セグメントサイズとして 4KiB を選択するとパフォーマンスが低下することがあります。

*セグメントサイズの変更にかかる時間*-ボリュームのセグメントサイズの変更にかかる時間は、次の要因によって異なります。

** ホストからの I/O 負荷
** ボリュームの修正の優先順位
** ボリュームグループ内のドライブの数
** ドライブチャネルの数
** ストレージアレイコントローラの処理能力：ボリュームのセグメントサイズを変更すると、I/Oパフォーマンスに影響しますが、データの可用性は維持されます。




 a| 
修正の優先順位
 a| 
変更優先度の設定が表示されます。これは、ボリュームグループ内のボリュームについてのみ表示されます。

変更優先度は、ボリュームの変更処理にどの程度の処理時間を割り当てるかをシステムパフォーマンスに対する相対的な優先度として定義したものです。修正の優先順位を上げると、システムパフォーマンスが低下する場合があります。

優先度レベルを選択するには、スライダバーを動かします。

*修正の優先順位率*--優先順位が最も低いとシステムのパフォーマンスは向上しますが、修正操作にかかる時間は長くなります。優先度を最も高くすると修正処理にかかる時間は短縮されますが、システムパフォーマンスが低下する可能性があります。

|===
====
. [ 保存（ Save ） ] をクリックします。
+
選択内容に基づいて、System Managerがボリュームの設定を変更します。



.完了後
メニューの Storage → Operations in Progress を選択すると、選択したボリュームに対して現在実行中の変更操作の進行状況が表示されます。
