---
permalink: sm-storage/change-the-reserved-capacity-settings-for-a-consistency-group-member-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, reserved capacity, settings, consistency group, member volume 
summary: 整合性グループのメンバーボリュームの設定を変更して、メンバーボリュームのリザーブ容量が残り少なくなったときにSystem Managerからアラート通知を送信する割合を調整したり、リザーブ容量が最大定義に達したときに使用するポリシーを変更したりできます 割合。 
---
= 整合性グループのメンバーボリュームのリザーブ容量設定を変更します
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
整合性グループのメンバーボリュームの設定を変更して、メンバーボリュームのリザーブ容量が残り少なくなったときにSystem Managerからアラート通知を送信する割合を調整したり、リザーブ容量が最大定義に達したときに使用するポリシーを変更したりできます 割合。

.このタスクについて
個々のメンバーボリュームのリザーブ容量設定を変更すると、整合性グループに関連付けられているすべてのメンバーボリュームのリザーブ容量設定も変更されます。

.手順
. 選択メニュー：Storage（Pool & Volume Groups）
. 予約容量*タブをクリックします。
. 編集する整合性グループのメンバーボリュームを選択し、*表示/設定の編集*をクリックします。
+
Member Volume Reserved Capacity Settings（メンバーボリュームのリザーブ容量設定）ダイアログボックスが表示されます。

. メンバーボリュームのリザーブ容量設定を適宜変更します。
+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 説明 


 a| 
アラートの送信しきい値
 a| 
このスピンボックスを使用して、メンバーボリュームのリザーブ容量が残り少なくなったときにSystem Managerからアラート通知を送信する割合を調整します。

メンバーボリュームのリザーブ容量が指定したしきい値を超えるとSystem Managerからアラートが送信されるため、前もってリザーブ容量を増やしたり不要なオブジェクトを削除したりできます。


NOTE: 1つのメンバーボリュームのアラート設定を変更すると、同じ整合性グループに属する_ALL_MEMBER_VOLUMESのアラート設定が変更されます。



 a| 
リザーブ容量がフルになったときの処理です
 a| 
次のいずれかのポリシーを選択できます。

** *最も古いSnapshotイメージをパージする*- System Managerは整合性グループの最も古いSnapshotイメージを自動的にパージします。これにより、メンバーのリザーブ容量が解放され、グループ内で再利用できます。
** *ベースボリュームへの書き込みを拒否*--リザーブ容量の割合が定義された上限に達すると、System Managerはリザーブ容量へのアクセスをトリガーしたベースボリュームに対するI/O書き込み要求をすべて拒否します。


|===
====
. [保存（Save）]をクリックして、変更を適用します。


.結果
System Managerはメンバーボリュームのリザーブ容量設定だけでなく、整合性グループ内のすべてのメンバーボリュームのリザーブ容量設定を変更します。
