---
permalink: sm-storage/convert-a-snapshot-volume-to-read-write-mode.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, convert, snapshot, volume, read-write mode 
summary: 必要に応じて、読み取り専用のSnapshotボリュームやSnapshot整合性グループのSnapshotボリュームを読み取り/書き込みモードに変換することができます。 
---
= Snapshotボリュームを読み取り/書き込みモードに変換します
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
必要に応じて、読み取り専用のSnapshotボリュームやSnapshot整合性グループのSnapshotボリュームを読み取り/書き込みモードに変換することができます。

読み取り/書き込みアクセス可能に変換されたSnapshotボリュームには、独自のリザーブ容量が割り当てられます。この容量は、ホストアプリケーションがベースボリュームに対して行う以降の変更を、参照元のSnapshotイメージに影響を及ぼさずに保存するために使用されます。

.手順
. メニューを選択します。Storage [Snapshots]。
. スナップショットボリューム*タブを選択します。
+
Snapshot Volumesテーブルが表示され、ストレージアレイに関連付けられているすべてのSnapshotボリュームが表示されます。

. 変換する読み取り専用Snapshotボリュームを選択し、*読み取り/書き込みに変換*をクリックします。
+
読み取り/書き込みに変換ダイアログボックスが開き、予約容量*ステップが有効になります。ボリューム候補表には、指定したリザーブ容量に対応する候補だけが表示されます。

. 読み取り/書き込みのSnapshotボリュームにリザーブ容量を割り当てるには、次のいずれかを実行します。
+
** *デフォルト設定を受け入れます*-この推奨オプションを使用して、Snapshotボリュームのリザーブ容量をデフォルト設定で割り当てます。
** *データストレージのニーズに合わせて独自の設定でリザーブ容量を割り当てる*--次のガイドラインに従ってリザーブ容量を割り当てます
+
*** リザーブ容量のデフォルト設定はベースボリュームの容量の40%で、通常はこの容量で十分です。
*** 必要な容量は、ボリュームに対するI/O書き込みの頻度とサイズによって異なります。




. 設定を確認または編集するには、「*次へ*」を選択します。
+
設定の編集ダイアログボックスが表示されます。

. 必要に応じてSnapshotボリュームの設定をそのまま使用するか指定し、「*完了*」を選択してSnapshotボリュームを変換します。
+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 説明 


 a| 
*リザーブ容量の設定*



 a| 
アラートの送信しきい値
 a| 
このスピンボックスを使用して、Snapshotグループのリザーブ容量が残り少なくなったときにシステムからアラート通知を送信する割合を調整します。

Snapshotボリュームのリザーブ容量が指定したしきい値を超えるとシステムからアラートが送信されるため、前もってリザーブ容量を増やしたり不要なオブジェクトを削除したりできます。

|===
====

