---
permalink: sm-storage/copy-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, copy volume 
summary: ボリュームのデータを同じストレージアレイ内の別のボリュームにコピーすることで、ソースボリュームのポイントインタイムの物理的な複製（クローン）を作成できます。 
---
= ボリュームをコピーする
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリュームのデータを同じストレージアレイ内の別のボリュームにコピーすることで、ソースボリュームのポイントインタイムの物理的な複製（クローン）を作成できます。

.作業を開始する前に
* ソースボリュームとターゲットボリュームに対するすべてのI/Oアクティビティを停止する必要があります。
* ソースボリュームとターゲットボリュームのすべてのファイルシステムをアンマウントする必要があります。
* ターゲットボリュームを過去にボリュームコピー処理で使用したことがある場合、そのデータが不要になったか、またはデータをバックアップしたことになります。


.このタスクについて
ソースボリュームは、ホストI/Oを受け入れてアプリケーションデータを格納するボリュームです。ボリュームコピーが開始されると、ソースボリュームのデータがターゲットボリュームに丸ごとコピーされます。

ターゲットボリュームは、ソースボリュームのデータのコピーを保持する標準のボリュームです。ボリュームコピー処理が完了すると、ターゲットボリュームはソースボリュームと同じになります。ターゲットボリュームにはソースボリュームと同じかそれ以上の容量が必要です。ただし、RAIDレベルは同じである必要はありません。

.オンラインコピーとオフラインコピーについて
[%collapsible]
====
*オンラインコピー*

オンラインコピーは、ストレージアレイ内のボリュームのポイントインタイムコピーを作成します。コピーの実行中も、そのボリュームへの書き込みを継続できます。そのためには、ボリュームのSnapshotを作成し、そのSnapshotをコピーの実際のソースボリュームとして使用します。ポイントインタイムイメージの作成対象となるボリュームはベースボリュームと呼ばれ、ストレージアレイ内の標準ボリュームまたはシンボリュームを使用できます。

*オフラインコピー*

オフラインコピーは、ソースボリュームからデータを読み取り、そのデータをターゲットボリュームにコピーします。コピーの実行中は、ソースボリュームに対するすべての更新が一時停止されます。ソースボリュームに対するすべての更新を一時停止するのは、時間の経過による不整合がターゲットボリュームで発生しないようにするためです。オフラインボリュームコピーの関係は、ソースボリュームとターゲットボリューム間の関係です。

====
[NOTE]
====
ボリュームコピー処理はターゲットボリュームのデータを上書きし、ターゲットボリュームに関連付けられているSnapshotボリュームがある場合はすべて使用停止にします。

====
.手順
. 選択メニュー： Storage [Volumes]
. ボリュームコピー処理のソースとして使用するボリュームを選択し、メニューからコピーサービス[Copy Volume]を選択します。
+
Copy Volume - Select Target（ボリュームのコピー-ターゲットの選択）ダイアログボックスが表示されます。

. データをコピーするターゲットボリュームを選択します。
+
このダイアログボックスの表には、ターゲットボリュームとして使用できるすべてのボリュームが表示されます。

. スライダバーを使用して、ボリュームコピー処理のコピー優先度を設定します。
+
コピー優先度は、I/O要求の処理と比較して、ボリュームコピー処理を完了するためにどの程度のシステムリソースが使用されるかを決定するものです。

+
.コピー優先度について
[%collapsible]
====
コピー優先度は5段階で設定できます。

** 最低
** 低
** 中
** 高
** 最高


コピー優先度を最低速度に設定すると、I/Oアクティビティが優先され、ボリュームコピー処理にかかる時間が長くなります。コピー優先度が最高のレートに設定されている場合は、ボリュームコピー処理が優先されますが、ストレージアレイのI/Oアクティビティに影響する可能性があります。

====
. オンラインコピーとオフラインコピーのどちらを作成するかを選択します。オンライン・コピーを作成するには'[**コピー・オペレーション中にソース・ボリュームをオンラインにしておく**]チェック・ボックスを選択します
. 次のいずれかを実行します。
+
** online_copy操作を実行するには、* Next *をクリックして、* Reserve Capacity *ダイアログボックスに進みます。
** _offline_copy操作を実行するには'[*終了*]をクリックしてオフライン・コピーを開始します


. オンラインコピーの作成を選択した場合は、オンラインコピーのデータおよびその他の情報を保存するために必要なリザーブ容量を設定し、[*Finish*]をクリックしてオンラインコピーを開始します。
+
ボリューム候補の表には、指定したリザーブ容量をサポートする候補だけが表示されます。リザーブ容量は、コピーサービス処理やストレージオブジェクトに使用される物理割り当て容量です。ホストから直接読み取ることはできません。

+
次のガイドラインに従ってリザーブ容量を割り当てます。

+
** リザーブ容量のデフォルト設定はベースボリュームの容量の40%で、通常はこの容量で十分です。
** ただし、リザーブ容量は元のデータに対する変更の数によって異なります。ストレージオブジェクトがアクティブになっている時間が長いほど、リザーブ容量を大きくする必要があります。




.結果
System Managerにより、ソースボリュームのすべてのデータがターゲットボリュームにコピーされます。ボリュームコピー処理の完了後、ターゲットボリュームはホストに対して自動的に読み取り専用になります。

.完了後
メニューHome（ホーム）[View Operations in Progress]（進行中の操作の表示）を選択して、ボリュームコピー操作の進行状況を表示します。この処理には時間がかかることがあり、システムのパフォーマンスに影響する可能性があります。
