---
permalink: sm-storage/copy-volume-function.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, copy, volume, 
summary: ボリュームコピー機能を使用すると、ソースボリュームとターゲットボリュームの2つのボリュームを同じストレージアレイ上に作成して、ボリュームのポイントインタイムコピーを作成できます。 
---
= ボリュームコピーの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリュームコピー機能を使用すると、ソースボリュームとターゲットボリュームの2つのボリュームを同じストレージアレイ上に作成して、ボリュームのポイントインタイムコピーを作成できます。

ターゲットボリュームのデータがソースボリュームのデータと同じになるように、ソースボリュームからターゲットボリュームに1バイトずつデータがコピーされます。



== データをコピーすることでアクセスを向上

ボリュームのストレージ要件が変わった場合、ボリュームコピー機能を使用して、小容量のドライブを使用するプールまたはボリュームグループから大容量のドライブを使用するプールまたはボリュームグループにデータをコピーできます。たとえば、ボリュームコピー機能を使用して次のことが可能です。

* 大容量ドライブにデータを移動
* データ転送速度が速いドライブに変更します。
* パフォーマンスを向上させるために、新しいテクノロジを使用するドライブに変更を加える。
* シンボリュームをシックボリュームに変更する。




== シンボリュームをシックボリュームに変更する

シンボリュームをシックボリュームに変更する場合は、ボリュームコピー処理を使用してシンボリュームのコピーを作成します。ボリュームコピー処理のターゲットは常にシックボリュームです。

[NOTE]
====
System Managerには、シンボリュームを作成するオプションはありません。シンボリュームを作成する場合は、コマンドラインインターフェイス（CLI）を使用します。

====


== データをバックアップする

ボリュームコピー機能を使用すると、ボリュームのデータを同じストレージアレイの別のボリュームにコピーすることでボリュームをバックアップできます。ターゲットボリュームをソースボリュームのバックアップとして使用して、システムテストを実施したり、テープドライブなどの別のデバイスにバックアップしたりできます。



== Snapshotボリュームのデータをベースボリュームにリストアします

ベースボリュームのデータを関連付けられたSnapshotボリュームのデータからリストアする必要がある場合は、ボリュームコピー機能を使用してSnapshotボリュームからベースボリュームにデータをコピーできます。Snapshotボリューム上にデータのボリュームコピーを作成し、そのデータをベースボリュームにコピーできます。



== ソースボリュームとターゲットボリューム

次の表に、ボリュームコピー機能でソースボリュームとターゲットボリュームに使用できるボリュームのタイプを示します。

[cols="1a,1a,1a,1a"]
|===
| ボリュームタイプ | オフラインボリュームコピーのソースボリュームを指定します | オンラインボリュームコピーのソースボリューム | オンラインおよびオフラインのターゲットボリューム 


 a| 
プール内のシックボリューム
 a| 
はい。
 a| 
はい。
 a| 
はい。



 a| 
ボリュームグループ内のシックボリューム
 a| 
はい。
 a| 
はい。
 a| 
はい。



 a| 
シンボリューム
 a| 
はい。
 a| 
はい。
 a| 
いいえ



 a| 
Snapshotボリューム
 a| 
はい^1です
 a| 
いいえ
 a| 
いいえ



 a| 
Snapshotベースボリューム
 a| 
はい。
 a| 
いいえ
 a| 
いいえ



 a| 
リモートミラープライマリボリューム
 a| 
はい^2^
 a| 
いいえ
 a| 
はい。

|===
^1 ^オンラインコピー操作が完了するまでは、Snapshotボリュームコピーを使用できません。

^2^ソースボリュームがプライマリボリュームの場合、ターゲットボリュームの容量はソースボリュームの使用可能容量以上である必要があります。
