---
permalink: sm-storage/create-snapshot-consistency-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, snapshot, consistency group 
summary: 整合性のあるコピーを保持するために、Snapshot整合性グループと呼ばれる複数のボリュームのセットを作成できます。 
---
= Snapshot整合性グループを作成します
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
整合性のあるコピーを保持するために、Snapshot整合性グループ_という名前の複数のボリュームのセットを作成できます。

このグループでは、すべてのボリュームのSnapshotイメージを同時に作成して整合性を保つことができます。Snapshot整合性グループに属する各ボリュームのことを「_member volume__」と呼びます。ボリュームをSnapshot整合性グループに追加すると、そのメンバーボリュームに対応する新しいSnapshotグループが自動的に作成されます。

.このタスクについて
Snapshot整合性グループ作成手順では、グループのメンバーボリュームを選択し、メンバーボリュームに容量を割り当てることができます。

Snapshot整合性グループを作成するプロセスは複数の手順で構成される手順 です。



== 手順1：Snapshot整合性グループにメンバーを追加する

メンバーを選択し、Snapshot整合性グループを構成する一連のボリュームを指定します。Snapshot整合性グループに対して実行するすべての操作は、選択したすべてのメンバーボリュームに対して一様に実行されます。

.作業を開始する前に
メンバーボリュームが最適lである必要があります。

.手順
. メニューを選択します。Storage [Snapshots]。
. スナップショット・コンシステンシ・グループ*タブをクリックします
. メニューを選択します。Create [Snapshot consistency group].
+
Create Snapshot Consistency Group（Snapshot整合グループの作成）ダイアログボックスが表示されます。

. Snapshot整合性グループにメンバーボリュームとして追加するボリュームを選択します。
. 「*次へ*」をクリックして、に進みます <<手順2：Snapshot整合性グループ用の容量をリザーブします>>。




== 手順2：Snapshot整合性グループ用の容量をリザーブします

Snapshot整合性グループにリザーブ容量を関連付けます。Snapshot整合性グループのプロパティに基づいて、System Managerから推奨されるボリュームと容量が提示されます。推奨されるリザーブ容量の設定をそのまま使用することも、割り当てられたストレージをカスタマイズすることもできます。

.このタスクについて
ボリューム候補の表には、リザーブ容量ダイアログボックスで、指定したリザーブ容量をサポートする候補だけが表示されます。リザーブ容量は、コピーサービス処理やストレージオブジェクトに使用される物理割り当て容量です。ホストから直接読み取ることはできません。

.手順
. スピンボックスを使用して、Snapshot整合性グループのリザーブ容量を割り当てます。次のいずれかを実行します。
+
** *デフォルトの設定をそのまま使用します*。
+
各メンバーボリュームのリザーブ容量を割り当てる推奨されるオプションであり、デフォルトの設定でリザーブ容量を割り当てます。

** *データストレージのニーズに合わせて独自の設定でリザーブ容量を割り当てることができます。*
+
次のガイドラインに従ってリザーブ容量を割り当てます。

+
*** リザーブ容量のデフォルト設定はベースボリュームの容量の40%です。通常はこの容量で十分です。
*** 必要な容量は、ボリュームに対するI/O書き込みの頻度とサイズ、およびSnapshotイメージを収集する数と期間によって異なります。




. *オプション：*デフォルトのリザーブ容量設定を変更した場合は、*候補の更新*をクリックして、指定したリザーブ容量の候補リストを更新します。
. 「*次へ*」をクリックして、に進みます <<手順3：Snapshot整合性グループの設定を編集する>>。




== 手順3：Snapshot整合性グループの設定を編集する

Snapshot整合性グループの自動削除に関する設定とリザーブ容量に関するアラートのしきい値を確認し、必要に応じて変更します。

.このタスクについて
Snapshot整合性グループ作成手順では、グループのメンバーボリュームを選択し、メンバーボリュームに容量を割り当てることができます。

.手順
. Snapshot整合性グループのデフォルトの設定をそのまま使用するか、必要に応じて変更します。
+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 説明 


 a| 
* Snapshot整合グループ設定*



 a| 
名前
 a| 
Snapshot整合性グループの名前を指定します。



 a| 
次の場合にSnapshotイメージの自動削除を有効にする...
 a| 
指定した制限に達したときにSnapshotイメージを自動的に削除する場合は、このチェックボックスをオンのままにします。制限はスピンボックスを使用して変更できます。このチェックボックスの選択を解除すると、Snapshotイメージが32個作成された時点で作成が停止します。



 a| 
*リザーブ容量の設定*



 a| 
アラートの送信しきい値
 a| 
このスピンボックスを使用して、Snapshot整合性グループのリザーブ容量が残り少なくなったときにシステムからアラート通知を送信する割合を調整します。

Snapshot整合性グループのリザーブ容量が指定したしきい値を超えると、事前の通知が表示され、残りのスペースがなくなる前にリザーブ容量を増やしたり不要なオブジェクトを削除したりできます。



 a| 
リザーブ容量がフルになったときの処理です
 a| 
次のいずれかのポリシーを選択します。

** *最も古いSnapshotイメージをパージする*- Snapshot整合性グループ内の最も古いSnapshotイメージが自動的にパージされ、そのSnapshotイメージのリザーブ容量が解放されてグループ内で再利用されます。
** *ベースボリュームへの書き込みを拒否*--リザーブ容量の割合が定義された上限に達すると'リザーブ容量へのアクセスをトリガーしたベースボリュームに対するI/O書き込み要求はすべて拒否されます


|===
====
. Snapshot整合性グループの設定が完了したら、「*完了」をクリックします。

