---
permalink: sm-storage/create-host-cluster.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, host, cluster 
summary: 同じボリュームへのI/Oアクセスを必要とするホストが複数ある場合は、ホストクラスタを作成します。 
---
= ホストクラスタを作成する
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
同じボリュームへのI/Oアクセスを必要とするホストが複数ある場合は、ホストクラスタを作成します。

.このタスクについて
ホストクラスタを作成する際は、次のガイドラインに注意してください。

* クラスタの作成に使用できるホストが複数ない場合、この処理は開始されません。
* ホストクラスタ内のホストはオペレーティングシステムが異なっていてもかまいません（異機種混在）。
* ホストクラスタのNVMeホストをNVMe以外のホストと混在させることはできません。
* Data Assurance（DA）対応ボリュームを作成する場合は、使用するホスト接続でDAがサポートされている必要があります。
+
ストレージアレイのコントローラで DA をサポートしていないホスト接続が使用されている場合、関連付けられているホストからは DA 対応ボリュームのデータにアクセスできません。

* 選択した名前がすでに使用されている場合、この処理は失敗します。
* 名前は 30 文字以内にする必要があります。


.手順
. メニューから「 Storage [Hosts] 」を選択します。
. メニューから「Create [Host Cluster]」を選択します。
+
Create Host Cluster（ホストクラスタの作成）ダイアログボックスが表示されます。

. ホストクラスタの設定を必要に応じて選択します。
+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 説明 


 a| 
名前
 a| 
新しいホストクラスタの名前を入力します。



 a| 
ボリュームアクセスを共有するホストを選択します
 a| 
ドロップダウンリストから2つ以上のホストを選択します。このリストには、ホストクラスタにまだ含まれていないホストのみが表示されます。

|===
====
. [ 作成（ Create ） ] をクリックします。
+
選択したホストが接続されているインターフェイスタイプのData Assurance（DA）機能が異なる場合、ホストクラスタでDAを使用できないことを示すメッセージがダイアログに表示されます。この場合、ホストクラスタにDA対応ボリュームを追加することはできません。続行するには「*はい」を選択し、キャンセルするには「*いいえ」を選択します。

+
DA を使用すると、ストレージシステム全体のデータの整合性が向上します。ホストとドライブの間でデータが移動されたときにストレージアレイがエラーの有無をチェックします。新しいボリュームに DA を使用すると、すべてのエラーが検出されます。



.結果
新しいホストクラスタが表に表示され、その下の行に割り当てられたホストが表示されます。
