---
permalink: sm-storage/create-host-automatically.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, host, automatically 
summary: Host Context Agent （ HCA ）を使用してホストを自動的に検出し、検出された情報が正しいかを確認することができます。ホストの作成は、ストレージアレイが接続されているホストを認識して、ボリュームへのI/Oアクセスを許可するために必要な手順の1つです。 
---
= ホストを自動で作成する
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Host Context Agent （ HCA ）を使用してホストを自動的に検出し、検出された情報が正しいかを確認することができます。ホストの作成は、ストレージアレイが接続されているホストを認識して、ボリュームへのI/Oアクセスを許可するために必要な手順の1つです。

.作業を開始する前に
Host Context Agent（HCA）がストレージアレイに接続されたすべてのホストにインストールされ、実行されていることを確認します。HCAがインストールされ、ストレージアレイに接続されているホストは、自動的に作成されます。HCAをインストールするには、ホストにSANtricity Storage Managerをインストールし、ホストオプションを選択します。HCAは、サポートされているすべてのオペレーティングシステムで使用できるわけではありません。使用できない場合は、ホストを手動で作成する必要があります。

.手順
. メニューから「 Storage [Hosts] 」を選択します。
+
自動で作成されたホストが表に表示されます。

. HCA から提供された情報（名前、ホストタイプ、ホストポート識別子）が正しいことを確認します。
+
いずれかの情報を変更する必要がある場合は、ホストを選択し、 * 表示 / 設定の編集 * をクリックします。

. *オプション：自動で作成されたホストをクラスタに追加する場合は、ホストクラスタを作成してホストを追加します。


.結果
ホストが自動的に作成されると、ホストタイルテーブルに次の項目が表示されます。

* ホストのシステム名から取得されたホスト名。
* ホストに関連付けられたホストポート識別子。
* ホストのホストオペレーティングシステムタイプ。

