---
permalink: sm-storage/create-snapshot-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, snapshot, volume 
summary: Snapshotボリュームを作成して、ボリュームまたはSnapshot整合性グループのSnapshotイメージにホストからアクセスできるようにします。Snapshotボリュームは読み取り専用または読み取り/書き込みに指定できます。 
---
= Snapshotボリュームを作成します
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Snapshotボリュームを作成して、ボリュームまたはSnapshot整合性グループのSnapshotイメージにホストからアクセスできるようにします。Snapshotボリュームは読み取り専用または読み取り/書き込みに指定できます。

.このタスクについて
Snapshotボリュームの作成手順では、SnapshotイメージからSnapshotボリュームを作成します。ボリュームが読み取り/書き込みの場合は、リザーブ容量を割り当てることができます。Snapshotボリュームは次のいずれかとして指定できます。

* 読み取り専用のSnapshotボリュームは、Snapshotイメージに格納されたデータに対する読み取りアクセスをホストアプリケーションに提供します。Snapshotイメージを変更することはできません。読み取り専用のSnapshotボリュームには、関連付けられたリザーブ容量はありません。
* 読み取り/書き込みのSnapshotボリュームは、Snapshotイメージに格納されたデータへの書き込みアクセスをホストアプリケーションに提供します。専用のリザーブ容量が割り当てられ、ホストアプリケーションがベースボリュームに対して行う以降の変更を、参照元のSnapshotイメージに影響を及ぼさずに保存するために使用されます。


Snapshotボリュームを作成するプロセスは複数の手順で構成される手順 です。



== 手順1：Snapshotボリュームのメンバーを確認します

ベースボリュームまたはSnapshot整合性グループのSnapshotイメージを選択します。Snapshot整合性グループのSnapshotイメージを選択した場合は、確認用にSnapshot整合性グループのメンバーボリュームが表示されます。

.手順
. メニューを選択します。Storage [Snapshots]。
. スナップショットボリューム*タブを選択します。
. 「 * Create * 」を選択します。
+
Create Snapshot Volume（スナップショットボリュームの作成）ダイアログボックスが表示されます。

. Snapshotボリュームに変換するSnapshotイメージ（ボリュームまたはSnapshot整合性グループ）を選択し、* Next（次へ）*をクリックします。[*Filter*]フィールドのテキスト・エントリを使用して、リストを絞り込みます。
+
Snapshot整合性グループのSnapshotイメージに対してを選択した場合は、Review Members（メンバーの確認）ダイアログボックスが表示されます。

+
[メンバーの確認]ダイアログ・ボックスで'スナップショット・ボリュームへの変換に選択したボリュームのリストを確認し'[次へ]をクリックします

. に進みます <<手順2：Snapshotボリュームをホストに割り当てる>>。




== 手順2：Snapshotボリュームをホストに割り当てる

特定のホストまたはホストクラスタを選択してSnapshotボリュームに割り当てます。これにより、ホストまたはホストクラスタにSnapshotボリュームへのアクセスが許可されます。必要に応じて、ホストをあとから割り当てることもできます。

.作業を開始する前に
* 有効なホストまたはホストクラスタがHostsページに表示されています。
* ホストに対してホストポート識別子が定義されている必要があります。
* DA対応ボリュームを作成する前に、使用するホスト接続でData Assurance（DA）機能がサポートされていることを確認してください。ストレージアレイのコントローラで DA をサポートしていないホスト接続が使用されている場合、関連付けられているホストからは DA 対応ボリュームのデータにアクセスできません。


.このタスクについて
ボリュームを割り当てる際は、次のガイドラインに注意してください。

* ホストのオペレーティングシステムによって、ホストがアクセスできるボリュームの数に制限がある場合があります。
* 割り当てることができるホストまたはホストクラスタは、ストレージアレイのSnapshotボリュームごとに1つです。
* 割り当てられたボリュームは、ストレージアレイのコントローラ間で共有されます。
* あるホストまたはホストクラスタからSnapshotボリュームへのアクセスに、同じ論理ユニット番号（LUN）を複数回使用することはできません。一意のLUNを使用する必要があります。


[NOTE]
====
ホストクラスタにボリュームを割り当てる場合、そのホストクラスタ内のいずれかのホストに対してすでに確立されている割り当てと競合していると、割り当ては失敗します。

====
.手順
. [*ホストへの割り当て*]ダイアログ・ボックスで'新しいボリュームに割り当てるホストまたはホスト・クラスタを選択しますホストを割り当てずにボリュームを作成する場合は、ドロップダウンリストから* Assign later *を選択します。
. アクセスモードを選択します。次のいずれかを選択します。
+
** *読み取り/書き込み*-このオプションは、Snapshotボリュームへの読み取り/書き込みアクセスをホストに提供し、リザーブ容量を必要とします。
** *読み取り専用*-このオプションは、Snapshotボリュームへの読み取り専用アクセスをホストに提供し、リザーブ容量は不要です。


. 「*次へ*」をクリックして、次のいずれかの操作を行います。
+
** Snapshotボリュームが読み取り/書き込みの場合は、Review Capacity（容量の確認）ダイアログボックスが表示されます。に進みます <<手順3：Snapshotボリューム用の容量をリザーブする>>。
** Snapshotボリュームが読み取り専用の場合は、Edit Priorityダイアログボックスが表示されます。に進みます <<手順4：Snapshotボリュームの設定を編集する>>。






== 手順3：Snapshotボリューム用の容量をリザーブする

読み取り/書き込みのSnapshotボリュームにリザーブ容量を関連付けます。ベースボリュームまたはSnapshot整合性グループのプロパティに基づいて、System Managerから推奨されるボリュームと容量が提示されます。推奨されるリザーブ容量の設定をそのまま使用することも、割り当てられたストレージをカスタマイズすることもできます。

.このタスクについて
Snapshotボリュームのリザーブ容量を必要に応じて増やしたり減らしたりできます。Snapshotのリザーブ容量が必要よりも多い場合は、サイズを縮小することで他の論理ボリュームに必要なスペースを解放できます。

.手順
. スピンボックスを使用して、Snapshotボリュームのリザーブ容量を割り当てます。
+
ボリューム候補表には、指定したリザーブ容量に対応する候補だけが表示されます。

+
次のいずれかを実行します。

+
** *デフォルトの設定をそのまま使用します*。
+
デフォルト設定を使用してSnapshotボリュームのリザーブ容量を割り当てるには、この推奨オプションを使用します。

** *データストレージのニーズに合わせて、独自の設定でリザーブ容量を割り当てます。*
+
デフォルトのリザーブ容量設定を変更した場合は、*候補の更新*をクリックして、指定したリザーブ容量の候補リストを更新します。

+
次のガイドラインに従ってリザーブ容量を割り当てます。

+
*** リザーブ容量のデフォルト設定はベースボリュームの容量の40%で、通常はこの容量で十分です。
*** 必要な容量は、ボリュームに対するI/O書き込みの頻度とサイズ、およびSnapshotイメージを収集する数と期間によって異なります。




. *オプション：Snapshot整合性グループのSnapshotボリュームを作成する場合は、「候補の変更」オプションがリザーブ容量候補の表に表示されます。[候補の変更]をクリックして、代替リザーブ容量候補を選択します。
. 「*次へ*」をクリックして、に進みます <<手順4：Snapshotボリュームの設定を編集する>>。




== 手順4：Snapshotボリュームの設定を編集する

名前、キャッシュ、リザーブ容量に関するアラートしきい値など、Snapshotボリュームの設定を変更します。

.このタスクについて
読み取り専用のパフォーマンスを向上させるために、ソリッドステートディスク（SSD）キャッシュにボリュームを追加することができます。SSDキャッシュは、ストレージアレイ内で論理的にグループ化したSSDドライブのセットで構成されます。

.手順
. Snapshotボリュームの設定をそのまま使用するか、必要に応じて変更します。
+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 説明 


 a| 
* Snapshotボリューム設定*



 a| 
名前
 a| 
Snapshotボリュームの名前を指定します。



 a| 
SSDキャッシュを有効にする
 a| 
SSDで読み取り専用のキャッシュを有効にする場合は、このオプションを選択します。注：この機能は、EF600またはEF300ストレージシステムでは使用できません。



 a| 
*リザーブ容量の設定*



 a| 
アラートの送信しきい値
 a| 
*読み取り/書き込みのSnapshotボリューム*にのみ表示されます。

このスピンボックスを使用して、Snapshotグループのリザーブ容量が残り少なくなったときにシステムからアラート通知を送信する割合を調整します。

Snapshotグループのリザーブ容量が指定したしきい値を超えると、事前の通知が表示され、残りのスペースがなくなる前にリザーブ容量を増やしたり不要なオブジェクトを削除したりできます。

|===
====
. Snapshotボリュームの設定を確認します。[戻る]をクリックして変更を行います。
. スナップショット・ボリュームの構成に問題がなければ'[*終了*]をクリックします

