---
permalink: sm-storage/create-host-manually.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, host, manually 
summary: 自動で検出できないホストについては、手動で作成することができます。ホストの作成は、ストレージアレイが接続されているホストを認識して、ボリュームへのI/Oアクセスを許可するために必要な手順の1つです。 
---
= ホストを手動で作成する
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
自動で検出できないホストについては、手動で作成することができます。ホストの作成は、ストレージアレイが接続されているホストを認識して、ボリュームへのI/Oアクセスを許可するために必要な手順の1つです。

.このタスクについて
ホストを作成する際は、次のガイドラインに注意してください。

* ホストに関連付けられたホストポート識別子を定義する必要があります。
* ホストに割り当てられたシステム名と同じ名前を指定してください。
* 選択した名前がすでに使用されている場合、この処理は失敗します。
* 名前は 30 文字以内にする必要があります。


.手順
. メニューから「 Storage [Hosts] 」を選択します。
. メニュー： Create [Host] をクリックします。
+
Create Host （ホストの作成）ダイアログボックスが表示されます。

. ホストの設定を必要に応じて選択します。
+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 説明 


 a| 
名前
 a| 
新しいホストの名前を入力します。



 a| 
ホストオペレーティングシステムのタイプ
 a| 
新しいホストで実行しているオペレーティングシステムをドロップダウンリストから選択します。



 a| 
ホストインターフェイスタイプ
 a| 
（オプション）ストレージアレイで複数のタイプのホストインターフェイスがサポートされている場合、使用するホストインターフェイスタイプを選択します。



 a| 
ホストポート
 a| 
次のいずれかを実行します。

** * I/O インターフェイス * を選択します
+
通常は、ホストポートはログイン済みで、ドロップダウンリストに表示されます。リストからホストポート識別子を選択することができます。

** * 手動で追加 *
+
ホストポート識別子がリストに表示されない場合は、ホストポートがログインしていません。HBA ユーティリティまたは iSCSI イニシエータユーティリティを使用して、ホストポート識別子を検索してホストに関連付けることができます。

+
ホストポート識別子を手動で入力するか、ユーティリティ（一度に1つずつ）から* Host Ports *フィールドにコピーアンドペーストできます。

+
ホストポート識別子は、一度に 1 つずつ選択してホストに関連付ける必要がありますが、ホストに関連付けられている識別子をいくつでも選択することができます。各識別子は、 ［ * ホストポート * ］ フィールドに表示されます。必要に応じて、横の * X * を選択して識別子を削除することもできます。





 a| 
CHAPイニシエータ
 a| 
（オプション）iSCSI IQNを使用してホストポートを選択または手動で入力した場合、Challenge Handshake Authentication Protocol（CHAP）を使用して認証するためにストレージアレイへのアクセスを試みるホストが必要な場合は、* CHAP initiator *チェックボックスをオンにします。選択または手動で入力した iSCSI ホストポートごとに、次の手順を実行します。

** CHAP 認証用に各 iSCSI ホストイニシエータに設定されたものと同じ CHAP シークレットを入力します。相互 CHAP 認証（ホストが自身をストレージアレイに対して検証し、ストレージアレイが自身をホストに対して検証できるようにする双方向認証）を使用する場合は、ストレージアレイの初期セットアップまたは設定変更時に CHAP シークレットも設定する必要があります。
** ホストの認証が不要な場合は、このフィールドを空白のままにします。


現在のところ、System Managerで使用されるiSCSI認証方式はCHAPだけです。

|===
====
. [ 作成（ Create ） ] をクリックします。


.結果
ホストの作成が完了すると、ホストに設定されている各ホストポートのデフォルト名（ユーザラベル）が作成されます。

デフォルトのエイリアスは<`Hostname_Port Number``>です。たとえば、「ホスト IPT 」用に作成される最初のポートのデフォルトのエイリアスは、 ipt_1 です。
