---
permalink: sm-storage/create-workloads.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, workloads 
summary: あらゆる種類のアプリケーションのワークロードを作成できます。 
---
= ワークロードの作成
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
あらゆる種類のアプリケーションのワークロードを作成できます。

.このタスクについて
ワークロードは、アプリケーションをサポートするストレージオブジェクトです。アプリケーションごとに1つ以上のワークロードまたはインスタンスを定義できます。一部のアプリケーションでは、特性が似たボリュームで構成されるようにワークロードが設定されます。これらのボリューム特性は、ワークロードがサポートするアプリケーションのタイプに基づいて最適化されます。たとえば、Microsoft SQL Serverアプリケーションをサポートするワークロードを作成し、そのワークロード用のボリュームを作成すると、Microsoft SQL Serverをサポートするようにボリューム特性が最適化されます。

次のアプリケーションタイプにかぎり、System Managerから最適化されたボリューム構成が提示されます。

* Microsoft®SQL Server™
* Microsoft®Exchange Server™
* ビデオ監視
* VMware ESXi™（仮想マシンファイルシステムで使用するボリューム用）


次のガイドラインに注意してください。

* アプリケーション固有のワークロードを使用する場合_は、アプリケーションワークロードのI/Oとアプリケーションインスタンスからの他のトラフィックの競合が最小限になるように最適化されたボリューム構成を推奨します。ボリュームの追加/編集ダイアログボックスを使用して、推奨されるボリューム構成を確認し、システムで推奨されるボリュームや特性を編集、追加、削除できます。
* _他のアプリケーションタイプを使用している場合_ボリュームの追加/編集ダイアログボックスを使用して、ボリューム構成を手動で指定します。


.手順
. 選択メニュー： Storage [Volumes]
. メニューを選択します。Create [Workload]。
+
[アプリケーションワークロードの作成]ダイアログボックスが表示されます。

. ドロップダウンリストを使用してワークロードを作成するアプリケーションのタイプを選択し、ワークロード名を入力します。
. [ 作成（ Create ） ] をクリックします。


.完了後
ワークロードを作成したら、そのワークロードにストレージ容量を追加できます。アプリケーション用に1つ以上のボリュームを作成し、各ボリュームに特定の量の容量を割り当てるには、* Create Volume *オプションを使用します。
