---
permalink: sm-storage/create-ssd-cache.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, ssd, cache 
summary: システムパフォーマンスを向上させるために、SSDキャッシュ機能を使用して、アクセス頻度が特に高いデータ（「ホット」データ）を低レイテンシのソリッドステートドライブ（SSD）にキャッシュすることができます。SSDキャッシュは、ホスト読み取りにのみ使用されます。 
---
= SSDキャッシュを作成する
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
システムパフォーマンスを向上させるために、SSDキャッシュ機能を使用して、アクセス頻度が特に高いデータ（「ホット」データ）を低レイテンシのソリッドステートドライブ（SSD）にキャッシュすることができます。SSDキャッシュは、ホスト読み取りにのみ使用されます。

.作業を開始する前に
ストレージアレイにSSDドライブが含まれている必要があります。

[NOTE]
====
SSDキャッシュは、EF600またはEF300ストレージシステムでは使用できません。

====
.このタスクについて
SSDキャッシュを作成するときは、1つまたは複数のドライブを使用することができます。読み取りキャッシュはストレージアレイ内にあるため、ストレージアレイを使用するすべてのアプリケーションでキャッシュが共有されます。キャッシュするボリュームを選択すると、あとは動的に自動でキャッシングが実行されます。

SSDキャッシュを作成する際は、次のガイドラインに従ってください。

* SSDキャッシュのセキュリティを有効にできるのは作成時だけで、あとから有効にすることはできません。
* SSDキャッシュはストレージアレイごとに1つだけサポートされます。
* ストレージアレイで使用可能なSSDキャッシュの最大容量は、コントローラのプライマリキャッシュ容量で決まります。
* SSDキャッシュはSnapshotイメージではサポートされません。
* SSDキャッシュが有効になっているボリュームや無効になっているボリュームをインポートまたはエクスポートしても、キャッシュデータはインポートまたはエクスポートされません。
* コントローラのSSDキャッシュを使用するように割り当てられたボリュームは、自動ロードバランシングによる転送の対象外となります。
* 関連するボリュームがセキュリティ有効の場合は、セキュリティ有効のSSDキャッシュを作成してください。


.手順
. 選択メニュー：Storage（Pool & Volume Groups）
. メニューをクリックします：Create [SSD Cache]。
+
SSDキャッシュの作成ダイアログボックスが表示されます。

. SSDキャッシュの名前を入力します。
. 次の特性に基づいて使用するSSDキャッシュ候補を選択します。
+
[cols="25h,~"]
|===
| 特性 | 使用 


 a| 
容量
 a| 
使用可能な容量がGiB単位で表示されます。アプリケーションのストレージニーズに応じて容量を選択します。

SSDキャッシュの最大容量は、コントローラのプライマリキャッシュ容量で決まります。SSDキャッシュに最大容量を超える容量を割り当てた場合、超過した容量は使用できません。

SSDキャッシュの容量は、全体の割り当て容量にカウントされます。



 a| 
合計ドライブ数
 a| 
このSSDキャッシュで使用できるドライブの数を示します。必要なドライブ数のSSD候補を選択します。



 a| 
セキュリティ対応
 a| 
SSDキャッシュがセキュリティ対応ドライブだけで構成されているかどうかを示します。セキュリティ対応ドライブには、Full Disk Encryption（FDE）ドライブと連邦情報処理標準（FIPS）ドライブがあります。

セキュリティ有効SSDキャッシュを作成する場合は、「セキュア対応」列で「はい- FDE *」または「はい- FIPS *」を探します。



 a| 
セキュリティを有効化
 a| 
セキュリティ対応ドライブでドライブセキュリティ機能を有効にするオプションです。セキュリティ有効SSDキャッシュを作成する場合は、セキュリティの有効化チェックボックスをオンにします。

[NOTE]
====
一度有効にしたセキュリティを無効にすることはできません。SSDキャッシュのセキュリティを有効にできるのは作成時だけで、あとから有効にすることはできません。

====


 a| 
DA対応
 a| 
このSSDキャッシュ候補でData Assurance（DA）を使用できるかどうかを示します。Data Assurance（DA）は、データがコントローラ経由でドライブに転送される際に発生する可能性があるエラーをチェックして修正します。

DAを使用する場合は、DAに対応したSSDキャッシュ候補を選択します。このオプションはDA機能が有効になっている場合にのみ使用できます。

SSDキャッシュにはDAに対応したドライブとDAに対応していないドライブの両方を含めることができますが、DAを使用するためにはすべてのドライブがDAに対応している必要があります。

|===
. SSD読み取りキャッシュを実装するボリュームにSSDキャッシュを関連付けます。互換性のあるボリュームでSSDキャッシュをすぐに有効にするには、*ホストにマップされている既存の互換性のあるボリュームでSSDキャッシュを有効にする*チェックボックスをオンにします。
+
互換性があるボリュームとは、ドライブセキュリティ機能とDA機能の設定が同じボリュームです。

. [ 作成（ Create ） ] をクリックします。

