---
permalink: sm-storage/create-pool-manually.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, pool, manually 
summary: プールの自動構成機能でニーズに合ったプールが提供されない場合は、プールを（一連の候補から）手動で作成できます。 
---
= プールを手動で作成する
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
プールの自動構成機能でニーズに合ったプールが提供されない場合は、プールを（一連の候補から）手動で作成できます。

プールは必要な論理ストレージ容量を提供します。この容量から個々のボリュームを作成し、アプリケーションをホストすることができます。

.作業を開始する前に
* ドライブタイプ（HDDまたはSSD）が同じドライブが少なくとも11本必要です。
* シェルフ損失の保護を有効にするには、プールを構成するドライブが少なくとも6つのドライブシェルフに配置されていて、同じシェルフのドライブが3本以上含まれていないことが必要です。
* ドロワー損失の保護を有効にするには、プールを構成するドライブが少なくとも5つのドロワーに同じ数ずつ配置されている必要があります。
* EF600またはEF300ストレージアレイを設定する場合は、各コントローラが最初の12個のスロットと直近の12個のスロットに同じ数のドライブにアクセスできることを確認します。この構成により、コントローラは両方のドライブ側PCIeバスをより効果的に使用できます。現在のところ、System Managerでは、ボリュームグループの作成時に詳細設定機能でドライブを選択できます。プールを作成する場合は、ストレージアレイのすべてのドライブを使用することを推奨します。


.手順
. 選択メニュー：Storage（Pool & Volume Groups）
. メニュー：[Create Pool（プールの作成）]をクリックします。
+
Create Pool（プールの作成）ダイアログボックスが表示されます。

. プールの名前を入力します。
. *オプション：ストレージアレイに複数のタイプのドライブがある場合、使用するドライブタイプを選択します。
+
作成可能なすべてのプールの候補が表示されます。

. 次の特性に基づいて使用するプール候補を選択し、*作成*をクリックします。
+
[cols="25h,~"]
|===
| 特性 | 使用 


 a| 
空き容量
 a| 
プールの空き容量がGiB単位で表示されます。アプリケーションのストレージニーズに応じて、必要な容量のプール候補を選択します。

予約済み（スペア）容量もプール全体に分散され、空き容量に含まれることはありません。



 a| 
合計ドライブ数
 a| 
プール候補に含まれるドライブの数が表示されます。

System Managerは、できるだけ多くのドライブを予約済み容量として自動的に確保します（System Managerではプール内の6本につき1本のドライブを予約済み容量として確保します）。

ドライブ障害が発生すると、予約済み容量を使用して再構築されたデータが格納されます。



 a| 
ドライブブロックサイズ（EF300およびEF600のみ）
 a| 
プール内のドライブが書き込めるブロックサイズ（セクターサイズ）が表示されます。値は次のとおりです。

** 512 -- 512バイトのセクターサイズ。
** 4K -- 4、096バイトのセクターサイズ。




 a| 
セキュリティ対応
 a| 
プール候補がセキュリティ対応ドライブだけで構成されているかどうかを示します。セキュリティ対応ドライブには、Full Disk Encryption（FDE）ドライブと連邦情報処理標準（FIPS）ドライブがあります。

** プールはドライブセキュリティを使用して保護できますが、この機能を使用するには、すべてのドライブがセキュリティ対応である必要があります。
** FDEのみのプールを作成する場合は、SecureCapable列で「* Yes-fde」を検索してください。FIPSのみのプールを作成する場合は、「はい- FIPS *」または「はい- FIPS（混在）」を探します。「Mixed」は140-2と140-3レベルのドライブが混在していることを示します。これらのレベルを組み合わせて使用する場合は、プールが下位レベルのセキュリティ（140～2）で動作することに注意してください。
** セキュリティ対応かどうかがドライブによって異なるプールや、セキュリティレベルが異なるドライブが混在したプールを作成することもできます。プールにセキュリティ対応でないドライブが含まれている場合、プールをセキュリティ対応にすることはできません。




 a| 
セキュリティを有効化
 a| 
セキュリティ対応ドライブでドライブセキュリティ機能を有効にするオプションです。プールがセキュリティ対応で、セキュリティキーを作成している場合、チェックボックスを選択してセキュリティを有効にできます。

[NOTE]
====
一度有効にしたドライブセキュリティは、プールを削除してドライブを消去しないかぎり解除できません。

====


 a| 
DA対応
 a| 
プール候補でData Assurance（DA）を使用できるかどうかを示します。DAは、データがコントローラ経由でドライブに転送される際に発生する可能性があるエラーをチェックして修正します。

DAはすべてのドライブがDAに対応している場合に有効になります。DAは、ボリュームの作成後にメニューを選択して無効にすることができます。Storage [Volumes]、[View/Edit Settings]、[Advanced]、[Permanently disable Data Assurance（データ保護を完全に無効にする）]。DAがボリュームで無効になっている場合、再度有効にすることはできません。



 a| 
リソースプロビジョニング対応（EF300およびEF600のみ）
 a| 
プール候補でリソースプロビジョニングを使用できるかどうかを示します。リソースプロビジョニングは、EF300およびEF600ストレージアレイで使用できる機能です。これにより、バックグラウンドの初期化プロセスを実行せずに、ボリュームをただちに使用できます。



 a| 
シェルフ損失の保護
 a| 
シェルフ損失の保護が使用可能かどうかを示します。

シェルフ損失の保護が有効な場合、1台のドライブシェルフとの通信が完全に失われた場合でもプール内のボリューム上のデータへのアクセスが保証されます。



 a| 
ドロワー損失の保護
 a| 
ドロワー損失の保護が使用可能かどうかを示します。この保護は、使用しているドライブシェルフにドロワーが搭載されている場合にのみ提供されます。

ドロワー損失の保護が有効な場合、ドライブシェルフの1台のドロワーとの通信が完全に失われた場合でもプール内のボリューム上のデータへのアクセスが保証されます。



 a| 
サポートされるボリュームのブロックサイズ（EF300およびEF600のみ）
 a| 
プール内のボリュームに対して作成できるブロックサイズが表示されます。

** 512n -- 512バイトネイティブ。
** 512e -- 512バイトエミュレーション。
** 4k -- 4,096バイト


|===

