---
permalink: sm-storage/decide-to-use-a-pool-or-volume-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, pool, volume group 
summary: ボリュームはプールまたはボリュームグループを使用して作成できます。どちらが適しているかは、主に、予想されるI/Oワークロードなどの主要なストレージ要件、パフォーマンス要件、データ保護要件によって決まります。 
---
= SANtricity ソフトウェアのプールとボリューム グループについて学習します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリュームはプールまたはボリュームグループを使用して作成できます。どちらが適しているかは、主に、予想されるI/Oワークロードなどの主要なストレージ要件、パフォーマンス要件、データ保護要件によって決まります。



== プールまたはボリュームグループを選択する理由

*プールを選択*

* ドライブのリビルド時間を短縮し、ストレージ管理を簡易化する必要がある場合、シンボリュームが必要な場合、大量のランダムワークロードが発生している場合。
* 各ボリュームのデータをプールを構成する一連のドライブにランダムに分散する場合。
+
プールまたはプール内のボリュームのRAIDレベルは設定または変更できません。プールではRAIDレベル6を使用します。



*ボリュームグループを選択*

* システムの帯域幅を最大限に使用する必要がある場合、ストレージの設定を調整する機能、大量のシーケンシャルワークロードを利用する場合。
* データをRAIDレベルに基づいてドライブに分散する場合。ボリュームグループは作成時にRAIDレベルを指定できます。
* 各ボリュームのデータをボリュームグループを構成する一連のドライブにシーケンシャルに書き込む場合。


[NOTE]
====
プールとボリュームグループは共存可能なため、ストレージアレイにプールとボリュームグループの両方を含めることができます。

====


== プールとボリュームグループの機能の違い

次の表に、ボリュームグループとプールの機能の比較を示します。

[cols="1a,1a,1a"]
|===
| 使用 | プール | ボリュームグループ 


 a| 
ランダムワークロード
 a| 
より良い
 a| 
良好です



 a| 
シーケンシャルワークロード
 a| 
良好です
 a| 
より良い



 a| 
ドライブのリビルド時間
 a| 
高速化
 a| 
遅い



 a| 
パフォーマンス（最適モード）
 a| 
良い：小さなブロックのランダムワークロードに最適
 a| 
良い：大きなブロックのシーケンシャルワークロードに最適



 a| 
パフォーマンス（ドライブリビルドモード）
 a| 
より良い：通常はRAID 6よりも良い
 a| 
Degraded：パフォーマンスが最大40%低下します



 a| 
複数のドライブ障害が発生した場合
 a| 
データ保護機能に優れる：リビルドを優先し、高速に処理
 a| 
データ保護機能が劣る：リビルドが遅く、データ損失のリスクが大きい



 a| 
ドライブの追加
 a| 
速い：オンザフライでプールに追加できます
 a| 
遅い：Dynamic Capacity Expansion処理が必要です



 a| 
シンボリュームがサポートされます
 a| 
はい。
 a| 
いいえ



 a| 
ソリッドステートディスク（SSD）のサポート
 a| 
はい。
 a| 
はい。



 a| 
管理の簡易化
 a| 
○：ホットスペアやRAID設定の構成は不要
 a| 
×：ホットスペアを割り当ててRAIDを設定する必要があります



 a| 
パフォーマンスの調整
 a| 
いいえ
 a| 
はい。

|===


== プールとボリュームグループの機能比較

プールとボリュームグループの機能と目的は同じです。どちらのオブジェクトも、ストレージアレイ内で論理的にグループ化されている一連のドライブであり、ホストがアクセス可能なボリュームを作成するために使用されます。

次の表は、プールとボリュームグループのどちらがストレージニーズに適しているかを判断する際に役立ちます。

[cols="1a,1a,1a"]
|===
| 機能 | プール | ボリュームグループ 


 a| 
異なるRAIDレベルがサポートされています
 a| 
いいえSystem Managerでは常にRAID 6を使用します。
 a| 
はい。RAID 0、1、10、5、6を使用可能。



 a| 
シンボリュームがサポートされています
 a| 
はい。
 a| 
いいえ



 a| 
Full Disk Encryption（FDE）がサポートされる
 a| 
はい。
 a| 
はい。



 a| 
Data Assurance（DA）がサポートされています
 a| 
はい。
 a| 
はい。



 a| 
シェルフ損失の保護がサポートされます
 a| 
はい。
 a| 
はい。



 a| 
ドロワー損失の保護がサポートされます
 a| 
はい。
 a| 
はい。



 a| 
ドライブ速度混在のサポート
 a| 
同じにすることを推奨しますが、必須ではありません。一番低速のドライブにすべてのドライブの速度が合わせられます。
 a| 
同じにすることを推奨しますが、必須ではありません。一番低速のドライブにすべてのドライブの速度が合わせられます。



 a| 
ドライブ容量混在がサポートされています
 a| 
同じにすることを推奨しますが、必須ではありません。一番容量の少ないドライブにすべてのドライブの容量が合わせられます。
 a| 
同じにすることを推奨しますが、必須ではありません。一番容量の少ないドライブにすべてのドライブの容量が合わせられます。



 a| 
最小ドライブ数
 a| 
11.
 a| 
RAIDレベルによって異なります。RAID 0には1本必要RAID 1または10には2本（偶数）必要。RAID 5の最小数は3RAID 6の最小数は5



 a| 
ドライブの最大数
 a| 
ストレージアレイの上限まで
 a| 
RAID 1および10：ストレージアレイのRAID 5、6～30ドライブの最大数



 a| 
ボリュームの作成時に個々のドライブを選択できます
 a| 
いいえ
 a| 
はい。



 a| 
ボリュームの作成時にセグメントサイズを指定可能
 a| 
はい。128Kをサポート。
 a| 
はい。



 a| 
ボリュームの作成時にI/O特性を指定できます
 a| 
いいえ
 a| 
はい。ファイルシステム、データベース、マルチメディア、カスタムをサポート。



 a| 
ドライブ障害からの保護
 a| 
プール内の各ドライブの予約済み容量を使用し、再構築にかかる時間を短縮。
 a| 
ホットスペアドライブを使用します。再構築はドライブのIOPSによって制限されます。



 a| 
容量制限に達したときの警告
 a| 
はい。使用済み容量が最大容量の一定の割合に達したときにアラートを設定できる。
 a| 
いいえ



 a| 
別のストレージアレイへの移行をサポート
 a| 
いいえ最初にボリュームグループに移行する必要があります。
 a| 
はい。



 a| 
動的セグメントサイズ（DSS）
 a| 
いいえ
 a| 
はい。



 a| 
RAIDレベルを変更できます
 a| 
いいえ
 a| 
はい。



 a| 
ボリュームの拡張（容量の拡張）
 a| 
はい。
 a| 
はい。



 a| 
容量の拡張（容量の追加）
 a| 
はい。
 a| 
はい。



 a| 
容量の削減
 a| 
はい。
 a| 
いいえ

|===
[NOTE]
====
ドライブタイプ（HDD、SSD）の混在は、プールでもボリュームグループでもサポートされていません。

====