---
permalink: sm-storage/decrease-reserved-capacity.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, decrease, reserved, capacity 
summary: 容量の削減オプションを使用して、Snapshotグループ、Snapshotボリューム、整合性グループのメンバーボリュームなど、次のストレージオブジェクトのリザーブ容量を削減します。リザーブ容量は、増やしたときの分量ずつしか減らすことができません。 
---
= リザーブ容量を削減します
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
容量の削減オプションを使用して、Snapshotグループ、Snapshotボリューム、整合性グループメンバーボリュームの各ストレージオブジェクトのリザーブ容量を削減します。リザーブ容量は、増やしたときの分量ずつしか減らすことができません。

.作業を開始する前に
* ストレージオブジェクトに複数のリザーブ容量ボリュームが含まれている必要があります。
* ストレージオブジェクトがミラーペアのボリュームでないことを確認する必要があります。
* ストレージオブジェクトがSnapshotボリュームの場合は、Snapshotボリュームの状態がDisabledである必要があります。
* ストレージオブジェクトがSnapshotグループの場合は、関連付けられたSnapshotイメージが含まれていないことを確認する必要があります。


.このタスクについて
次のガイドラインを確認してください。

* リザーブ容量ボリュームは、追加したときと逆の順序でのみ削除できます。
* 読み取り専用のSnapshotボリュームについては、関連付けられたリザーブ容量がないため、リザーブ容量を削減することはできません。リザーブ容量が必要なのは、読み取り/書き込みのSnapshotボリュームだけです。


.手順
. 選択メニュー：Storage（Pool & Volume Groups）
. 予約容量*タブをクリックします。
. リザーブ容量を削減するストレージオブジェクトを選択し、*容量の削減*をクリックします。
+
リザーブ容量の削減ダイアログボックスが表示されます。

. リザーブ容量を削減する容量を選択し、*削減*をクリックします。


.結果
System Managerは次の処理を実行します。

* ストレージオブジェクトの容量を更新します。
* ストレージオブジェクトの更新後の新しいリザーブ容量を表示します。
* Snapshotボリュームの容量を削減すると、System ManagerはSnapshotボリュームの状態を自動的に無効に移行します。無効の場合、Snapshotボリュームは現在Snapshotイメージに関連付けられておらず、したがってI/O処理用にホストに割り当てることはできません

