---
permalink: sm-storage/delete-snapshot-consistency-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, delete, snapshot, consistency, group 
summary: 不要になったSnapshot整合性グループを削除することができます。 
---
= Snapshot整合性グループを削除します
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
不要になったSnapshot整合性グループを削除することができます。

.作業を開始する前に
すべてのメンバーボリュームのイメージについて、バックアップやテストに使用する必要がなくなったことを確認します。

.このタスクについて
この処理を実行すると、Snapshot整合性グループに関連付けられているすべてのSnapshotイメージまたはスケジュールが削除されます。

.手順
. メニューを選択します。Storage [Snapshots]。
. スナップショット・コンシステンシ・グループ*タブを選択します
. 削除するSnapshot整合性グループを選択し、メニューから「一般的でないタスク」「削除」を選択します。
+
Confirm Delete Snapshot Consistency Group（スナップショット整合グループの削除の確認）ダイアログボックスが表示されます。

. この処理を実行することを確認し、* Delete *をクリックします。


.結果
System Managerは次の処理を実行します。

* Snapshot整合性グループから既存のSnapshotイメージとSnapshotボリュームをすべて削除します。
* Snapshot整合性グループの各メンバーボリュームに関連付けられているSnapshotイメージを削除します。
* Snapshot整合性グループの各メンバーボリュームに関連付けられているSnapshotボリュームを削除します。
* Snapshot整合性グループの各メンバーボリュームに関連付けられているリザーブ容量をすべて削除します（選択した場合）。

