---
permalink: sm-storage/delete-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, delete, volume 
summary: ボリュームを削除する一般的な状況としては、作成したボリュームのパラメータや容量に誤りがあった場合、ストレージ構成のニーズを満たさなくなった場合、バックアップやアプリケーションのテストに必要なくなったSnapshotイメージがある場合などがあります。 
---
= ボリュームを削除します
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリュームを削除する一般的な状況としては、作成したボリュームのパラメータや容量に誤りがあった場合、ストレージ構成のニーズを満たさなくなった場合、バックアップやアプリケーションのテストに必要なくなったSnapshotイメージがある場合などがあります。

ボリュームを削除すると、プールまたはボリュームグループの空き容量が増えます。削除するボリュームを1つ以上選択できます。

.作業を開始する前に
削除するボリュームで、次の点を確認します。

* すべてのデータがバックアップされます。
* すべての入出力（I/O）が停止しています。
* デバイスとファイルシステムがアンマウントされている。


.このタスクについて
次のいずれかの条件に該当するボリュームは削除できません。

* ボリュームが初期化中である。
* ボリュームが再構築中である。
* ボリュームが属するボリュームグループにコピーバック処理を実行中のドライブが含まれている。
* ボリュームのステータスが失敗になった場合を除き、セグメントサイズの変更などの変更処理を実行中です。
* ボリュームにいずれかのタイプの永続的予約が設定されている。
* ボリュームがボリュームコピー処理のソースボリュームまたはターゲットボリュームで、処理のステータスが「保留」、「実行中」、または「失敗」である。


[CAUTION]
====
ボリュームを削除すると、それらのボリューム上のすべてのデータが失われます。

====
[NOTE]
====
ボリュームのサイズが一定（現在は128TB）を超えた場合、削除はバックグラウンドで実行されており、解放されたスペースをすぐに使用できるとは限りません。

====
.手順
. 選択メニュー： Storage [Volumes]
. [ 削除（ Delete ） ] をクリックします。
+
ボリュームの削除ダイアログボックスが表示されます。

. 削除するボリュームを1つ以上選択し、処理を確定します。
. [ 削除（ Delete ） ] をクリックします。


.結果
System Managerは次の処理を実行します。

* 関連付けられているSnapshotイメージ、スケジュール、およびSnapshotボリュームを削除します。
* ミラーリング関係を削除します。
* プールまたはボリュームグループの空き容量を増やします。

