---
permalink: sm-storage/disable-resource-provisioning-on-existing-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, disable, resource provisioning, 
summary: 既存のプールまたはボリュームグループでリソースのプロビジョニングを有効または無効にすることができます。 
---
= 既存のボリュームグループおよびプールでリソースのプロビジョニングを有効または無効にします
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
DULBE対応ドライブの場合は、プールまたはボリュームグループ内の既存のボリュームでリソースプロビジョニングを有効または無効にすることができます。

リソースプロビジョニングは、EF300およびEF600ストレージアレイで使用できる機能です。これにより、バックグラウンドの初期化プロセスを実行せずに、ボリュームをただちに使用できます。ボリュームに割り当てられているすべてのドライブブロックの割り当てが解除され（マッピング解除）、SSDの寿命が延び、書き込みパフォーマンスが最大化されます。

デフォルトでは、ドライブがDULBEをサポートするシステムでリソースプロビジョニングが有効になっています。リソースプロビジョニングを有効にする必要はありません。ただし、事前に無効にしておく必要があります。

.作業を開始する前に
* EF300またはEF600ストレージアレイが必要です。
* SSDボリュームグループまたはプールが必要です。このプールでは、すべてのドライブがNVMe Deallocated or Unwritten Logical Block Error（DULBE）エラーリカバリ機能をサポートしています。そうしないと、リソースプロビジョニングオプションを使用できません。


.このタスクについて
既存のボリュームグループおよびプールでリソースのプロビジョニングを有効にすると、選択したボリュームグループまたはプール内のすべてのボリュームが変更され、ブロックの割り当てが解除されます。このプロセスでは、UNMAP単位で一貫した割り当てを行うためにバックグラウンド処理が必要になることがあります。この処理では、スペースについてマッピングは解除されません。バックグラウンド処理が完了したら、オペレーティングシステムで未使用ブロックのマッピングを解除して空きスペースを確保する必要があります。

既存のボリュームグループまたはプールのリソースプロビジョニングを無効にすると、バックグラウンド処理によってすべてのボリューム内のすべての論理ブロックが書き換えられます。既存データはそのまま維持されます。書き込みは、ボリュームグループまたはプールに関連付けられたドライブ上のブロックをマッピングまたはプロビジョニングします。


NOTE: 新しいボリュームグループおよびプールについては、メニューからリソースのプロビジョニングを有効または無効にできます。設定[システム]、[追加設定]、[リソースプロビジョニングボリュームの有効化/無効化]の順に選択します。

.手順
. 選択メニュー：Storage（Pool & Volume Groups）
. リストからプールまたはボリュームグループを1つ選択します。
+
プールまたはボリュームグループは一度に1つだけ選択できます。リストを下にスクロールして、他のプールまたはボリュームグループを確認します。

. [一般的でないタスク]を選択し、[リソースプロビジョニングを有効にする]または[リソースプロビジョニングを無効にする]のいずれかを選択します。
. ダイアログボックスで、処理を確認します。



NOTE: *DULBEを再度有効にした場合--バックグラウンド処理が完了した後'ホストを再起動してDULBE設定の変更を検出し'すべてのファイルシステムを再マウントする必要がある場合があります
