---
permalink: sm-storage/disable-resource-provisioning-on-existing-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, disable, resource provisioning, 
summary: 既存のプールまたはボリュームグループでリソースのプロビジョニングを有効または無効にすることができます。 
---
= SANtricity System Manager で既存のボリューム グループとプールのリソース プロビジョニングを有効または無効にする
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
DULBE対応ドライブの場合は、プールまたはボリュームグループ内の既存のボリュームでリソースプロビジョニングを有効または無効にすることができます。

リソースプロビジョニングは、EF80、EF50、EF300/EF300C、およびEF600/EF600Cストレージアレイで利用可能な機能であり、バックグラウンドでの初期化プロセスなしでボリュームをすぐに使用できるようになります。ボリュームに割り当てられていたすべてのドライブブロックが解放（マッピング解除）されるため、SSDの寿命が延び、最大書き込み性能が向上する可能性があります。

デフォルトでは、ドライブがDULBEをサポートするシステムでリソースプロビジョニングが有効になっています。リソースプロビジョニングを有効にする必要はありません。ただし、事前に無効にしておく必要があります。

.作業を開始する前に
* EF80、EF50、EF300、またはEF600ストレージアレイが必要です。
* SSDボリュームグループまたはプールが必要です。このプールでは、すべてのドライブがNVMe Deallocated or Unwritten Logical Block Error（DULBE）エラーリカバリ機能をサポートしています。そうしないと、リソースプロビジョニングオプションを使用できません。


.このタスクについて
既存のボリュームグループおよびプールでリソースのプロビジョニングを有効にすると、選択したボリュームグループまたはプール内のすべてのボリュームが変更され、ブロックの割り当てが解除されます。このプロセスでは、UNMAP単位で一貫した割り当てを行うためにバックグラウンド処理が必要になることがあります。この処理では、スペースについてマッピングは解除されません。バックグラウンド処理が完了したら、オペレーティングシステムで未使用ブロックのマッピングを解除して空きスペースを確保する必要があります。

既存のボリュームグループまたはプールのリソースプロビジョニングを無効にすると、バックグラウンド処理によってすべてのボリューム内のすべての論理ブロックが書き換えられます。既存データはそのまま維持されます。書き込みは、ボリュームグループまたはプールに関連付けられたドライブ上のブロックをマッピングまたはプロビジョニングします。


NOTE: 新しいボリュームグループおよびプールについては、メニューからリソースのプロビジョニングを有効または無効にできます。設定[システム]、[追加設定]、[リソースプロビジョニングボリュームの有効化/無効化]の順に選択します。

.手順
. 左側のパネルから、メニュー：Storage[Pools and volume groups]を選択します。
. *ellipsis*アイコンをクリックし、選択したプールまたはボリュームグループに対して*Enable resource provisioning*または*Disable resource provisioning*のいずれかを選択します。
. ダイアログボックスで、処理を確認します。



NOTE: *DULBEを再度有効にした場合--バックグラウンド処理が完了した後'ホストを再起動してDULBE設定の変更を検出し'すべてのファイルシステムを再マウントする必要がある場合があります
