---
permalink: sm-storage/enable-security.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, enable, security, pool, volume group 
summary: プールまたはボリュームグループのドライブセキュリティを有効にして、プールまたはボリュームグループに含まれているドライブ上のデータへの不正アクセスを防止できます。ドライブの読み取りおよび書き込みアクセスは、セキュリティキーが設定されたコントローラからのみ可能です。 
---
= プールまたはボリュームグループのセキュリティを有効にします
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
プールまたはボリュームグループのドライブセキュリティを有効にして、プールまたはボリュームグループに含まれているドライブ上のデータへの不正アクセスを防止できます。ドライブの読み取りおよび書き込みアクセスは、セキュリティキーが設定されたコントローラからのみ可能です。

.作業を開始する前に
* ドライブセキュリティ機能を有効にする必要があります。
* セキュリティキーを作成する必要があります。
* プールまたはボリュームグループの状態が最適lである必要があります。
* プールまたはボリュームグループ内のすべてのドライブがセキュリティ対応である必要があります。


.このタスクについて
ドライブセキュリティを使用する場合は、セキュリティ対応のプールまたはボリュームグループを選択します。プールまたはボリュームグループにはセキュリティ対応とセキュリティ対応でないドライブの両方を含めることができますが、暗号化機能を使用するためにはすべてのドライブがセキュリティ対応である必要があります。

一度有効にしたセキュリティを解除するには、プールまたはボリュームグループを削除してからドライブを消去する必要があります。

.手順
. 選択メニュー：Storage（Pool & Volume Groups）
. セキュリティを有効にするプールまたはボリュームグループを選択し、[メニュー:その他のセキュリティの有効化]をクリックします。
+
[セキュリティの有効化の確認]ダイアログボックスが表示されます。

. 選択したプールまたはボリュームグループのセキュリティを有効にすることを確認し、*有効*をクリックします。

