---
permalink: sm-storage/faq-pools-volume-groups.html 
sidebar: sidebar 
keywords:  
summary: この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。 
---
= SANtricity System Manager のプールとボリューム グループに関する FAQ
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。



== ボリュームグループとは何ですか？

ボリュームグループは、同じ特性を持つボリュームのコンテナです。ボリュームグループごとに容量とRAIDレベルが定義されています。ボリュームグループを使用して、ホストにアクセス可能な1つ以上のボリュームを作成することができます。（ボリュームはボリュームグループまたはプールから作成します）。



== プールとは何ですか？

プールは、論理的にグループ化された一連のドライブです。プールを使用して、ホストにアクセス可能な 1 つ以上のボリュームを作成することができます。（ボリュームはプールまたはボリュームグループから作成します）。

プールを使用すると、管理者が各ホストの使用状況を監視して、ストレージスペースが不足する可能性があるタイミングを判断する必要がなくなり、従来のようなディスクサイズの変更に伴うシステム停止もありません。プールの容量が不足してきたらシステムを停止せずにプールにドライブを追加することができ、ホストには透過的に容量が拡張されます。

プールを使用すると、データは自動的に再分散されてバランスが維持されます。パリティ情報とスペア容量がプール全体に分散されるため、プール内のすべてのドライブを障害が発生したドライブの再構築に使用できます。このアプローチでは専用のホットスペアドライブは使用されません。代わりに、予約済み（スペア）容量がプール全体で確保されます。ドライブ障害が発生すると、他のドライブのセグメントが読み取られてデータが再作成されます。その後、新しいドライブが選択されて障害が発生したドライブにあった各セグメントが書き込まれるため、ドライブ間のデータ分散は維持されます。



== リザーブ容量とは何ですか？

リザーブ容量は物理的に割り当てられた容量で、Snapshotイメージ、整合性グループメンバーボリューム、ミラーペアボリュームなどのコピーサービスオブジェクトのデータの格納に使用されます。

コピーサービス処理に関連付けられているリザーブ容量ボリュームは、プールまたはボリュームグループに配置されます。リザーブ容量は、プールまたはボリュームグループから作成します。



== FDE / FIPSセキュリティとは何ですか？

FDE / FIPSセキュリティとは、一意の暗号化キーを使用して書き込み時にデータを暗号化し、読み取り時に復号化するセキュリティ対応ドライブを指します。セキュリティ対応ドライブは、ストレージアレイから物理的に取り外されたドライブ上のデータへの不正アクセスを防止します。

セキュリティ対応ドライブには、Full Disk Encryption（FDE）ドライブと連邦情報処理標準（FIPS）ドライブがあります。FIPSドライブは認定テストをパスしたドライブです。

[NOTE]
====
FIPSのサポートが必要なボリュームには、FIPSドライブのみを使用します。ボリュームグループまたはプールにFIPSドライブとFDEドライブが混在している場合、すべてのドライブがFDEドライブとして扱われます。また、FIPSドライブのみを含むボリュームグループまたはプールでは、FDEドライブを追加したりスペアとして使用したりすることはできません。

====


== 冗長性チェックとは何ですか？

冗長性チェックでは、プールまたはボリュームグループ内のボリューム上のデータに整合性があるかどうかが判別されます。冗長性データは、プールまたはボリュームグループ内のいずれかのドライブで障害が発生した場合に、交換用ドライブに迅速に情報を再構築するために使用されます。

このチェックは、一度に1つのプールまたはボリュームグループでのみ実行できます。ボリュームの冗長性チェックでは、次の処理が実行されます。

* RAID 3ボリューム、RAID 5ボリューム、またはRAID 6ボリューム内のデータブロックがスキャンされ、各ブロックの冗長性情報がチェックされます。（RAID 3をボリュームグループに割り当てるには、コマンドラインインターフェイスを使用する必要があります）。
* RAID 1のミラーリングされたドライブ上のデータブロックが比較されます。
* データに整合性がないことがコントローラファームウェアで確認された場合は、冗長性エラーが返されます。


[NOTE]
====
同じプールまたはボリュームグループですぐに冗長性チェックを実行すると、原因 でエラーが発生する場合があります。この問題を回避するには、同じプールまたはボリュームグループで別の冗長性チェックを実行する前に、1~2分待ってください。

====


== プールとボリュームグループの違いは何ですか？

プールはボリュームグループに似ていますが、次の点が異なります。

* プール内のデータは、同じ一連のドライブに格納されるボリュームグループ内のデータとは異なり、プール内のすべてのドライブにランダムに格納されます。
* プールの方がドライブ障害時のパフォーマンスの低下と再構築にかかる時間が少なくなります。
* プールには予約済み容量が組み込まれているため、専用のホットスペアドライブは必要ありません。
* プールでは多数のドライブをグループ化できます。
* プールにはRAIDレベルを指定する必要はありません。




== プールを手動で設定するのはどのような場合ですか？

プールを手動で設定する理由を、次の例に示します。

* ストレージアレイ上に複数のアプリケーションがあり、それらのアプリケーションと同じドライブリソースの競合が発生しないようにする場合は、1つ以上のアプリケーション用に小規模なプールを手動で作成することを検討してください。
+
データを分散するための多数のボリュームを含む大規模なプールにワークロードを割り当てるのではなく、1~2個のボリュームだけを割り当てることができます。特定のアプリケーションのワークロード専用の個別のプールを手動で作成すると、ストレージアレイの処理をより迅速に実行でき、競合が軽減されます。

+
プールを手動で作成するには、「* Storage *」を選択し、「* Pools & Volume Groups」を選択します。All Capacity（すべての容量）タブで、MENU（メニュー）：Create（プール）をクリックします。

* 同じドライブタイプのプールが複数ある場合は、System Managerでプールに使用するドライブを自動的に推奨できないことを示すメッセージが表示されます。ただし、既存のプールに手動でドライブを追加することはできます。
+
既存のプールにドライブを手動で追加するには：プールとボリュームグループページでプールを選択し、*容量の追加*をクリックします。





== 容量アラートが重要なのはなぜですか？

容量アラートは、ドライブをプールに追加するタイミングを示します。ストレージアレイの処理を正常に実行するには、プールに十分な空き容量が必要です。プールの空き容量が指定した割合以上になったときにアラートを送信するようにSANtricity System Managerを設定すると、これらの処理の中断を回避できます。

プールの作成時にこの割合を設定するには、* Pool auto-configuration *オプションまたは* Create pool *オプションを使用します。自動オプションを選択すると、アラート通知を受信するタイミングはデフォルト設定によって自動的に決まります。プールを手動で作成する場合は、アラート通知の設定を指定します。必要に応じて、デフォルトの設定をそのまま使用することもできます。これらの設定は、後で「Settings [Alerts]」（設定[Alerts]）メニューで調整できます。

[NOTE]
====
プールの空き容量が指定した割合に達すると、アラート設定に指定した方法でアラート通知が送信されます。

====


== 予約済み容量を増やせない場合、どのような理由が考えられますか?

使用可能なすべての容量でボリュームを作成した場合は、予約済み容量を増やせないことがあります。

予約済み容量は、ドライブ障害に備えてプール内に確保されている容量（ドライブ数）です。プールが作成されると、プール内のドライブ数に応じて自動的にデフォルトの予約済み容量が確保されます。使用可能なすべての容量でボリュームを作成している場合は、ドライブを追加するかボリュームを削除してプールに容量を追加しないと、予約済み容量を増やすことはできません。

予約済み容量は* Pools & Volume Groups *から変更できます。編集するプールを選択します。[設定の表示/編集]をクリックし、[*設定*]タブを選択します。

[NOTE]
====
予約済み容量はプール内の複数のドライブに分散されますが、予約するときはドライブ数で指定します。

====


== プールから削除できるドライブの数に制限はありますか。

SANtricity System Managerでは、プールから削除できるドライブ数の制限が設定されています。

* プール内のドライブの数を11本より少なくすることはできません。
* 削除対象のドライブに含まれるデータがプール内の残りのドライブに再配置される場合、そのデータを十分に格納できる空き容量がプール内にない場合は、そのドライブは削除できません。
* 一度に削除できるドライブは最大60本です。60本を超えるドライブを選択した場合、ドライブの削除オプションは無効になります。60本を超えるドライブを取り外す必要がある場合は、ドライブの取り外し処理を繰り返します。




== ドライブでサポートされているメディアタイプを教えてください。

サポートされているメディアタイプは、ハードディスクドライブ（HDD）とソリッドステートディスク（SSD）です。



== 一部のドライブが表示されないのはなぜですか？

容量の追加ダイアログで、既存のプールまたはボリュームグループに容量を追加できるドライブがすべて表示されるわけではありません。

ドライブを追加できない理由は次のとおりです。

* 未割り当てで、セキュリティ有効でないドライブを指定する必要があります。すでに別のプールやボリュームグループに含まれているドライブ、またはホットスペアとして設定されているドライブは使用できません。未割り当てだが、セキュリティ有効なドライブは、手動で消去すると使用可能になります。
* 最適な状態でないドライブは使用できません。
* 容量が小さすぎるドライブは使用できません。
* プールまたはボリュームグループ内でドライブのメディアタイプが一致している必要があります。次のものを混在させることはできません。
+
** ソリッドステートディスク（SSD）搭載のハードディスクドライブ（HDD）
** NVMeとSASドライブ
** ボリュームブロックサイズが512バイトおよび4KiBのドライブ


* プールまたはボリュームグループに含まれているドライブがすべてセキュリティ対応の場合は、セキュリティ対応でないドライブは表示されません。
* プールまたはボリュームグループに含まれているドライブがすべて連邦情報処理標準（FIPS）ドライブの場合、非FIPSドライブは表示されません。
* プールまたはボリュームグループに含まれているドライブがすべてData Assurance（DA）対応で、プールまたはボリュームグループにDA有効ボリュームが1つ以上ある場合は、DA非対応のドライブは使用できないためプールまたはボリュームグループに追加できません。ただし、プールまたはボリュームグループにDA有効ボリュームがない場合は、DA非対応のドライブをプールまたはボリュームグループに追加できます。DA対応と非対応のドライブが混在している場合は、DA対応ボリュームを作成できないことに注意してください。


[NOTE]
====
ストレージアレイの容量は、新しいドライブを追加するか、プールまたはボリュームグループを削除することで増やすことができます。

====


== シェルフ/ドロワー損失の保護を維持するにはどうすればよいですか？

プールまたはボリュームグループのシェルフ/ドロワー損失の保護を維持するには、次の表の基準を使用します。

[cols="1a,1a,1a"]
|===
| レベル | シェルフ/ドロワー損失の保護の基準 | 必要なシェルフ/ドロワーの最小数 


 a| 
プール
 a| 
シェルフの場合、プールに同じシェルフのドライブが3本以上含まれない。

ドロワーの場合、プールに各ドロワーから同数のドライブが含まれている。
 a| 
シェルフの場合は6

ドロワーの場合は5



 a| 
RAID 6
 a| 
ボリュームグループに同じシェルフまたはドロワーのドライブが3本以上含まれない。
 a| 
3.



 a| 
RAID 3またはRAID 5
 a| 
ボリュームグループ内のドライブがすべて別々のシェルフまたはドロワーに配置されている。
 a| 
3.



 a| 
RAID 1
 a| 
ミラーペア内のドライブがそれぞれ別のシェルフまたはドロワーに配置されている。
 a| 
2.



 a| 
RAID 0
 a| 
シェルフ/ドロワー損失の保護は実現できない。
 a| 
該当なし

|===
[NOTE]
====
プールまたはボリュームグループですでにドライブに障害が発生している場合は、シェルフ/ドロワー損失の保護は維持されません。この状況で、ドライブシェルフまたはドロワーへのアクセス、さらにその結果プールまたはボリュームグループ内の別のドライブへのアクセスを失うと、データが失われます。

====


== プールとボリュームグループの最適なドライブ配置は何ですか？

プールおよびボリュームグループを作成するときは、ドライブの選択範囲を上下のドライブスロットに合わせて調整してください。

EF600およびEF300コントローラの場合、ドライブスロット0~11は1つのPCIブリッジに接続され、スロット12~23は別のPCIブリッジに接続されます。最適なパフォーマンスを確保するには、ドライブを選択した際に、上下のスロットから同数のドライブを選択する必要があります。この配置により、ボリュームが必要以上に短い時間で帯域幅の上限に達しないようにすることができます。



== アプリケーションに最適なRAIDレベルはどれですか？

ボリュームグループのパフォーマンスを最大限に高めるには、適切なRAIDレベルを選択する必要があります。適切なRAIDレベルを特定するには、ボリュームグループにアクセスしているアプリケーションでの読み取りと書き込みの割合を把握します。これらの割合を取得するには、[パフォーマンス]ページを使用します。



=== RAIDレベルとアプリケーションパフォーマンス

RAIDには、_levels _という一連の構成が採用されており、ユーザデータと冗長性データのドライブに対する書き込み/読み出し方法が決定されます。RAIDレベルごとにパフォーマンス機能が異なります。読み取り比率が高いアプリケーションの場合、RAID 5ボリュームまたはRAID 6ボリュームを使用するとパフォーマンスが向上します。これは、RAID 5およびRAID 6構成の読み取りパフォーマンスが優れているためです。

読み取り比率が低い（書き込み中心の）アプリケーションの場合、RAID 5ボリュームまたはRAID 6ボリュームでは同様のパフォーマンスを実現できません。パフォーマンスの低下は、コントローラがデータと冗長性データをRAID 5ボリュームグループまたはRAID 6ボリュームグループのドライブに書き込む方法に起因します。

次の情報に基づいてRAIDレベルを選択します。

* RAID 0 *

* * 概要 *
+
** 冗長性なし、ストライピングモード。


* *どのように機能するか*
+
** RAID 0は、ボリュームグループ内のすべてのドライブにデータをストライピングします。


* *データ保護機能*
+
** 高可用性が求められる場合、RAID 0は推奨されません。RAID 0は重要度の低いデータに適しています。
** ボリュームグループ内の1本のドライブで障害が発生すると、関連付けられているすべてのボリュームで障害が発生し、すべてのデータが失われます。


* *必要なドライブ数*
+
** RAIDレベル0には少なくとも1本のドライブが必要です。
** RAID 0ボリュームグループには30本を超えるドライブを含めることができます。
** ストレージアレイのすべてのドライブを含むボリュームグループを作成できます。




* RAID 1またはRAID 10 *

* * 概要 *
+
** ストライピング/ミラーモード。


* *どのように機能するか*
+
** RAID 1では、ディスクミラーリングを使用して、2本のディスクに同時にデータが書き込まれます。
** RAID 10は、ドライブストライピングを使用して、複数のミラーリングされたドライブペアにデータをストライピングします。


* *データ保護機能*
+
** RAID 1とRAID 10は、ハイパフォーマンスと最高のデータ可用性を提供します。
** RAID 1とRAID 10は、ドライブミラーリングを使用して、あるドライブから別のドライブにまったく同じコピーを作成します。
** ドライブペアの一方のドライブで障害が発生した場合、ストレージアレイはデータやサービスを失うことなくもう一方のドライブに即座に切り替えることができます。
** 単一ドライブ障害が発生すると、関連付けられているボリュームはデグレード状態になります。ミラードライブがデータへのアクセスを許可します。
** ボリュームグループ内のドライブペアで障害が発生すると、関連付けられているすべてのボリュームで障害が発生し、データが失われる可能性があります。


* *必要なドライブ数*
+
** RAID 1には、ユーザデータ用に1本、ミラーデータ用に1本、合計2本以上のドライブが必要です。
** 4本以上のドライブを選択すると、ボリュームグループ全体でRAID 10が自動的に設定されます。ユーザデータ用にドライブが2本、ミラーデータ用にドライブが2本です。
** ボリュームグループのドライブ数は偶数でなければなりません。ドライブ数が偶数ではなく未割り当てのドライブが残っている場合は、「* Pools & Volume Groups」に移動してボリュームグループにドライブを追加し、処理を再試行します。
** RAID 1とRAID 10のボリュームグループは、30本を超えるドライブで構成できます。ストレージアレイのすべてのドライブを含むボリュームグループを作成できます。




* RAID 5 *

* * 概要 *
+
** 高I/Oモード。


* *どのように機能するか*
+
** ユーザデータと冗長性情報（パリティ）が複数のドライブにストライピングされます。
** 冗長性情報を格納するために、ドライブ1本分の容量が使用されます。


* *データ保護機能*
+
** RAID 5ボリュームグループで1本のドライブに障害が発生すると、関連付けられているすべてのボリュームがデグレード状態になります。冗長な情報があるので、データには引き続きアクセスできます。
** RAID 5ボリュームグループで複数のドライブに障害が発生すると、関連付けられているすべてのボリュームに障害が発生し、すべてのデータが失われます。


* *必要なドライブ数*
+
** ボリュームグループには最低3本のドライブが必要です。
** 通常、ボリュームグループのドライブ数は最大30本に制限されます。




* RAID 6 *

* * 概要 *
+
** 高I/Oモード。


* *どのように機能するか*
+
** ユーザデータと冗長性情報（デュアルパリティ）が複数のドライブにストライピングされます。
** 冗長性情報を格納するために、ドライブ2本分の容量が使用されます。


* *データ保護機能*
+
** RAID 6ボリュームグループで1本または2本のドライブに障害が発生すると、関連付けられているすべてのボリュームがデグレード状態になりますが、冗長性情報があるためデータには引き続きアクセスできます。
** RAID 6ボリュームグループで3本以上のドライブに障害が発生すると、関連付けられているすべてのボリュームに障害が発生し、すべてのデータが失われます。


* *必要なドライブ数*
+
** ボリュームグループには最低5本のドライブが必要です。
** 通常、ボリュームグループのドライブ数は最大30本に制限されます。




[NOTE]
====
プールのRAIDレベルは変更できません。ユーザーインタフェースは'プールを自動的にRAID 6として構成します

====


=== RAIDレベルとデータ保護

RAID 1、RAID 5、およびRAID 6は、フォールトトレランス用に冗長性データをドライブメディアに書き込みます。冗長性データには、データのコピー（ミラー）、またはデータから導出されたエラー修正コードがあります。ドライブで障害が発生した場合は、冗長性データを使用して交換用ドライブに迅速に情報を再構築できます。

単一のボリュームグループ全体で単一のRAIDレベルを設定します。そのボリュームグループの冗長性データは、すべてボリュームグループ内に格納されます。ボリュームグループの容量は、メンバードライブのアグリゲート容量から冗長性データ用に確保された容量を引いた値です。冗長性を確保するために必要な容量は、使用するRAIDレベルによって異なります。



== Data Assuranceとは何ですか？

Data Assurance（DA）はT10 Protection Information（PI）標準を実装しています。I/Oパスでデータが転送される際に発生する可能性のあるエラーをチェックして修正することで、データの整合性が向上します。

Data Assurance機能の一般的な用途として、コントローラとドライブ間のI/Oパスがチェックされます。DA 機能はプールおよびボリュームグループのレベルで提供されます。

この機能を有効にすると、ボリューム内の各データブロックに巡回冗長検査（CRC）と呼ばれるエラーチェック用のコードが付加されます。データブロックが移動されると、ストレージアレイはこれらのCRCコードを使用して、転送中にエラーが発生したかどうかを判断します。破損している可能性があるデータはディスクに書き込まれず、ホストにも返されません。DA機能を使用する場合は、新しいボリュームを作成するときにDAに対応したプールまたはボリュームグループを選択します（プールとボリュームグループの候補の表で「DA」の横の「はい」を探します）。

これらのDA対応ボリュームは、必ずDAに対応したI/Oインターフェイスを使用しているホストに割り当ててください。DAに対応したI/Oインターフェイスには、ファイバチャネル、SAS、iSCSI over TCP/IP、NVMe/FC、NVMe/IB、 NVMe/RoCEとiSER over InfiniBand（iSCSI Extensions for RDMA/IB）：SRP over InfiniBandではDAはサポートされていません。



== セキュリティ対応（ドライブセキュリティ）とは何ですか？

ドライブセキュリティは、セキュリティ有効ドライブをストレージアレイから取り外したときに、そのドライブ上のデータへの不正アクセスを防止する機能です。対応するドライブには、Full Disk Encryption（FDE）ドライブと連邦情報処理標準（FIPS）ドライブがあります。



== リザーブ容量を増やすときは、どのような点に注意する必要がありますか？

一般に、リザーブ容量がフルに近付いているという警告が表示されたときに、容量を拡張します。リザーブ容量は8GiB単位でのみ拡張できます。

* 必要に応じて拡張できるように、プールまたはボリュームグループに十分な空き容量が必要です。
+
プールまたはボリュームグループに空き容量がない場合は、未割り当て容量を未使用ドライブの形式でプールまたはボリュームグループに追加できます。

* プールまたはボリュームグループ内のボリュームのステータスが最適で、変更処理の実行中でないことを確認してください。
* プールまたはボリュームグループに容量の拡張に使用する空き容量が必要です。
* 読み取り専用のSnapshotボリュームのリザーブ容量は増やすことはできません。リザーブ容量が必要なのは、読み取り/書き込みのSnapshotボリュームだけです。


Snapshot処理の場合、リザーブ容量は通常ベースボリュームの40%です。非同期ミラーリング処理のリザーブ容量は、一般にベースボリュームの20%です。ベースボリュームで多くの変更が見込まれる場合や、ストレージオブジェクトのコピーサービス処理の使用期間が非常に長くなることが想定される場合は、これよりも割合を増やしてください。



== 削減する量を選択できない場合、どのような理由が考えられますか?

リザーブ容量は、増やしたときの分量ずつしか減らすことができません。メンバーボリュームのリザーブ容量は、追加したときと逆の順序でのみ削除できます。

次のいずれかの条件に該当する場合は、ストレージオブジェクトのリザーブ容量を削減できません。

* ストレージオブジェクトがミラーペアのボリュームである。
* ストレージオブジェクトにリザーブ容量用のボリュームが1つしかない。ストレージオブジェクトには、リザーブ容量用のボリュームが少なくとも2つ含まれている必要があります。
* ストレージオブジェクトが無効になっているSnapshotボリュームである。
* ストレージオブジェクトに関連付けられているSnapshotイメージが含まれている。


リザーブ容量のボリュームは、追加したときと逆の順序でのみ削除できます。

読み取り専用のSnapshotボリュームについては、関連付けられたリザーブ容量がないため、リザーブ容量を削減することはできません。リザーブ容量が必要なのは、読み取り/書き込みのSnapshotボリュームだけです。



== メンバーボリュームごとにリザーブ容量が必要なのはなぜですか？

Snapshot整合性グループの各メンバーボリュームには、参照先の整合性グループSnapshotイメージに影響を与えずに、ホストアプリケーションによる変更をベースボリュームに保存するための独自のリザーブ容量が必要です。リザーブ容量を使用すると、読み取り/書き込み用のメンバーボリュームに含まれているデータのコピーに、ホストアプリケーションが書き込みアクセスすることができます。

整合性グループのSnapshotイメージにホストから直接読み取りや書き込みを行うことはできません。Snapshotイメージには、ベースボリュームから取得されたデータのみが保存されます。

読み取り/書き込み用の整合性グループSnapshotボリュームの作成中に、System Managerは整合性グループのメンバーボリュームごとにリザーブ容量を作成します。このリザーブ容量によって、ホストアプリケーションは、整合性グループのSnapshotイメージに含まれているデータのコピーに書き込みアクセスすることができます。



== SSDキャッシュのすべての統計情報を表示するにはどうすればよいですか？また、何が

SSDキャッシュについては、一般統計と詳細統計を表示できます。一般統計は詳細統計のサブセットです。

詳細統計は'すべてのSSD統計を.csvファイルにエクスポートした場合にのみ表示できます統計を確認および解釈する際には、複数の統計を組み合わせることで見えてくる情報もあることに注意してください。



=== 一般統計

SSDキャッシュの統計を表示するには、次のメニューを選択します。Storage [Pools & Volume Groups]統計を表示するSSDキャッシュを選択し、メニューを選択します。More [View Statistics]公称統計はView SSD Cache Statistics（SSDキャッシュ統計の表示）ダイアログに表示されます。

次に、詳細統計のサブセットである、一般統計の一覧を示します。

[cols="25h,~"]
|===
| 一般統計 | 説明 


 a| 
読み取り/書き込み
 a| 
SSDキャッシュが有効なボリュームに対するホストの読み取りと書き込みの合計数。読み取り数を書き込み数と比較します。効率的なSSDキャッシュ処理には、読み取り数が書き込み数より多いことが必要です。書き込みに対する読み取りの比率が大きいほど、キャッシュ処理が向上します。



 a| 
キャッシュヒット
 a| 
キャッシュヒットの数。



 a| 
キャッシュヒット率（%）
 a| 
キャッシュヒット数を読み取りと書き込みの合計数で割った値。効果的なSSDキャッシュ処理には、キャッシュヒットの割合が50%より高いことが必要です。この値が小さい場合は、次のような状況が考えられます。

* 書き込みに対する読み取りの比率が小さすぎる
* 読み取りが繰り返されない
* キャッシュ容量が小さすぎる




 a| 
キャッシュ割り当て率（%）
 a| 
割り当てられているSSDキャッシュストレージの量。このコントローラで使用可能なSSDキャッシュストレージの割合として表されます。割り当てられたバイト数を使用可能なバイト数で割った値です。キャッシュ割り当ての割合は、通常は100%と表示されます。この数値が100%未満の場合は、キャッシュがウォームアップされていないか、アクセスされているすべてのデータよりもSSDキャッシュ容量が大きいことを意味します。後者の場合、SSDキャッシュ容量を小さくしても同レベルのパフォーマンスが得られる可能性があります。この値は、キャッシュされたデータがSSDキャッシュに配置されたことを示しているわけではなく、SSDキャッシュにデータを配置可能となる前の準備手順にすぎません。



 a| 
キャッシュ使用率（%）
 a| 
有効なボリュームのデータが格納されているSSDキャッシュストレージの量。割り当てられているSSDキャッシュストレージの割合として表されます。この値はSSDキャッシュの利用率または密度を表し、ユーザデータのバイト数を割り当てられているバイト数で割った値です。キャッシュ使用率の割合は、通常は100%より小さく、多くの場合はるかに小さくなります。この数値は、SSDキャッシュ容量のうち、キャッシュデータが書き込まれている割合を示します。SSDキャッシュの各割り当て単位はサブブロックと呼ばれる小さい単位に分割され、それぞれ独立して使用されるため、この値は100%より小さくなります。この値が大きいほど一般には有効ですが、小さい数値でもパフォーマンスが大幅に向上する可能性があります。

|===


=== 詳細統計

詳細統計は、一般統計とその他の統計で構成されます。これらの追加統計は一般統計とともに保存されますが、一般統計とは異なり、View SSD Cache Statistics（SSDキャッシュ統計の表示）ダイアログには表示されません。詳細統計は'.csvファイルに統計をエクスポートした後にのみ表示できます

「.csv」ファイルを表示するときに、詳細統計が一般統計の後にリストされていることに注目してください。

[cols="25h,~"]
|===
| 詳細統計 | 説明 


 a| 
読み取りブロック
 a| 
ホスト読み取りのブロック数。



 a| 
書き込みブロック
 a| 
ホスト書き込みのブロック数。



 a| 
完全ヒットブロック
 a| 
キャッシュヒットのブロック数。この値は、SSDキャッシュから完全に読み込まれたブロックの数を示します。SSDキャッシュがパフォーマンスの向上に効果があるのは、フルキャッシュヒットである処理に対してのみです。



 a| 
部分ヒット
 a| 
すべてのブロックではなく、少なくとも1つのブロックがSSDキャッシュ内にあったホスト読み取りの数。部分ヒットはSSDキャッシュ*ミス*で、読み取りはベースボリュームから行われています。



 a| 
部分ヒット-ブロック
 a| 
部分ヒットのブロック数。部分キャッシュヒットと部分キャッシュヒットブロックは、SSDキャッシュ内にデータの一部しかない処理の結果として発生します。この場合、キャッシュされているハードディスクドライブ（HDD）ボリュームからデータを取得する必要があります。このタイプのヒットの場合、SSDキャッシュから得られるパフォーマンス上のメリットはありません。部分キャッシュヒットブロック数が完全キャッシュヒットブロック数より多い場合は、別のI/O特性タイプ（ファイルシステム、データベース、またはWebサーバ）を使用するとパフォーマンスが向上する可能性があります。SSDキャッシュのウォームアップ中は、キャッシュヒットに比べて、部分ヒットとミスの数が増えることが予想されます。



 a| 
ミス
 a| 
SSDキャッシュ内にブロックがなかったホスト読み取りの数。SSDキャッシュミスは、ベースボリュームから読み取りが行われた場合に発生します。SSDキャッシュのウォームアップ中は、キャッシュヒットに比べて、部分ヒットとミスの数が増えることが予想されます。



 a| 
ミス-ブロック
 a| 
ミスしたブロックの数。



 a| 
取り込み処理（ホスト読み取り）
 a| 
ベースボリュームからSSDキャッシュへデータがコピーされたホスト読み取りの数。



 a| 
取り込み処理（ホスト読み取り）-ブロック
 a| 
取り込み処理（ホスト読み取り）のブロック数。



 a| 
取り込み処理（ホスト書き込み）
 a| 
ベースボリュームからSSDキャッシュへデータがコピーされたホスト書き込みの数。書き込みI/O処理によってキャッシュが一杯にならないキャッシュ設定では、取り込み処理（ホスト書き込み）の数が0になることがあります。



 a| 
取り込み処理（ホスト書き込み）-ブロック
 a| 
取り込み処理（ホスト書き込み）のブロック数。



 a| 
無効化処理
 a| 
データが無効化された、またはSSDキャッシュから削除された回数。キャッシュの無効化処理は、各ホスト書き込み要求、Forced Unit Access（FUA）によるホスト読み取り要求、確認要求、およびその他一部の状況で実行されます。



 a| 
リサイクル処理
 a| 
別のベースボリュームや論理ブロックアドレス（LBA）範囲にSSDキャッシュブロックが再利用された回数。効果的なキャッシュでは、再利用の回数は、読み取り処理と書き込み処理の合計数よりも少なくする必要があります。リサイクル処理の回数が読み取りと書き込みの合計数に近づいている場合、SSDキャッシュがスラッシングしています。キャッシュ容量を増やす必要があります。または、ワークロードがSSDキャッシュの使用に適していません。



 a| 
使用可能なバイト数
 a| 
SSDキャッシュ内でこのコントローラによって使用可能なバイト数。



 a| 
割り当てバイト数
 a| 
このコントローラによってSSDキャッシュから割り当てられたバイト数。SSDキャッシュから割り当てられたバイトは、空の場合と、ベースボリュームのデータが含まれている場合があります。



 a| 
ユーザデータバイト数
 a| 
SSDキャッシュ内の、ベースボリュームのデータを含む割り当て済みバイト数。使用可能なバイト数、割り当て済みバイト数、およびユーザデータのバイト数を使用して、キャッシュ割り当ての割合とキャッシュ利用率の割合が計算されます。

|===


== プールの最適化容量とは何ですか？

SSDドライブでは、その容量の一部が未割り当ての場合に寿命が長くなり、最大書き込みパフォーマンスが向上します。

プールに関連付けられているドライブの未割り当て容量は、プールの予約済み容量、空き容量（ボリュームで使用されていない容量）、および使用可能容量のうちの最適化容量として確保された容量で構成されます。この最適化容量は使用可能容量を減らすことで最小レベルの最適化容量を確保するため、ボリュームの作成には使用できません。

プールの作成時に、パフォーマンス、ドライブの寿命、使用可能容量のバランスに基づいて、推奨される最適化容量が決定されます。プール設定ダイアログにある追加の最適化容量スライダを使用して、プールの最適化容量を調整できます。スライダを動かすことで、使用可能容量を犠牲にしてパフォーマンスの向上とドライブ寿命の延長を図るか、またはパフォーマンスとドライブ寿命を犠牲にして使用可能容量を増やすことができます。

[NOTE]
====
追加の最適化容量スライダは、EF600およびEF300ストレージシステムに対してのみ使用できます。

====


== ボリュームグループの最適化容量とは何ですか？

SSDドライブでは、その容量の一部が未割り当ての場合に寿命が長くなり、最大書き込みパフォーマンスが向上します。

ボリュームグループに関連付けられているドライブの未割り当て容量は、ボリュームグループの空き容量（ボリュームで使用されていない容量）と、使用可能容量のうちの最適化容量として確保された容量で構成されます。この最適化容量は使用可能容量を減らすことで最小レベルの最適化容量を確保するため、ボリュームの作成には使用できません。

ボリュームグループの作成時に、パフォーマンス、ドライブの寿命、使用可能容量のバランスに基づいて、推奨される最適化容量が決定されます。ボリュームグループ設定ダイアログの最適化容量のスライダを使用して、ボリュームグループの最適化容量を調整できます。スライダを動かすことで、使用可能容量を犠牲にしてパフォーマンスの向上とドライブ寿命の延長を図るか、またはパフォーマンスとドライブ寿命を犠牲にして使用可能容量を増やすことができます。

[NOTE]
====
追加の最適化容量スライダは、EF600およびEF300ストレージシステムに対してのみ使用できます。

====


== リソースプロビジョニング機能とは何ですか？

リソースプロビジョニングは、EF300およびEF600ストレージアレイで使用できる機能です。これにより、バックグラウンドの初期化プロセスを実行せずに、ボリュームをただちに使用できます。

リソースプロビジョニングボリュームは、SSDグループまたはプール内のシックボリュームです。ボリュームの作成時にはドライブ容量が割り当てられますが（ボリュームに割り当てられます）、ドライブブロックは割り当て解除されます（マッピング解除されます）。これに対し、従来のシックボリュームでは、Data Assurance保護情報のフィールドを初期化し、各RAIDストライプでデータとRAIDパリティの整合性を確保するために、すべてのドライブブロックがバックグラウンドボリューム初期化処理中にマッピングまたは割り当てられます。リソースプロビジョニングボリュームでは、時間制限付きのバックグラウンド初期化は実行されません。代わりに、各RAIDストライプは、ストライプ内のボリュームブロックへの最初の書き込み時に初期化されます。

リソースプロビジョニングボリュームはSSDボリュームグループおよびプールでのみサポートされます。グループまたはプール内のすべてのドライブでNVMeのDeallocated or Unwritten Logical Block Error（DULBE）エラーリカバリ機能がサポートされます。リソースでプロビジョニングされたボリュームを作成すると、そのボリュームに割り当てられていたすべてのドライブブロックが割り当て解除（マッピング解除）されます。また、ホストではNVMe Dataset ManagementコマンドまたはSCSI Unmapコマンドを使用して、ボリューム内の論理ブロックの割り当てを解除できます。ブロックの割り当てを解除すると、SSDの消耗度が改善され、書き込みパフォーマンスが最大化されます。向上率はドライブのモデルと容量によって異なります。


NOTE: 現在、EF300CまたはEF600CストレージアレイではDULBEはサポートされていません。



== リソースでプロビジョニングされるボリューム機能について、どのような点に注意する必要がありますか？

リソースプロビジョニングは、EF300およびEF600ストレージアレイで使用できる機能です。これにより、バックグラウンドの初期化プロセスを実行せずに、ボリュームをただちに使用できます。

リソースプロビジョニングボリュームは、SSDグループまたはプール内のシックボリュームです。ボリュームの作成時にはドライブ容量が割り当てられますが（ボリュームに割り当てられます）、ドライブブロックは割り当て解除されます（マッピング解除されます）。これに対し、従来のシックボリュームでは、Data Assurance保護情報のフィールドを初期化し、各RAIDストライプでデータとRAIDパリティの整合性を確保するために、すべてのドライブブロックがバックグラウンドボリューム初期化処理中にマッピングまたは割り当てられます。リソースプロビジョニングボリュームでは、時間制限付きのバックグラウンド初期化は実行されません。代わりに、各RAIDストライプは、ストライプ内のボリュームブロックへの最初の書き込み時に初期化されます。

リソースプロビジョニングボリュームはSSDボリュームグループおよびプールでのみサポートされます。グループまたはプール内のすべてのドライブでNVMeのDeallocated or Unwritten Logical Block Error（DULBE）エラーリカバリ機能がサポートされます。リソースでプロビジョニングされたボリュームを作成すると、そのボリュームに割り当てられていたすべてのドライブブロックが割り当て解除（マッピング解除）されます。また、ホストではNVMe Dataset ManagementコマンドまたはSCSI Unmapコマンドを使用して、ボリューム内の論理ブロックの割り当てを解除できます。ブロックの割り当てを解除すると、SSDの消耗度が改善され、書き込みパフォーマンスが最大化されます。向上率はドライブのモデルと容量によって異なります。

DULBEがサポートされているシステムでは、リソースプロビジョニングがデフォルトで有効になっています。このデフォルト設定は、* Pools & Volume Groups *で無効にできます。


NOTE: 現在、EF300CまたはEF600CストレージアレイではDULBEはサポートされていません。
