---
permalink: sm-storage/faq-systems-clusters.html 
sidebar: sidebar 
keywords:  
summary: この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。 
---
= SANtricity System Manager のホスト システムとホスト クラスタに関する FAQ
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。



== ホストおよびホストクラスタとは何ですか？

ホストは、ストレージアレイ上のボリュームにI/Oを送信するサーバです。ホストクラスタはホストのグループです。ホストクラスタを作成すると、同じボリュームを複数のホストに簡単に割り当てることができます。

ホストは個別に定義します。ホストを独立したエンティティにすることも、ホストクラスタに追加することもできます。個々のホストにボリュームを割り当てることができます。または、ホストをホストクラスタの一部として指定し、1つ以上のボリュームへのアクセスをホストクラスタ内の他のホストと共有することもできます。

ホストクラスタは、SANtricity System Managerで作成する論理エンティティです。ボリュームを割り当てる前に、ホストクラスタにホストを追加する必要があります。



== ホストクラスタを作成する必要があるのはどのような場合ですか？

複数のホストから同じボリュームセットにアクセスする場合は、ホストクラスタを作成する必要があります。通常、個々のホストには、ボリュームへのアクセスを調整するためのクラスタリングソフトウェアがインストールされています。



== 正しいホストオペレーティングシステムタイプを特定するにはどうすればよいですか？

Host Operating System Typeフィールドには、ホストのオペレーティングシステムが表示されます。推奨されるホストタイプをドロップダウンリストから選択できます。

ドロップダウンリストに表示されるホストタイプは、ストレージアレイのモデルとファームウェアバージョンによって異なります。最新バージョンでは、最も一般的なオプションが最初に表示されますが、これは最も適切なオプションです。このリストに表示されるオプションが完全にサポートされているとは限りません。

[NOTE]
====
ホストのサポートの詳細については、を参照してください https://imt.netapp.com/matrix/#welcome["NetApp Interoperability Matrix Tool で確認できます"^]。

====
リストに表示されるホストタイプは次のとおりです。

[cols="35h,~"]
|===
| ホストオペレーティングシステムのタイプ | オペレーティングシステム（OS）とマルチパスドライバ 


 a| 
Linux DM-MP（カーネル3.10以降）
 a| 
Device Mapper Multipathのフェイルオーバー解決策 と3.10以降のカーネルを使用するLinuxオペレーティングシステムをサポートします。



 a| 
VMware ESXi
 a| 
VMwareに組み込みのストレージアレイタイプポリシーモジュールであるSATP_ALUAを使用してNative Multipathing Plug-in（NMP）アーキテクチャを実行するVMware ESXiオペレーティングシステムをサポートします。



 a| 
Windows（クラスタまたは非クラスタ）
 a| 
ATTOマルチパスドライバを実行しないWindowsクラスタ構成または非クラスタ構成をサポートします。



 a| 
ATTOクラスタ（すべてのオペレーティングシステム）
 a| 
ATTO Technology、Inc.のマルチパスドライバを使用するすべてのクラスタ構成をサポートします。



 a| 
Linux（Veritas DMP）
 a| 
Veritas DMPマルチパス解決策 を使用するLinuxオペレーティングシステムをサポートします。



 a| 
Linux（ATTO）
 a| 
ATTO Technology、Inc.のマルチパスドライバを使用するLinuxオペレーティングシステムをサポートします。



 a| 
Mac OS（ATTO）
 a| 
ATTO Technology、Inc.のマルチパスドライバを使用するMac OSバージョンをサポートします。



 a| 
Windows（ATTO）
 a| 
ATTO Technology、Inc.のマルチパスドライバを使用するWindowsオペレーティングシステムをサポートします。



 a| 
IBM SVCの場合
 a| 
IBM SAN Volume Controller構成をサポートします。



 a| 
工場出荷時のデフォルト
 a| 
ストレージアレイの初回起動用です。ホストオペレーティングシステムのタイプが工場出荷時のデフォルトに設定されている場合は、接続先ホストで実行されているホストオペレーティングシステムとマルチパスドライバに合わせて変更します。



 a| 
Linux DM-MP（カーネル3.9以前）
 a| 
Device Mapper Multipathのフェイルオーバー解決策 と3.9以前のカーネルを使用するLinuxオペレーティングシステムをサポートします。



 a| 
Windowsクラスタ（廃止）
 a| 
ホストオペレーティングシステムのタイプがこの値に設定されている場合は、代わりにWindows（クラスタまたは非クラスタ）の設定を使用します。

|===


== HBAおよびアダプタポートとは何ですか？

ホストバスアダプタ（HBA）はホストに搭載されるボードで、1つ以上のホストポートが搭載されています。ホストポートは、コントローラに物理的に接続されるホストバスアダプタ（HBA）のポートで、I/O処理に使用されます。

HBAのアダプタポートはホストポートと呼ばれます。ほとんどのHBAには1つまたは2つのホストポートがあります。HBAと各HBAホストポートには、それぞれ一意のWorld Wide Identifier（WWID）が割り当てられています。ホストポート識別子は、SANtricity System Managerからホストを手動で作成するときに、適切なHBAを物理ホストに関連付けるために使用されます。



== ホストポートをホストに一致させるにはどうすればよいですか？

ホストを手動で作成する場合は、まずホストで利用可能な適切なHost Bus Adapter（HBA；ホストバスアダプタ）ユーティリティを使用して、ホストにインストールされている各HBAに関連付けられているホストポート識別子を特定する必要があります。

この情報を確認したら、Create Hostダイアログのリストから、ストレージアレイにログインしているホストポート識別子を選択します。

[NOTE]
====
作成するホストに適したホストポート識別子を選択してください。誤ったホストポート識別子を関連付けると、別のホストからこのデータへの原因 の意図しないアクセスが発生する可能性があります。

====


== CHAPシークレットを作成するにはどうすればよいですか？

ストレージアレイに接続されているiSCSIホスト上でチャレンジハンドシェイク認証プロトコル（CHAP）認証を設定する場合は、iSCSIホストごとにイニシエータのCHAPシークレットを再入力する必要があります。

これを行うには、System Managerをホストの作成処理または設定の表示/編集オプションのどちらかとして使用します。

CHAP相互認証を使用する場合は、ストレージアレイのターゲットCHAPシークレットを［設定］ページで定義し、各iSCSIホストでそのターゲットCHAPシークレットを再入力する必要もあります。



== デフォルトクラスタとは何ですか？

デフォルトクラスタはシステム定義のエンティティです。ストレージアレイにログインしたホストポート識別子が関連付けられていない場合、そのポートはデフォルトクラスタに割り当てられているボリュームにアクセスできます。関連付けられていないホストポート識別子は、特定のホストに論理的に関連付けられておらず、ホストに物理的に搭載されてストレージアレイにログインしているホストポートです。

[NOTE]
====
ホストがストレージアレイ内の特定のボリュームにアクセスできるようにする場合は、デフォルトクラスタを使用する_は_しない_選択します。代わりに、ホストポート識別子を対応するホストに関連付ける必要があります。このタスクは、ホスト作成処理中に手動で実行できます。その後、ボリュームを個々のホストまたはホストクラスタに割り当てます。

====
デフォルトクラスタは、すべてのホストとストレージアレイに接続されたすべてのログイン済みホストポート識別子がすべてのボリュームにアクセスできるようにするための外部ストレージ環境を構築する場合にのみ使用してください（フルアクセスモード） 特にストレージアレイやユーザインターフェイスでホストが認識されないようにする必要があります。

最初にボリュームをデフォルトクラスタに割り当てる際には、コマンドラインインターフェイス（CLI）を使用する必要があります。ただし、ボリュームを少なくとも1つデフォルトクラスタに割り当てると、このエンティティを管理できるユーザインターフェイスに表示されます（デフォルトクラスタ）。



== ホスト接続レポートとは何ですか？

ホスト接続レポートを有効にすると、ストレージアレイはコントローラと設定されたホスト間の接続を継続的に監視し、接続が中断された場合に警告します。

ケーブルに緩み、損傷、脱落が生じた場合や、ホストに問題が生じた場合は、接続の中断が発生する可能性があります。これらの状況では、Recovery Guruメッセージが発行されることがあります。

* *ホストの冗長性が失われました*--どちらかのコントローラがホストと通信できない場合に開きます
* *ホストタイプが正しくありません*--ストレージアレイでホストタイプが正しく指定されていないと'フェイルオーバーの問題が発生する可能性があります


コントローラのリブートにかかる時間が接続タイムアウトよりも長くなる可能性がある場合は、ホスト接続レポートを無効にすることができます。この機能を無効にすると、Recovery Guruメッセージが生成されなくなります。

[NOTE]
====
また、コントローラのリソース使用量を監視してバランスを調整する自動ロードバランシングも無効になります。ただし、ホスト接続レポートを再度有効にしても、自動ロードバランシング機能は自動的には有効になりません。

====