---
permalink: sm-storage/faq-storage-drives.html 
sidebar: sidebar 
keywords:  
summary: この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。 
---
= SANtricity System Manager のストレージ ドライブに関する FAQ
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。



== ホットスペアドライブとは何ですか？

ホットスペアは、RAID 1、RAID 5、またはRAID 6のボリュームグループで、スタンバイドライブとして機能します。問題なく動作するドライブですが、データは格納されていません。ボリュームグループ内のドライブで障害が発生すると、障害が発生したドライブのデータがホットスペアに自動的に再構築されます。

ストレージアレイのドライブで障害が発生した場合、障害が発生したドライブからホットスペアドライブに自動的に切り替わります。物理的にドライブを交換する必要はありません。ドライブ障害の発生時にホットスペアドライブが使用可能であれば、冗長性データを使用して障害が発生したドライブからホットスペアドライブにデータが再構築されます。

ホットスペアドライブは、特定のボリュームグループ専用ではありません。容量が同じかそれよりも小さいストレージアレイ内で障害が発生したどのドライブにも、ホットスペアドライブを使用できます。ホットスペアドライブのメディアタイプ（HDDまたはSSD）は、保護対象のドライブと同じである必要があります。

[NOTE]
====
ホットスペアドライブはプールではサポートされません。プールでは、ホットスペアドライブの代わりに、プールを構成する各ドライブ内の予約済み容量を使用します。

====


== 予約済み容量とは何ですか？

予約済み容量は、ドライブ障害に備えてプール内に確保されている容量（ドライブ数）です。

プールが作成されると、プール内のドライブ数に応じて自動的にデフォルトの予約済み容量が確保されます。

プールの予約済み容量は再構築時に使用されますが、ボリュームグループでは同じ目的でホットスペアドライブが使用されます。予約済み容量を使用する方式は、再構築の時間を短縮できるため、ホットスペアドライブよりも優れています。予約済み容量は、ホットスペアドライブの場合は1本のドライブに確保されるのではなく、プール内の複数のドライブに分散されるため、特定のドライブの速度や可用性に制限されません。



== ドライブを論理的に交換するのはどのような場合ですか？

ドライブに障害が発生した場合や、何らかの理由でドライブを交換する場合、ストレージアレイに未割り当てのドライブがあれば、障害が発生したドライブを未割り当てのドライブに論理的に交換することができます。未割り当てのドライブがない場合は、ドライブを物理的に交換します。

元のドライブのデータは、交換用ドライブにコピーまたは再構築されます。



== 再構築中のドライブのステータスはどこで確認できますか。

ドライブの再構築ステータスは、処理実行中ダッシュボードで確認できます。

ホームページの右上にある* View Operations in Progress *リンクをクリックします。

ドライブによっては、完全な再構築にかなりの時間がかかることがあります。ボリューム所有権が変更された場合は、迅速な再構築の代わりに完全な再構築が実行されることがあります。
