---
permalink: sm-storage/faq-storage-array-settings.html 
sidebar: sidebar 
keywords:  
summary: この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。 
---
= SANtricity System Managerのストレージアレイ設定に関するFAQ
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。



== 自動ロードバランシングとは何ですか？

自動ロードバランシングはI/Oを自動的に分散する機能を提供し、ホストからの受信I/Oトラフィックは動的に管理されて両方のコントローラに分散されます。

自動ロードバランシング機能を使用すると、負荷の変化に動的に対応してボリュームのコントローラ所有権が自動的に調整されるため、コントローラ間でワークロードが移動する際の負荷の不均衡が解消され、I/Oリソースの管理が強化されます。

各コントローラのワークロードは継続的に監視され、ホストにインストールされたマルチパスドライバとの連携により、必要に応じて自動的に負荷を分散できます。ワークロードがコントローラ間で自動的に再分散されるため、ストレージアレイの負荷の変化に合わせてボリュームのコントローラ所有権を手動で調整する必要がなくなり、ストレージ管理者の負担が軽減されます。

自動ロードバランシングを有効にすると、次の機能が実行されます。

* コントローラのリソース利用率を自動的に監視して負荷を分散します。
* ボリュームのコントローラ所有権が必要に応じて自動的に調整され、ホストとストレージアレイの間のI/O帯域幅が最適化されます。


[NOTE]
====
コントローラのSSDキャッシュを使用するように割り当てられたボリュームは、自動ロードバランシングによる転送の対象外となります。

====


== コントローラキャッシュとは何ですか？

コントローラキャッシュは、コントローラとホストの間、およびコントローラとディスクの間の2種類のI/O（入出力）処理をスムーズに行うための物理メモリスペースです。

読み取りおよび書き込みのデータ転送では、ホストとコントローラは高速な接続を介して通信します。ただし、ディスクは比較的低速なデバイスであるため、コントローラのバックエンドからディスクへの通信は低速になります。

コントローラキャッシュがデータを受信すると、コントローラはデータを保持していることをホストアプリケーションに通知します。これにより、ホストアプリケーションはI/Oがディスクに書き込まれるのを待たずに代わりに、アプリケーションは処理を続行できます。また、サーバアプリケーションはキャッシュされたデータにアクセスできるため、データにアクセスするためにディスクを読み取る必要がなくなります。

コントローラキャッシュは、ストレージアレイの全体的なパフォーマンスに次のように影響します。

* キャッシュはバッファとして機能するため、ホストとディスクのデータ転送を同期する必要がありません。
* ホストからの読み取り/書き込み処理の対象となるデータが以前の処理ですでにキャッシュに格納されていれば、ディスクにアクセスする必要はありません。
* 書き込みキャッシュを使用している場合、ホストは以前の書き込み処理がディスクに書き込まれる前に後続の書き込みコマンドを送信できます。
* キャッシュプリフェッチを有効にすると、シーケンシャルリードアクセスが最適化されます。読み取り処理ではデータがディスクから読み取られるのではなく、キャッシュ内のデータが使用される可能性が高くなります。


[CAUTION]
====
*データ損失の可能性*--バッテリなしの書き込みキャッシュ*オプションを有効にして保護用のユニバーサル電源装置を持たないと、データが失われる可能性があります。また、コントローラのバッテリがない場合に*バッテリなしの書き込みキャッシュ*オプションを有効にすると、データが失われる可能性があります。

====


== キャッシュフラッシュとは何ですか？

キャッシュ内の書き込み前のデータの量が一定のレベルに達すると、コントローラはキャッシュされたデータを定期的にドライブに書き込みます。この書き込みプロセスは「フラッシュ」と呼ばれます。

コントローラは、デマンドベースと経過時間ベースの2つのアルゴリズムを使用してキャッシュをフラッシュします。デマンドベースのアルゴリズムは、キャッシュされたデータの量がキャッシュフラッシュしきい値を下回るまで使用されます。デフォルトでは、キャッシュの80%が使用中になるとフラッシュが開始されます。

System Managerでは、「デマンド・キャッシュ・フラッシュの開始」しきい値を、環境で使用されるI/Oのタイプに最も適した値に設定できます。書き込み操作が主な環境では'新しい書き込み要求をディスクに移動せずにキャッシュで処理できる可能性を高めるために'デマンド・キャッシュ・フラッシュの開始パーセントを高く設定する必要があります割合を高く設定すると、キャッシュフラッシュの回数が減ってキャッシュに残るデータ量が増えるため、キャッシュヒットの可能性が高まります。

I/Oが不規則な（データバーストが発生する）環境では、キャッシュフラッシュを低く設定して、データバースト間でキャッシュが頻繁にフラッシュされるようにします。さまざまな負荷を処理する多様なI/O環境や、負荷のタイプが不明な環境では、このしきい値を中間の50%に設定します。80%未満に設定した場合、ホスト読み取りに必要なデータがキャッシュにないためにパフォーマンスが低下する可能性があります。また、割合を低くすると、キャッシュレベルを維持するために必要なディスクへの書き込み回数が増えるため、システムオーバーヘッドが増大します。

経過時間ベースのアルゴリズムでは、書き込みデータがディスクにフラッシュされるまでのキャッシュでの保持期間を指定します。キャッシュフラッシュしきい値に達するまでは、経過時間ベースのアルゴリズムが使用されます。デフォルトは10秒ですが、カウントされるのは非アクティブな期間のみです。System Managerではフラッシュのタイミングを変更できません。代わりに、コマンドラインインターフェイス（CLI）で* Set Storage Array *コマンドを使用する必要があります。

[CAUTION]
====
*データ損失の可能性*--バッテリなしの書き込みキャッシュ*オプションを有効にして保護用のユニバーサル電源装置を持たないと、データが失われる可能性があります。また、コントローラのバッテリがない場合に*バッテリなしの書き込みキャッシュ*オプションを有効にすると、データが失われる可能性があります。

====


== キャッシュブロックサイズとは何ですか？

ストレージアレイのコントローラはキャッシュを複数の「ブロック」に編成します。ブロックは、サイズが8KiB、16KiB、または32KiBのメモリチャンクです。ストレージシステムのボリュームはすべて同じキャッシュスペースを共有するため、ボリュームで使用できるキャッシュブロックサイズは1つだけです。

使用するブロックサイズはアプリケーションによって異なり、ストレージのパフォーマンスに影響する可能性があります。System Managerのデフォルトのブロックサイズは32KiBですが、8KiB、16KiB、または32KiBに設定できます。ファイルシステムやデータベースアプリケーションには小さいサイズが適しています。大容量のデータ転送、シーケンシャルI/O、マルチメディアなどの広帯域幅を必要とするアプリケーションには、大きいサイズが適しています。



== ストレージアレイのクロックを同期する必要があるのはいつですか？

SANtricity System Managerに表示されるタイムスタンプが管理クライアント（ブラウザからSANtricity System Managerにアクセスするコンピュータ）に表示されるタイムスタンプと一致していない場合は、ストレージアレイのコントローラクロックを手動で同期する必要があります。このタスクを実行する必要があるのは、SANtricityシステムマネージャでNTP（ネットワークタイムプロトコル）が有効になっていない場合だけです。

[NOTE]
====
クロックを手動で同期する代わりに、NTPサーバを使用することを強く推奨します。NTPは、SNTP（Simple Network Time Protocol）を使用して自動的にクロックを外部サーバと同期します。

====
同期ステータスは、ストレージアレイクロックの同期化ダイアログボックスで確認できます。このダイアログボックスはシステムページから使用できます。ダイアログボックスに表示された時間が一致しない場合は、同期を実行します。このダイアログボックスを定期的に表示することで、コントローラクロックの時間表示が同期されているかどうかを確認できます。
