---
permalink: sm-storage/faq-remote-storage.html 
sidebar: sidebar 
keywords:  
summary: この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。 
---
= SANtricity System Managerのリモートストレージに関するFAQ
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。



== リモートストレージ接続を作成するときは、どのような点に注意する必要がありますか？

リモートストレージ機能を設定するには、リモートデバイスとターゲットストレージシステムをiSCSI経由で直接接続する必要があります。

iSCSIシステム接続をセットアップするには、以下を参照してください。

* link:../sm-hardware/configure-iscsi-ports-hardware.html["iSCSIポートを設定"]
* https://www.netapp.com/pdf.html?item=/media/28697-tr-4893-deploy.pdf["Remote Storageテクニカルレポート"^]




== リモートボリュームの削除を求めるプロンプトが表示されるのはなぜですか？

リモートボリュームの最大数に達すると、ストレージシステムは未使用のリモートボリュームを自動的に検出し、削除するように求めます。

場合によっては、作成プロセス中に未使用のリモートボリュームがクリーンアップされないことがあります。追加のインポート処理を開始する前に、システムが最適で、ネットワーク接続が安定していることを確認してください。



== デスティネーション アレイのボリュームが一部表示されないのはなぜですか?

リモートストレージ機能のインポートを設定する際、ブロックサイズ、容量、またはボリュームの可用性が原因で一部のボリュームがターゲット候補のリストに表示されないことがあります。

ボリューム候補をリストに表示するには、以下の条件を満たしている必要があります。

* リモートボリュームと同等以上の容量。
* リモートボリュームと同じブロックサイズ。
* 現在のステータスが最適であること。


次の条件を満たすボリューム候補はリストから除外されます。

* 次のいずれかの関係：ボリュームコピー、Snapshot、またはミラーリング。
* 再設定処理を実行中です。
* 別のデバイス（ホストまたはホストクラスタ）へのマッピング。
* 読み取りフラッシュキャッシュが有効です。




== インポートでリモートボリュームについて、どのような点に注意する必要がありますか？

リモートストレージ機能を使用する場合は、リモートボリュームがデータのソースであることに注意してください。

インポートの実行中は、リモートボリュームからデスティネーションストレージシステム上のターゲットボリュームにデータが転送されます。この2つのボリュームは、同じブロックサイズである必要があります。



== リモートストレージのインポートを開始するときは、どのような点に注意する必要がありますか？

リモートストレージ機能を使用すると、リモートストレージシステムからローカルのEシリーズストレージシステム上のボリュームにデータをコピーできます。この機能を使用する前に、次のガイドラインを確認してください。



=== 設定

リモートストレージのインポートを作成する前に、次の操作を実行し、以下の条件を確認する必要があります。

* ローカルのEシリーズストレージシステムの各コントローラにリモートストレージシステムへのiSCSI接続が確立されていることを確認します。
* ローカルのEシリーズストレージシステムで、インポート処理のターゲットボリュームを作成します。ボリュームの容量がソースボリュームと同じかそれよりも大きく、かつソースボリュームと同じブロックサイズでマッピングされていないことを確認します。を参照してください link:create-volumes.html["ボリュームを作成します"]。
* iSCSI Qualified Name（IQN）を使用して、ローカルのEシリーズストレージシステムをリモートシステム上のホストとして設定します。IQNは次のメニューから確認できます。Settings（システム）> iSCSI settings（iSCSI設定）> Target IQN（ターゲットIQN）。また、使用するシステムに基づいて適切なホストタイプを設定してください。
* すべてのI/Oを停止し、ファイルシステムをアンマウントして、リモートストレージシステム上の選択したボリュームに対するホストまたはアプリケーションへの割り当てをすべて削除します。
* 新しく作成したローカルのEシリーズストレージシステムホストにボリュームを割り当てます。
* インポートを作成できるように、リモートストレージシステムから次の情報を収集します。
+
** iSCSI修飾名（IQN）
** iSCSI IPアドレス
** ソースデータの発信元であるリモートストレージデバイスのLUN番号


* インポートプロセスが開始されると、ローカルのデスティネーションボリューム全体がコピーされたデータで上書きされます。ローカルデスティネーションボリュームに新たに書き込まれたデータは、インポートの作成後にリモートストレージデバイス上のボリュームに伝播されます。そのため、インポートプロセスを開始する前にリモートストレージシステムのボリュームをバックアップすることを推奨します。




=== インポートプロセス

以下に、インポートプロセスの概要を示します。

. System Managerインターフェイスにアクセスし、* Remote Storage *ページに移動します。「*読み込み*」を選択して、新しいインポートの作成を開始します。手順の詳細については、を参照してください link:rtv-import-remote-storage.html["リモートストレージをインポートします"]。
+
オフラインインポートを実行する場合は、インポートが完了するまでデスティネーションボリュームをマッピングしないでください。

. インポートの進捗状況を監視します。
+
インポートが開始されたら、ターゲットボリュームをマッピングできます。インポート処理にかかる時間は、リモートストレージデバイス（ソースボリューム）のサイズ、インポートの優先度設定、ストレージシステムとその関連ボリュームのI/O負荷の量によって異なります。

+
インポートが完了すると、ターゲットボリュームがソースボリュームと同じになります。

. マッピング関係を解除する準備ができたら、インポートオブジェクトに対して*操作実行中*パネルから*切断*を実行します。


インポートが切断されると、ローカル宛先のパフォーマンスは通常に戻り、リモート接続による影響を受けなくなります。



=== 制限事項

リモートストレージ機能には、次の制限事項があります。

* ミラーリングを無効にする必要があります。
* E シリーズシステムのデスティネーションボリュームに Snapshot が存在しないようにします。
* インポートを開始する前に、 E シリーズシステムのデスティネーションボリュームをホストにマッピングしないでください。
* E シリーズシステムのデスティネーションボリュームでリソースプロビジョニングが無効になっている必要があります。
* リモートストレージボリュームをホストまたは複数のホストに直接マッピングすることはできません。
* Web Services Proxy はサポートされていません。
* iSCSI CHAP シークレットはサポートされません。
* SMcli はサポートされません。
* VMware データストアはサポートされません。
* インポートペアが存在する場合、関係 / インポートペアにあるストレージシステムは一度に 1 つだけアップグレードできます。




=== 追加情報

リモートストレージ機能の詳細については、を参照してください https://www.netapp.com/pdf.html?item=/media/28697-tr-4893-deploy.pdf["Remote Storageテクニカルレポート"^]。
