---
permalink: sm-storage/faq-snapshots.html 
sidebar: sidebar 
keywords:  
summary: この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。 
---
= SANtricity System Manager のスナップショットに関する FAQ
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。



== ボリューム、ホスト、またはホスト クラスタが一部表示されないのはなぜですか?

ベースボリュームでData Assurance（DA）が有効なSnapshotボリュームを、DA対応でないホストに割り当てることはできません。DA対応でないホストにSnapshotボリュームを割り当てるには、ベースボリュームのDAを無効にする必要があります。

Snapshotボリュームを割り当てるホストについては、次のガイドラインを考慮してください。

* DA対応でないI/Oインターフェイスを使用してストレージアレイに接続されているホストは、DA対応ではありません。
* ホストメンバーが1つでもDA対応でないホストクラスタは、DA対応ではありません。


[NOTE]
====
Snapshot（整合性グループ、Snapshotグループ、Snapshotイメージ、Snapshotボリューム）、ボリュームコピーに関連付けられているボリュームでは、DAを無効にできません。 ミラーリングも可能です。ベースボリュームのDAを無効にするには、最初に関連付けられているすべてのリザーブ容量とSnapshotオブジェクトを削除する必要があります。

====


== Snapshotイメージとは何ですか？

Snapshotイメージは、ボリュームの内容を特定の時点でキャプチャした論理コピーです。Snapshotイメージが使用するストレージスペースは最小限です。

Snapshotイメージのデータは次のように格納されます。

* Snapshotイメージが作成された時点では、Snapshotイメージはベースボリュームと完全に一致します。Snapshotの作成後、ベースボリューム上のブロックに対して最初の書き込み要求が行われると、新しいデータがベースボリュームに書き込まれる前に元のデータがSnapshotリザーブ容量にコピーされます。
* 以降のSnapshotには、最初のSnapshotイメージの作成後に変更されたデータブロックのみが含まれます。以降のcopy-on-write処理では、新しいデータがベースボリュームに書き込まれる前に、ベースボリュームで上書きされる元のデータがSnapshotリザーブ容量に保存されます。




== Snapshotイメージを使用するのはなぜですか？

Snapshotを使用すると、偶然または悪意のある行為によるデータの損失や破損からデータを保護し、リカバリすることができます。

ベースボリュームまたはベースボリュームのグループであるSnapshot整合性グループを選択し、次のいずれかまたは複数の方法でSnapshotイメージをキャプチャします。

* 1つのベースボリューム、または複数のベースボリュームで構成されるSnapshot整合性グループのSnapshotイメージを作成できます。
* 手動でSnapshotを作成するか、ベースボリュームまたはSnapshot整合性グループの定期的なSnapshotイメージを自動的にキャプチャするスケジュールを作成できます。
* ホストからアクセス可能なSnapshotイメージのSnapshotボリュームを作成できます。
* ロールバック処理を実行してSnapshotイメージをリストアできます。


複数のSnapshotイメージがリストアポイントとして保持されるため、特定の時点の既知の正常なデータセットにロールバックできます。ロールバック機能により、偶発的なデータの削除や破損からの保護が提供されます。



== Snapshotにはどのような種類のボリュームを使用できますか？

Snapshotイメージを格納できるボリュームは、標準ボリュームとシンボリュームだけです。標準以外のボリュームは使用できません。ベースボリュームはプールまたはボリュームグループのどちらかに配置できます。



== Snapshot整合性グループを作成するのはどのような場合ですか？

Snapshot整合性グループは、複数のボリュームで同時にSnapshotイメージが作成されるようにする場合に作成します。

たとえば、リカバリ目的で整合性を保つ必要がある複数のボリュームで構成されるデータベースが該当します。この場合、すべてのボリュームのSnapshotを同時に収集し、収集したSnapshotを使用してデータベース全体をリストアするために、Snapshot整合性グループが必要です。

Snapshot整合性グループに含まれるボリュームのことを_member volume__と呼びます。

Snapshot整合性グループに対して次のSnapshot処理を実行できます。

* メンバーボリュームの同時イメージを取得するために、Snapshot整合性グループのSnapshotイメージを作成する。
* メンバーボリュームの定期的な同時イメージを自動的にキャプチャするために、Snapshot整合性グループのスケジュールを作成する。
* ホストからアクセス可能なSnapshot整合性グループイメージのSnapshotボリュームを作成する。
* Snapshot整合性グループのロールバック処理を実行する。




== Snapshotボリュームとは何ですか？また、Snapshotボリュームにリザーブ容量が必要になるのはいつですか？

Snapshotボリュームを使用すると、ホストはSnapshotイメージのデータにアクセスできます。Snapshotボリュームには独自のリザーブ容量があり、元のSnapshotイメージに影響を与えることなくベースボリュームへの変更が保存されます。Snapshotイメージに対するホストからの読み取りや書き込みはできません。Snapshotデータの読み取りまたは書き込みを行う場合は、Snapshotボリュームを作成してホストに割り当てます。

2種類のSnapshotボリュームを作成できます。Snapshotボリュームのタイプによって、リザーブ容量が使用されるかどうかが決まります。

* *読み取り専用*--読み取り専用として作成されたスナップショット・ボリュームは'スナップショット・イメージに含まれるデータのコピーへの読み取りアクセスをホスト・アプリケーションに提供します読み取り専用のSnapshotボリュームはリザーブ容量を使用しません。
* *読み取り/書き込み*-読み書き可能として作成されたSnapshotボリュームでは、参照されているSnapshotイメージに影響を与えることなくSnapshotボリュームに変更を加えることができます。読み書き可能なSnapshotボリュームは、リザーブ容量を使用してこの変更を格納します。読み取り専用のSnapshotボリュームは、いつでも読み書き可能ボリュームに変換できます。




== Snapshotグループとは何ですか？

Snapshotグループは、1つの関連するベースボリュームのポイントインタイムSnapshotイメージの集まりです。

System Managerでは、Snapshotイメージを_ Snapshotグループ_に編成します。Snapshotグループに対するユーザの操作は必要ありませんが、Snapshotグループではリザーブ容量をいつでも調整できます。また、次の条件を満たす場合は、リザーブ容量の作成を求められることがあります。

* SnapshotグループがまだないベースボリュームのSnapshotを作成するたびに、System ManagerはSnapshotグループを自動的に作成します。これにより、ベースボリュームのリザーブ容量が作成され、後続のSnapshotイメージの格納に使用されます。
* ベースボリュームのSnapshotスケジュールを作成するたびに、System ManagerはSnapshotグループを自動的に作成します。




== Snapshotボリュームを無効にするのはどのような場合ですか？

Snapshotイメージに別のSnapshotボリュームを割り当てる場合は、Snapshotボリュームを無効にします。無効にしたSnapshotボリュームは、あとで使用できます。

Snapshotボリュームまたは整合性グループのSnapshotボリュームが不要になり、あとで再作成する予定がない場合は、無効にするのではなく、ボリュームを削除してください。



== 無効状態とは何ですか？

無効状態のSnapshotボリュームは、現在Snapshotイメージに割り当てられていません。Snapshotボリュームを有効にするには、再作成処理を使用して無効なSnapshotボリュームに新しいSnapshotイメージを割り当てる必要があります。

Snapshotボリュームの特性は、割り当てられているSnapshotイメージによって定義されます。無効ステータスのSnapshotボリュームでは、読み取り/書き込みアクティビティは中断されています。



== Snapshotスケジュールを一時停止するのはどのような場合ですか？

スケジュールを一時停止すると、スケジュールに基づいたSnapshotイメージの作成は実行されません。ストレージスペースを節約するためにSnapshotスケジュールを一時停止し、あとでスケジュールされたSnapshotを再開できます。

Snapshotスケジュールが不要な場合は、スケジュールを一時停止するのではなく、削除してください。
