---
permalink: sm-storage/how-workloads-work.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, application, workloads, volume, 
summary: ボリュームを作成する際には、ワークロードを選択して特定のアプリケーション用にストレージアレイの構成をカスタマイズします。 
---
= ワークロードの仕組み
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリュームを作成する際には、ワークロードを選択して特定のアプリケーション用にストレージアレイの構成をカスタマイズします。

ワークロードは、アプリケーションをサポートするストレージオブジェクトです。アプリケーションごとに1つ以上のワークロードまたはインスタンスを定義できます。一部のアプリケーションでは、特性が似たボリュームで構成されるようにワークロードが設定されます。これらのボリューム特性は、ワークロードがサポートするアプリケーションのタイプに基づいて最適化されます。たとえば、Microsoft SQL Serverアプリケーションをサポートするワークロードを作成し、そのワークロード用のボリュームを作成すると、Microsoft SQL Serverをサポートするようにボリューム特性が最適化されます。

ボリュームの作成時には、ワークロードの用途について回答 から質問するプロンプトが表示されます。たとえば、Microsoft Exchange用のボリュームを作成する場合は、必要なメールボックスの数、メールボックスに必要とされる平均容量、およびデータベースのコピーをいくつ作成するかについて設定します。この情報に基づいて最適なボリューム構成が作成されるため、必要に応じて編集することができます。必要に応じて、ボリューム作成のこの手順をスキップできます。



== ワークロードのタイプ

アプリケーション固有とその他の2種類のワークロードを作成できます。

* *アプリケーション固有*。アプリケーション固有のワークロードを使用してボリュームを作成する場合、アプリケーションワークロードのI/Oとアプリケーションインスタンスからの他のトラフィックの競合が最小限になるように最適化されたボリューム構成が提示されることがあります。I/Oタイプ、セグメントサイズ、コントローラ所有権、読み取り/書き込みキャッシュなどのボリューム特性が自動的に推奨され、次のアプリケーションタイプ用に作成されるワークロードに合わせて最適化されます。
+
** Microsoft®SQL Server™
** Microsoft®Exchange Server™
** ビデオ監視アプリケーション
** VMware ESXi™（仮想マシンファイルシステムで使用するボリューム用）
+
ボリュームの追加/編集ダイアログボックスを使用して、推奨されるボリューム構成を確認し、システムで推奨されるボリュームや特性を編集、追加、削除できます。



* *その他*（または特定のボリューム作成サポートのないアプリケーション）。特定のアプリケーションに関連付けられていないワークロードを作成する場合や、ストレージアレイで使用する予定のアプリケーションに対する最適化が組み込まれていない場合は、その他のワークロードではボリューム構成を手動で指定する必要があります。ボリュームの追加/編集ダイアログボックスを使用して、ボリューム構成を手動で指定する必要があります。




== アプリケーションとワークロードの表示

アプリケーションとワークロードを表示するには、SANtricity システムマネージャを起動します。このインターフェイスから、アプリケーション固有のワークロードに関連する情報をいくつかの方法で表示できます。

* ボリュームのタイルで「*アプリケーションとワークロード*」タブを選択すると、ストレージアレイのボリュームをワークロード別にグループ化し、ワークロードが関連付けられているアプリケーションタイプを表示できます。
* パフォーマンスタイルの*アプリケーションとワークロード*タブを選択すると、論理オブジェクトのパフォーマンス指標（レイテンシ、IOPS、MB）を表示できます。オブジェクトはアプリケーションおよび関連付けられているワークロード別にグループ化されます。このパフォーマンスデータを定期的に収集することで、ベースラインとなる数値を設定して傾向を分析することができ、I/Oパフォーマンスに関する問題の調査に役立ちます。

