---
permalink: sm-storage/how-reserved-capacity-works.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, reserved, capacity, 
summary: リザーブ容量は、Snapshotや非同期ミラーリング処理などのコピーサービス処理がボリュームに提供されている場合に自動的に作成されます。 
---
= リザーブ容量の仕組み
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
リザーブ容量は、Snapshotや非同期ミラーリング処理などのコピーサービス処理がボリュームに提供されている場合に自動的に作成されます。

リザーブ容量の目的は、何らかの不具合が発生した場合に備えて、これらのボリューム上のデータ変更を保存することです。ボリュームと同様に、リザーブ容量はプールまたはボリュームグループから作成されます。



== リザーブ容量を使用するコピーサービスオブジェクト

リザーブ容量は、以下のコピーサービスオブジェクトによって使用される、基盤となるストレージメカニズムです。

* Snapshotグループ
* 読み取り/書き込みSnapshotボリューム
* 整合性グループメンバーボリューム
* ミラーペアボリューム


これらのコピーサービスオブジェクトを作成または拡張するときは、プールまたはボリュームグループから新しいリザーブ容量を作成する必要があります。リザーブ容量は通常、Snapshot処理の場合はベースボリュームの40%、非同期ミラーリング処理の場合はベースボリュームの20%です。ただし、リザーブ容量は元のデータに対する変更の数によって異なります。



== シンボリュームとリザーブ容量

シンボリュームの場合、最大レポート容量の256TiBに達していると容量を拡張できません。シンボリュームのリザーブ容量が最大レポート容量よりも大きいサイズに設定されていることを確認してください。（シンボリュームは常にシンプロビジョニングされます。つまり、データがボリュームに書き込まれるときに容量が割り当てられます）。

プール内のシンボリュームを使用してリザーブ容量を作成する場合は、リザーブ容量に関して次の操作と結果を確認してください。

* シンボリュームのリザーブ容量に障害が発生した場合、シンボリューム自体が自動的に失敗状態に移行することはありません。ただし、シンボリュームに対するI/O処理はすべてリザーブ容量ボリュームにアクセスする必要があるため、I/O処理は常にCheck Conditionを要求元ホストに返します。リザーブ容量ボリュームの根本的な問題を解決できる場合は、リザーブ容量ボリュームが最適状態に戻り、シンボリュームが再び機能するようになります。
* 既存のシンボリュームを使用して非同期ミラーペアを作成する場合、そのシンボリュームは新しいリザーブ容量ボリュームを使用して再初期化されます。初期同期プロセス中は、プライマリ側のプロビジョニングされたブロックのみが転送されます。




== 容量アラート

コピーサービスオブジェクトには、容量の警告およびアラートのしきい値を設定可能で、リザーブ容量がフルの場合の応答も設定可能です。

コピーサービスオブジェクトボリュームのリザーブ容量がフルに近付くと、アラートが送信されます。デフォルトでは、このアラートはリザーブ容量ボリュームの使用率が75%に達したときに発行されます。ただし、必要に応じて増減できます。このアラートを受け取った場合は、その時点でリザーブ容量ボリュームの容量を増やすことができます。この点で、各コピーサービスオブジェクトを個別に設定できます。



== 孤立したリザーブ容量ボリューム

孤立したリザーブ容量ボリュームとは、関連付けられているコピーサービスオブジェクトが削除されたためにコピーサービス処理のデータを保存しなくなったボリュームのことです。コピーサービスオブジェクトが削除されたときは、リザーブ容量ボリュームも削除されている必要があります。リザーブ容量ボリュームの削除に失敗しました。

孤立したリザーブ容量ボリュームは、どのホストからもアクセスできないため、再生候補となります。孤立したリザーブ容量ボリュームを手動で削除して、その容量を他の処理で使用できるようにします。

System Managerでは、孤立したリザーブ容量ボリュームについて、ホームページの通知領域に「再利用未使用容量」というメッセージが表示されます。未使用容量を再利用する*をクリックすると、未使用容量の再生ダイアログボックスが表示され、孤立したリザーブ容量ボリュームを削除できます。



== リザーブ容量の特性

* 十分な空き容量を保持するために、ボリュームの作成時にはリザーブ容量に割り当てられる容量を考慮する必要があります。
* リザーブ容量はベースボリュームより小さくすることができます（最小サイズは8MiB）。
* 一部のスペースはメタデータによって消費されますが、ごくわずか（192KiB）なので、リザーブ容量ボリュームのサイズを特定する際に考慮する必要はありません。
* リザーブ容量は、ホストから直接読み取りまたは書き込みすることはできません。
* リザーブ容量は、読み取り/書き込みSnapshotボリューム、Snapshotグループ、整合性グループメンバーボリューム、ミラーペアボリュームごとに確保されます。

