---
permalink: sm-storage/how-ssd-cache-works.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, ssd cache, 
summary: SSDキャッシュ機能は、アクセス頻度が特に高いデータ（「ホット」データ）を低レイテンシのソリッドステートドライブ（SSD）にキャッシュすることでシステムのパフォーマンスを動的に向上させるコントローラベースの解決策 です。SSDキャッシュは、ホスト読み取りにのみ使用されます。 
---
= SSDキャッシュの仕組み
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SSDキャッシュ機能は、アクセス頻度が特に高いデータ（「ホット」データ）を低レイテンシのソリッドステートドライブ（SSD）にキャッシュすることでシステムのパフォーマンスを動的に向上させるコントローラベースの解決策 です。SSDキャッシュは、ホスト読み取りにのみ使用されます。

[NOTE]
====
この機能は、EF600またはEF300ストレージシステムでは使用できません。

====


== SSDキャッシュとプライマリキャッシュ

SSDキャッシュはセカンダリキャッシュであり、コントローラの動的ランダムアクセスメモリ（DRAM）にあるプライマリキャッシュと組み合わせて使用されます。

SSDキャッシュとプライマリキャッシュは動作が異なります。

* プライマリキャッシュの場合、I/O処理ごとにキャッシュ経由でデータをステージングする必要があります。
+
プライマリキャッシュでは、データはホスト読み取り後にDRAMに格納されます。

* SSDキャッシュを使用するのは、データをキャッシュに配置してシステム全体のパフォーマンスを向上させると効果的なだけです。
+
SSDキャッシュでは、データはボリュームからコピーされて2つの内部RAIDボリューム（コントローラごとに1つ）に格納されます。RAIDボリュームはSSDキャッシュの作成時に自動的に作成されます。



内部RAIDボリュームは、内部的なキャッシュ処理に使用されます。ユーザがアクセスすることはできず、ユーザインターフェイスにも表示されません。ただし、ストレージアレイで許可されるボリュームの総数には、これら2つのボリュームも含まれます。



== SSDキャッシュの使用方法

インテリジェントキャッシングでは、低レイテンシのドライブにデータが配置されるため、以降そのデータに対して要求があった場合の応答速度が大幅に向上します。キャッシュ内のデータをプログラムが要求すると(キャッシュヒットと呼ばれます)'低遅延ドライブはそのトランザクションを処理できますそれ以外の場合は「キャッシュミス」が発生し、元の低速ドライブからデータにアクセスする必要があります。キャッシュヒット数が増加するほど、全体的なパフォーマンスが向上します。

ホストプログラムがストレージアレイのドライブにアクセスすると、データはSSDキャッシュに格納されます。ホストプログラムが再度同じデータにアクセスすると、そのデータはハードドライブではなくSSDキャッシュから読み取られます。よくアクセスされるデータはSSDキャッシュに格納されます。ハードドライブは、SSDキャッシュからデータを読み取ることができない場合にのみアクセスされます。

SSDキャッシュは、データをキャッシュに配置するとシステム全体のパフォーマンスを向上できる場合にのみ使用されます。

CPUがリードデータを処理する必要がある場合は、次の手順に従います。

. DRAMキャッシュをチェックします。
. DRAMキャッシュで検出されない場合は、SSDキャッシュをチェックします。
. SSDキャッシュで検出されない場合は、ハードドライブから取得します。データをキャッシュする価値があると判断された場合は、SSDキャッシュにコピーします。




== パフォーマンスの向上

最もアクセスされるデータ（ホットスポット）をSSDキャッシュにコピーすると、ハードディスクの処理効率が向上し、レイテンシが低減され、読み取りと書き込みの速度が向上します。ハイパフォーマンスのSSDを使用してHDDボリュームのデータをキャッシュすると、I/Oパフォーマンスと応答時間が向上します。

SSDキャッシュとの間のデータの移動には、単純なボリュームI/Oのメカニズムが使用されます。データがキャッシュされてSSDに格納されると、そのデータの以降の読み取りはSSDキャッシュに対して実行されるため、HDDボリュームにアクセスする必要はありません。



== SSDキャッシュとドライブセキュリティ機能

ドライブセキュリティを使用している（セキュリティ有効）ボリュームでSSDキャッシュを使用する場合は、そのボリュームとSSDキャッシュのドライブセキュリティ機能が同じである必要があります。同じでない場合、ボリュームはセキュリティ有効になりません。



== SSDキャッシュを実装する

SSDキャッシュを実装するには、次の手順を実行します。

. SSDキャッシュを作成します。
. SSD読み取りキャッシュを実装するボリュームにSSDキャッシュを関連付けます。


[NOTE]
====
コントローラのSSDキャッシュを使用するように割り当てられたボリュームは、自動ロードバランシングによる転送の対象外となります。

====