---
permalink: sm-storage/how-do-i-view-and-interpret-all-ssd-cache-statistics.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, ssd cache, statistics 
summary: SSDキャッシュについては、一般統計と詳細統計を表示できます。一般統計は詳細統計のサブセットです。 
---
= SSDキャッシュのすべての統計情報を表示するにはどうすればよいですか？また、何が
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SSDキャッシュについては、一般統計と詳細統計を表示できます。一般統計は詳細統計のサブセットです。

詳細統計は'すべてのSSD統計を.csvファイルにエクスポートした場合にのみ表示できます統計を確認および解釈する際には、複数の統計を組み合わせることで見えてくる情報もあることに注意してください。



== 一般統計

SSDキャッシュの統計を表示するには、次のメニューを選択します。Storage [Pools & Volume Groups]統計を表示するSSDキャッシュを選択し、メニューを選択します。More [View Statistics]公称統計はView SSD Cache Statistics（SSDキャッシュ統計の表示）ダイアログに表示されます。

次に、詳細統計のサブセットである、一般統計の一覧を示します。

[cols="25h,~"]
|===
| 一般統計 | 説明 


 a| 
読み取り/書き込み
 a| 
SSDキャッシュが有効なボリュームに対するホストの読み取りと書き込みの合計数。読み取り数を書き込み数と比較します。効率的なSSDキャッシュ処理には、読み取り数が書き込み数より多いことが必要です。書き込みに対する読み取りの比率が大きいほど、キャッシュ処理が向上します。



 a| 
キャッシュヒット
 a| 
キャッシュヒットの数。



 a| 
キャッシュヒット率（%）
 a| 
キャッシュヒット数を読み取りと書き込みの合計数で割った値。効果的なSSDキャッシュ処理には、キャッシュヒットの割合が50%より高いことが必要です。この値が小さい場合は、次のような状況が考えられます。

* 書き込みに対する読み取りの比率が小さすぎる
* 読み取りが繰り返されない
* キャッシュ容量が小さすぎる




 a| 
キャッシュ割り当て率（%）
 a| 
割り当てられているSSDキャッシュストレージの量。このコントローラで使用可能なSSDキャッシュストレージの割合として表されます。割り当てられたバイト数を使用可能なバイト数で割った値です。キャッシュ割り当ての割合は、通常は100%と表示されます。この数値が100%未満の場合は、キャッシュがウォームアップされていないか、アクセスされているすべてのデータよりもSSDキャッシュ容量が大きいことを意味します。後者の場合、SSDキャッシュ容量を小さくしても同レベルのパフォーマンスが得られる可能性があります。この値は、キャッシュされたデータがSSDキャッシュに配置されたことを示しているわけではなく、SSDキャッシュにデータを配置可能となる前の準備手順にすぎません。



 a| 
キャッシュ使用率（%）
 a| 
有効なボリュームのデータが格納されているSSDキャッシュストレージの量。割り当てられているSSDキャッシュストレージの割合として表されます。この値はSSDキャッシュの利用率または密度を表し、ユーザデータのバイト数を割り当てられているバイト数で割った値です。キャッシュ使用率の割合は、通常は100%より小さく、多くの場合はるかに小さくなります。この数値は、SSDキャッシュ容量のうち、キャッシュデータが書き込まれている割合を示します。SSDキャッシュの各割り当て単位はサブブロックと呼ばれる小さい単位に分割され、それぞれ独立して使用されるため、この値は100%より小さくなります。この値が大きいほど一般には有効ですが、小さい数値でもパフォーマンスが大幅に向上する可能性があります。

|===


== 詳細統計

詳細統計は、一般統計とその他の統計で構成されます。これらの追加統計は一般統計とともに保存されますが、一般統計とは異なり、View SSD Cache Statistics（SSDキャッシュ統計の表示）ダイアログには表示されません。詳細統計は'.csvファイルに統計をエクスポートした後にのみ表示できます

「.csv」ファイルを表示するときに、詳細統計が一般統計の後にリストされていることに注目してください。

[cols="25h,~"]
|===
| 詳細統計 | 説明 


 a| 
読み取りブロック
 a| 
ホスト読み取りのブロック数。



 a| 
書き込みブロック
 a| 
ホスト書き込みのブロック数。



 a| 
完全ヒットブロック
 a| 
キャッシュヒットのブロック数。この値は、SSDキャッシュから完全に読み込まれたブロックの数を示します。SSDキャッシュがパフォーマンスの向上に効果があるのは、フルキャッシュヒットである処理に対してのみです。



 a| 
部分ヒット
 a| 
すべてのブロックではなく、少なくとも1つのブロックがSSDキャッシュ内にあったホスト読み取りの数。部分ヒットはSSDキャッシュ*ミス*で、読み取りはベースボリュームから行われています。



 a| 
部分ヒット-ブロック
 a| 
部分ヒットのブロック数。部分キャッシュヒットと部分キャッシュヒットブロックは、SSDキャッシュ内にデータの一部しかない処理の結果として発生します。この場合、キャッシュされているハードディスクドライブ（HDD）ボリュームからデータを取得する必要があります。このタイプのヒットの場合、SSDキャッシュから得られるパフォーマンス上のメリットはありません。部分キャッシュヒットブロック数が完全キャッシュヒットブロック数より多い場合は、別のI/O特性タイプ（ファイルシステム、データベース、またはWebサーバ）を使用するとパフォーマンスが向上する可能性があります。SSDキャッシュのウォームアップ中は、キャッシュヒットに比べて、部分ヒットとミスの数が増えることが予想されます。



 a| 
ミス
 a| 
SSDキャッシュ内にブロックがなかったホスト読み取りの数。SSDキャッシュミスは、ベースボリュームから読み取りが行われた場合に発生します。SSDキャッシュのウォームアップ中は、キャッシュヒットに比べて、部分ヒットとミスの数が増えることが予想されます。



 a| 
ミス-ブロック
 a| 
ミスしたブロックの数。



 a| 
取り込み処理（ホスト読み取り）
 a| 
ベースボリュームからSSDキャッシュへデータがコピーされたホスト読み取りの数。



 a| 
取り込み処理（ホスト読み取り）-ブロック
 a| 
取り込み処理（ホスト読み取り）のブロック数。



 a| 
取り込み処理（ホスト書き込み）
 a| 
ベースボリュームからSSDキャッシュへデータがコピーされたホスト書き込みの数。書き込みI/O処理によってキャッシュが一杯にならないキャッシュ設定では、取り込み処理（ホスト書き込み）の数が0になることがあります。



 a| 
取り込み処理（ホスト書き込み）-ブロック
 a| 
取り込み処理（ホスト書き込み）のブロック数。



 a| 
無効化処理
 a| 
データが無効化された、またはSSDキャッシュから削除された回数。キャッシュの無効化処理は、各ホスト書き込み要求、Forced Unit Access（FUA）によるホスト読み取り要求、確認要求、およびその他一部の状況で実行されます。



 a| 
リサイクル処理
 a| 
別のベースボリュームや論理ブロックアドレス（LBA）範囲にSSDキャッシュブロックが再利用された回数。効果的なキャッシュでは、再利用の回数は、読み取り処理と書き込み処理の合計数よりも少なくする必要があります。リサイクル処理の回数が読み取りと書き込みの合計数に近づいている場合、SSDキャッシュがスラッシングしています。キャッシュ容量を増やす必要があります。または、ワークロードがSSDキャッシュの使用に適していません。



 a| 
使用可能なバイト数
 a| 
SSDキャッシュ内でこのコントローラによって使用可能なバイト数。



 a| 
割り当てバイト数
 a| 
このコントローラによってSSDキャッシュから割り当てられたバイト数。SSDキャッシュから割り当てられたバイトは、空の場合と、ベースボリュームのデータが含まれている場合があります。



 a| 
ユーザデータバイト数
 a| 
SSDキャッシュ内の、ベースボリュームのデータを含む割り当て済みバイト数。使用可能なバイト数、割り当て済みバイト数、およびユーザデータのバイト数を使用して、キャッシュ割り当ての割合とキャッシュ利用率の割合が計算されます。

|===