---
permalink: sm-storage/how-workloads-work.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, application, workloads, volume, 
summary: ボリュームを作成する際には、ワークロードを選択して特定のアプリケーション用にストレージアレイの構成をカスタマイズします。 
---
= SANtricityソフトウェアにおけるワークロードの仕組み
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリュームを作成する際には、ワークロードを選択して特定のアプリケーション用にストレージアレイの構成をカスタマイズします。

ワークロードは、アプリケーションをサポートするストレージオブジェクトです。アプリケーションごとに1つ以上のワークロードまたはインスタンスを定義できます。



== ワークロードの作成

特定のアプリケーションに関連付けられていないワークロードを作成する場合は、手動で指定する必要があります。また、「ボリュームの追加」ページを使用して、ボリューム構成を手動で指定する必要があります。



== アプリケーションとワークロードの表示

アプリケーションとワークロードを表示するには、SANtricity システムマネージャを起動します。このインターフェイスから、アプリケーション固有のワークロードに関連する情報をいくつかの方法で表示できます。

* ボリュームページで*アプリケーションとワークロード*タブを選択すると、ストレージアレイのボリュームがワークロードと、そのワークロードに関連付けられているアプリケーションの種類ごとにグループ化されて表示されます。
* パフォーマンスページの*アプリケーションとワークロード*タブを選択すると、論理オブジェクトのパフォーマンスメトリック（レイテンシ、IOPS、MB）を表示できます。オブジェクトは、アプリケーションと関連するワークロードごとにグループ化されています。定期的にこのパフォーマンスデータを収集することで、基準となる測定値を確立し、傾向を分析することができます。これは、I/Oパフォーマンスに関連する問題を調査する際に役立ちます。

