---
permalink: sm-storage/how-volumes-are-assigned-to-hosts-and-host-clusters.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, volumes, assigned, hosts, clusters 
summary: ホストまたはホストクラスタからボリュームへI/Oを送信するには、ボリュームをホストまたはホストクラスタに割り当てる必要があります。 
---
= ホストおよびホストクラスタへのボリュームの割り当て方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ホストまたはホストクラスタからボリュームへI/Oを送信するには、ボリュームをホストまたはホストクラスタに割り当てる必要があります。

ボリュームを作成するときにホストまたはホストクラスタを選択するか、あとからボリュームをホストまたはホストクラスタに割り当てることができます。ホストクラスタはホストのグループです。ホストクラスタを作成すると、同じボリュームを複数のホストに簡単に割り当てることができます。

ホストへのボリュームの割り当ては柔軟性が高く、ストレージの特定のニーズを満たすことができます。

* *ホストクラスタの一部ではなく、スタンドアロンホスト*--ボリュームを個々のホストに割り当てることができます。ボリュームにアクセスできるのは1つのホストだけです。
* *ホストクラスタ*--ボリュームをホストクラスタに割り当てることができますボリュームには、ホストクラスタ内のすべてのホストからアクセスできます。
* *ホストクラスタ内のホスト*--ホストクラスタの一部である個別のホストにボリュームを割り当てることができますホストはホストクラスタの一部ですが、ボリュームにアクセスできるのは個々のホストだけであり、ホストクラスタ内の他のホストからはアクセスできません。


ボリュームの作成時に、論理ユニット番号（LUN）が自動的に割り当てられます。LUNは、I/O処理中のホストとコントローラの間の「アドレス」の役割を果たします。LUNはボリュームが作成されたあとに変更できます。
