---
permalink: sm-storage/how-volumes-work.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, volume, copy, 
summary: ボリュームは、ストレージアレイ上のストレージスペースを管理および編成するデータコンテナです。 
---
= ボリュームの仕組み
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリュームは、ストレージアレイ上のストレージスペースを管理および編成するデータコンテナです。

ストレージアレイ上の使用可能なストレージ容量からボリュームを作成して、システムのリソースを簡単に編成して使用することができます。この概念は、コンピュータ上のフォルダ/ディレクトリを使用してファイルを整理し、すばやく簡単にアクセスできるようにすることに似ています。

ボリュームは、ホストから認識できる唯一のデータレイヤです。SAN環境では、論理ユニット番号（LUN）にマッピングされたボリュームをホストから認識できます。LUNは、FC、iSCSI、SASなど、ストレージアレイでサポートされている1つ以上のホストアクセスプロトコルを使用してアクセス可能なユーザデータを保持します。



== プールおよびボリュームグループから作成できるボリュームタイプ

ボリュームは、プールまたはボリュームグループから容量を取得します。ストレージアレイ上のプールまたはボリュームグループから次のタイプのボリュームを作成できます。

* *プールから*--プールからは、_フルプロビジョニング（シック）ボリューム_または_シンプロビジョニング（シン）ボリュームとしてボリュームを作成できます。_
+
[NOTE]
====
System Managerインターフェイスには、シンボリュームを作成するオプションはありません。シンボリュームを作成する場合は、コマンドラインインターフェイス（CLI）を使用します。

====
* *ボリュームグループから*--ボリュームグループからボリュームを作成できるのは_完全にプロビジョニングされた（シック）ボリューム_のみです。


シックボリュームとシンボリュームは、次に示す方法でストレージアレイから容量を取得します。

* シックボリュームの容量は、ボリュームの作成時に割り当てられます。
* シンボリュームの容量は、ボリュームへの書き込みの際にデータとして割り当てられます。


シンプロビジョニングを使用すると、無駄な容量の割り当てを回避し、ストレージの初期コストを削減できます。ただし、シックボリュームが作成されるとすべてのストレージが一度に割り当てられるため、完全なプロビジョニングのメリットとしてはレイテンシの低下が挙げられます。

[NOTE]
====
EF600およびEF300ストレージシステムでは、シンプロビジョニングはサポートされません。

====


== ボリュームの特性

プールまたはボリュームグループ内の各ボリュームには、格納されるデータのタイプに基づいて独自の特性があります。たとえば、次のような特性があります。

* *セグメントサイズ*-セグメントは、あるドライブに格納されるデータの量（KiB）です。この量に達すると、ストライプ（RAIDグループ）内の次のドライブへと進みます。セグメントサイズは、ボリュームグループの容量と同じかそれよりも小さくなります。プールのセグメントサイズは固定で、変更することはできません。
* *容量*-プールまたはボリュームグループの空き容量からボリュームを作成します。ボリュームを作成するには、プールまたはボリュームグループがすでに存在している必要があります。また、ボリュームを作成するための十分な空き容量がプールまたはボリュームグループに必要です。
* *コントローラ所有権*--すべてのストレージアレイは'1台または2台のコントローラを持つことができますシングルコントローラアレイでは、ボリュームのワークロードが1台のコントローラで管理されます。デュアル・コントローラ・アレイでは'ボリュームを「所有」する優先コントローラ（AまたはB）がボリュームに割り当てられますデュアルコントローラ構成では、自動ロードバランシング機能を使用してボリューム所有権が自動的に調整され、コントローラ間でワークロードが移動する際の負荷の不均衡が解消されます。自動ロードバランシングはI/Oワークロードを自動的に分散する機能を提供し、ホストからの受信I/Oトラフィックは動的に管理されて両方のコントローラに分散されます。
* *ボリューム割り当て*--ボリュームの作成時または後で、ホストにボリュームへのアクセス権を与えることができます。すべてのホストアクセスは、論理ユニット番号（LUN）を使用して管理されます。ホストは、ボリュームに割り当てられているLUNを検出します。ボリュームを複数のホストに割り当てる場合は、クラスタリングソフトウェアを使用して、すべてのホストからボリュームを使用できるようにしてください。
+
ホストタイプでは、ホストがアクセスできるボリュームの数に制限がある場合があります。特定のホストで使用するボリュームを作成するときは、この制限に注意してください。

* *わかりやすい名前*--ボリュームに任意の名前を付けることができますが、わかりやすい名前にすることをお勧めします。


ボリュームの作成時には、各ボリュームに容量が割り当てられ、名前、セグメントサイズ（ボリュームグループの場合のみ）、コントローラ所有権、およびボリュームとホストの割り当てが指定されます。ボリュームデータは、必要に応じてコントローラ間で自動的に負荷分散されます。
