---
permalink: sm-storage/increase-capacity-of-a-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, increase, capacity, volume 
summary: プールまたはボリュームグループ内の使用可能な空き容量を使用して、ボリュームのレポート容量（ホストに報告される容量）を拡張できます。 
---
= SANtricity System Managerでボリュームの容量を増やす
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
プールまたはボリュームグループ内の使用可能な空き容量を使用して、ボリュームのレポート容量（ホストに報告される容量）を拡張できます。

.作業を開始する前に
* ボリュームの関連付けられたプールまたはボリュームグループに十分な空き容量が必要です。
* ボリュームが最適状態で、変更中の状態ではありません。
* シンボリュームのレポート容量が最大値の256TiBに達していない必要があります。
* ボリュームでホットスペアドライブが使用されていない必要があります。（ボリュームグループ内のボリュームにのみ適用されます）。



NOTE: ボリューム容量は一度に最大128TiBまで拡張できます。

.このタスクについて
このプールまたはボリュームグループ内の他のボリュームで今後必要になる容量を考慮してください。Snapshotイメージ、Snapshotボリューム、またはリモートミラーを十分に作成できる空き容量があることを確認してください。

[NOTE]
====
ボリュームの容量の拡張は、特定のオペレーティングシステムでのみサポートされています。サポートされていないホストオペレーティングシステム上でボリューム容量を拡張すると、拡張した容量は使用できなくなり、元のボリューム容量をリストアすることもできなくなります。

====
.手順
. 左側のパネルから、menu:Storage[Volumes]を選択します。
. 容量を増やしたいボリュームを選択し、menu:ellipsis icon[Increase Capacity]をクリックします。
+
容量の増加の確認ページが表示されます。

. 続行するには、 * はい * を選択します。
+
「報告された容量の増加」ページが表示されます。

+
このページには、ボリュームの現在の報告容量と、ボリュームに関連付けられているプールまたはボリューム グループで使用可能な空き容量が表示されます。

. *Increase reported capacity by adding...*ボックスを使用して、現在利用可能な報告容量に容量を追加します。容量値の表示単位を、メビバイト（MiB）、ギビバイト（GiB）、またはテビバイト（TiB）のいずれかに変更できます。
. [* 拡大（ * ） ] をクリックします


.結果
* System Managerは、選択に基づいてボリュームの容量を拡張します。
* メニューの「ストレージ」→「進行中の操作」を選択すると、選択したボリュームに対して現在実行中の容量増加操作の進行状況が表示されます。この処理には時間がかかり、システムのパフォーマンスに影響を与える可能性があります。


.完了後
ボリュームの容量を拡張したら、それに応じてファイルシステムのサイズを手動で拡張する必要があります。方法は、使用しているファイルシステムによって異なります。詳細については、ホストオペレーティングシステムのドキュメントを参照してください。
