---
permalink: sm-storage/increase-reserved-capacity.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, increase, reserved, capacity 
summary: ストレージオブジェクトに対するコピーサービス処理に使用される物理的に割り当てられている容量であるリザーブ容量を増やすことができます。 
---
= リザーブ容量を増やします
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージオブジェクトに対するコピーサービス処理に使用される物理的に割り当てられている容量であるリザーブ容量を増やすことができます。

Snapshot処理の場合は、通常はベースボリュームの40%、非同期ミラーリング処理の場合は、通常はベースボリュームの20%です。一般には、ストレージオブジェクトのリザーブ容量がフルに近付いているという警告が表示されたときに、リザーブ容量を拡張します。

.作業を開始する前に
* プールまたはボリュームグループ内のボリュームのステータスが最適で、変更処理の実行中でないことを確認してください。
* プールまたはボリュームグループに容量の拡張に使用する空き容量が必要です。
+
プールまたはボリュームグループに空き容量がない場合は、未割り当て容量を未使用ドライブの形式でプールまたはボリュームグループに追加できます。



.このタスクについて
次のストレージオブジェクトの場合、リザーブ容量は8GiB単位でのみ拡張できます。

* Snapshotグループ
* Snapshotボリューム
* 整合性グループメンバーボリューム
* ミラーペアボリューム


プライマリボリュームで多数の変更が見込まれる場合や、特定のコピーサービス処理のライフサイクルが非常に長くなる場合は、リザーブ容量の割合を高くします。

[NOTE]
====
読み取り専用のSnapshotボリュームのリザーブ容量は増やすことはできません。リザーブ容量が必要なのは、読み取り/書き込みのSnapshotボリュームだけです。

====
.手順
. 選択メニュー：Storage（Pool & Volume Groups）
. 予約容量*タブを選択します。
. リザーブ容量を増やすストレージオブジェクトを選択し、*容量の拡張*をクリックします。
+
リザーブ容量の拡張ダイアログボックスが表示されます。

. スピンボックスを使用して容量の割合を調整します。
+
選択したストレージオブジェクトが含まれているプールまたはボリュームグループに空き容量が存在せず、ストレージアレイに未割り当ての容量がある場合は、新しいプールまたはボリュームグループを作成できます。その後、そのプールまたはボリュームグループ上の新しい空き容量を使用してこの処理を再試行できます。

. [* 拡大（ * ） ] をクリックします


.結果
System Managerは次の処理を実行します。

* ストレージオブジェクトのリザーブ容量を拡張します。
* 新たに追加したリザーブ容量を表示します。

