---
permalink: sm-storage/initialize-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, initialize, volumes 
summary: ボリュームは、最初に作成されるときに自動的に初期化されます。ただし、一定の障害状況からリカバリするために、ボリュームを手動で初期化するようRecovery Guruから指示される場合があります。このオプションを使用する場合は、必ずテクニカルサポートの指示に従ってください。初期化するボリュームは1つ以上選択できます。 
---
= ボリュームを初期化
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリュームは、最初に作成されるときに自動的に初期化されます。ただし、一定の障害状況からリカバリするために、ボリュームを手動で初期化するようRecovery Guruから指示される場合があります。このオプションを使用する場合は、必ずテクニカルサポートの指示に従ってください。初期化するボリュームは1つ以上選択できます。

.作業を開始する前に
* すべてのI/O処理を停止しておきます。
* 初期化するボリューム上のデバイスまたはファイルシステムをすべてアンマウントしておく必要があります。
* ボリュームは最適ステータスであり、ボリューム上で変更処理が実行されていません。


[CAUTION]
====
この処理は開始後にキャンセルすることはできません。ボリュームのすべてのデータが消去されます。Recovery Guruの指示があった場合を除き、この処理は実行しないでください。この手順 を開始する前に、テクニカルサポートにお問い合わせください。

====
.このタスクについて
ボリュームを初期化しても、ボリュームのWWN、ホストの割り当て、割り当て済み容量、およびリザーブ容量の設定は保持されます。Data Assurance（DA）設定とセキュリティ設定も同じままです。

次のタイプのボリュームは初期化できません：

* Snapshotボリュームのベースボリューム
* ミラー関係のプライマリボリューム
* ミラー関係のセカンダリボリューム
* ボリュームコピーのソースボリューム
* ボリュームコピーのターゲットボリューム
* すでに初期化が進行中のボリューム


このトピックは、プールまたはボリュームグループから作成された標準のボリュームのみに該当します。

.手順
. 選択メニュー： Storage [Volumes]
. 任意のボリュームを選択し、メニューを選択します。More [Initialize volumes]。
+
Initialize Volumes（ボリュームの初期化）ダイアログボックスが表示されます。このダイアログボックスには、ストレージアレイ上のすべてのボリュームが表示されます。

. 初期化するボリュームを1つ以上選択し、処理を確定します。


.結果
System Managerは次の処理を実行します。

* 初期化されたボリュームからすべてのデータが消去されます。
* ブロックインデックスがクリアされます。これにより、書き込み前のブロックはゼロで埋められているかのように読み取られます（ボリュームは完全に空のように表示されます）。


メニューを選択します。Home [View Operations in Progress]は、選択したボリュームに対して現在実行中の初期化処理の進捗状況を表示します。この処理には時間がかかることがあり、システムのパフォーマンスに影響する可能性があります。
