---
permalink: sm-storage/interpret-performance-data.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, interpret, performance data 
summary: パフォーマンスデータは、ストレージアレイのパフォーマンス調整に役立ちます。 
---
= パフォーマンスデータを解釈する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
パフォーマンスデータは、ストレージアレイのパフォーマンス調整に役立ちます。

パフォーマンスデータを解釈するときは、いくつかの要因がストレージアレイのパフォーマンスに影響することに注意してください。次の表に、考慮すべき主な要素を示します。

[cols="25h,~"]
|===
| パフォーマンスデータ | パフォーマンス調整の関連事項 


 a| 
レイテンシ（ミリ秒、ms）
 a| 
特定のオブジェクトのI/Oアクティビティを監視します。

ボトルネックになっているオブジェクトを特定できる可能性があります。

* ボリュームグループが複数のボリューム間で共有されている場合は、個々のボリュームに独自のボリュームグループを割り当てると、ドライブのシーケンシャルパフォーマンスが向上し、レイテンシが低減される可能性があります。
* プールではレイテンシが大きくなり、ドライブ間でワークロードが不均一な場合があるため、レイテンシの値はあまり意味がなく、一般的に高くなります。
* ドライブタイプと速度はレイテンシに影響します。ランダムI/Oの場合、ドライブの回転速度が速いほど、ディスク上の別の場所との間の移動にかかる時間は短くなります。
* ドライブ数が少なすぎると、キューに格納されるコマンドが多くなり、ドライブのコマンド処理時間が長くなるため、システムの一般的なレイテンシが増加します。
* I/Oが大きいと、データの転送にかかる時間が長くなるため、レイテンシが大きくなります。
* レイテンシが高い場合、I/Oパターンが本質的にランダムである可能性があります。ランダムI/Oのドライブは、シーケンシャルストリームのドライブよりもレイテンシが高くなります。
* 共通のボリュームグループのドライブ間またはボリューム間でレイテンシが不均衡な場合は、ドライブが低速である可能性があります。




 a| 
IOPS
 a| 
1秒あたりの入出力処理（IOPSまたはIO/秒）に影響する要因には、次のものがあります。

* アクセスパターン（ランダムまたはシーケンシャル）
* I/Oサイズ
* RAIDレベル
* キャッシュブロックサイズ
* 読み取りキャッシュが有効になっているかどうか
* 書き込みキャッシュが有効になっているかどうか
* 動的キャッシュ読み取りプリフェッチ
* セグメントサイズ
* ボリュームグループまたはストレージアレイ内のドライブの数


キャッシュヒット率が高いほど、I/O速度は高くなります。書き込みキャッシュが有効な場合の方が、無効な場合に比べて書き込みI/O速度が高くなります。個々のボリュームの書き込みキャッシュを有効にするかどうかを判断するときは、現在のIOPSと最大IOPSを確認します。シーケンシャルI/Oパターンの方が、ランダムI/Oパターンよりも高速です。I/Oパターンに関係なく、書き込みキャッシュを有効にしてI/O速度を最大化し、アプリケーションの応答時間を短縮してください。

ボリュームのIOPS統計からは、セグメントサイズの変更によるパフォーマンスの向上を確認できます。実際に試して最適なセグメントサイズを決定するか、ファイルシステムサイズまたはデータベースブロックサイズを使用します。



 a| 
MiB/秒
 a| 
転送またはスループットの速度は、アプリケーションのI/OサイズとI/O速度によって決まります。一般に、アプリケーションのI/O要求のサイズが小さいと転送速度は遅くなりますが、I/O速度は上がり、応答時間は短縮されます。アプリケーションのI/O要求のサイズが大きい場合は、スループットが高速になる可能性があります。

一般的なアプリケーションのI/Oパターンを理解しておくと、特定のストレージアレイの最大I/O転送速度を決定するのに役立ちます。



 a| 
CPU
 a| 
使用中の処理能力の割合を示します。

同じタイプのオブジェクトのCPU使用率に差異がある場合があります。たとえば、一方のコントローラのCPU使用率は高く、時間とともに増加していて、もう一方のコントローラは使用率が低く安定しています。この場合、1つ以上のボリュームのコントローラ所有権を、CPU使用率の低いコントローラに変更できます。

ストレージアレイ間でCPUを監視する必要がある場合があります。CPU使用率が時間とともに増加し続け、アプリケーションのパフォーマンスが低下する場合は、ストレージアレイの追加が必要になることがあります。ストレージアレイを追加することで、許容されるパフォーマンスレベルで引き続きアプリケーションのニーズを満たすことができます。



 a| 
ヘッドルーム
 a| 
ヘッドルームとは、コントローラ、コントローラホストチャネル、およびコントローラのドライブチャネルの残りのパフォーマンス容量を指します。この値は割合で表され、これらのオブジェクトで実現可能な最大パフォーマンスと現在のパフォーマンスレベルとのギャップを表しています。

* コントローラの場合、ヘッドルームは最大限可能なIOPSの割合です。
* チャネルの場合、ヘッドルームは最大スループット（MiB/秒）の割合です計算には、読み取りスループット、書き込みスループット、双方向スループットが含まれています。


|===