---
permalink: sm-storage/performance-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, performance, terms 
summary: ストレージアレイに関連するパフォーマンスの用語を次に示します。 
---
= パフォーマンスの用語
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイに関連するパフォーマンスの用語を次に示します。

[cols="25h,~"]
|===
| 期間 | 説明 


 a| 
アプリケーション
 a| 
アプリケーションとは、SQLやExchangeなどのソフトウェアプログラムです。



 a| 
CPU
 a| 
CPUは「中央処理装置」用ではありません。 cpuは、ストレージアレイの使用中の処理容量の割合を示します。



 a| 
ホスト
 a| 
ホストは、ストレージアレイ上のボリュームにI/Oを送信するサーバです。



 a| 
IOPS
 a| 
IOPSは、1秒あたりのI/O処理数です。



 a| 
レイテンシ
 a| 
レイテンシは、読み取りや書き込みコマンドなどの要求を送信してから、ホストまたはストレージアレイから応答が返されるまでの時間です。



 a| 
LUN
 a| 
Logical Unit Number（LUN；論理ユニット番号）は、ホストがボリュームへのアクセスに使用する番号で、アドレススペースに割り当てられます。ボリュームは、LUNの形式でホストに容量として提示されます。

各ホストには独自のLUNアドレススペースがあります。したがって、同じLUNを複数のホストで使用して、異なるボリュームにアクセスできます。



 a| 
MIB
 a| 
MiBは、メビバイト（メガバイナリバイト）の略です。1MiBは220、つまり1、048、576バイトです。10を基数とするMBとは異なる単位です。1MBは1、024バイトです。



 a| 
オブジェクト
 a| 
オブジェクトとは、任意の論理または物理ストレージコンポーネントのことです。

論理オブジェクトには、ボリュームグループ、プール、ボリュームがあります。物理オブジェクトには、ストレージアレイ、アレイコントローラ、ホスト、ドライブがあります。



 a| 
プール
 a| 
プールは、論理的にグループ化された一連のドライブです。プールを使用して、ホストにアクセス可能な 1 つ以上のボリュームを作成することができます。（ボリュームはプールまたはボリュームグループから作成します）。



 a| 
読み取り
 a| 
読み取りは「読み取り処理」では省略されます。読み取り処理は、ホストがストレージアレイにデータを要求したときに行われます。



 a| 
ボリューム
 a| 
ボリュームは、アプリケーション、データベース、およびファイルシステムがデータを格納するコンテナです。ホストがストレージアレイのストレージにアクセスするために作成される論理コンポーネントです。

ボリュームは、プールまたはボリュームグループの使用可能な容量から作成します。ボリュームごとに容量が定義されています。ボリュームが複数のドライブで構成される場合でも、ホスト側では1つの論理コンポーネントとして認識され、



 a| 
ボリューム名
 a| 
ボリューム名は、ボリュームの作成時に割り当てられる文字列です。デフォルトの名前をそのまま使用することも、ボリュームに格納されたデータのタイプを表した名前を指定することもできます。



 a| 
ボリュームグループ
 a| 
ボリュームグループは、同じ特性を持つボリュームのコンテナです。ボリュームグループごとに容量とRAIDレベルが定義されています。ボリュームグループを使用して、ホストにアクセス可能な1つ以上のボリュームを作成することができます。（ボリュームはボリュームグループまたはプールから作成します）。



 a| 
ワークロード
 a| 
ワークロードは、アプリケーションをサポートするストレージオブジェクトです。アプリケーションごとに1つ以上のワークロードまたはインスタンスを定義できます。一部のアプリケーションでは、特性が似たボリュームで構成されるようにワークロードが設定されます。これらのボリューム特性は、ワークロードがサポートするアプリケーションのタイプに基づいて最適化されます。たとえば、Microsoft SQL Serverアプリケーションをサポートするワークロードを作成し、そのワークロード用のボリュームを作成すると、Microsoft SQL Serverをサポートするようにボリューム特性が最適化されます。



 a| 
書き込み
 a| 
書き込みは、ホストからストレージ用のアレイにデータが送信されるときの「書き込み処理」には適していません。

|===