---
permalink: sm-storage/redistribute-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, redistribute, volumes 
summary: ボリュームの再配置は、ボリュームを優先コントローラ所有者に戻すために実行します。通常、ホストとストレージアレイの間のデータパスに問題が発生した場合、マルチパスドライバがボリュームを優先コントローラ所有者から移動します。 
---
= ボリュームを再配置する
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリュームの再配置は、ボリュームを優先コントローラ所有者に戻すために実行します。通常、ホストとストレージアレイの間のデータパスに問題が発生した場合、マルチパスドライバがボリュームを優先コントローラ所有者から移動します。

.作業を開始する前に
* 再配置するボリュームが使用中でない必要があります。使用中の場合はI/Oエラーが発生します。
* 再配置するボリュームを使用しているすべてのホストにマルチパスドライバがインストールされている必要があります。インストールされていない場合はI/Oエラーが発生します。
+
ホストにマルチパスドライバがインストールされていないボリュームを再配置する場合は、再配置処理の実行中に_VOLUMESへのI/Oアクティビティをすべて停止して、アプリケーションエラーを回避する必要があります。



.このタスクについて
ほとんどのホストマルチパスドライバは、優先コントローラ所有者へのパスで各ボリュームへのアクセスを試みます。ただし、この優先パスが使用できなくなると、ホストのマルチパスドライバは代替パスにフェイルオーバーします。このフェイルオーバー原因 によって、ボリューム所有権が代替コントローラに変更される可能性があります。フェイルオーバーの原因となった状況を解決すると、一部のホストではボリュームの所有権が優先コントローラ所有者に自動的に戻りますが、場合によっては手動でのボリュームの再配置が必要になります。

.手順
. 選択メニュー： Storage [Volumes]
. メニューを選択します。 More [redistribute volumes （ボリュームの再配置） ]
+
ボリュームの再配置ダイアログボックスが表示されますストレージアレイ上のボリュームのうち、優先コントローラ所有者が現在の所有者と一致しないボリュームがすべてこのダイアログボックスに表示されます。

. 再配置するボリュームを1つ以上選択し、処理を確定します。


.結果
System Managerによって、選択したボリュームが優先コントローラ所有者に移動されるか、ボリュームの再配置の不要なダイアログボックスが表示されることがあります。
