---
permalink: sm-storage/replace-drive-logically-storage.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, replace, drive, logically 
summary: ドライブに障害が発生した場合や、何らかの理由でドライブを交換する場合、ストレージアレイに未割り当てのドライブがあれば、障害が発生したドライブを未割り当てのドライブに論理的に交換することができます。未割り当てのドライブがない場合は、ドライブを物理的に交換します。 
---
= ドライブを論理的に交換します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ドライブに障害が発生した場合や、何らかの理由でドライブを交換する場合、ストレージアレイに未割り当てのドライブがあれば、障害が発生したドライブを未割り当てのドライブに論理的に交換することができます。未割り当てのドライブがない場合は、ドライブを物理的に交換します。

.このタスクについて
ドライブを未割り当てのドライブに論理的に交換すると、未割り当てのドライブが割り当てられ、関連付けられているプールまたはボリュームグループの永続的なメンバーとなります。次のタイプのドライブを交換するには、論理的交換オプションを使用します。

* 障害ドライブ
* 不明なドライブです
* 寿命に近付いていることがRecovery Guruによって通知されたSSDドライブ
* ドライブ障害の兆候があることがRecovery Guruによって通知されたハードドライブ
* 割り当てられたドライブ（プール内ではなく、ボリュームグループ内のドライブでのみ使用可能）


交換用ドライブには次の特性が必要です。

* 最適状態です
* 未割り当て状態
* 交換するドライブと属性（メディアタイプ、インターフェイスタイプなど）が同じ
* FDE機能が同じ（推奨、必須ではない）
* DA機能が同じ（推奨、必須ではない）


.手順
. 「 * ハードウェア * 」を選択します。
. 図にコントローラが表示されている場合は、*シェルフの前面を表示*をクリックします。
+
図の表示が切り替わり、コントローラではなくドライブが表示されます。

. 論理的に交換するドライブをクリックします。
+
ドライブのコンテキストメニューが表示されます。

. 論理的に置換*をクリックします。
. *オプション：*交換後にドライブを使用停止する*チェックボックスをオンにして、元のドライブを交換後に使用停止にします。
+
このチェックボックスは、元の割り当てドライブが障害状態でも不明状態でもない場合にのみ有効になります。

. [交換用ドライブの選択*]テーブルで、使用する交換用ドライブを選択します。
+
この表には、交換対象のドライブと互換性があるドライブのみが表示されます。可能であれば、シェルフ損失の保護およびドロワー損失の保護が維持されるドライブを選択してください。

. [*置換*]をクリックします。
+
元のドライブが障害状態または不明な場合、データはパリティ情報を使用して交換用ドライブで再構築されます。この再構築は自動的に開始されます。ドライブの障害インジケータライトが消灯し、プールまたはボリュームグループ内のドライブのアクティビティインジケータライトが点滅を開始します。

+
元のドライブが障害状態でも不明状態でもない場合は、元のドライブのデータが交換用ドライブにコピーされます。このコピー処理は自動的に開始されます。コピー処理が完了すると、元のドライブは未割り当て状態、またはチェックボックスを選択した場合は失敗状態に移行します。


