---
permalink: sm-storage/requirements-and-guidelines-for-snapshots.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, requirements, guidelines, snapshots 
summary: Snapshotを作成して使用する場合は、次の要件およびガイドラインを確認してください。 
---
= Snapshotの要件とガイドライン
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Snapshotを作成して使用する場合は、次の要件およびガイドラインを確認してください。



== SnapshotイメージとSnapshotグループ

* 各Snapshotイメージは1つのSnapshotグループにのみ関連付けられます。
* Snapshotグループは、関連オブジェクトに対してスケジュールされたSnapshotイメージまたはインスタントSnapshotイメージを初めて作成したときに作成されます。これにより、リザーブ容量が作成されます。
+
Snapshotグループは、Pools & Volume Groupsページで表示できます。

* スケジュールされたSnapshotイメージは、ストレージアレイがオフラインの場合や電源がオフの場合は作成されません。
* Snapshotスケジュールが設定されたSnapshotグループを削除すると、Snapshotスケジュールも削除されます。
* 不要になったSnapshotボリュームは、削除する代わりに、関連付けられているリザーブ容量とともに再利用できます。これにより、同じベースボリュームの別のSnapshotボリュームが作成されます。Snapshotイメージが同じベースボリューム内にあるかぎり、SnapshotボリュームまたはSnapshot整合性グループのSnapshotボリュームは、同じSnapshotイメージまたは別のSnapshotイメージに再関連付けできます。




== Snapshot整合性グループ

* Snapshot整合性グループには、Snapshot整合性グループのメンバーであるボリュームごとにSnapshotグループが1つ含まれています。
* Snapshot整合性グループは1つのスケジュールにのみ関連付けることができます。
* Snapshotスケジュールが設定されたSnapshot整合性グループを削除すると、Snapshotスケジュールも削除されます。
* Snapshot整合性グループに関連付けられているSnapshotグループを個別に管理することはできません。管理処理（Snapshotイメージの作成、SnapshotイメージまたはSnapshotグループの削除、Snapshotイメージのロールバック）は、Snapshot整合性グループレベルで実行する必要があります。




== ベースボリューム

* SnapshotボリュームのData Assurance（DA）とセキュリティの設定は、関連付けられているベースボリュームと同じである必要があります。
* 障害のあるベースボリュームからSnapshotボリュームを作成することはできません。
* ベースボリュームがボリュームグループに含まれている場合は、関連付けられているSnapshot整合性グループのメンバーボリュームをプールまたはボリュームグループに配置できます。
* ベースボリュームがプールに含まれている場合は、関連付けられているSnapshot整合性グループのすべてのメンバーボリュームを、ベースボリュームと同じプールに配置する必要があります。




== リザーブ容量

* リザーブ容量は1つのベースボリュームのみに関連付けられます。
* スケジュールを使用すると、Snapshotイメージが大量に作成される可能性があります。スケジュールされたSnapshot用の十分なリザーブ容量があることを確認してください。
* Snapshot整合性グループのリザーブ容量ボリュームのData Assurance（DA）とセキュリティの設定は、Snapshot整合性グループのメンバーボリューム用の関連付けられているベースボリュームと同じである必要があります。




== 保留中のSnapshotイメージ

次の状況では、Snapshotイメージの作成が保留状態になることがあります。

* このSnapshotイメージを含むベースボリュームが非同期ミラーグループのメンバーである場合。
* ベースボリュームで同期処理を実行中の場合。同期処理が完了した時点でSnapshotイメージの作成が完了します。




== Snapshotイメージの最大数

* あるボリュームがSnapshot整合性グループのメンバーである場合、System Managerはそのメンバーボリューム用のSnapshotグループを作成します。このSnapshotグループは、ベースボリュームあたりのSnapshotグループの許容最大数にカウントされます。
* SnapshotグループまたはSnapshot整合性グループにSnapshotイメージを作成しようとしていて、関連付けられているグループがSnapshotイメージの最大数に達している場合は、次の2つのオプションがあります。
+
** SnapshotグループまたはSnapshot整合性グループの自動削除を有効にします。
** SnapshotグループまたはSnapshot整合性グループから1つ以上のSnapshotイメージを手動で削除し、処理を再試行します。






== 自動削除

SnapshotグループまたはSnapshot整合性グループで自動削除が有効になっている場合、グループに新しいSnapshotイメージが作成されると、最も古いSnapshotイメージがSystem Managerによって削除されます。



== ロールバック処理

* ロールバック処理の実行中は、次の操作は実行できません。
+
** ロールバックに使用されているSnapshotイメージを削除する。
** ロールバック処理の対象であるベースボリュームの新しいSnapshotイメージの作成
** 関連付けられているSnapshotグループのRepository-Fullポリシーの変更


* 次のいずれかの処理の進行中は、ロールバック処理を開始できません。
+
** 容量の拡張（プールまたはボリュームグループへの容量の追加）
** ボリュームの拡張（ボリュームの容量の拡張）
** ボリュームグループのRAIDレベルの変更
** ボリュームのセグメントサイズが変更された


* ベースボリュームがボリュームコピーの対象である場合は、ロールバック処理を開始できません。
* ベースボリュームがリモートミラーのセカンダリボリュームである場合は、ロールバック処理を開始できません。
* 関連付けられているSnapshotリポジトリボリューム内の使用済み容量に読み取り不能なセクターが含まれている場合、ロールバック処理は失敗します。

