---
permalink: sm-storage/rtv-manage-progress-of-remote-volume-import.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, remote, storage, imports 
summary: インポートプロセスが開始されると、進行状況を表示して対処することができます。 
---
= リモートストレージのインポートの進捗状況を管理します
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
インポートプロセスが開始されると、進行状況を表示して対処することができます。

.このタスクについて
インポート処理ごとに、処理の進捗状況ダイアログに完了率と推定残り時間が表示されます。処理には、インポートの優先順位の変更、処理の停止と再開、および処理との切断が含まれます。

進行中の処理は、ホームページ（メニュー：ホーム[進行中の処理を表示]）から表示することもできます。

.手順
. [リモートストレージ]ページで、[*オペレーションの表示*]を選択します。
+
[処理を実行中（Operations in Progress）]ダイアログボックスが表示されます。

. 必要に応じて、[アクション*（* Actions *）]列のリンクを使用して、オペレーションの停止と再開、優先度の変更、またはオペレーションからの切断を行います。
+
** *優先度の変更*--進行中または保留中のオペレーションの処理優先度を変更するには'*Change Priority*を選択しますオペレーションに優先度を適用し、 * OK * をクリックする。
** *停止*--リモートストレージデバイスからのデータのコピーを一時停止するには'*Stop*を選択しますインポートペア間の関係はそのままです。インポート操作を続行する準備ができたら、 * 再開 * を選択できます。
** *再開*--停止したプロセスまたは停止したプロセスを'停止したプロセスまたは停止したプロセスを開始するには'*Resume*を選択します次に、レジューム操作に優先度を適用し、 * OK * をクリックします。この操作は'インポートを最初から再開しない（_not_restart）最初からプロセスを再開する場合は、「 * 切断」を選択し、リモートストレージのインポートウィザードを使用してインポートを再作成する必要があります。
** *切断*-停止、完了、または失敗したインポート処理のソースボリュームとデスティネーションボリュームの関係を解除するには、「*切断」を選択します。



