---
permalink: sm-storage/rtv-remote-storage-requirements.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, remote, storage, requirements 
summary: リモートストレージ機能を使用する前に、次の要件および制限事項を確認してください。 
---
= リモートストレージ機能の要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
リモートストレージ機能を使用する前に、次の要件および制限事項を確認してください。



== サポートされているプロトコル

サポートされるプロトコルは次のとおりです。

* iSCSI
* IPv4


Eシリーズのサポート情報と設定情報の最新情報については、を参照してください https://imt.netapp.com/matrix/#welcome["NetApp Interoperability Matrix Tool で確認できます"^]。



== ハードウェア要件

E シリーズストレージシステムには次のものが必要です。

* 2 台（デュプレックスモード）
* 1 つ以上の iSCSI 接続を介して両方の E シリーズコントローラがリモートストレージシステムと通信するための iSCSI 接続
* SANtricity OS 11.71 以降
* サブモデル ID （ SMID ）で有効化されたリモートストレージ機能


リモートシステムには、 E シリーズストレージシステムと別のベンダーのシステムを使用できます。次のものを含める必要があります

* iSCSI対応インターフェイス




== 制限事項

リモートストレージ機能には、次の制限事項があります。

* ミラーリングを無効にする必要があります。
* E シリーズシステムのデスティネーションボリュームに Snapshot が存在しないようにします。
* インポートを開始する前に、 E シリーズシステムのデスティネーションボリュームをホストにマッピングしないでください。
* E シリーズシステムのデスティネーションボリュームでリソースプロビジョニングが無効になっている必要があります。
* リモートストレージボリュームをホストまたは複数のホストに直接マッピングすることはできません。
* Web Services Proxy はサポートされていません。
* iSCSI CHAP シークレットはサポートされません。
* SMcli はサポートされません。
* VMware データストアはサポートされません。
* インポートペアが存在する場合、関係 / インポートペアにあるストレージシステムは一度に 1 つだけアップグレードできます。

