---
permalink: sm-storage/rtv-remote-storage-volume-requirements.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, remote, storage, volume, requirements 
summary: インポートに使用するボリュームは、サイズ、ステータス、およびその他の条件の要件を満たしている必要があります。 
---
= Remote Storageのボリューム要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
インポートに使用するボリュームは、サイズ、ステータス、およびその他の条件の要件を満たしている必要があります。



== リモートストレージボリューム

インポートのソースボリュームを「リモートストレージボリューム」と呼びます。 このボリュームは次の条件を満たしている必要があります。

* 別のインポートに含めることはできません
* オンラインステータスである必要があります


インポートが開始されると、コントローラファームウェアによってリモートストレージボリュームがバックグラウンドで作成されます。そのため、リモートストレージボリュームは System Manager では管理できず、インポート処理にのみ使用できます。

作成されたリモートストレージボリュームは、 E シリーズシステム上の他の標準ボリュームと同様に扱われますが、次の例外があります。

* リモートストレージデバイスのプロキシとして使用できます。
* 他のボリュームコピーや Snapshot の候補として使用することはできません。
* インポートの実行中は Data Assurance 設定を変更できません。
* ホストはインポート処理専用に予約されているため、どのホストにもマッピングできません。


各リモートストレージボリュームは 1 つのリモートストレージオブジェクトにのみ関連付けられます。ただし、 1 つのリモートストレージオブジェクトを複数のリモートストレージボリュームに関連付けることができます。リモートストレージボリュームは、次の組み合わせによって一意に識別されます。

* リモートストレージのオブジェクト ID
* リモートストレージデバイスの LUN 番号




== ターゲットボリュームの候補

ターゲットボリュームが、ローカルの E シリーズシステムのデスティネーションボリュームです。デスティネーションボリュームは、次の条件を満たしている必要があります。

* RAID / DDP ボリュームである必要があります。
* リモートストレージボリュームと同じかそれ以上の容量が必要です。
* リモートストレージボリュームと同じブロックサイズが必要です。
* 有効な状態（最適）である必要があります。
* ボリュームコピー、 Snapshot コピー、非同期ミラーリング、同期ミラーリングの関係を確立することはできません。
* 再設定処理を実行できません：動的ボリューム拡張、動的容量拡張、動的セグメントサイズ、動的 RAID 移行、動的な容量削減、 最適化。
* インポートを開始する前にホストにマッピングすることはできません（ただし、インポートの完了後にマッピングすることはできます）。
* Flash Read Cached （ FRC ）を有効にできません。


System Manager は、リモートストレージのインポートウィザードの一環として、これらの要件を自動的にチェックします。デスティネーションボリュームを選択する際には、すべての要件を満たすボリュームだけが表示されます。
