---
permalink: sm-storage/rtv-import-remote-storage.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, import, remote, storage 
summary: リモートシステムからローカルのEシリーズストレージシステムへのストレージのインポートを開始するには、リモートストレージのインポートウィザードを使用します。 
---
= SANtricity System Managerでリモートストレージをインポートする
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
リモートシステムからローカルのEシリーズストレージシステムへのストレージのインポートを開始するには、リモートストレージのインポートウィザードを使用します。

.作業を開始する前に
* E シリーズストレージシステムがリモートストレージシステムと通信できるように設定されている必要があります。
+
[NOTE]
====
ハードウェアの構成については、EシリーズおよびSANtricity のドキュメントセンターで入手できるリモートストレージ機能のユーザガイドを参照してください https://docs.netapp.com/us-en/e-series/remote-storage-volumes/setup-remote-volumes-concept.html["ハードウェアを設定する"^]で、を参照してください https://www.netapp.com/pdf.html?item=/media/28697-tr-4893-deploy.pdf["Remote Storageテクニカルレポート"^]。

====
* リモートストレージシステムについて、次の情報を収集します。
+
** iSCSI IQN
** iSCSI IP アドレス
** リモートストレージデバイス（ソースボリューム）の LUN 番号


* ローカルの E シリーズストレージシステムの場合、データのインポートに使用するボリュームを作成または選択します。を参照してください link:create-volumes.html["ボリュームを作成します"]。ターゲットボリュームが、次の要件を満たしている必要があります。
+
** リモートストレージデバイス（ソースボリューム）のブロックサイズと一致します。
** には、リモートストレージデバイスと同じかそれ以上の容量が必要です。
** の状態が「最適」で、利用可能です。




要件の一覧については、を参照してください link:rtv-remote-storage-volume-requirements.html["リモートストレージボリュームの要件"]。

* *推奨：*インポート処理を開始する前に、リモートストレージシステムのボリュームをバックアップしてください。


.このタスクについて
このタスクでは、リモートストレージデバイスとローカルの E シリーズストレージシステム上のボリュームの間のマッピングを作成します。設定が完了すると、インポートが開始されます。

[NOTE]
====
多くの変数がインポート操作とその完了時間に影響を与える可能性があるため、最初に小さい「テスト」インポートを実行することをお勧めします。これらのテストを使用して、すべての接続が想定どおりに機能し、インポート処理が適切な時間で完了することを確認します。

====
.手順
. 「ストレージ[リモートストレージ]」メニューを選択します。
. [ リモートストレージのインポート ] をクリックします。
+
リモートストレージをインポートするためのウィザードが表示されます。

. ソースの設定パネルの*手順1a *で、接続情報を入力します。別のiSCSI接続を追加する場合は、*別のIPアドレスを追加*をクリックして、リモートストレージのIPアドレスを追加します。完了したら、 * 次へ * をクリックします。
+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 説明 


 a| 
名前
 a| 
System Managerインターフェイスで識別するリモートストレージデバイスの名前を入力します。

名前には最大30文字を使用できます。使用できる文字は、アルファベット、数字、およびアンダースコア（_）、ダッシュ（-）、ハッシュ記号（#）のみです。スペースを含めることはできません。



 a| 
iSCSI接続プロパティ
 a| 
リモートストレージデバイスの接続プロパティを入力します。

** * iSCSI Qualified Name（IQN）*：iSCSI IQNを入力します。
** *IPアドレス*: IPv4アドレスを入力します。
** *ポート*：ソース・デバイスとターゲット・デバイス間の通信に使用するポート番号を入力します。デフォルトでは、ポート番号は3260です。


|===
====
+
「*次へ*」をクリックすると、ソースの設定パネルの*ステップ1b *が表示されます。

. [*LUN*]フィールドで'ソースとして使用するリモート・ストレージ・デバイスのLUN番号を選択し'[次へ]をクリックします
+
ターゲットの設定パネルが開き、インポートのターゲットとして使用するボリューム候補が表示されます。ブロックサイズ、容量、またはボリュームの可用性が原因で、一部のボリュームが候補のリストに表示されません。

. E シリーズストレージシステムのターゲットボリュームを表から選択します。必要に応じて、スライダを使用してインポートの優先度を変更します。「 * 次へ * 」をクリックします。「 continue 」と入力し、「 * Continue * 」をクリックして、次のダイアログボックスで操作を確認します。
+
ターゲットボリュームの容量がソースボリュームよりも大きい場合、 E シリーズシステムに接続されているホストにはその容量は報告されません。新しい容量を使用するには、インポート処理が完了して切断されたあとに、ホストでファイルシステムの拡張処理を実行する必要があります。

+
ダイアログで設定を確定すると、 [ レビュー（ Review ） ] パネルが表示されます。

. [レビュー]パネルで、設定が正しいことを確認し、[完了]をクリックしてインポートを開始します。
+
別のインポートを開始するかどうかを確認するダイアログボックスが表示されます。

. 必要に応じて、 * はい * をクリックして別のリモートストレージインポートを作成します。[ソースの設定]パネルの[はい]をクリックすると、[手順1a*]に戻ります。ここで、既存の構成を選択するか、新しい構成を追加できます。別のインポートを作成しない場合は、[*いいえ*（* No *）]をクリックしてダイアログボックスを終了します。
+
インポートプロセスが開始されると、ターゲットボリューム全体がコピーされたデータで上書きされます。ホストがこのプロセス中にターゲットボリュームに新しいデータを書き込むと、その新しいデータはリモートデバイス（ソースボリューム）に伝播されます。

. リモートストレージパネルの View Operations （操作の表示）ダイアログで、操作の進行状況を表示します。


.結果
インポート処理が完了するまでの時間は、リモートストレージシステムのサイズ、インポートの優先度設定、ストレージシステムと関連するボリュームの両方の I/O 負荷の量によって異なります。

インポートが完了すると、ローカルボリュームがリモートストレージデバイスの複製になります。

.完了後
2つのボリューム間の関係を解除する準備ができたら、インポートオブジェクトの「処理を実行中」ビューで「*切断」を選択します。関係が切断されると、ローカルボリュームのパフォーマンスは通常の状態に戻り、リモート接続による影響はなくなります。
