---
permalink: sm-storage/rtv-modify-connection-settings-for-remote-storage.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, modify, connection, settings, remote, storage 
summary: 設定の表示 / 編集オプションを使用して、任意のリモートストレージ構成の接続設定を編集、追加、または削除できます。 
---
= リモートストレージの接続設定を変更します
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
設定の表示 / 編集オプションを使用して、任意のリモートストレージ構成の接続設定を編集、追加、または削除できます。

.このタスクについて
接続プロパティを変更すると、実行中のインポートに影響します。中断を避けるため、インポートが実行されていないときにのみ接続プロパティを変更してください。

.手順
. 「ストレージ[リモートストレージ]」メニューを選択します。
. リストから、変更するリモートストレージオブジェクトを選択します。
. [* 設定の表示 / 編集 * ] をクリックします。
+
リモートストレージ設定ダイアログボックスが表示されます。

. [ 接続のプロパティ *] タブをクリックします。
+
リモートストレージのインポート用に設定されている IP アドレスとポートの設定が表示されます。

. 次のいずれかを実行します。
+
** *編集*--リモートストレージオブジェクトの対応する行アイテムの横にある*編集*をクリックします変更した IP アドレスまたはポート情報をフィールドに入力します。
** *追加--*Add*をクリックして、表示されたフィールドに新しいIPアドレスとポート情報を入力します。[ * 追加 ] をクリックして確定すると、リモートストレージオブジェクトのリストに新しい接続が表示されます。
** *削除*--リストから目的の接続を選択し、*Delete*をクリックします。表示されたフィールドに「削除」と入力して操作を確認し、「削除」をクリックします。リモートストレージオブジェクトのリストから接続が削除されます。


. [ 保存（ Save ） ] をクリックします。
+
変更した接続設定がリモートストレージオブジェクトに適用されます。


