---
permalink: sm-storage/rtv-how-remote-storage-works.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, remote, storage 
summary: リモートストレージ機能を使用すると、リモートストレージシステムからローカルのEシリーズストレージシステムにデータをインポートできます。この機能は、機器のアップグレード時など、最小限のダウンタイムでデータ移行を合理化したい場合に役立ちます。 
---
= リモートストレージの仕組み
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
リモートストレージ機能を使用すると、リモートストレージシステムからローカルのEシリーズストレージシステムにデータをインポートできます。この機能は、機器のアップグレード時など、最小限のダウンタイムでデータ移行を合理化したい場合に役立ちます。

リモートストレージ機能を設定するには、ハードウェアをセットアップし、System Managerを使用してリモートストレージオブジェクトを作成する必要があります。この設定が完了すると、インポートプロセスが開始されます。



== ハードウェアのセットアップ

次のワークフローに従って、ハードウェア接続を準備します。

これらの手順の詳細については、EシリーズおよびSANtricity ドキュメントセンターのユーザガイドで説明しています https://docs.netapp.com/us-en/e-series/remote-storage-volumes/index.html["Remote Storage Volumes の概要"^]で、を参照してください https://www.netapp.com/pdf.html?item=/media/28697-tr-4893-deploy.pdf["Remote Storageテクニカルレポート"^]。

ローカルのEシリーズストレージシステム：

. 各コントローラがリモートストレージシステムにiSCSI接続されていることを確認します。この接続により、ローカルのEシリーズシステムは、リモートシステム上でホストとして設定できるiSCSIイニシエータとして機能します。
. インポート処理のデスティネーションボリュームを作成します。ボリュームの容量がリモートストレージシステムのソースボリュームと同じかそれよりも大きく、同じブロックサイズでマッピングされていないことを確認してください。を参照してください link:create-volumes.html["ボリュームを作成します"]。
. System Managerインターフェイスから、ローカルのEシリーズシステムのiSCSI Qualified Name（IQN）を収集します。IQNはあとで、リモートストレージシステムでローカルEシリーズシステムをホストとして設定する際に使用します。System Managerで、次のメニューに移動します。Settings（システム）> iSCSI settings（iSCSI設定）> Target IQN（ターゲットIQN）の順に選択します。


リモートストレージシステム：

. IQNを使用して、ローカルEシリーズシステムをリモートシステム上のホストとして設定します。適切なホストタイプを次のように設定します。
+
** リモートシステムがEシリーズモデルの場合は、を参照してください link:overview-hosts.html["ホストとホストクラスタの概要"]。ホストタイプとして「Factory Default」を使用します。
** リモートシステムが別のベンダーのものである場合は、使用可能なオプションに基づいて適切なホストタイプを選択します。


. すべてのI/Oを停止し、ファイルシステムをアンマウントして、ソースボリュームのホストまたはアプリケーションへの割り当てをすべて削除します。
. 新しく作成したEシリーズストレージシステムホストにボリュームを割り当てます。
. 選択したソースボリュームについて、インポートを作成できるように、リモートストレージシステムから次の情報を収集します。
+
** iSCSI修飾名（IQN）
** iSCSI IPアドレス
** ソースボリュームのLUN番号






== System Managerのセットアップ

次のワークフローを使用して、インポート用のリモートストレージオブジェクトを作成します。

. System Managerのインターフェイスでリモートストレージウィザードを使用して、リモートストレージデバイス（データインポートのソース）をEシリーズシステムのターゲットボリュームにマッピングします。「完了」を選択すると、インポート処理が開始されます。
. View Operations（操作の表示）ダイアログまたはOperations in Progress（進行中の操作）パネルからインポートを監視します。必要に応じて、プロセスを一時停止および再開することもできます。
. 必要に応じて、インポートの完了時にソースボリュームとターゲットボリュームの間の接続を解除するか、将来のインポート用に接続を維持します。

