---
permalink: sm-storage/schedule-snapshot-images.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, schedule, snapshot, images 
summary: Snapshotスケジュールを作成して、ベースボリュームに関する問題が発生した場合のリカバリを有効にし、スケジュールされたバックアップを実行します。ベースボリュームまたはSnapshot整合性グループのSnapshotは、任意の時刻に日次、週次、または月単位のスケジュールで作成できます。 
---
= Snapshotイメージのスケジュールを設定
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Snapshotスケジュールを作成して、ベースボリュームに関する問題が発生した場合のリカバリを有効にし、スケジュールされたバックアップを実行します。ベースボリュームまたはSnapshot整合性グループのSnapshotは、任意の時刻に日次、週次、または月単位のスケジュールで作成できます。

.作業を開始する前に
ベースボリュームが最適lである必要があります。

.このタスクについて
このタスクでは、既存のSnapshot整合性グループまたはベースボリュームのSnapshotスケジュールを作成する方法について説明します。

[NOTE]
====
ベースボリュームまたはSnapshot整合性グループのSnapshotイメージの作成と同時にSnapshotスケジュールを作成することもできます。

====
.手順
. 次のいずれかを実行して、Snapshotスケジュールを作成します。
+
** 選択メニュー： Storage [Volumes]
+
このSnapshotスケジュールのオブジェクト（ボリュームまたはSnapshot整合性グループ）を選択し、メニュー：コピーサービス[ Snapshotスケジュールの作成]を選択します。

** メニューを選択します。Storage [Snapshots]。
+
[*スケジュール*]タブを選択し、[*作成*]をクリックします。



. このSnapshotスケジュールのオブジェクト（ボリュームまたはSnapshot整合性グループ）を選択し、* Next *をクリックします。
+
Create Snapshot Schedule（スナップショットスケジュールの作成）ダイアログボックスが表示されます。

. 次のいずれかを実行します。
+
** *別のSnapshotオブジェクト*から以前に定義されたスケジュールを使用します。
+
詳細オプションが表示されていることを確認します。[*詳細オプションを表示*]をクリックします。[*スケジュールのインポート*]をクリックし、インポートするスケジュールのあるオブジェクトを選択して、[*インポート*]をクリックします。

** *基本オプションまたは詳細オプション*を変更します。
+
ダイアログボックスの右上にある*その他のオプションを表示*をクリックしてすべてのオプションを表示し、次の表を参照してください。



+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| フィールド | 説明 


 a| 
*基本設定*



 a| 
日を選択します
 a| 
Snapshotイメージの個々の曜日を選択します。



 a| 
開始時刻
 a| 
日次Snapshotの新しい開始時間をドロップダウンリストから選択します（30分単位で選択可能）。開始時間のデフォルトは現在時刻の30分前です。



 a| 
タイムゾーン
 a| 
ドロップダウンリストから、アレイのタイムゾーンを選択します。



 a| 
* 詳細設定 *



 a| 
曜日/月
 a| 
次のいずれかのオプションを選択します。

** *毎日/毎週*--同期スナップショットの個々の曜日を選択します日次スケジュールを設定する場合は、右上の[すべての日を選択]チェックボックスをオンにすることもできます。
** *毎月/毎年*--同期スナップショットの個々の月を選択します[* on day(s)*]フィールドに、同期を実行する月の日を入力します。有効なエントリは* 1 ~* 31 *および* Last *です。複数の日にちをカンマまたはセミコロンで区切ることができます。日にちの範囲を入力するには、ハイフンを使用します。たとえば、「1、3、4」、「10-15」、「Last」のようになります。月単位のスケジュールを設定する場合は、右上の[すべての月を選択]チェックボックスをオンにすることもできます。




 a| 
開始時刻
 a| 
日次Snapshotの新しい開始時間をドロップダウンリストから選択します（30分単位で選択可能）。開始時間のデフォルトは現在時刻の30分前です。



 a| 
タイムゾーン
 a| 
ドロップダウンリストから、アレイのタイムゾーンを選択します。



 a| 
1日あたりのSnapshot数/ Snapshotの作成間隔
 a| 
1日に作成するSnapshotイメージの数を選択します。複数選択する場合は、Snapshotイメージを作成する間隔も選択してください。複数のSnapshotイメージを作成する場合は、リザーブ容量が十分にあることを確認してください。



 a| 
Snapshotイメージを今すぐ作成？
 a| 
スケジュール設定する自動イメージに加えてインスタントイメージを作成するには、このチェックボックスをオンにします。



 a| 
開始日/終了日または終了日なし
 a| 
同期の開始日を入力します。終了日を入力するか、「*終了日なし*」を選択してください。

|===
====
. 次のいずれかを実行します。
+
** オブジェクトがSnapshot整合性グループの場合は、* Create *をクリックして設定を受け入れ、スケジュールを作成します。
** オブジェクトがボリュームの場合は、* Next *をクリックして、Snapshotイメージにリザーブ容量を割り当てます。
+
ボリューム候補の表には、指定したリザーブ容量をサポートする候補だけが表示されます。リザーブ容量は、コピーサービス処理やストレージオブジェクトに使用される物理割り当て容量です。ホストから直接読み取ることはできません。



. スピンボックスを使用して、Snapshotイメージにリザーブ容量を割り当てます。次のいずれかを実行します。
+
** *デフォルト設定を受け入れます。*
+
デフォルト設定を使用してSnapshotイメージにリザーブ容量を割り当てるには、この推奨オプションを使用します。

** *データストレージのニーズに合わせて独自の設定でリザーブ容量を割り当てることができます。*
+
デフォルトのリザーブ容量設定を変更した場合は、*候補の更新*をクリックして、指定したリザーブ容量の候補リストを更新します。

+
次のガイドラインに従ってリザーブ容量を割り当てます。

+
*** リザーブ容量のデフォルト設定はベースボリュームの容量の40%です。通常はこの容量で十分です。
*** 必要な容量は、ボリュームに対するI/O書き込みの頻度とサイズ、およびSnapshotイメージを収集する数と期間によって異なります。




. 「 * 次へ * 」をクリックします。
+
設定の編集ダイアログボックスが表示されます。

. 必要に応じてスナップショットスケジュールの設定を編集し、*完了*をクリックします。
+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 説明 


 a| 
* Snapshotイメージの上限*



 a| 
次の場合にSnapshotイメージの自動削除を有効にする...
 a| 
指定した制限に達したときにSnapshotイメージを自動的に削除する場合は、このチェックボックスをオンのままにします。制限はスピンボックスを使用して変更できます。このチェックボックスの選択を解除すると、Snapshotイメージが32個作成された時点で作成が停止します。



 a| 
*リザーブ容量の設定*



 a| 
アラートの送信しきい値
 a| 
スピンボックスを使用して、スケジュール用のリザーブ容量が残り少なくなったときにシステムからアラート通知を送信する割合を調整します。

スケジュール用のリザーブ容量が指定したしきい値を超えると、事前の通知が表示され、残りのスペースがなくなる前にリザーブ容量を増やしたり不要なオブジェクトを削除したりできます。



 a| 
リザーブ容量がフルになったときの処理です
 a| 
次のいずれかのポリシーを選択します。

** *最も古いSnapshotイメージをパージする*--システムは最も古いSnapshotイメージを自動的にパージし、そのSnapshotイメージのリザーブ容量を解放して、Snapshotグループ内で再利用します。
** *ベースボリュームへの書き込みを拒否*--リザーブ容量の割合が定義された上限に達すると'リザーブ容量へのアクセスをトリガーしたベースボリュームに対するI/O書き込み要求はすべて拒否されます


|===
====

