---
permalink: sm-storage/snapshot-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, snapshot, terms 
summary: ストレージアレイに関連するSnapshotの用語を次に示します。 
---
= Snapshotに関する用語
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイに関連するSnapshotの用語を次に示します。

[cols="25h,~"]
|===
| 期間 | 説明 


 a| 
Snapshot機能
 a| 
Snapshot機能は、ボリュームのイメージの作成と管理に使用されます。



 a| 
Snapshotイメージ
 a| 
Snapshot イメージは、ボリュームのデータを特定の時点でキャプチャした論理コピーです。リストアポイントと同様に、 Snapshot イメージを使用して既知の正常なデータセットにロールバックできます。ホストはSnapshotイメージにアクセスできますが、直接読み取ったり書き込んだりすることはできません。



 a| 
ベースボリューム
 a| 
ベースボリュームは、Snapshotイメージの作成元のボリュームです。シックボリュームの場合もシンボリュームの場合もあり、通常はホストに割り当てられています。ベースボリュームはボリュームグループまたはディスクプールのどちらかに配置できます。



 a| 
Snapshotボリューム
 a| 
Snapshotボリュームを使用すると、ホストはSnapshotイメージのデータにアクセスできます。Snapshotボリュームには独自のリザーブ容量があり、元のSnapshotイメージに影響を与えることなくベースボリュームへの変更が保存されます。



 a| 
Snapshotグループ
 a| 
Snapshotグループは、1つのベースボリュームのSnapshotイメージの集まりです。



 a| 
リザーブ容量ボリューム
 a| 
リザーブ容量ボリュームは、ベースボリュームのうちどのデータブロックが上書きされるか、およびそれらのブロックの保持される内容を追跡します。



 a| 
Snapshotスケジュール
 a| 
Snapshotスケジュールは、Snapshotイメージの自動作成に使用するタイムテーブルです。イメージを作成する頻度を制御することができます。



 a| 
Snapshot整合性グループ
 a| 
Snapshot整合性グループは、Snapshotイメージが作成されるときに1つのエンティティとして扱われるボリュームの集まりです。各ボリュームのSnapshotイメージが作成されますが、すべてのイメージが同じ時点で作成されます。



 a| 
Snapshot整合性グループメンバーボリューム
 a| 
Snapshot整合性グループに属する各ボリュームをメンバーボリュームと呼びます。ボリュームをSnapshot整合性グループに追加すると、System Managerはそのメンバーボリュームに対応する新しいSnapshotグループを自動的に作成します。



 a| 
ロールバック
 a| 
ロールバックとは、ベースボリュームのデータを過去のある時点に戻すプロセスです。



 a| 
リザーブ容量
 a| 
リザーブ容量は、コピーサービス処理やストレージオブジェクトに使用される物理割り当て容量です。ホストから直接読み取ることはできません。

|===