---
permalink: sm-storage/ssd-cache-and-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, ssd, cache, volumes 
summary: 読み取り専用のパフォーマンスを向上させるために、SSDキャッシュにボリュームを追加することができます。SSDキャッシュは、ストレージアレイ内で論理的にグループ化した一連のソリッドステートディスク（SSD）ドライブで構成されます。 
---
= SSDキャッシュとボリューム
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
読み取り専用のパフォーマンスを向上させるために、SSDキャッシュにボリュームを追加することができます。SSDキャッシュは、ストレージアレイ内で論理的にグループ化した一連のソリッドステートディスク（SSD）ドライブで構成されます。

[NOTE]
====
この機能は、EF600またはEF300ストレージシステムでは使用できません。

====


== 個のボリューム

SSDキャッシュとの間のデータの移動には、単純なボリュームI/Oのメカニズムが使用されます。データがキャッシュされてSSDに格納されると、そのデータの以降の読み取りはSSDキャッシュに対して実行されるため、HDDボリュームにアクセスする必要はありません。

SSDキャッシュはセカンダリキャッシュであり、コントローラの動的ランダムアクセスメモリ（DRAM）にあるプライマリキャッシュと組み合わせて使用されます。

* プライマリキャッシュでは、データはホスト読み取り後にDRAMに格納されます。
* SSDキャッシュでは、データはボリュームからコピーされて2つの内部RAIDボリューム（コントローラごとに1つ）に格納されます。RAIDボリュームはSSDキャッシュの作成時に自動的に作成されます。


内部RAIDボリュームは、内部的なキャッシュ処理に使用されます。ユーザがアクセスすることはできず、ユーザインターフェイスにも表示されません。ただし、ストレージアレイで許可されるボリュームの総数には、これら2つのボリュームも含まれます。

[NOTE]
====
コントローラのSSDキャッシュを使用するように割り当てられたボリュームは、自動ロードバランシングによる転送の対象外となります。

====


== ドライブセキュリティ機能

ドライブセキュリティを使用している（セキュリティ有効）ボリュームでSSDキャッシュを使用する場合は、そのボリュームとSSDキャッシュのドライブセキュリティ機能が同じである必要があります。同じでない場合、ボリュームはセキュリティ有効になりません。
