---
permalink: sm-storage/start-snapshot-image-rollback-for-consistency-group-member-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, start, snapshot, image, rollback, snapshot, consistency, group, member, volumes 
summary: ロールバック処理を実行して、Snapshotイメージに保存されている内容と一致するようにSnapshot整合性グループメンバーボリュームの内容を変更することができます。 
---
= Snapshot整合性グループのメンバーボリュームのSnapshotイメージのロールバックを開始します
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ロールバック処理を実行して、Snapshotイメージに保存されている内容と一致するようにSnapshot整合性グループメンバーボリュームの内容を変更することができます。

ロールバック処理では、Snapshot整合性グループに関連付けられているSnapshotイメージの内容は変更されません。

.作業を開始する前に
* ロールバック処理を開始するための十分なリザーブ容量が確保されています。
* 選択したSnapshotイメージとボリュームがどちらも最適な状態である必要があります。
* 選択したボリュームですでに実行中のロールバック処理がないことを確認します。


.このタスクについて
ロールバックの開始手順によって、Snapshot整合性グループのSnapshotイメージに対してロールバックが開始されます。このとき、ストレージ容量を追加することもできます。Snapshot整合性グループに対して複数のロールバック処理を同時に開始することはできません。

[NOTE]
====
ホストはロールバック後の新しいボリュームにすぐにアクセスできますが、ロールバックを実行中のメンバーボリュームに読み取り/書き込みアクセスすることはできません。リカバリ用にロールバック前のベースボリュームを保持するためには、ロールバックを開始する直前にメンバーボリュームのSnapshotイメージを作成します。

====
Snapshot整合性グループのSnapshotイメージのロールバックを開始するプロセスは、複数の手順で構成される手順 です。



== 手順1：メンバーを選択します

ロールバックするメンバーボリュームを選択する必要があります。

.手順
. メニューを選択します。Storage [Snapshots]。
. 「* Snapshot Images *」タブを選択します。
. Snapshot整合性グループのSnapshotイメージを選択し、メニュー：ロールバック[開始]を選択します。
+
ロールバックの開始ダイアログボックスが表示されます。

. 1つ以上のメンバーボリュームを選択します。
. 「*次へ*」をクリックして、次のいずれかの操作を行います。
+
** 選択したいずれかのメンバーボリュームが、Snapshotイメージを格納する複数のリザーブ容量オブジェクトに関連付けられている場合は、Review Capacity（容量の確認）ダイアログボックスが表示されます。に進みます <<手順2：容量を確認する>>。
** 選択したメンバーボリュームのいずれも、Snapshotイメージを格納する複数のリザーブ容量オブジェクトに関連付けられていない場合は、優先度の編集ダイアログボックスが表示されます。に進みます <<手順3：優先度を編集する>>。






== 手順2：容量を確認する

複数のリザーブ容量オブジェクト（Snapshotグループ、リザーブ容量ボリュームなど）に関連付けられているメンバーボリュームを選択した場合は、ロールバックされたボリュームのリザーブ容量を確認して拡張できます。

.手順
. 予約済み容量が非常に少ない（またはゼロの）メンバーボリュームの横にある* Edit *列で*容量の増加*リンクをクリックします。
+
リザーブ容量の拡張ダイアログボックスが表示されます。

. スピンボックスを使用して容量の割合を調整し、*増加*をクリックします。
+
選択したストレージオブジェクトを含むプールまたはボリュームグループに空き容量がない場合や、ストレージアレイに未割り当て容量がない場合は、容量を追加できます。新しいプールまたはボリュームグループを作成し、そのプールまたはボリュームグループ上の新しい空き容量を使用してこの処理を再試行できます。

. 「*次へ*」をクリックして、に進みます <<手順3：優先度を編集する>>。
+
[優先度の編集]ダイアログボックスが表示されます。





== 手順3：優先度を編集する

必要に応じて、ロールバック処理の優先度を編集できます。

.このタスクについて
ロールバックの優先度によって、システムパフォーマンスを考慮せずロールバック処理専用となるシステムリソースの数が決まります。

.手順
. スライダを使用して、ロールバックの優先度を必要に応じて調整します。
. この操作を実行することを確認し、[完了]をクリックします。


.結果
System Managerは次の処理を実行します。

* 選択したSnapshotイメージに保存された内容を使用してSnapshot整合性グループメンバーボリュームをリストアします。
* ホストからロールバックされたボリュームにすぐにアクセスできるようにします。ロールバック処理が完了するまで待つ必要はありません。


.完了後
ロールバック処理の進捗状況を表示するには、MENU（ホーム）：[View Operations in Progress]（進行中の処理の表示）を選択します。

ロールバック処理が失敗すると、処理は一時停止します。一時停止した処理を再開できます。処理が再び失敗する場合は、Recovery Guru手順 に従って問題を修正するか、テクニカルサポートにお問い合わせください。
