---
permalink: sm-storage/start-snapshot-image-rollback-for-base-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, start, snapshot, image, rollback, base, volume 
summary: ロールバック処理を実行して、Snapshotイメージに保存されている内容と一致するようにベースボリュームの内容を変更することができます。ロールバック処理では、ベースボリュームに関連付けられているSnapshotイメージの内容は変更されません。 
---
= ベースボリュームのSnapshotイメージのロールバックを開始する
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ロールバック処理を実行して、Snapshotイメージに保存されている内容と一致するようにベースボリュームの内容を変更することができます。

ロールバック処理では、ベースボリュームに関連付けられているSnapshotイメージの内容は変更されません。

.作業を開始する前に
* ロールバック処理を開始するための十分なリザーブ容量が確保されています。
* 選択したSnapshotイメージとボリュームがどちらも最適な状態である必要があります。
* 選択したボリュームですでに実行中のロールバック処理がないことを確認します。


.このタスクについて
ロールバックの開始手順によって、ベースボリュームのSnapshotイメージに対してロールバックが開始されます。このとき、ストレージ容量を追加することもできます。1つのベースボリュームに対して複数のロールバック処理を同時に開始することはできません。

[NOTE]
====
ホストはロールバック後の新しいベースボリュームにすぐにアクセスできますが、ロールバックを実行中のベースボリュームに読み取り/書き込みアクセスすることはできません。リカバリ用にロールバック前のベースボリュームを保持するためには、ロールバックを開始する直前にベースボリュームのSnapshotを作成します。

====
.手順
. メニューを選択します。Storage [Snapshots]。
. 「* Snapshot Images *」タブを選択します。
. Snapshotイメージを選択し、メニューからロールバック[開始]を選択します。
+
ロールバックの開始の確認ダイアログボックスが表示されます。

. *オプション：*必要に応じて、*容量を増やす*オプションを選択します。
+
リザーブ容量の拡張ダイアログボックスが表示されます。

+
.. スピンボックスを使用して容量の割合を調整します。
+
選択したストレージオブジェクトを含むプールまたはボリュームグループに空き容量がない場合や、ストレージアレイに未割り当て容量がない場合は、容量を追加できます。新しいプールまたはボリュームグループを作成し、そのプールまたはボリュームグループ上の新しい空き容量を使用してこの処理を再試行できます。

.. [* 拡大（ * ） ] をクリックします


. この処理を実行することを確認し、*ロールバック*をクリックします。


.結果
System Managerは次の処理を実行します。

* 選択したSnapshotイメージに保存された内容を使用してボリュームをリストアします。
* ホストからロールバックされたボリュームにすぐにアクセスできるようにします。ロールバック処理が完了するまで待つ必要はありません。


.完了後
ロールバック処理の進捗状況を表示するには、MENU（ホーム）：[View Operations in Progress]（進行中の処理の表示）を選択します。

ロールバック処理が失敗すると、処理は一時停止します。一時停止した処理を再開できます。処理が再び失敗する場合は、Recovery Guru手順 に従って問題を修正するか、テクニカルサポートにお問い合わせください。
