---
permalink: sm-storage/take-action-on-a-copy-volume-operation.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, copy, volume, 
summary: 実行中のボリュームコピー処理の表示、ボリュームコピー処理の停止、優先度の変更、再コピー、クリアを行うことができます。 
---
= ボリュームコピー処理に対して実行します
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
実行中のボリュームコピー処理の表示、ボリュームコピー処理の停止、優先度の変更、再コピー、クリアを行うことができます。

.手順
. メニューを選択します。ホーム[進行中の操作を表示]。
+
[処理を実行中]ダイアログボックスが表示されます。

. 処理を実行するボリュームコピー処理を探し、* Actions *列のリンクをクリックして、次のいずれかの操作を実行します。
+
特に、処理を停止する場合は、ダイアログに表示されているすべての警告テキストをお読みください。

+
[cols="25h,~"]
|===
| アクション | 説明 


 a| 
停止します
 a| 
ステータスが実行中、保留、または失敗であるボリュームコピー処理を停止できます。

ボリュームコピーが停止されると、マッピングされたすべてのホストがソースボリュームに書き込みアクセスできるようになります。ソースボリュームにデータが書き込まれると、ターゲットボリューム上のデータはソースボリューム上のデータと一致しなくなります。



 a| 
優先度を変更します
 a| 
ステータスが実行中であるボリュームコピー処理の優先度を変更して、ボリュームコピー処理が完了するまでの速度を選択できます。



 a| 
再コピー
 a| 
停止したボリュームコピー処理を再開する場合や、ボリュームコピー処理が失敗または停止した場合に、ボリュームを再コピーできます。ボリュームコピー処理が最初から開始されます。

再コピー操作では、ターゲットボリューム上の既存のデータが上書きされます。この操作は、ターゲットボリュームに関連付けられているSnapshotボリュームがある場合は失敗します。



 a| 
クリア
 a| 
ステータスが実行中、保留、または失敗であるボリュームコピー処理を削除できます。

[NOTE]
====
この操作は必ず、「*クリア*」を選択する前に実行してください。確認ダイアログはありません。

====
|===

