---
permalink: sm-storage/types-of-copy-volume-operations.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, copy, volume, 
summary: オフラインとオンラインのどちらかのボリュームコピー処理を実行できます。オフライン処理では、ソースボリュームからデータを読み取ってターゲットボリュームにコピーします。オンライン処理では、Snapshotボリュームをソースとして使用して、そのデータをターゲットボリュームにコピーします。 
---
= ボリュームコピー処理のタイプ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
オフラインの_ボリュームコピー操作または_オンラインの_ボリュームコピー操作のいずれかを実行できます。オフライン処理では、ソースボリュームからデータを読み取ってターゲットボリュームにコピーします。オンライン処理では、Snapshotボリュームをソースとして使用して、そのデータをターゲットボリュームにコピーします。

データの整合性を確保するために、どちらのタイプのボリュームコピー処理でも、ターゲットボリュームに対するすべてのI/Oアクティビティが中断されます。これは、手順 が完了するまでターゲットボリューム上のデータが整合性のない状態になるためです。

オフラインおよびオンラインのボリュームコピー処理について以下で説明します。



== オフラインのボリュームコピー処理です

オフラインのボリュームコピー関係は、ソースボリュームとターゲットボリューム間の関係です。オフラインコピーは、ソースボリュームからデータを読み取り、そのデータをターゲットボリュームにコピーします。コピーの実行中は、ソースボリュームに対するすべての更新が一時停止されます。ソースボリュームに対するすべての更新を一時停止するのは、時間の経過による不整合がターゲットボリュームで発生しないようにするためです。

[cols="25h,~"]
|===
2+| オフラインコピー処理に関する重要なポイント 


 a| 
読み取り要求と書き込み要求
 a| 
* ボリュームコピー処理のステータスが実行中または保留の場合、オフラインコピーに参加しているソースボリュームは読み取り専用のI/Oアクティビティに使用できます。
* 書き込み要求はオフラインコピーが完了したあとで許可されます。
* 書き込み禁止のエラーメッセージが表示されないようにするために、ステータスが実行中のボリュームコピー処理に参加しているソースボリュームにはアクセスしないでください。




 a| 
ジャーナリングファイルシステム
 a| 
* ソースボリュームがジャーナリングファイルシステムでフォーマットされている場合は、ソースボリュームに対する読み取り要求の問題 処理がストレージアレイコントローラから拒否されてエラーメッセージが表示されることがあります。
* ジャーナリングファイルシステムのドライバは、読み取り要求の問題 処理を試行する前に書き込み要求を発行します。コントローラは書き込み要求を拒否します。書き込み要求が拒否されたために、読み取り要求が発行されない可能性があります。この状況により、ソースボリュームが書き込み禁止であることを示すエラーメッセージが表示される場合があります。
* この問題 が実行されないようにするために、ボリュームコピー処理のステータスが実行中のときは、オフラインコピーに参加しているソースボリュームにはアクセスしないでください。


|===


== オンラインのボリュームコピー処理です

オンラインのボリュームコピー関係は、Snapshotボリュームとターゲットボリューム間の関係です。ソースボリュームがオンラインになっていて、データの書き込みに使用できる場合は、ボリュームコピー処理を開始できます。そのためには、ボリュームのSnapshotを作成し、そのSnapshotをコピーの実際のソースボリュームとして使用します。

ソースボリュームに対してボリュームコピー処理を開始すると、System ManagerはベースボリュームのSnapshotイメージおよびベースボリュームとターゲットボリュームのSnapshotイメージ間のコピー関係を作成します。Snapshotイメージをソースボリュームとして使用すると、ストレージアレイでは、コピーの実行中も引き続きソースボリュームへの書き込みを行うことができます。

オンラインコピー処理中は、copy-on-write手順 が原因でパフォーマンスが低下します。オンラインコピーが完了すると、ベースボリュームのパフォーマンスが元に戻ります。

[cols="25h,~"]
|===
2+| オンラインコピー処理に関する重要なポイント 


 a| 
どのような種類のボリュームを使用できますか？
 a| 
* ポイントインタイムイメージの作成対象となるボリュームはベースボリュームとも呼ばれます。このボリュームには、ストレージアレイ上の標準ボリュームまたはシンボリュームを使用する必要があります。
* ターゲットボリュームには、ボリュームグループ内の標準ボリュームまたはプール内の標準ボリュームを使用できます。ターゲットボリュームに、シンボリュームやSnapshotグループ内のベースボリュームを使用することはできません。
* オンラインのボリュームコピー機能を使用すると、シンボリュームから同じストレージアレイにあるプール内の標準ボリュームにデータをコピーできます。ただし、ボリュームコピー機能を使用して標準ボリュームからシンボリュームにデータをコピーすることはできません。




 a| 
ベースボリュームのパフォーマンス
 a| 
* コピー元として使用するSnapshotボリュームがアクティブな場合は、copy-on-write処理が原因でベースボリュームのパフォーマンスが低下します。コピーが完了すると、Snapshotは無効になり、ベースボリュームのパフォーマンスが元に戻ります。Snapshotは無効ですが、リザーブ容量ボリュームとコピー関係はそのまま残ります。




 a| 
作成されるボリュームのタイプ
 a| 
* Snapshotボリュームとリザーブ容量ボリュームは、オンラインコピー処理中に作成されます。
* Snapshotボリュームは、データを格納する実際のボリュームではなく、特定の時点でボリュームに格納されていたデータへの参照です。
* 作成されるSnapshotごとに、そのSnapshotのデータを保持するためのリザーブ容量ボリュームが作成されます。リザーブ容量ボリュームは、Snapshotイメージの管理にのみ使用されます。




 a| 
リザーブ容量ボリューム
 a| 
* ソースボリューム上のデータブロックが変更される前に、変更対象のブロックの内容が保管用のリザーブ容量ボリュームにコピーされます。
* リザーブ容量ボリュームにはそのデータブロック内の元のデータのコピーが格納されるため、データブロックに対する以降の変更はソースボリュームにのみ書き込まれます。
* リザーブ容量ボリュームに格納されるのはSnapshotの作成時刻以降に変更されたデータブロックだけであるため、オンラインコピー処理で使用されるディスクスペースは完全な物理コピーよりも少なくなります。


|===