---
permalink: sm-storage/view-ssd-cache-statistics.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, ssd cache, statistics 
summary: SSDキャッシュについて、読み取り、書き込み、キャッシュヒット、キャッシュ割り当ての割合、 キャッシュ使用率です。 
---
= SSDキャッシュの統計を表示します
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SSDキャッシュについて、読み取り、書き込み、キャッシュヒット、キャッシュ割り当ての割合、 キャッシュ使用率です。

詳細統計のサブセットである一般統計は、View SSD Cache Statisticsダイアログボックスに表示されます。SSDキャッシュの詳細統計は、すべてのSSD統計を「.csv」ファイルにエクスポートした場合にのみ表示できます。

統計を確認および解釈する際には、複数の統計を組み合わせることで見えてくる情報もあることに注意してください。

.手順
. 選択メニュー：Storage（Pool & Volume Groups）
. 統計を表示するSSDキャッシュを選択し、メニューをクリックします。More [SSD Cache statistics（SSDキャッシュ統計の表示）]
+
View SSD Cache Statistics（SSDキャッシュ統計の表示）ダイアログボックスが表示され、選択したSSDキャッシュの公称統計が表示されます。

+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 説明 


 a| 
読み取り
 a| 
SSDキャッシュが有効なボリュームに対するホストの読み取りの合計数が表示されます。書き込みに対する読み取りの比率が大きいほど、キャッシュ処理が向上します。



 a| 
書き込み
 a| 
SSDキャッシュが有効なボリュームに対するホストの書き込みの合計数。書き込みに対する読み取りの比率が大きいほど、キャッシュ処理が向上します。



 a| 
キャッシュヒット
 a| 
キャッシュヒット数が表示されます。



 a| 
キャッシュヒット率
 a| 
キャッシュヒット率が表示されます。この値は、「キャッシュヒット数/（読み取り数+書き込み数）」の式で算出されます。効果的なSSDキャッシュ処理には、キャッシュヒットの割合が50%より高いことが必要です。



 a| 
キャッシュ割り当て率
 a| 
割り当てられているSSDキャッシュストレージの割合が表示されます。この値は、このコントローラで使用できるSSDキャッシュストレージの割合で表したもので、割り当てられているバイト数/使用可能なバイト数から導き出されます。



 a| 
キャッシュ使用率
 a| 
有効なボリュームのデータが格納されているSSDキャッシュストレージの割合が表示されます。この値は、割り当てられているSSDキャッシュストレージの割合で表したものです。この値はSSDキャッシュの利用率または密度を表し、割り当てられたバイト数を使用可能なバイト数で割った値です。



 a| 
すべてエクスポート（Export All）
 a| 
SSDキャッシュのすべての統計をCSV形式にエクスポートします。エクスポートされたファイルには、SSDキャッシュの使用可能なすべての統計（一般統計と詳細統計の両方）が含まれます。

|===
====
. 「*キャンセル*」をクリックして、ダイアログボックスを閉じます。

