---
permalink: sm-storage/view-performance-data-graphical.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, graphical, performance, 
summary: 論理オブジェクト、物理オブジェクト、アプリケーション、およびワークロードのパフォーマンスデータをグラフで表示できます。 
---
= SANtricity System Managerでグラフィカルなパフォーマンスデータを表示する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
論理オブジェクト、物理オブジェクト、アプリケーション、およびワークロードのパフォーマンスデータをグラフで表示できます。

.このタスクについて
パフォーマンスグラフには、履歴データとキャプチャ中のライブデータが表示されます。「ライブ更新」というラベルの付いたグラフ上の縦線は、履歴データとライブデータを区別します。

*ダッシュボードビュー*

ダッシュボードには、ストレージアレイレベルのパフォーマンスを示すグラフが含まれています。この画面から限られた指標を選択することも、*パフォーマンスの詳細を表示*をクリックしてメニュー：Monitoring[Performance]に移動し、利用可能なすべての指標を選択することもできます。

*詳細表示*

パフォーマンス ページに表示されるグラフは、お客様の選択内容に基づいています：

* *オブジェクトの種類* -- 含めるオブジェクトのカテゴリを選択します（例：ストレージ アレイ、コントローラ、プールとボリューム グループ、アプリケーション、ワークロード、ボリューム、チャネル、ドライブ）。
* *オブジェクト* -- 選択したオブジェクト タイプに対して、最大 5 つの特定のオブジェクトを選択します。


.手順
. メニューの「監視」→「パフォーマンス」を選択してください。
. 表示するデータを選択するには、*オブジェクトタイプ*と*オブジェクト*を使用します。最大5つのオブジェクトを選択できます。オブジェクト名または部分的な名前を検索するには、*オブジェクト*リストの検索フィールドを使用してください。
+
すべてのオブジェクトタイプで、すべての指標が利用できるわけではありません。ストレージアレイとコントローラはレイテンシを報告せず、CPU使用率を報告するのはコントローラのみであり、ヘッドルームを報告するのはコントローラとチャネルのみです。

. 表示する期間を選択するには、*時間範囲* を使用してください。
. *Refresh*をクリックします。
. *オプション：* 個々のグラフで、*比較*を使用して、同じオブジェクトに対して別のメトリックタイプを重ねて表示します。
. 必要に応じて、パフォーマンスデータを表示するための追加のオプションを使用します。
+
.その他のオプション
[%collapsible]
====
[cols="25h,~"]
|===
| オプション | 説明 


 a| 
Time range
 a| 
表示する期間（5分、1時間、8時間、1日、7日）を選択します。 または30日）。デフォルトは1時間です。


NOTE: 30日間のパフォーマンスデータを読み込むには、数分かかる場合があります。データの読み込み中は、ウェブページから移動したり、ウェブページを更新したり、ブラウザを閉じたりしないでください。



 a| 
データポイントの詳細
 a| 
グラフにカーソルを合わせると、特定のデータポイントの指標が表示されます。



 a| 
スクロールバー
 a| 
グラフの下にあるスクロールバーを使用すると、前後の期間を表示できます。



 a| 
ズームバー
 a| 
グラフの下にあるズームバーハンドルをドラッグすると、期間を拡大表示できます。ズームバーを広げるほど、グラフの細かい部分が小さくなります。

グラフをリセットするには、いずれかの期間のオプションを選択します。



 a| 
ドラッグアンドドロップ
 a| 
グラフ上で、カーソルをある時点から別の時点にドラッグすると、特定の期間を拡大表示できます。

グラフをリセットするには、いずれかの期間のオプションを選択します。

|===
====

