---
permalink: sm-storage/view-performance-data-graphical.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, graphical, performance, 
summary: 論理オブジェクト、物理オブジェクト、アプリケーション、およびワークロードのパフォーマンスデータをグラフで表示できます。 
---
= グラフィカルなパフォーマンスデータを表示します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
論理オブジェクト、物理オブジェクト、アプリケーション、およびワークロードのパフォーマンスデータをグラフで表示できます。

.このタスクについて
パフォーマンスグラフには、履歴データとキャプチャ中のライブデータが表示されます。「ライブ更新」というラベルの付いたグラフ上の縦線は、履歴データとライブデータを区別します。

*ホームページ表示*

ホームページには、ストレージアレイレベルのパフォーマンスを示すグラフが表示されます。このビューから限定された指標を選択することも、「*パフォーマンスの詳細を表示」をクリックして利用可能なすべての指標を選択することもできます。

*詳細表示*

詳細なパフォーマンスビューでは、3つのタブからそれぞれグラフを使用できます。

* *論理ビュー*--ボリュームグループおよびプール別にグループ化された論理オブジェクトのパフォーマンスデータを表示します論理オブジェクトには、ボリュームグループ、プール、ボリュームがあります。
* *物理ビュー*--コントローラ、ホストチャネル、ドライブチャネル、ドライブのパフォーマンスデータを表示します。
* *アプリケーションとワークロードビュー*-定義したアプリケーションタイプとワークロード別にグループ化された論理オブジェクト（ボリューム）のリストが表示されます。


.手順
. 「* Home *」を選択します。
. アレイレベルのビューを選択するには、IOPS、MiB/秒、またはCPUボタンをクリックします。
. 詳細を表示するには、*パフォーマンスの詳細を表示*をクリックします。
. 論理ビュー*タブ、*物理ビュー*タブ、または*アプリケーションとワークロードの表示*タブを選択します。
+
オブジェクトタイプに応じて、各タブに異なるグラフが表示されます。

+
[cols="25h,~"]
|===
| ビューのタブ | 各オブジェクトタイプについて表示されるパフォーマンスデータ 


 a| 
論理ビュー
 a| 
** *ストレージアレイ*：IOPS、MiB/秒
** *プール*：レイテンシ、IOPS、MiB/秒
** *ボリュームグループ*：レイテンシ、IOPS、MiB/秒
** *ボリューム*：レイテンシ、IOPS、MiB/秒




 a| 
物理ビュー
 a| 
** *コントローラ*：IOPS、MiB/秒、CPU、ヘッドルーム
** *ホストチャネル*：レイテンシ、IOPS、MiB/秒、ヘッドルーム
** *ドライブチャネル*：レイテンシ、IOPS、MiB/秒
** *ドライブ*：レイテンシ、IOPS、MiB/秒




 a| 
アプリケーションとワークロードビュー
 a| 
** *ストレージアレイ*：IOPS、MiB/秒
** *アプリケーション*：レイテンシ、IOPS、MiB/秒
** *ワークロード*：レイテンシ、IOPS、MiB/秒
** *ボリューム*：レイテンシ、IOPS、MiB/秒


|===
. オプションを使用して、必要なオブジェクトと情報を表示します。
+
.オプション（ Options ）
[%collapsible]
====
[cols="25h,~"]
|===
| オブジェクトを表示するためのオプション | 説明 


 a| 
ドロワーを展開してオブジェクトのリストを表示します。
 a| 
_Navigationドロワー_には、プール、ボリュームグループ、ドライブなどのストレージオブジェクトが含まれます。

ドロワーをクリックすると、ドロワー内のオブジェクトのリストが表示されます。



 a| 
表示するオブジェクトを選択します。
 a| 
各オブジェクトの左側にあるチェックボックスをオンにして、表示するパフォーマンスデータを選択します。



 a| 
フィルタを使用して、オブジェクト名または名前の一部を検索します。
 a| 
[フィルタ（Filter）]ボックスに、ドロワー内のオブジェクトのみをリストするオブジェクトの名前または名前の一部を入力する。



 a| 
オブジェクトを選択した後、*グラフの更新*をクリックします。
 a| 
ドロワーからオブジェクトを選択した後、[*グラフの更新*]を選択して、選択した項目のグラフデータを表示します。



 a| 
グラフの表示と非表示を切り替えます
 a| 
グラフの表示と非表示を切り替えるには、グラフのタイトルを選択します。

|===
====
. 必要に応じて、パフォーマンスデータを表示するための追加のオプションを使用します。
+
.その他のオプション
[%collapsible]
====
[cols="25h,~"]
|===
| オプション | 説明 


 a| 
期間
 a| 
表示する期間（5分、1時間、8時間、1日、7日）を選択します。 または30日）。デフォルトは1時間です。


NOTE: 30日間のパフォーマンスデータをロードするには数分かかることがあります。データのロード中は、Webページから移動したり閉じたりしないでください。また、ブラウザをリフレッシュしないでください。



 a| 
データポイントの詳細
 a| 
グラフにカーソルを合わせると、特定のデータポイントの指標が表示されます。



 a| 
スクロールバー
 a| 
グラフの下にあるスクロールバーを使用すると、前後の期間を表示できます。



 a| 
ズームバー
 a| 
グラフの下にあるズームバーハンドルをドラッグすると、期間を拡大表示できます。ズームバーを広げるほど、グラフの細かい部分が小さくなります。

グラフをリセットするには、いずれかの期間のオプションを選択します。



 a| 
ドラッグアンドドロップ
 a| 
グラフ上で、カーソルをある時点から別の時点にドラッグすると、特定の期間を拡大表示できます。

グラフをリセットするには、いずれかの期間のオプションを選択します。

|===
====

