---
permalink: sm-storage/what-is-the-default-cluster.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, default, cluster, 
summary: デフォルトクラスタはシステム定義のエンティティです。ストレージアレイにログインしたホストポート識別子が関連付けられていない場合、そのポートはデフォルトクラスタに割り当てられているボリュームにアクセスできます。関連付けられていないホストポート識別子は、特定のホストに論理的に関連付けられておらず、ホストに物理的に搭載されてストレージアレイにログインしているホストポートです。 
---
= デフォルトクラスタとは何ですか？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
デフォルトクラスタはシステム定義のエンティティです。ストレージアレイにログインしたホストポート識別子が関連付けられていない場合、そのポートはデフォルトクラスタに割り当てられているボリュームにアクセスできます。関連付けられていないホストポート識別子は、特定のホストに論理的に関連付けられておらず、ホストに物理的に搭載されてストレージアレイにログインしているホストポートです。

[NOTE]
====
ホストがストレージアレイ内の特定のボリュームにアクセスできるようにする場合は、デフォルトクラスタを使用する_は_しない_選択します。代わりに、ホストポート識別子を対応するホストに関連付ける必要があります。このタスクは、ホストの作成時に手動で実行することも、各ホストにインストールされているHost Context Agent（HCA）を使用して自動的に実行することもできます。その後、ボリュームを個々のホストまたはホストクラスタに割り当てます。

====
デフォルトクラスタは、すべてのホストとストレージアレイに接続されたすべてのログイン済みホストポート識別子がすべてのボリュームにアクセスできるようにするための外部ストレージ環境を構築する場合にのみ使用してください（フルアクセスモード） 特にストレージアレイやユーザインターフェイスでホストが認識されないようにする必要があります。

最初にボリュームをデフォルトクラスタに割り当てる際には、コマンドラインインターフェイス（CLI）を使用する必要があります。ただし、ボリュームを少なくとも1つデフォルトクラスタに割り当てると、このエンティティを管理できるユーザインターフェイスに表示されます（デフォルトクラスタ）。
