---
sidebar: sidebar 
permalink: whats-new.html 
keywords: whats new, new features, SANtricity 12.0 
summary: SANtricity OS の新機能 
---
= SANtricity OS 12.0の新機能
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ./media/


[role="lead"]
SANtricity System Manager 12.0の新機能を次の表で説明します。



== バージョン12.0の新機能


NOTE: SANtricity OS 12.0リリースは、新しいEF80およびEF50オールフラッシュ ストレージ システムとのみ互換性があります。SANtricity OS 11.9以前を使用している場合は、以前のリリースの新機能のリストについてlink:known-issues.html["既知の問題"]を参照してください。

[cols="35h,~"]
|===
| 新機能 | 説明 


 a| 
新しいストレージ システム モデル – EF80およびEF50オールフラッシュ ストレージ システム
 a| 
今回のリリースでは、EF80およびEF50オールNVMeフラッシュ ストレージ システムが導入されました。EF80およびEF50は、24台のNVMe SSDドライブと、コントローラごとに1枚のホスト インターフェイス カード（HIC）をサポートします。サポートされているNVMe over Fabricsホスト インターフェイスには、NVMe over RoCE、EF80用のNVMe over IB、およびEF50用のNVMe over FCが含まれます。サポートされているSCSIインターフェイスには、Fibre Channelが含まれます。

EF80およびEF30は、30TBまたは60TBの大容量NVMe SSDドライブにも対応しています。EF80およびEF30は、ダイナミックディスクプールでの使用のみに対応しており、従来のRAIDには対応していません。



 a| 
SANtricity System Manager の新しいユーザーインターフェイス
 a| 
新しいEF80およびEF50コントローラーの場合、SANtricity System Managerのユーザーインターフェイスが、よりモダンな外観と操作性を実現するために再設計されました。新しいインターフェイスには、左側のパネルナビゲーションと、管理タスクを効率化するための使いやすさの向上が含まれています。


NOTE: 新しいユーザーインターフェイスは現在、SANtricity 12.0リリースのEF80およびEF50ストレージシステムでのみ利用可能です。SANtricity 11.9以前のバージョンを使用している場合は、レガシーユーザーインターフェースの使用方法についてlink:https://docs.netapp.com/us-en/e-series-santricity-119/system-manager/index.html["SANtricity System Manager 11.9"]を参照してください。



 a| 
サーバー証明書のサブジェクト代替名（SAN）には、文字、数字、ハイフンのみが使用可能になりました
 a| 
SANtricity System ManagerまたはUnified Managerでサーバ証明書を作成または編集する際、Subject Alternative Names（SANs）フィールドには英字、数字、ハイフンのみが許可されるようになりました。この変更により、セキュリティが強化され、SSL/TLS証明書の業界標準との互換性が確保されます。



 a| 
SSDおよびNVMeベースのシステムでは、ダイナミックディスクプールのセグメントサイズがデフォルトで32Kになりました
 a| 
SSDおよびNVMeベースのシステムにおけるDynamic Disk Poolの場合、デフォルトのセグメントサイズが32Kに変更されました。以前は、これらのシステムにおけるdynamic disk poolのデフォルトのセグメントサイズは128Kに固定されていました。この変更により、小規模なI/O操作と大規模なI/O操作が混在するワークロードのパフォーマンスが最適化されます。



 a| 
スクリプトエディタがSANtricity System Managerで利用可能になりました
 a| 
新しいスクリプトエディタがSANtricity System Manager内で利用可能になりました。スクリプトエディタを使用すると、スクリプトファイルの作成や編集、スクリプトファイルのストレージ管理ステーションのローカルディスクへの保存、またはディスクからのスクリプトファイルの読み込みを行うことができます。スクリプトエディタは、ストレージシステムの管理に必要な構文チェック機能とコマンド実行機能を提供します。詳細については、link:sm-support/use-script-editor.html["スクリプト エディタを使用する"^]を参照してください。

|===