---
sidebar: sidebar 
permalink: whats-new.html 
keywords: whats new, new features, SANtricity 11.80 
summary: SANtricity OS の新機能 
---
= SANtricity OS 11.80の新機能
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
次の表に、SANtricity System Manager 11.8の新機能を示します。



== バージョン11.80.1R1の新機能

[cols="35h,~"]
|===
| 新機能 | 説明 


 a| 
新しい自己署名およびCA署名管理証明書のキーサイズが拡張されました。
 a| 
SANtricity System ManagerおよびUnified Managerアプリケーションの自己署名証明書の管理証明書キーサイズが、2、048ビットから3、072ビットに変更されました。この変更は、SANtricityアプリケーションから新しく生成された自己署名証明書とCA署名証明書に適用されます。キーの長さは固定であり、NVSRAMのデフォルトのキーサイズ定義の影響を受けません。

|===


== バージョン11.80.1の新機能

[cols="35h,~"]
|===
| 新機能 | 説明 


 a| 
`-identifyDevices` パラメータ
 a| 
新しい `-identifyDevices` SMcliでパラメータを使用できるようになりました。この新しいパラメータを使用すると、ストレージアレイに関連付けられているすべてのSCSIネイティブブロックデバイスを検索できます。詳細については、を参照してください https://docs.netapp.com/us-en/e-series-cli/get-started/downloadable-smcli-parameters.html#identify-Devices["ダウンロード可能なSMcliコマンドラインパラメータ"^]。



 a| 
イーサネットカーネル統計
 a| 
System Managerの[iSCSI統計パッケージの表示]ページに、新しい[イーサネットカーネル統計]オプションが追加されました。この新しいオプションを使用すると、iSCSIデバイスのプラットフォームカーネルドライバの統計を表示できます。詳細については、を参照してください https://docs.netapp.com/us-en/e-series-santricity/sm-support/view-iscsi-statistics-packages-support.html["iSCSI統計パッケージの表示"^]。



 a| 
REST APIエンドポイントを使用してIPアドレスをブロックする機能を追加
 a| 
[Settings]エンドポイントを使用して、特定のIPアドレスをブロックできるようになりました。 (`/devmgr/v2/settings`）。[Settings]エンドポイントで設定すると、ホワイトリストで指定したIPアドレスだけがストレージデバイスと通信できます。この新機能では、IPv4およびIPv6アドレスリストがサポートされます。



 a| 
vCenterストレージプラグイン
 a| 
vCenter Storageプラグインは、Eシリーズ11.80.1リリースとの互換性を考慮して更新されています。



 a| 
Web Services Proxyの使用方法
 a| 
Web Services Proxyは、Eシリーズ11.80.1リリースとの互換性を確保するためにバージョン6.1に更新されています。

|===


== バージョン11.80の新機能

[cols="35h,~"]
|===
| 新機能 | 説明 


 a| 
強化されたボリュームパリティスキャン
 a| 
REST APIまたはCLIを使用して、ボリュームパリティスキャンをバックグラウンドプロセスとして起動できるようになりました。パリティスキャンは、スキャン処理を完了するために必要な限りバックグラウンドで実行されます。スキャン処理は、コントローラのリブートおよびフェイルオーバー処理の間も維持されます。



 a| 
Unified ManagerでのSAMLのサポート
 a| 
Unified ManagerでSecurity Assertion Markup Language（SAML）がサポートされるようになりました。Unified ManagerでSAMLを有効にすると、ユーザインターフェイスを操作するために、アイデンティティプロバイダに対して多要素認証を使用する必要があります。Unified ManagerでSAMLを有効にすると、IdPを経由せずにREST APIを使用して要求を認証することはできません。



 a| 
自動構成機能
 a| 
アレイの初期セットアップ時に自動構成機能で使用するボリュームのブロックサイズパラメータを設定できるようになりました。この機能は、CLIでは「blocksize」パラメータとしてのみ使用できます。



 a| 
コントローラファームウェアの暗号化署名
 a| 
コントローラファームウェアは暗号署名されています。シグネチャは、初回ダウンロード時および各コントローラのブート時にチェックされます。エンドユーザへの影響はありません。署名は、CAによって発行された拡張検証証明書によって裏付けられます。



 a| 
ドライブファームウェアの暗号化署名
 a| 
ドライブファームウェアは暗号署名されています。署名は最初のダウンロード時にチェックされ、CAによって発行された拡張検証証明書によってバックアップされます。ドライブファームウェアの内容がZIPファイルとして提供されるようになりました。ZIPファイルには、署名済みの古いファームウェアと署名済みの新しいファームウェアが含まれています。ユーザーは、ターゲットシステムで実行されているコードのリリースバージョンに基づいて適切なファイルを選択する必要があります。



 a| 
外部キーサーバ管理-証明書のキーサイズ
 a| 
新しいデフォルトの証明書キーサイズは3072ビット（2048から）です。最大4096ビットのキーサイズがサポートされます。デフォルト以外のキーサイズをサポートするには、NVSRAMビットを変更する必要があります。

キーサイズの選択値は次のとおりです。

* デフォルト= 0
* 長さ2048 = 1
* 長さ3072 = 2
* 長さ4096 = 3


SMcliを使用してキーサイズを4096に変更するには、次の手順を実行します。

`set controller[b] globalnvsrambyte[0xc0]=3;`
`set controller[a] globalnvsrambyte[0xc0]=3;`

キーのサイズを調べます。

`show allcontrollers globalnvsrambyte[0xc0];`



 a| 
ディスクプールの改善
 a| 
11.80以降を実行しているコントローラで作成されたディスクプールは、_Version 0_poolsではなく_Version 1_poolsになります。_Version 1_diskプールが存在する場合、ダウングレード操作は制限されます。

ストレージアレイプロファイルでディスクプールのバージョンを特定できます。



 a| 
System ManagerとUnified Managerは、ブラウザの最小要件を満たしていないと起動しません。
 a| 
System ManagerまたはUnified Managerを起動するには、少なくともバージョンのブラウザが必要です。サポートされる最小バージョンは次のとおりです。

* Firefoxの最小バージョン80
* Chrome最小バージョン89
* エッジ最小バージョン90
* Safariの最小バージョン14




 a| 
FIPS 140-3 NVMe SSDドライブのサポート
 a| 
NetApp認定のFIPS 140-3 NVMe SSDドライブがサポートされるようになりました。これらは、ストレージアレイプロファイルおよびSystem Managerで正しく識別されます。



 a| 
EF300およびEF600でのSSD読み取りキャッシュのサポート
 a| 
SAS拡張構成のHDDを使用するEF300およびEF600コントローラでSSD読み取りキャッシュがサポートされるようになりました。



 a| 
EF300およびEF600でのiSCSIとFibre Channelの非同期リモートミラーリングのサポート
 a| 
NVMeおよびSASベースのボリュームを使用するEF300およびEF600コントローラで非同期リモートミラーリング（ARVM）がサポートされるようになりました。



 a| 
ベーストレイにドライブを搭載しないEF300およびEF600をサポート
 a| 
ベーストレイにNVMeドライブを搭載しないEF300およびEF600コントローラ構成がサポートされるようになりました。



 a| 
すべてのプラットフォームでUSBポートが無効になっている
 a| 
すべてのプラットフォームでUSBポートが無効になりました。

|===