---
sidebar: sidebar 
permalink: whats-new.html 
keywords: whats new, new features, SANtricity 12.10 
summary: SANtricity OS の新機能 
---
= SANtricity OS 12.10の新機能
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ./media/


[role="lead"]
SANtricity System Manager 12.10の新機能を次の表で説明します。



[[new-features-in-version-12-10]]
== バージョン12.10の新機能

[cols="35h,~"]
|===
| 新機能 | 説明 


 a| 
EF50およびEF80ストレージ システム向けSAS拡張サポート
 a| 
EF50およびEF80ストレージシステムは、SAS拡張をサポートするようになり、ストレージ容量と柔軟性の向上が可能になりました。SAS拡張を使用すると、EF50およびEF80システムにストレージエンクロージャを追加接続できるため、必要に応じてストレージ環境を拡張できます。この機能は、大容量ストレージソリューションを必要とし、EF50およびEF80プラットフォームへの投資を最大限に活用したい組織にとって特に有益です。



 a| 
EシリーズストレージシステムのTCP経由のNVMeサポート
 a| 
Eシリーズ ストレージ システムは、NVMe over TCP をサポートするようになり、ハイパフォーマンス ストレージ アクセスのためのホスト インターフェイス オプションが追加されました。NVMe over TCP は、標準的な TCP/IP ネットワーク上で NVMe プロトコルのメリットを活用し、ストレージ システムと接続されたホスト間の効率的で低レイテンシな通信を実現します。このサポートにより、Eシリーズ システムの汎用性が向上し、NVMe over TCP が推奨または必須とされる環境への導入が可能になります。



 a| 
SANtricity System Manager のユーザー インターフェイスの強化
 a| 
SANtricity System Manager のユーザー インターフェイスに、ナビゲーション、使いやすさ、および全体的なユーザー エクスペリエンスを向上させるための機能強化が加えられました。これらの機能強化には、管理タスクのレイアウトと構成の更新、および一般的なストレージ管理操作のためのより直感的なワークフローが含まれます。



 a| 
新しい SANtricity System Manager ユーザーインターフェースに対応した Eシリーズ プラットフォームサポートの拡張
 a| 
SANtricity System Manager の新しいユーザーインターフェースは、EF80 および EF50 ストレージシステム向けの SANtricity 12.00 リリースで導入され、追加の Eシリーズ ストレージ プラットフォームをサポートするように拡張されました。これにより、より広範囲の Eシリーズ ストレージ システムを管理するユーザーが、最新のインターフェースと強化されたユーザビリティ機能のメリットを享受できるようになりました。拡張されたサポートには、Eシリーズ ストレージ システムの特定のモデルとの互換性が含まれており、ユーザーはより多くのストレージ インフラストラクチャにわたって、改善されたナビゲーションと効率化された管理タスクを活用できます。



 a| 
EF80およびEF50システムにおける、ハイパフォーマンスと大容量が混在するドライブのサポート
 a| 
EF80およびEF50ストレージ システムは、Performance NVMe SSDドライブとCapacity NVMe SSDドライブを同一のストレージ アレイ内でサポートするようになりました。ただし、ドライブの最小台数（Performance用は6台、Capacity用は12台）が条件となります。PerformanceドライブとCapacityドライブは、別々のプールとボリューム グループに配置する必要があります。



 a| 
標準ボリューム名とシン ボリューム名の文字数制限が増加
 a| 
標準ボリューム名とシン ボリューム名の文字数制限が、30文字から60文字に引き上げられました。


NOTE: 標準ボリュームまたはシンボリュームに30文字を超える名前が存在する場合、SANtricity OSソフトウェアのバージョン11.90以前へのダウングレードはサポートされません。SANtricity OSソフトウェアのバージョン11.90以前へのダウングレードを計画している場合は、ダウングレードする前に、30文字を超える名前の標準ボリュームまたはシンボリュームの名前を変更してください。



 a| 
SANtricity System Manager ユーザーインターフェイスの最小非アクティブタイムアウト制限が 10 分になりました
 a| 
SANtricity System Manager のユーザーインターフェイスの非アクティブタイムアウト制限が更新され、最短10分になりました。以前は、非アクティブタイムアウトの最小制限時間は15分でした。この変更により、ユーザーインターフェイスが10分間非アクティブ状態になると自動的にログアウトされるようになり、セキュリティが強化されます。

|===


[[new-features-in-version-12-0r1]]
== Version 12.0R1の新機能

このバージョンには軽微な変更のみが含まれており、新機能は追加されていません。このリリースの変更点の詳細については、Eシリーズ SANtricity OS 12.0R1 READMEを参照してください。



[[new-features-in-version-12-0]]
== バージョン12.0の新機能


NOTE: SANtricity OS 12.0リリースは、新しいEF80およびEF50オールフラッシュ ストレージ システムとのみ互換性があります。SANtricity OS 11.9以前を使用している場合は、以前のリリースの新機能のリストについてlink:known-issues.html["既知の問題"]を参照してください。

[cols="35h,~"]
|===
| 新機能 | 説明 


 a| 
新しいストレージ システム モデル – EF80およびEF50オールフラッシュ ストレージ システム
 a| 
今回のリリースでは、EF80およびEF50というオールNVMeフラッシュストレージシステムを紹介します。EF80およびEF50は、コントローラごとに24台のNVMe SSDドライブとコントローラ間ミラーリングカードをサポートします。サポートされているNVMe over Fabricsホスト インターフェイスには、NVMe over RoCE、NVMe over IB、EF80用のNVMe over FC、およびEF50用のNVMe over FCが含まれます。両システムでサポートされているSCSIインターフェイスはFibre Channelです。EF50はコントローラあたり最大2枚のホスト インターフェイス カードをサポートし、EF80はコントローラあたり最大3枚のホスト インターフェイス カードをサポートします。

EF80およびEF50は、30TBまたは60TBの大容量NVMe SSDドライブにも対応しています。EF80およびEF50は、アレイに30TBまたは60TBのドライブが搭載されている場合にのみ、ダイナミックディスクプールを利用できます。



 a| 
SANtricity System Manager の新しいユーザーインターフェイス
 a| 
新しいEF80およびEF50コントローラーの場合、SANtricity System Managerのユーザーインターフェイスが、よりモダンな外観と操作性を実現するために再設計されました。新しいインターフェイスには、左側のパネルナビゲーションと、管理タスクを効率化するための使いやすさの向上が含まれています。


NOTE: 新しいユーザーインターフェイスは現在、SANtricity 12.00リリースのEF80およびEF50ストレージシステムでのみ利用可能です。SANtricity 11.9以前のバージョンを使用している場合は、レガシーユーザーインターフェースの使用方法についてlink:https://docs.netapp.com/us-en/e-series-santricity-119/system-manager/index.html["SANtricity System Manager 11.9"]を参照してください。



 a| 
サーバー証明書のサブジェクト代替名（SAN）には、文字、数字、ハイフンのみが使用可能になりました
 a| 
SANtricity System ManagerまたはUnified Managerでサーバ証明書を作成または編集する際、Subject Alternative Names（SANs）フィールドには英字、数字、ハイフンのみが許可されるようになりました。この変更により、セキュリティが強化され、SSL/TLS証明書の業界標準との互換性が確保されます。



 a| 
SSDおよびNVMeベースのシステムでは、ダイナミックディスクプールのセグメントサイズがデフォルトで32Kになりました
 a| 
SSDおよびNVMeベースのシステムにおけるDynamic Disk Poolの場合、デフォルトのセグメントサイズが32Kに変更されました。以前は、これらのシステムにおけるdynamic disk poolのデフォルトのセグメントサイズは128Kに固定されていました。この変更により、小規模なI/O操作と大規模なI/O操作が混在するワークロードのパフォーマンスが最適化されます。



 a| 
スクリプトエディタがSANtricity System Managerで利用可能になりました
 a| 
新しいスクリプトエディタがSANtricity System Manager内で利用可能になりました。スクリプトエディタを使用すると、スクリプトファイルの作成や編集、スクリプトファイルのストレージ管理ステーションのローカルディスクへの保存、またはディスクからのスクリプトファイルの読み込みを行うことができます。スクリプトエディタは、ストレージシステムの管理に必要な構文チェック機能とコマンド実行機能を提供します。詳細については、link:sm-support/use-script-editor.html["スクリプト エディタを使用する"^]を参照してください。

|===