---
permalink: sm-mirroring/asynchronous-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, asynchronous, mirroring, terms, 
summary: ストレージアレイに関連する非同期ミラーリングの用語を次に示します。 
---
= 非同期ミラーリングに関する用語
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイに関連する非同期ミラーリングの用語を次に示します。

[cols="25h,~"]
|===
| 期間 | 説明 


 a| 
ローカルストレージアレイ
 a| 
ローカルストレージアレイは、操作の対象となるストレージアレイです。

Local Role列に* Primary *と表示された場合は、ミラー関係のプライマリロールが割り当てられたボリュームがストレージアレイに含まれていることを示しています。Local Role列に「* Secondary」と表示されている場合、ストレージアレイにミラー関係のセカンダリロールが割り当てられたボリュームが含まれていることを示しています。



 a| 
ミラー整合性グループ
 a| 
ミラー整合性グループは、1つ以上のミラーペアのコンテナです。非同期ミラーリング処理では、ミラー整合性グループを作成する必要があります。



 a| 
ミラーペア
 a| 
ミラーペアは、プライマリボリュームとセカンダリボリュームの2つのボリュームで構成されます。

非同期ミラーリングでは、ミラーペアは常にミラー整合性グループに属します。書き込み処理はまずプライマリボリュームに対して実行され、その後セカンダリボリュームにレプリケートされます。ミラー整合性グループ内の各ミラーペアで同じ同期設定が共有されます。



 a| 
プライマリボリューム
 a| 
ミラーペアのプライマリボリュームは、ミラーリングするソースボリュームです。



 a| 
リモートストレージアレイ
 a| 
通常、リモートストレージアレイはセカンダリサイトとして指定され、セカンダリサイトにはミラーリング構成のデータのレプリカが格納されます。



 a| 
リザーブ容量
 a| 
リザーブ容量は、コピーサービス処理やストレージオブジェクトに使用される物理割り当て容量です。ホストから直接読み取ることはできません。



 a| 
ロール変更
 a| 
ロール変更とは、セカンダリボリュームにプライマリロールを、セカンダリボリュームにプライマリロールを割り当てる処理です。



 a| 
セカンダリボリューム
 a| 
ミラーペアのセカンダリボリュームは、通常はセカンダリサイトに配置され、データのレプリカが格納されます。



 a| 
同期
 a| 
同期は、ローカルストレージアレイとリモートストレージアレイの間の初期同期で実行されます。また、通信が中断されてプライマリボリュームとセカンダリボリュームが同期されていない状態になったときにも実行されます。通信リンクが再確立されると、レプリケートされていないデータがセカンダリボリュームのストレージアレイに同期されます。

|===