---
permalink: sm-mirroring/asynchronous-mirror-status.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, asynchronous, mirror, status, consistency, group, 
summary: ミラーステータスは、ミラー整合性グループとミラーボリュームペアの状態を定義します。 
---
= 非同期ミラーのステータス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ミラーステータスは、ミラー整合性グループとミラーボリュームペアの状態を定義します。

[NOTE]
====
この機能は、EF600またはEF300ストレージシステムでは使用できません。

====


== ミラー整合性グループのステータス

[cols="25h,~"]
|===
| ステータス | 説明 


 a| 
同期（初期）
 a| 
ミラーボリュームペア間で完了した初期データ同期の進行状況。

初期同期中に、ボリュームは、デグレード/失敗/最適/不明の各状態に移行できます。



 a| 
同期（間隔）
 a| 
ミラーボリュームペア間で完了した定期的なデータ同期の進行状況。



 a| 
システムが中断しました
 a| 
ミラー整合性グループレベルで、すべてのミラーペアに関して、データの同期がストレージシステムによって一時停止された状態。

ミラー整合性グループ内の少なくとも1つのミラーペアが停止または失敗状態です。



 a| 
ユーザが中断しました
 a| 
ミラー整合性グループレベルで、すべてのミラーペアに関して、データの同期がユーザによって一時停止された状態。

この状態は、ローカルストレージアレイ上の変更されたデータがリモートストレージアレイにコピーされる際に発生する可能性があるホストアプリケーションへのパフォーマンスへの影響を軽減するのに役立ちます。



 a| 
一時停止中
 a| 
リモートストレージアレイにアクセスする際にエラーが発生したため、データ同期プロセスが一時停止しています。



 a| 
孤立
 a| 
孤立したミラーペアボリュームは、ミラー整合性グループの一方（プライマリまたはセカンダリ）でミラー整合性グループのメンバーボリュームが削除され、もう一方では削除されていない場合に発生します。

孤立したミラーペアボリュームは、アレイ間の通信がリストアされ、ミラー構成の両サイドでミラーパラメータが調整されたときに検出されます。

ミラーペアを削除すると、孤立したミラーペアの状態を修正できます。



 a| 
ロール変更を保留中/実行中です
 a| 
ミラー整合性グループ間のロールの変更が保留中または進行中です。

ロールの（プライマリロールまたはセカンダリロールへの）反転変更は、選択したミラー整合性グループ内のすべての非同期ミラーペアに影響します。

保留中のロール変更はキャンセルできますが、進行中のロール変更はキャンセルできません。



 a| 
ロールの競合
 a| 
ロール変更処理中にローカルストレージアレイとリモートストレージアレイの間の通信に問題が発生したため、ミラー整合性グループ間でロールの競合が発生しました。

ロールの競合は、通信の問題が解決した時点で発生します。Recovery Guruを使用してこのエラーを解決してください。

ロールの競合を解決する際には、強制昇格は許可されません。

|===


== ミラーペアのステータス

ミラーペアのステータスは、プライマリボリュームとセカンダリボリュームのデータが同期されているかどうかを示します。

[cols="25h,~"]
|===
| ステータス | 説明 


 a| 
同期中です
 a| 
ミラーペア間で完了した初期または定期的なデータ同期の進行状況。

同期には、初期同期と定期的同期の2種類があります。初期同期の進行状況は、[実行時間の長いオペレーション（Long Running Operations）]ダイアログボックスにも表示されます。



 a| 
最適
 a| 
ミラーペア内のボリュームは同期されています。これは、ストレージアレイ間の接続に問題がなく、各ボリュームが想定される動作状態であることを示します。



 a| 
不完全です
 a| 
System Managerでサポートされていないストレージアレイ上でミラーペアの作成手順が開始され、セカンダリ上でミラーペアが完成していないため、リモートストレージアレイ上の非同期ミラーペアが不完全です。

ミラーペアの作成プロセスは、リモートストレージアレイ上のミラー整合性グループにボリュームが追加されたときに完了します。このボリュームが非同期ミラーペアのセカンダリボリュームになります。

リモートストレージアレイがSystem Managerで管理されている場合、ミラーペアは自動的に完成します。



 a| 
失敗しました
 a| 
プライマリボリューム、セカンダリボリューム、またはミラーのリザーブ容量に障害が発生したため、非同期ミラーリング処理を正常に実行できません。



 a| 
孤立
 a| 
孤立したミラーペアボリュームは、ミラー整合性グループの一方（プライマリまたはセカンダリ）でミラー整合性グループのメンバーボリュームが削除され、もう一方では削除されていない場合に発生します。

孤立したミラーペアボリュームは、2つのストレージアレイ間の通信がリストアされ、ミラー構成の両サイドでミラーパラメータが調整されたときに検出されます。

ミラーペアを削除すると、孤立したミラーペアの状態を修正できます。



 a| 
停止しました
 a| 
ミラー整合性グループがシステムによる一時停止状態のため、ミラーペアは停止状態です。

|===