---
permalink: sm-mirroring/change-synchronization-settings-for-a-mirrored-pair.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, change, synchronization, settings, mirrored, pair, 
summary: ミラーペアが通信の中断後に再同期処理を完了するために使用する、同期優先度と再同期ポリシーを変更できます。 
---
= ミラーペアの同期の設定を変更する
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ミラーペアが通信の中断後に再同期処理を完了するために使用する、同期優先度と再同期ポリシーを変更できます。

.このタスクについて
ミラーペアの同期設定は、プライマリボリュームを含むストレージアレイでのみ編集できます。

.手順
. 選択メニュー：Storage [Synchronous Mirroring]
. 編集するミラーペアを選択し、メニューから[More（詳細）][Edit settings（設定の編集）]を選択します。
+
設定の表示/編集ダイアログボックスが表示されます。

. スライダバーを使用して同期優先度を編集します。
+
同期優先度は、I/O要求の処理と比較して、通信中断後の再同期処理を完了するためにどの程度のシステムリソースが使用されるかを決定するものです。

+
.同期速度について
[%collapsible]
====
同期優先度は5段階で設定できます。

** 最低
** 低
** 中
** 高
** 最高


====
+
同期優先度を最低に設定すると、I/Oアクティビティが優先され、再同期処理にかかる時間が長くなります。同期優先度が最高に設定されている場合は再同期処理が優先されますが、ストレージアレイのI/Oアクティビティに影響する可能性があります。

. 再同期ポリシーを適宜編集します。
+
リモートストレージアレイ上のミラーペアを手動または自動で再同期できます。

+
** *手動*（推奨オプション）-ミラーペアとの通信が回復したあとに同期を手動で再開する場合に選択します。このオプションを選択すると、最適なタイミングでデータをリカバリできます。
** *自動*--ミラーペアとの通信が回復した後、再同期を自動的に開始する場合に選択します。


. [ 保存（ Save ） ] を選択します。

