---
permalink: sm-mirroring/complete-mirrored-pair-for-primary-volumes-created-on-legacy-system.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, complete, mirrored, pair, volumes, created, legacy, 
summary: SANtricity System Managerで管理できない従来のストレージアレイにプライマリボリュームを作成した場合は、System Managerを使用してそのアレイにセカンダリボリュームを作成できます。 
---
= 従来型システムで作成されたプライマリボリュームのミラーペアを作成します
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SANtricity System Managerで管理できない従来のストレージアレイにプライマリボリュームを作成した場合は、SANtricity System Managerを使用してそのアレイにセカンダリボリュームを作成できます。

.このタスクについて
System Managerで管理可能な別のインターフェイスや新しいアレイを使用する従来型アレイ間で、非同期ミラーリングを実行できます。

* System Managerを使用する2つのストレージアレイをミラーリングする場合は、ミラーペア作成手順ですでにミラーペアの作成が完了しているため、このタスクはスキップできます。
* このタスクはリモートストレージアレイで実行します。


.手順
. メニューを選択します。Storage [非同期ミラーリング]。
. [ミラーペア*（Mirrored Pair *）]タブを選択します。
+
ミラーペアの表に、ストレージアレイに関連付けられているすべてのミラーペアが表示されます。

. ステータスが「Incomplete」のミラーペアボリュームを探し、ミラーペアの列に表示された「* Complete Mirrored pair *」リンクをクリックします。
. 次のいずれかのオプションボタンを選択して、ミラーペア作成手順を自動と手動のどちらで実行するかを選択します。
+
** *自動*--新しいセカンダリボリュームを作成します
+
セカンダリボリュームを作成する既存のプールまたはボリュームグループを選択して、ミラーペアのリモート側のデフォルト設定を受け入れます。デフォルト設定を使用してセカンダリボリュームにリザーブ容量を割り当てるには、この推奨オプションを使用します。

** *手動*--既存のボリュームを選択します
+
セカンダリボリュームのパラメータを独自に定義します。

+
... Next（次へ）*をクリックして、セカンダリボリュームを選択します。
... セカンダリボリュームとして使用する既存のボリュームを選択し、* Next *をクリックしてリザーブ容量を割り当てます。
... リザーブ容量を割り当てます。次のいずれかを実行します。
+
**** デフォルトの設定を使用します。
+
リザーブ容量のデフォルト設定はベースボリュームの容量の20%であり、通常はこの容量で十分です。

**** データストレージの非同期ミラーリングのニーズに合わせて独自の設定でリザーブ容量を割り当てる
+
必要な容量は、プライマリボリュームに対するI/O書き込みの頻度とサイズ、およびその容量を維持する必要がある期間によって異なります。一般に、次のいずれかまたは両方に該当する場合は、リザーブ容量を大きくします。

+
***** ミラーペアを長期にわたって維持する場合。
***** 大量のI/Oアクティビティにより、プライマリボリュームのデータブロックの大部分で変更が発生する場合。プライマリボリュームに対する一般的なI/Oアクティビティを判断するには、過去のパフォーマンスデータやその他のオペレーティングシステムユーティリティを使用します。








. [*Complete]を選択します。


.結果
System Managerは次の処理を実行します。

* リモートストレージアレイにセカンダリボリュームが作成され、ミラーペアのリモート側にリザーブ容量が割り当てられます。
* ローカルストレージアレイとリモートストレージアレイの間で初期同期を開始します。
* ミラーリングしているボリュームがシンボリュームの場合、初期同期では、割り当てられたブロックのみがセカンダリボリュームに転送されます。この転送によって、初期同期を完了するために転送する必要があるデータの量が削減されます。
* ローカルストレージアレイとリモートストレージアレイにミラーペア用のリザーブ容量を作成します。

