---
permalink: sm-mirroring/faq-async-mirroring.html 
sidebar: sidebar 
keywords:  
summary: この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。 
---
= SANtricity System Managerの非同期ミラーリングに関するFAQ
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。



== 非同期ミラーリングと同期ミラーリングの違いは何ですか？

非同期ミラーリング機能が同期ミラーリング機能と本質的に違う点は、非同期ミラーリングは特定の時点におけるソースボリュームの状態をキャプチャし、前回のイメージキャプチャ以降に変更されたデータのみをコピーする点です。

同期ミラーリングでは、プライマリボリュームの状態はある時点でキャプチャされるのではなく、プライマリボリューム上で行われたすべての変更がセカンダリボリュームに反映されます。セカンダリボリュームは、プライマリボリュームに書き込みが行われるたびにセカンダリボリュームにも書き込みが行われるため、どの時点においてもプライマリボリュームと同一です。プライマリボリュームで行われた変更でセカンダリボリュームが更新されるまで、ホストは書き込みが成功したという確認応答を受信しません。

非同期ミラーリングでは、リモートストレージアレイとローカルストレージアレイは完全には同期されません。そのため、ローカルストレージアレイの損失によってアプリケーションをリモートストレージアレイに移行する必要がある場合、一部のトランザクションが失われる可能性があります。

ミラーリング機能間の比較：

[cols="1a,1a"]
|===
| 非同期ミラーリング | 同期ミラーリング 


 a| 
*レプリケーション方法*



 a| 
* *ポイントインタイム*
+
ミラーリングはオンデマンドで、またはユーザ定義のスケジュールに従って自動的に行われます。スケジュールは分単位で定義できます。同期の最小間隔は10分です。


 a| 
* *連続*
+
ミラーリングは継続して自動的に実行され、ホストに書き込みがあるたびにデータがコピーされます。





 a| 
*リザーブ容量*



 a| 
* *複数*
+
ミラーペアごとにリザーブ容量ボリュームが1つ必要です。


 a| 
* * シングル *
+
すべてのミラーボリュームに対してリザーブ容量ボリュームが1個必要です。





 a| 
*通信*



 a| 
* * iSCSIおよびファイバ・チャネル*
+
ストレージアレイ間でiSCSIインターフェイスとFibre Channelインターフェイスをサポートします。


 a| 
* *ファイバ・チャネル*
+
ストレージアレイ間でFibre Channelインターフェイスのみをサポートします。





 a| 
*距離*



 a| 
* *無制限*
+
ローカルストレージアレイとリモートストレージアレイの間のサポートされる距離は事実上無制限です。通常は、ネットワークとチャネル拡張テクノロジの機能によってのみ距離が制限されます。


 a| 
* *制限付き*
+
レイテンシおよびアプリケーションパフォーマンスの要件を満たすために、通常はローカルストレージアレイから約10km（6.2マイル）以内とする必要があります。



|===


== 選択したミラーリング機能にアクセスできない場合、どのような理由が考えられますか?

ミラーリングはSANtricity Unified Managerインターフェイスで設定します。

[NOTE]
====
同期ミラーリングは、EF600 / EF600CまたはEF300 / EF300Cストレージアレイでは使用できません。

====
2つのアレイ間のミラーリングを有効にして設定するには、次の点を確認します。

* Web Services Proxyサービスが実行されている必要があります。（Unified Managerは、Web Services Proxyとともにホストシステムにインストールされます）。
* Unified ManagerがHTTPS接続経由でローカルホストで実行されている必要があります。
* ミラーリングに使用する2つのストレージアレイがUnified Managerで検出されている必要があります。
* Unified Managerには、ストレージアレイの有効なSSL証明書が必要です。自己署名証明書を受け入れることも、Unified ManagerからCA署名証明書をインストールすることもできます。


設定手順については、以下を参照してください。

* link:../um-manage/create-asynchronous-mirrored-pair-um.html["非同期ミラーペアの作成（Unified Manager）"]
* link:../um-manage/create-synchronous-mirrored-pair-um.html["同期ミラーペアの作成（Unified Manager）"]




== ミラー整合性グループを作成するときは、どのような点に注意する必要がありますか？

ミラー整合性グループを作成する際は、次のガイドラインに従ってください。

[NOTE]
====
同期ミラーリングは、EF600 / EF600CまたはEF300 / EF300Cストレージシステムでは使用できません。

====
Unified Managerのミラーペアの作成ウィザードで整合性グループを作成しておきます。

Unified Managerに関する次の要件を満たしている必要があります。

* Web Services Proxyサービスが実行されている必要があります。
* Unified ManagerがHTTPS接続経由でローカルホストで実行されている必要があります。
* Unified Managerにストレージアレイの有効なSSL証明書が表示されている必要があります。Unified Managerのメニューから「Certificate Management」に移動し、自己署名証明書を受け入れるか、独自のセキュリティ証明書をインストールできます。


また、ストレージアレイに関する次の要件を満たしていることも確認してください。

* Unified Managerで2つのストレージアレイが検出されている必要があります。
* 各ストレージアレイに2台のコントローラが必要です。
* プライマリアレイとセカンダリアレイの各コントローラにイーサネット管理ポートが設定されていて、各コントローラがネットワークに接続されている必要があります。
* ストレージアレイに必要なファームウェアの最小バージョンは7.84です（それぞれ異なるバージョンのOSを実行できます）。
* ローカルとリモートのストレージアレイのパスワードを確認しておく必要があります。
* ローカルとリモートのストレージアレイをFibre ChannelファブリックまたはiSCSIインターフェイスを介して接続します。




== 非同期ミラーリング-ミラーペアを作成するときは、どのような点に注意する必要がありますか？

ミラーペアはSANtricity Unified Managerインターフェイスで設定し、SANtricity System Managerで管理します。

ミラーペアを作成する際は、次のガイドラインに従ってください。

* 2つのストレージアレイが必要です。
* 各ストレージアレイに2台のコントローラが必要です。
* プライマリアレイとセカンダリアレイの各コントローラにイーサネット管理ポートが設定されていて、各コントローラがネットワークに接続されている必要があります。
* ローカルとリモートのストレージアレイをFibre ChannelファブリックまたはiSCSIインターフェイスを介して接続します。
* ストレージアレイに必要なファームウェアの最小バージョンは7.84です（それぞれ異なるバージョンのOSを実行できます）。
* ローカルとリモートのストレージアレイのパスワードを確認しておく必要があります。
* ミラーリングするプライマリボリューム以上のセカンダリボリュームを作成するには、リモートストレージアレイに十分な空き容量が必要です。
* Web Services ProxyとUnified Managerをインストールしておきます。Unified Managerインターフェイスでミラーペアが設定されている必要があります。
* Unified Managerで2つのストレージアレイが検出されている必要があります。
* ストレージアレイに少なくとも1つのミラー整合性グループが含まれている必要があります。Unified Managerのミラーペアの作成ウィザードで整合性グループを作成しておきます。




== ミラーペアボリュームでリザーブ容量を増やすときは、どのような点に注意する必要がありますか？

通常、ミラーペアのリザーブ容量がフルに近付いているという警告が表示されたときに、リザーブ容量を拡張します。リザーブ容量は8GiB単位でのみ拡張できます。

非同期ミラーリング処理のリザーブ容量は、一般にベースボリュームの20%です。次のいずれかまたは両方に該当する場合は、リザーブ容量を大きくします。

* ミラーペアを長期にわたって維持する場合。
* 大量のI/Oアクティビティにより、プライマリボリュームのデータブロックの大部分で変更が発生する場合。プライマリボリュームに対する一般的なI/Oアクティビティを判断するには、過去のパフォーマンスデータやその他のオペレーティングシステムユーティリティを使用します。


ミラーペアのリザーブ容量を増やすには、次のいずれかの操作を実行します。

* ミラーペアボリュームの容量の割合を調整するには、メニューからStorage（Pool and Volumes Groups）を選択し、* Reserved Capacity *タブをクリックします。
* プールまたはボリュームグループの空き容量を使用して新しいボリュームを作成します。
+
プールまたはボリュームグループに空き容量がない場合は、未設定の容量を未使用ドライブの形式でプールまたはボリュームグループに追加できます。





== リザーブ容量を要求した量で増やせない場合、どのような理由が考えられますか?

リザーブ容量は4GiB単位でのみ拡張できます。

次のガイドラインを確認してください。

* 必要に応じて拡張できるように、プールまたはボリュームグループに十分な空き容量が必要です。
+
プールまたはボリュームグループに空き容量がない場合は、未割り当て容量を未使用ドライブの形式でプールまたはボリュームグループに追加できます。

* プールまたはボリュームグループ内のボリュームのステータスが最適で、変更処理の実行中でないことを確認してください。
* プールまたはボリュームグループに容量の拡張に使用する空き容量が必要です。


非同期ミラーリング処理のリザーブ容量は、一般にベースボリュームの20%です。ベースボリュームで多くの変更が見込まれる場合や、ストレージオブジェクトのコピーサービス処理の使用期間が非常に長くなることが想定される場合は、これよりも割合を増やしてください。



== この割合を変更するのはどのような場合ですか？

リザーブ容量は通常、Snapshot処理の場合はベースボリュームの40%、非同期ミラーリング処理の場合はベースボリュームの20%です。

通常はこの容量で十分です。必要な容量は、ベースボリュームに対するI/O書き込みの頻度とサイズ、およびストレージオブジェクトのコピーサービス処理を使用する期間によって異なります。

一般に、次のいずれかまたは両方に該当する場合は、リザーブ容量の割合を大きくします。

* 特定のストレージオブジェクトのコピーサービス処理の期間が非常に長い場合。
* 大量のI/Oアクティビティにより、ベースボリュームのデータブロックの大部分で変更が発生する場合。ベースボリュームに対する一般的なI/Oアクティビティを判断するには、過去のパフォーマンスデータやその他のオペレーティングシステムユーティリティを使用します。




== リザーブ容量の候補が複数表示されるのはなぜですか？

プールまたはボリュームグループ内にストレージオブジェクトに対して選択した容量の割合を満たす複数のボリュームがある場合は、複数の候補が表示されます。

ベースボリューム上でコピーサービス処理用にリザーブする物理ドライブスペースの割合を変更すると、推奨される候補の一覧が更新されます。選択内容に基づいて最適な候補が表示されます。



== 表に「該当なし」と表示される場合、どのような理由が考えられますか？

リモートストレージアレイにあるデータを表示できない場合は、テーブルにNot availableという値が表示されます。

リモートストレージアレイのデータを表示するには、Unified ManagerからSystem Managerを起動します。



== プールおよびボリューム グループが一部表示されないのはなぜですか?

非同期ミラーペアのセカンダリボリュームを作成するときに、その非同期ミラーペアに使用できるすべてのプールとボリュームグループのリストが表示されます。使用できないプールまたはボリュームグループはリストに表示されません。

以下は、プールまたはボリュームグループを使用できない理由です。

* プールまたはボリュームグループのセキュリティ機能が一致しない。
* プールまたはボリュームグループの状態が最適でない。
* プールまたはボリュームグループの容量が小さすぎる。




== 非同期ミラーリング - ボリュームが一部表示されないのはなぜですか?

ミラーペアのプライマリボリュームを選択すると、対応するすべてのボリュームのリストが表示されます。

使用できないボリュームはリストに表示されません。次のいずれかの理由で、ボリュームが対象外になっている可能性があります。

* 最適状態でない。
* すでにミラー関係に参加している。
* シンボリュームの場合は、自動拡張を有効にする必要があります。



NOTE: EF600およびEF300コントローラでは、非同期ミラーペアのプライマリボリュームとセカンダリボリュームのプロトコル、トレイレベル、セグメントサイズ、セキュリティタイプ、およびRAIDレベルが同じである必要があります。対応していない非同期ミラーペアは、使用可能なボリュームのリストに表示されません。



== 非同期ミラーリング - リモート ストレージ アレイ上のボリュームが一部表示されないのはなぜですか?

リモートストレージアレイ上のセカンダリボリュームを選択すると、そのミラーペアに対応するすべてのボリュームのリストが表示されます。

使用できないボリュームはリストに表示されません。次のいずれかの理由で、ボリュームが対象外になっている可能性があります。

* 最適状態でない。
* すでにミラー関係に参加している。
* シンボリューム属性が、プライマリボリュームとセカンダリボリュームで一致しない。
* Data Assurance（DA）を使用する場合、プライマリボリュームとセカンダリボリュームでDA設定を同じにする必要があります。
+
** プライマリボリュームでDAを有効にする場合、セカンダリボリュームでもDAを有効にする必要があります。
** プライマリボリュームでDAを有効にしない場合、セカンダリボリュームでもDAを無効にする必要があります。






== リモート ストレージ アレイのIPアドレスを更新するのはどのような場合ですか?

リモートストレージアレイのIPアドレスを更新するのは、iSCSIポートのIPアドレスが変わったために、ローカルストレージアレイがリモートストレージアレイと通信できない場合です。

iSCSI接続と非同期ミラーリング関係を確立する際、ローカルおよびリモート両方のストレージアレイは、リモートストレージアレイのIPアドレスを非同期ミラーリング構成に保存します。iSCSIポートのIPアドレスが変わると、そのポートを使用しようとしているリモートストレージアレイで通信エラーが発生します。

IPアドレスが変更されたストレージアレイは、iSCSI接続を介してミラーリングするように設定されたミラー整合性グループに関連付けられている各リモートストレージアレイにメッセージを送信します。このメッセージを受け取ったストレージアレイは、リモートターゲットのIPアドレスを自動的に更新します。

IPアドレスが変更されたストレージアレイがアレイ間メッセージをリモートストレージアレイに送信できない場合は、接続問題 のアラートが送信されます。Update Remote IP Addressオプションを使用して、ローカルストレージアレイとの接続を再確立します。
