---
permalink: sm-mirroring/faq-sync-mirroring.html 
sidebar: sidebar 
keywords:  
summary: この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。 
---
= SANtricity System Managerの同期ミラーリングに関するFAQ
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。



== 非同期ミラーリングと同期ミラーリングの違いは何ですか？

非同期ミラーリング機能が同期ミラーリング機能と本質的に違う点は、非同期ミラーリングは特定の時点におけるソースボリュームの状態をキャプチャし、前回のイメージキャプチャ以降に変更されたデータのみをコピーする点です。

同期ミラーリングでは、プライマリボリュームの状態はある時点でキャプチャされるのではなく、プライマリボリューム上で行われたすべての変更がセカンダリボリュームに反映されます。セカンダリボリュームは、プライマリボリュームに書き込みが行われるたびにセカンダリボリュームにも書き込みが行われるため、どの時点においてもプライマリボリュームと同一です。プライマリボリュームで行われた変更でセカンダリボリュームが更新されるまで、ホストは書き込みが成功したという確認応答を受信しません。

非同期ミラーリングでは、リモートストレージアレイとローカルストレージアレイは完全には同期されません。そのため、ローカルストレージアレイの損失によってアプリケーションをリモートストレージアレイに移行する必要がある場合、一部のトランザクションが失われる可能性があります。

ミラーリング機能間の比較：

[cols="1a,1a"]
|===
| 非同期ミラーリング | 同期ミラーリング 


 a| 
*レプリケーション方法*



 a| 
* *ポイントインタイム*
+
ミラーリングはオンデマンドで、またはユーザ定義のスケジュールに従って自動的に行われます。スケジュールは分単位で定義できます。同期の最小間隔は10分です。


 a| 
* *連続*
+
ミラーリングは継続して自動的に実行され、ホストに書き込みがあるたびにデータがコピーされます。





 a| 
*リザーブ容量*



 a| 
* *複数*
+
ミラーペアごとにリザーブ容量ボリュームが1つ必要です。


 a| 
* * シングル *
+
すべてのミラーボリュームに対してリザーブ容量ボリュームが1個必要です。





 a| 
*通信*



 a| 
* * iSCSIおよびファイバ・チャネル*
+
ストレージアレイ間でiSCSIインターフェイスとFibre Channelインターフェイスをサポートします。


 a| 
* *ファイバ・チャネル*
+
ストレージアレイ間でFibre Channelインターフェイスのみをサポートします。





 a| 
*距離*



 a| 
* *無制限*
+
ローカルストレージアレイとリモートストレージアレイの間のサポートされる距離は事実上無制限です。通常は、ネットワークとチャネル拡張テクノロジの機能によってのみ距離が制限されます。


 a| 
* *制限付き*
+
レイテンシおよびアプリケーションパフォーマンスの要件を満たすために、通常はローカルストレージアレイから約10km（6.2マイル）以内とする必要があります。



|===


== 同期ミラーリング - ボリュームが一部表示されないのはなぜですか?

ミラーペアのプライマリボリュームを選択すると、対応するすべてのボリュームのリストが表示されます。

使用できないボリュームはリストに表示されません。次のいずれかの理由で、ボリュームが対象外になっている可能性があります。

* ボリュームが、Snapshotボリュームやシンボリュームなどの標準以外のボリュームである。
* 最適状態でない。
* すでにミラー関係に参加している。




== 同期ミラーリング - リモート ストレージ アレイのボリュームが一部表示されないのはなぜですか?

リモートストレージアレイ上のセカンダリボリュームを選択すると、そのミラーペアに対応するすべてのボリュームのリストが表示されます。

使用できないボリュームはリストに表示されません。次のいずれかの理由で、ボリュームが対象外になっている可能性があります。

* ボリュームが、Snapshotボリュームやシンボリュームなどの標準以外のボリュームである。
* 最適状態でない。
* すでにミラー関係に参加している。
* Data Assurance（DA）を使用する場合、プライマリボリュームとセカンダリボリュームでDA設定を同じにする必要があります。
+
** プライマリボリュームでDAを有効にする場合、セカンダリボリュームでもDAを有効にする必要があります。
** プライマリボリュームでDAを有効にしない場合、セカンダリボリュームでもDAを無効にする必要があります。






== 同期ミラーリング-ミラーペアを作成するときは、どのような点に注意する必要がありますか？

ミラーペアはSANtricity Unified Managerインターフェイスで設定し、SANtricity System Managerで管理します。

ミラーペアを作成する際は、次のガイドラインに従ってください。

* 2つのストレージアレイが必要です。
* 各ストレージアレイに2台のコントローラが必要です。
* プライマリアレイとセカンダリアレイの各コントローラにイーサネット管理ポートが設定されていて、各コントローラがネットワークに接続されている必要があります。
* ローカルとリモートのストレージアレイをFibre Channelファブリックを介して接続します。
* ストレージアレイに必要なファームウェアの最小バージョンは7.84です（それぞれ異なるバージョンのOSを実行できます）。
* ローカルとリモートのストレージアレイのパスワードを確認しておく必要があります。
* ミラーリングするプライマリボリューム以上のセカンダリボリュームを作成するには、リモートストレージアレイに十分な空き容量が必要です。
* Web Services ProxyとUnified Managerをインストールしておきます。Unified Managerインターフェイスでミラーペアが設定されている必要があります。
* Unified Managerで2つのストレージアレイが検出されている必要があります。




== 同期優先度は同期速度にどのような影響を与えますか？

同期優先度は、同期アクティビティに割り当てられる処理時間をシステムパフォーマンスと比較して決定します。

プライマリボリュームのコントローラ所有者は、この処理をバックグラウンドで実行します。同時にコントローラ所有者は、プライマリボリュームへのローカルのI/O書き込みと、対応するセカンダリボリュームへのリモートの書き込みを処理します。再同期には、I/Oアクティビティに使用されるはずのコントローラの処理リソースが使用されるため、再同期がホストアプリケーションのパフォーマンスに影響する可能性があります。

同期優先度に応じた所要時間や、同期優先度がシステムパフォーマンスに与える影響を特定する際には、次のガイドラインに注意してください。

.同期優先度について
[%collapsible]
====
優先度は次のとおりです。

* 最低
* 低
* 中
* 高
* 最高


最低ではシステムパフォーマンスが優先されますが、再同期化に時間がかかります。最高では再同期化が優先されますが、システムパフォーマンスが低下する可能性があります。

====
これらのガイドラインは、各優先度の大まかな違いを示しています。

[cols="35h,~"]
|===
| 完全同期の優先度 | 最高の同期速度と比較した経過時間 


 a| 
最低
 a| 
最高の優先度であれば、約8倍の時間を要します。



 a| 
低
 a| 
最高の優先度であれば、約6回。



 a| 
中
 a| 
最高の優先度であれば、約3倍から半分。



 a| 
高
 a| 
優先度が最高の場合は、約2倍です。

|===
同期の所要時間には、ボリュームサイズとホストのI/O速度が影響します。



== 手動同期ポリシーの使用が推奨されるのはなぜですか？

手動再同期が推奨されるのは、データがリカバリされる可能性が最も高い方法で再同期プロセスを管理できるためです。

自動再同期ポリシーを使用していて、再同期中に通信が中断する問題が発生した場合は、セカンダリボリューム上のデータが一時的に破損する可能性があります。再同期が完了すると、データは修正されます。
