---
permalink: sm-mirroring/how-does-asynchronous-mirroring-differ-from-synchronous-mirroring-async.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, asysnchronous, mirroring, differ, synchronous, mirroring, 
summary: 非同期ミラーリング機能が同期ミラーリング機能と本質的に違う点は、非同期ミラーリングは特定の時点におけるソースボリュームの状態をキャプチャし、前回のイメージキャプチャ以降に変更されたデータのみをコピーする点です。 
---
= 非同期ミラーリングと同期ミラーリングの違いは何ですか？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
非同期ミラーリング機能が同期ミラーリング機能と本質的に違う点は、非同期ミラーリングは特定の時点におけるソースボリュームの状態をキャプチャし、前回のイメージキャプチャ以降に変更されたデータのみをコピーする点です。

同期ミラーリングでは、プライマリボリュームの状態はある時点でキャプチャされるのではなく、プライマリボリューム上で行われたすべての変更がセカンダリボリュームに反映されます。セカンダリボリュームは、プライマリボリュームに書き込みが行われるたびにセカンダリボリュームにも書き込みが行われるため、どの時点においてもプライマリボリュームと同一です。プライマリボリュームで行われた変更でセカンダリボリュームが更新されるまで、ホストは書き込みが成功したという確認応答を受信しません。

非同期ミラーリングでは、リモートストレージアレイとローカルストレージアレイは完全には同期されません。そのため、ローカルストレージアレイの損失によってアプリケーションをリモートストレージアレイに移行する必要がある場合、一部のトランザクションが失われる可能性があります。

ミラーリング機能間の比較：

[cols="1a,1a"]
|===
| 非同期ミラーリング | 同期ミラーリング 


 a| 
*レプリケーション方法*



 a| 
* *ポイントインタイム*
+
ミラーリングはオンデマンドで、またはユーザ定義のスケジュールに従って自動的に行われます。スケジュールは分単位で定義できます。同期の最小間隔は10分です。


 a| 
* *連続*
+
ミラーリングは継続して自動的に実行され、ホストに書き込みがあるたびにデータがコピーされます。





 a| 
*リザーブ容量*



 a| 
* *複数*
+
ミラーペアごとにリザーブ容量ボリュームが1つ必要です。


 a| 
* * シングル *
+
すべてのミラーボリュームに対してリザーブ容量ボリュームが1個必要です。





 a| 
*通信*



 a| 
* * iSCSIおよびファイバ・チャネル*
+
ストレージアレイ間でiSCSIインターフェイスとFibre Channelインターフェイスをサポートします。


 a| 
* *ファイバ・チャネル*
+
ストレージアレイ間でFibre Channelインターフェイスのみをサポートします。





 a| 
*距離*



 a| 
* *無制限*
+
ローカルストレージアレイとリモートストレージアレイの間のサポートされる距離は事実上無制限です。通常は、ネットワークとチャネル拡張テクノロジの機能によってのみ距離が制限されます。


 a| 
* *制限付き*
+
レイテンシおよびアプリケーションパフォーマンスの要件を満たすために、通常はローカルストレージアレイから約10km（6.2マイル）以内とする必要があります。



|===