---
permalink: sm-mirroring/remove-mirrored-pair.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, remove, asynchronous, mirror, relationship, 
summary: ミラーペアを削除して、ローカルストレージアレイ上のプライマリボリュームとリモートストレージアレイ上のセカンダリボリュームからミラー関係を削除します。 
---
= 非同期ミラー関係を削除します
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ミラーペアを削除して、ローカルストレージアレイ上のプライマリボリュームとリモートストレージアレイ上のセカンダリボリュームからミラー関係を削除します。

.このタスクについて
孤立したミラーペアに関する次の情報を確認します。

* 孤立したミラーペアは、一方（ローカルストレージアレイまたはリモートストレージアレイ）でミラー整合性グループのメンバーボリュームが削除され、もう一方では削除されていない場合に発生します。
* 孤立したミラーペアは、アレイ間の通信がリストアされ、ミラー構成の両サイドでミラーパラメータが調整されたときに検出されます。
* ミラーペアを削除すると、孤立したミラーペアの状態を修正できます。


.手順
. メニューを選択します。Storage [非同期ミラーリング]。
. [ミラーペア*（Mirrored Pair *）]タブを選択します。
+
ミラーペアの表に、ストレージアレイに関連付けられているすべてのミラーペアが表示されます。

. 削除するミラーペアを選択し、* Remove *をクリックします。
. ミラーペアの削除を確認し、* Remove *をクリックします。


.結果
System Managerは次の処理を実行します。

* ローカルストレージアレイ上とリモートストレージアレイ上のミラー整合性グループからミラー関係を削除し、リザーブ容量を削除します。
* ホストがアクセス可能なミラーリングされていないボリュームに、プライマリボリュームとセカンダリボリュームを返します。
* 非同期ミラーペアを削除することで、非同期ミラーリングタイルを更新します。

