---
permalink: sm-mirroring/requirements-for-using-synchronous-mirroring.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, requirements, synchronous, mirroring, 
summary: 同期ミラーリングを使用する場合は、次の要件に注意してください。 
---
= 同期ミラーリングを使用するための要件
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
同期ミラーリングを使用する場合は、次の要件に注意してください。



== Unified Manager の略

2つのアレイ間のミラーリングを有効にして設定するには、Unified Managerインターフェイスを使用する必要があります。Unified Managerは、Web Services Proxyとともにホストシステムにインストールされます。

* Web Services Proxyサービスが実行されている必要があります。
* Unified ManagerがHTTPS接続経由でローカルホストで実行されている必要があります。
* Unified Managerにストレージアレイの有効なSSL証明書が表示されている必要があります。Unified Managerのメニューから「Certificate Management」に移動し、自己署名証明書を受け入れるか、独自のセキュリティ証明書をインストールできます。




== ストレージアレイ

[NOTE]
====
EF300またはEF600ストレージアレイではミラーリングを使用できません。

====
* 2つのストレージアレイが必要です。
* 各ストレージアレイに2台のコントローラが必要です。
* Unified Managerで2つのストレージアレイが検出されている必要があります。
* プライマリアレイとセカンダリアレイの各コントローラにイーサネット管理ポートが設定されていて、各コントローラがネットワークに接続されている必要があります。
* ストレージアレイに必要なファームウェアの最小バージョンは7.84です（それぞれ異なるバージョンのOSを実行できます）。
* ローカルとリモートのストレージアレイのパスワードを確認しておく必要があります。
* ミラーリングするプライマリボリューム以上のセカンダリボリュームを作成するには、リモートストレージアレイに十分な空き容量が必要です。
* ローカルとリモートのストレージアレイをFibre Channelファブリックを介して接続します。




== サポートされる接続

同期ミラーリングの通信は、Fibre Channel（FC）ホストポートを搭載したコントローラでのみサポートされます。

同期ミラーリングでは、ローカルストレージアレイとリモートストレージアレイの両方にある各コントローラで最も大きい番号のホストポートが使用されます。通常、コントローラのホストバスアダプタ（HBA）ホストポート4は、データ送信のミラーリング用に予約されています。



== ミラーボリュームの候補

* 同期ミラーペアのプライマリボリュームとセカンダリボリュームでは、RAIDレベル、キャッシングパラメータ、およびセグメントサイズが異なる場合があります。
* 同期ミラーペアのプライマリボリュームとセカンダリボリュームは、標準ボリュームである必要があります。シンボリュームやSnapshotボリュームは使用できません。
* セカンダリボリュームには、プライマリボリュームと同等以上のサイズが必要です。
* Snapshotを関連付けることができるのはプライマリボリュームのみです。また、ボリュームコピー処理のソースボリュームまたはターゲットボリュームとして使用できるのもプライマリボリュームのみです。
* ボリュームに設定できるミラー関係は1つだけです。
* 特定のストレージアレイでサポートされるボリュームの数には制限があります。ストレージアレイに設定されているボリュームの数がサポートされている制限よりも少ないことを確認してください。同期ミラーリングがアクティブな場合は、作成済みの2つのリザーブ容量ボリュームがボリュームの制限に含まれます。




== リザーブ容量

* コントローラのリセットおよびその他の一時的な中断からリカバリするための書き込み情報をログに記録するには、プライマリボリュームとセカンダリボリュームにリザーブ容量が必要です。
* 同期ミラーリングがアクティブ化されると、リザーブ容量ボリュームが自動的に作成されます。ミラーペアのプライマリボリュームとセカンダリボリュームにはリザーブ容量が必要であるため、同期ミラー関係にある両方のストレージアレイに十分な空き容量が確保されていることを確認してください。




== ドライブセキュリティ機能

* セキュリティ対応ドライブを使用する場合、プライマリボリュームとセカンダリボリュームのセキュリティ設定に互換性がある必要があります。この制限は強制的には適用されないため、自分で確認する必要があります。
* セキュリティ対応ドライブを使用する場合、プライマリボリュームとセカンダリボリュームで同じタイプのドライブを使用する必要があります。この制限は強制的には適用されないため、自分で確認する必要があります。
+
** プライマリボリュームでFull Disk Encryption（FDE）ドライブを使用する場合、セカンダリボリュームでもFDEドライブを使用する必要があります。
** プライマリボリュームで連邦情報処理標準（FIPS）140-2準拠ドライブを使用する場合、セカンダリボリュームでもFIPS 140-2準拠ドライブを使用する必要があります。


* Data Assurance（DA）を使用する場合、プライマリボリュームとセカンダリボリュームでDA設定を同じにする必要があります。

