---
permalink: sm-mirroring/requirements-for-using-asynchronous-mirroring.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, requirements, asynchronous, mirroring, 
summary: 非同期ミラーリングを使用する場合は、次の要件に注意してください。 
---
= 非同期ミラーリングを使用するための要件
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
非同期ミラーリングを使用する場合は、次の要件に注意してください。



== Unified Manager の略

2つのアレイ間のミラーリングを有効にして設定するには、Unified Managerインターフェイスを使用する必要があります。Unified Managerは、Web Services Proxyとともにホストシステムにインストールされます。

* Web Services Proxyサービスが実行されている必要があります。
* Unified ManagerがHTTPS接続経由でローカルホストで実行されている必要があります。
* Unified Managerにストレージアレイの有効なSSL証明書が表示されている必要があります。Unified Managerのメニューから「Certificate Management」に移動し、自己署名証明書を受け入れるか、独自のセキュリティ証明書をインストールできます。




== ストレージアレイ

[NOTE]
====
EF600またはEF300ストレージアレイではミラーリングを使用できません。

====
* 2つのストレージアレイが必要です。
* 各ストレージアレイに2台のコントローラが必要です。
* Unified Managerで2つのストレージアレイが検出されている必要があります。
* プライマリアレイとセカンダリアレイの各コントローラにイーサネット管理ポートが設定されていて、各コントローラがネットワークに接続されている必要があります。
* ストレージアレイに必要なファームウェアの最小バージョンは7.84です（それぞれ異なるバージョンのOSを実行できます）。
* ローカルとリモートのストレージアレイのパスワードを確認しておく必要があります。
* ミラーリングするプライマリボリューム以上のセカンダリボリュームを作成するには、リモートストレージアレイに十分な空き容量が必要です。
* ローカルとリモートのストレージアレイをFibre ChannelファブリックまたはiSCSIインターフェイスを介して接続します。




== サポートされる接続

非同期ミラーリングでは、ローカルとリモートのストレージシステム間の通信にFC接続、iSCSI接続、またはその両方を使用できます。ミラー整合性グループを作成するときに、リモートストレージアレイに対してFCとiSCSIの両方の接続が確立されている場合は、そのグループでどちらを使用するかを選択することができます。あるチャネルタイプから別のチャネルタイプへのフェイルオーバーはありません。

非同期ミラーリングでは、ストレージアレイのホスト側のI/Oポートを使用して、プライマリ側からセカンダリ側にミラーデータが送信されます。

* * Fibre Channel（FC）インターフェイス経由のミラーリング*
+
ストレージアレイの各コントローラでは、最も番号が大きいFCホストポートがミラーリング処理の専用ポートとして使用されます。

+
ベースのFCポートとホストインターフェイスカード（HIC）のFCポートの両方があるコントローラでは、HICの最も番号が大きいポートが使用されます。専用ポートにログオンしたホストはログアウトされ、ホストログイン要求は許可されません。このポートでは、ミラーリング処理の対象となるコントローラからのI/O要求のみが許可されます。

+
専用のミラーリングポートは、ディレクトリサービスとネームサービスのインターフェイスをサポートするFCファブリック環境に接続されている必要があります。特に、FC-ALおよびポイントツーポイントはミラー関係が確立されたコントローラ間の接続オプションとしてサポートされないことに注意してください。

* * iSCSIインターフェイス経由のミラーリング*
+
FCとは異なり、iSCSIでは専用のポートを必要としません。iSCSI環境で非同期ミラーリングを使用する場合、ストレージアレイのどのフロントエンドiSCSIポートも非同期ミラーリング専用にする必要はありません。これらのポートは、非同期ミラーリングのトラフィックとホスト/アレイ間のI/O接続で共有されます。

+
コントローラはリモートストレージシステムのリストを管理しており、iSCSIイニシエータはこのリストを使用してセッションの確立を試みます。iSCSI接続の確立に成功した最初のポートは、そのリモートストレージアレイとの以降のすべての通信に使用されます。通信に失敗すると、使用可能なすべてのポートを使用して新しいセッションの確立が試行されます。

+
iSCSIポートは、アレイレベルでポート単位で設定します。設定メッセージおよびデータ転送用のコントローラ間通信では、次の設定を含むグローバル設定が使用されます。

+
** VLAN：ローカルシステムとリモートシステムが通信するためには、両方のシステムでVLAN設定が同じである必要があります
** iSCSIリスニングポート
** ジャンボフレーム
** イーサネットの優先順位
+
[NOTE]
====
コントローラ間のiSCSI通信には、管理イーサネットポートではなくホスト接続ポートを使用する必要があります。

====


+
非同期ミラーリングでは、ストレージアレイのホスト側のI/Oポートを使用して、プライマリ側からセカンダリ側にミラーデータが送信されます。非同期ミラーリングは高レイテンシで低コストのネットワーク向けの機能であるため、iSCSI接続（TCP / IPベースの接続）が適しています。iSCSI環境で非同期ミラーリングを使用する場合、アレイのどのフロントエンドiSCSIポートも非同期ミラーリング専用にする必要はありません。これらのポートは、非同期ミラーリングのトラフィックとホスト/アレイ間のI/O接続で共有されます





== ミラーボリュームの候補

* 非同期ミラーペアのプライマリボリュームとセカンダリボリュームでは、RAIDレベル、キャッシングパラメータ、およびセグメントサイズが異なる場合があります。
* セカンダリボリュームには、プライマリボリュームと同等以上のサイズが必要です。
* ボリュームに設定できるミラー関係は1つだけです。
* ボリューム候補は、同じ データ セキュリティ 機能を共有している必要があります。
+
** プライマリボリュームがFIPSに対応している場合、セカンダリボリュームはFIPSに対応している必要があります。
** プライマリボリュームがFDEに対応している場合、セカンダリボリュームはFDEに対応している必要があります。
** プライマリボリュームでドライブセキュリティを使用していない場合、セカンダリボリュームでドライブセキュリティを使用していない必要があります。






== リザーブ容量

* コントローラのリセットおよびその他の一時的な中断からリカバリするための書き込み情報をログに記録するには、ミラーペアのプライマリボリュームとセカンダリボリュームにリザーブ容量ボリュームが必要です。
* ミラーペアのプライマリボリュームとセカンダリボリュームには追加のリザーブ容量が必要であるため、ミラー関係にある両方のストレージアレイに空き容量が確保されていることを確認してください。




== ドライブセキュリティ機能

* セキュリティ対応ドライブを使用する場合、プライマリボリュームとセカンダリボリュームのセキュリティ設定に互換性がある必要があります。この制限は強制的には適用されないため、自分で確認する必要があります。
* セキュリティ対応ドライブを使用する場合、プライマリボリュームとセカンダリボリュームで同じタイプのドライブを使用する必要があります。この制限は強制的には適用されないため、自分で確認する必要があります。
* Data Assurance（DA）を使用する場合、プライマリボリュームとセカンダリボリュームでDA設定を同じにする必要があります。

