---
permalink: sm-mirroring/role-change-of-volumes-in-a-mirrored-pair.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, role, change, between, volume, mirrored, pair, 
summary: ミラーペア内のボリューム間でロールを変更できます。ロール変更では、プライマリボリュームをセカンダリロールに降格するか、またはセカンダリボリュームをプライマリロールに昇格できます。 
---
= ミラーペア内のボリューム間でのロール変更
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ミラーペア内のボリューム間でロールを変更できます。ロール変更では、プライマリボリュームをセカンダリロールに降格するか、またはセカンダリボリュームをプライマリロールに昇格できます。

[NOTE]
====
この機能は、EF600またはEF300ストレージシステムでは使用できません。

====
ロール変更処理に関する次の情報を確認してください。

* プライマリボリュームがセカンダリロールに降格されると、そのミラーペア内のセカンダリボリュームがプライマリロールに昇格されます。その逆も同様です。
* プライマリボリュームがセカンダリロールに降格されると、そのボリュームに割り当てられたホストはボリュームへの書き込みアクセスができなくなります。
* セカンダリボリュームがプライマリロールに昇格されると、そのボリュームにアクセスするホストはボリュームに書き込めるようになります。
* ローカルストレージアレイがリモートストレージアレイと通信できない場合は、ローカルストレージアレイで強制的にロールを変更できます。




== 強制的なロール変更

ローカルストレージアレイとリモートストレージアレイ間の通信の問題によってセカンダリボリュームの昇格またはプライマリボリュームの降格を実行できない場合は、ミラーペア内のボリューム間で強制的にロールを変更できます。

セカンダリ側のボリュームを強制的にプライマリロールに移行できます。これで、新しく昇格されたボリュームにリカバリホストがアクセスできるようになり、業務を続行できます。

[NOTE]
====
リモートストレージアレイがリカバリして通信の問題が解決すると、「同期ミラーリング-プライマリボリュームが競合しています」状態が発生します。リカバリ手順にはボリュームの再同期が含まれます。Recovery Guruを使用してこのエラーを解決してください。

====


== 強制昇格が許可される場合と許可されない場合

次の状況では、ミラーペア内のボリュームの強制昇格が許可されません。

* ミラーペア内のいずれかのボリュームが初期同期中である。
* ミラーペアが失敗、Role-Change-Pending、Role-Change-In-Progressのいずれかの状態であるか、関連付けられているいずれかのリザーブ容量ボリュームに障害が発生している。




== ロール変更を実行中です

ミラーリング構成内の2つのストレージアレイの接続が切断されて、ミラーペアのプライマリボリュームが強制的にセカンダリロールに降格され、ミラーペアのセカンダリボリュームが強制的にプライマリロールに昇格されると、 その後、通信が回復すると、両方のストレージアレイのボリュームがRole-Change-In-Progress状態になります。

システムでは、変更ログを転送し、再同期を実行し、ミラーペアを通常の動作状態に戻して、同期を続行することで、ロール変更プロセスを完了します。
