---
permalink: sm-mirroring/role-change-of-a-mirror-consistency-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, role, change, mirror, consistency, group, secondary, mirror, consistency, group, 
summary: ミラー整合性グループ内のミラーペア間でロールを変更できます。ロール変更では、プライマリミラー整合性グループをセカンダリロールに降格するか、またはセカンダリミラー整合性グループをプライマリロールに昇格できます。 
---
= ミラー整合性グループのロール変更
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ミラー整合性グループ内のミラーペア間でロールを変更できます。ロール変更では、プライマリミラー整合性グループをセカンダリロールに降格するか、またはセカンダリミラー整合性グループをプライマリロールに昇格できます。

[NOTE]
====
この機能は、EF600またはEF300ストレージシステムでは使用できません。

====
ロール変更処理に関する次の情報を確認してください。

* ロール変更は、選択したミラー整合性グループ内のすべてのミラーペアに反映されます。
* ミラー整合性グループがセカンダリロールに降格されると、そのミラー整合性グループ内のすべてのミラーペアもセカンダリロールに降格されます。その逆も同様です。
* プライマリミラー整合性グループがセカンダリロールに降格されると、そのグループ内のメンバーボリュームに割り当てられたホストはボリュームへの書き込みアクセスができなくなります。
* ミラー整合性グループがプライマリロールに昇格されると、そのグループ内のメンバーボリュームにアクセスするホストはボリュームに書き込めるようになります。
* ローカルストレージアレイがリモートストレージアレイと通信できない場合は、ローカルストレージアレイで強制的にロールを変更できます。




== 強制的なロール変更

ローカルストレージアレイとリモートストレージアレイ間の通信の問題によってセカンダリミラー整合性グループ内のメンバーボリュームの昇格またはプライマリミラー整合性内のメンバーボリュームの降格を実行できない場合は、ミラー整合性グループ間で強制的にロールを変更できます グループ：

セカンダリ側のミラー整合性グループを強制的にプライマリロールに移行できます。これで、そのミラー整合性グループ内の新しく昇格されたメンバーボリュームにリカバリホストがアクセスできるようになり、業務を続行できます。



== 強制昇格が許可される場合と許可されない場合

ミラー整合性グループの強制昇格が許可されるのは、ミラー整合性グループのすべてのメンバーボリュームが同期されていて、一貫したリカバリポイントがある場合のみです。

次の状況では、ミラー整合性グループの強制昇格が許可されません。

* ミラー整合性グループのいずれかのメンバーボリュームが初期同期中である。
* （フルリザーブ容量エラーなどが原因で）ミラー整合性グループのいずれかのメンバーボリュームにリカバリポイントのポイントインタイムイメージがない。
* ミラー整合性グループにメンバーボリュームが含まれていない。
* ミラー整合性グループが失敗、Role-Change-Pending、Role-Change-In-Progressのいずれかの状態であるか、関連付けられているいずれかのメンバーボリュームまたはリザーブ容量ボリュームに障害が発生している。




== ミラーグループのロールの競合

ローカルストレージアレイとリモートストレージアレイ間の通信の問題が解決すると、Mirror Group Role Conflict状態が発生します。Recovery Guruを使用してこのエラーを解決してください。二重ロールの競合の解決時に、強制昇格は許可されません。

Mirror Group Role Conflict状態を回避して、後続のリカバリ手順を行わないようにするには、ストレージアレイ間の接続が回復するまで待ってから強制的にロールを変更してください。



== ロール変更を実行中です

ミラーリング構成内の2つのストレージアレイの接続が切断されて、ミラー整合性グループのプライマリ側が強制的にセカンダリロールに降格され、ミラー整合性グループのセカンダリ側が強制的にプライマリロールに昇格されると、 その後、通信が回復すると、両方のストレージアレイのミラー整合性グループがRole-Change-In-Progress状態になります。

システムでは、変更ログを転送し、再同期を実行し、ミラー整合性グループを通常の動作状態に戻して、定期的な同期を続行することで、ロール変更プロセスを完了します。
