---
permalink: sm-mirroring/suspend-or-resume-mirror-consistency-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, suspend, resume, synchronization, mirror, consistency, group, 
summary: ミラー整合性グループ内のすべてのミラーペアでデータの同期を中断または再開できます。これは、個々のミラーペアで同期を中断または再開するよりも効率的です。 
---
= ミラー整合性グループの同期を中断または再開します
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ミラー整合性グループ内のすべてのミラーペアでデータの同期を中断または再開できます。これは、個々のミラーペアで同期を中断または再開するよりも効率的です。

.このタスクについて
グループでの同期を中断および再開すると、ホストアプリケーションのパフォーマンスへの影響を軽減できます。このパフォーマンスへの影響は、ローカルストレージアレイで変更されたデータがリモートストレージアレイにコピーされる間に発生する可能性があります。

ミラー整合性グループとそのミラーペアは、再開オプションを使用して同期アクティビティを再開するまで中断されたままになります。

.手順
. メニューを選択します。Storage [非同期ミラーリング]。
. [ミラー整合性グループ*（Mirror Consistency Groups *）]タブを選択します。
+
ミラー整合性グループテーブルが表示され、ストレージアレイに関連付けられているすべてのミラー整合性グループが表示されます。

. 中断または再開するミラー整合性グループを選択し、メニュー：その他[中断]またはメニュー：その他[再開]を選択します。
+
確認メッセージが表示されます。

. 「*はい*」を選択して確定します。


.結果
System Managerは次の処理を実行します。

* ミラー関係を削除せずに、ミラー整合性グループ内のすべてのミラーペア間のデータ転送を中断または再開します。
* ミラーグループの中断中にミラー整合性グループのプライマリ側に書き込まれたデータをログに記録し、ミラーグループが再開されたときにミラー整合性グループのセカンダリ側にデータを自動的に書き込みます。完全同期は必要ありません。
* a_suspended_mirror整合性グループの場合、Mirror Consistency Groupsテーブルに* user-suspended *が表示されます。
* 再開されたミラー整合性グループでは、ミラー整合性グループの中断中にプライマリボリュームに書き込まれたデータがセカンダリボリュームにただちに書き込まれます。自動同期間隔が設定されている場合は、定期的な同期が再開されます。

