---
permalink: sm-mirroring/synchronous-mirroring-status.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, synchronous, mirroring, status, 
summary: 同期ミラーペアのステータスは、プライマリボリュームとセカンダリボリュームのデータが同期されているかどうかを示します。ミラーステータスは、ミラーペアに含まれるボリュームのコンポーネントステータスとは無関係です。 
---
= 同期ミラーリングのステータス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
同期ミラーペアのステータスは、プライマリボリュームとセカンダリボリュームのデータが同期されているかどうかを示します。ミラーステータスは、ミラーペアに含まれるボリュームのコンポーネントステータスとは無関係です。

[NOTE]
====
この機能は、EF600またはEF300ストレージシステムでは使用できません。

====
同期ミラーペアは、次のいずれかのステータスになります。

* *最適*
+
ミラーペア内のボリュームが同期されていることを示します。つまり、ストレージアレイ間のファブリック接続が機能しており、各ボリュームが想定される動作状態になっています。

* *同期中*
+
ミラーペア間のデータ同期の進捗状況が表示されます。このステータスは、初期同期中にも表示されます。

+
通信リンクの中断後、リンクの中断中にプライマリボリュームで変更されたデータのブロックだけがセカンダリボリュームにコピーされます。

* *非同期*
+
プライマリボリュームのストレージアレイがリモートアレイに受信データを書き込めないことを示します。ローカルホストは引き続きプライマリボリュームへの書き込みを行うことができますが、リモートでの書き込みは行われません。次に示すような別の条件によって、プライマリボリュームのストレージアレイがセカンダリボリュームに受信データを書き込めなくなる場合があります。

+
** セカンダリボリュームにアクセスできない。
** リモートストレージアレイにアクセスできません。
** ストレージアレイ間のファブリック接続にアクセスできません。
** 新しいWorld Wide Identifier（WWID）を使用してセカンダリボリュームを更新できない。


* *一時停止*
+
同期ミラーリング処理がユーザによって中断されたことを示します。ミラーペアが中断されると、セカンダリボリュームへの接続は試行されなくなります。プライマリボリュームへの書き込みは、ミラーのリザーブ容量ボリュームに永続的に記録されます。

* *失敗*
+
プライマリボリューム、セカンダリボリューム、またはミラーのリザーブ容量の障害が原因で、同期ミラーリング処理を正常に実行できないことを示します。


