---
permalink: sm-mirroring/test-communication-for-mirror-consistency-groups.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, test, communication, mirror, consistency, groups, 
summary: 通信リンクをテストして、ミラー整合性グループに関連付けられているローカルストレージアレイとリモートストレージアレイ間の通信に関する潜在的な問題を診断できます。 
---
= ミラー整合性グループの通信をテストする
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通信リンクをテストして、ミラー整合性グループに関連付けられているローカルストレージアレイとリモートストレージアレイ間の通信に関する潜在的な問題を診断できます。

.作業を開始する前に
テスト対象のミラー整合性グループがローカルストレージアレイとリモートストレージアレイ上に存在する必要があります。

.このタスクについて
次の4つのテストを実行できます。

* *接続*-- 2台のコントローラに通信パスがあることを確認します接続テストでは、ストレージアレイ間でメッセージを送信して、リモートストレージアレイに対応するミラー整合性グループが存在するかどうかを検証します。また、リモートストレージアレイ上のミラー整合性グループメンバーボリュームがローカルストレージアレイ上のミラー整合性グループメンバーボリュームと一致するかどうかも検証します。
* * Latency *--ミラー整合性グループに関連付けられたリモートストレージアレイ上の各ミラーボリュームにSCSI Test Unitコマンドを送信して、最小、平均、最大のレイテンシをテストします。
* *bandwidth*-- 2つのアレイ間メッセージをリモートストレージアレイに送信して、最小、平均、最大の帯域幅、およびテストを実行しているアレイ上のポートのネゴシエートされたリンク速度をテストします。
* *ポート接続*--ローカルストレージアレイ上のミラーリングに使用されているポート'およびリモートストレージアレイ上のミラーデータを受信しているポートを表示します


.手順
. メニューを選択します。Storage [非同期ミラーリング]。
. ミラー整合性グループ*タブを選択し、テストするミラー整合性グループを選択します。
. [*通信のテスト*]を選択します。
+
[通信のテスト]ダイアログボックスが表示されます。

. 選択したミラー整合性グループに関連付けられているローカルとリモートのストレージアレイ間で実行する通信テストを1つ以上選択し、* Test *をクリックします。
. 結果ウィンドウに表示された情報を確認します。
+
[cols="35h,~"]
|===
| 通信テストのステータス | 説明 


 a| 
正常。エラーはありません
 a| 
ミラー整合性グループが正常に通信しています。



 a| 
合格（ただし、正常ではない）
 a| 
ネットワークまたは接続に問題がないかどうかを確認してから、もう一度テストを実行してください。



 a| 
失敗ステータス
 a| 
エラーの理由が示されます。問題を修正するには、Recovery Guruを参照してください。



 a| 
ポートの接続エラーです
 a| 
ローカルストレージアレイが接続されていないか、リモートストレージアレイに接続できないことが原因である可能性があります。問題を修正するには、Recovery Guruを参照してください。

|===


.結果
通信テストが完了すると、このダイアログボックスに正常、パス、失敗のいずれかのステータスが表示されます。

通信テストから失敗ステータスが返された場合は、このダイアログボックスを閉じたあとで、ミラー整合性グループ間の通信が復旧するまでテストが続行されます。
