---
permalink: sm-mirroring/volume-ownership-async.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, volume, ownership, async, change, preferred, controller, owner, mirrored, pair, 
summary: ミラーペア内の優先コントローラ所有者を変更できます。 
---
= ボリューム所有権
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ミラーペア内の優先コントローラ所有者を変更できます。

[NOTE]
====
この機能は、EF600またはEF300ストレージシステムでは使用できません。

====
ミラーペアのプライマリボリュームがコントローラAに所有されている場合、セカンダリボリュームもリモートストレージアレイのコントローラAに所有されます。プライマリボリュームの所有者を変更すると、両方のボリュームが同じコントローラで所有されるようにセカンダリボリュームの所有者も自動的に変更されます。プライマリ側で現在の所有権が変更されると、セカンダリ側の対応する所有権も自動的に変更されます。

たとえば、コントローラAに所有されているプライマリボリュームの所有コントローラをコントローラBに変更したとしますこの場合、次回のリモート書き込みで、セカンダリボリュームの所有コントローラがコントローラAからコントローラBに切り替わりますセカンダリ側のコントローラ所有権の切り替えはプライマリ側で制御されるため、ストレージ管理者による特別な対応は必要ありません。



== コントローラがリセットされます

コントローラをリセットすると、プライマリ側でボリューム所有権が優先コントローラ所有者からストレージアレイ内の別のコントローラに変更されます。

セカンダリボリュームへのリモート書き込みが行われる前に、コントローラのリセットまたはストレージアレイの電源の再投入によってリモート書き込みが中断されることがあります。この場合、コントローラはミラーペアの完全な同期を実行する必要はありません。

コントローラのリセット中にリモートでの書き込みが中断されると、プライマリ側の新しいコントローラ所有者は、優先コントローラ所有者のリザーブ容量ボリューム内のログファイルに格納された情報を読み取ります。その後、新しいコントローラ所有者は、影響を受けたデータブロックをプライマリボリュームからセカンダリボリュームにコピーします。そのため、ミラーボリュームの完全な同期が不要になります。
