---
permalink: sm-mirroring/workflow-for-mirroring-a-volume-asynchronously.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, workflow, mirroring, asynchronously, 
summary: 次のワークフローを使用して非同期ミラーリングを設定します。 
---
= ボリュームを非同期でミラーリングするためのワークフロー
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
次のワークフローを使用して非同期ミラーリングを設定します。

[NOTE]
====
この機能は、EF600またはEF300ストレージシステムでは使用できません。

====
. Unified Managerで初期設定を実行します。
+
.. データ転送元としてローカルストレージアレイを選択します。
.. ミラー整合性グループを作成するか、既存のミラー整合性グループを選択します。ミラー整合性グループは、ローカルアレイのプライマリボリュームとリモートアレイのセカンダリボリュームのコンテナです。プライマリボリュームとセカンダリボリュームは「ミラーペア」と呼ばれます。 ミラー整合性グループを初めて作成する場合は、手動同期とスケジュールされた同期のどちらを実行するかを指定します。
.. ローカルストレージアレイからプライマリボリュームを選択し、リザーブ容量を確認します。リザーブ容量は、コピー処理に使用される物理割り当て容量です。
.. 転送先としてリモートストレージアレイを選択し、セカンダリボリュームを選択して、リザーブ容量を確認します。
.. プライマリボリュームからセカンダリボリュームへの初回のデータ転送を開始します。ボリュームサイズによっては、この初回転送に数時間かかることがあります。


. 初期同期の進捗状況を確認します。
+
.. Unified Managerで、ローカルアレイのSystem Managerを起動します。
.. System Managerで、ミラーリング処理のステータスを確認します。ミラーリングが完了すると、ミラーペアのステータスは「最適」になります。


. *オプション：*以降のデータ転送については、System Managerでスケジュールを再設定したり、手動で実行したりできます。新しいブロックと変更されたブロックのみがプライマリボリュームからセカンダリボリュームに転送されます。
+
[NOTE]
====
非同期レプリケーションは定期的に行われるため、システムでは変更されたブロックを統合してネットワーク帯域幅を節約できます。書き込みスループットと書き込みレイテンシへの影響は最小限に抑えられます。

====

