---
permalink: sm-interface/administrator-password-protection.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, admin password 
summary: ストレージアレイには、不正なアクセスを防ぐために管理者パスワードを設定する必要があります。 
---
= パスワード保護を管理します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイには、不正なアクセスを防ぐためにパスワードを設定する必要があります。



== パスワードを設定および変更する

System Managerを初めて起動したときは、管理者パスワードの設定を求めるプロンプトが表示されます。管理者パスワードを持つユーザは、オブジェクトや設定の追加、変更、削除など、ストレージアレイの設定を変更できます。初回起動時に管理者パスワードを設定するには、を参照してください link:../san-getstarted/access-sam.html["System Managerにアクセスします"]。

セキュリティ上の理由から、パスワードの入力を試行できるのは5回までとなっており、この回数を超えるとストレージアレイは「ロックアウト」状態になります。この状態のストレージアレイは以降のパスワード入力を拒否します。パスワードを再度入力するには、ストレージアレイが「通常」状態にリセットされるまで10分間待つ必要があります。

adminパスワードに加えて、ストレージアレイには、1つ以上のロールがマッピングされた事前定義済みのユーザプロファイルが含まれています。詳細については、を参照してください link:../sm-settings/permissions-for-mapped-roles.html["マッピングされたロールの権限"]。ユーザプロファイルとマッピングは変更できません。変更できるのはパスワードだけです。adminパスワードまたはその他のユーザパスワードを変更する場合は、を参照してください link:../sm-settings/change-passwords.html["パスワードを変更します"]。



== セッションタイムアウト後にパスワードを再入力します

1つの管理セッションでパスワードの入力を求められるのは1回のみです。ただし、操作を行わないまま30分が経過するとセッションはタイムアウトし、パスワードをもう一度入力する必要があります。セッション中に別の管理クライアントから同じストレージアレイを管理している別のユーザがパスワードを変更した場合は、次回の設定処理や表示処理でパスワードの入力を求められます。

セッションタイムアウトを調整したり、セッションタイムアウトを無効にしたりできます。を参照してください link:../sm-settings/manage-session-timeouts-sam.html["セッションタイムアウトの管理"]。



== ドライブまたはパスワード保護を削除します

パスワードで保護されたドライブを取り外す場合やパスワードで保護されたドライブを無効にする場合は、次の点に注意してください。

* *パスワード保護が設定されたドライブを取り外すと、パスワードはストレージアレイの各ドライブの予約領域に保存されます。ストレージアレイからすべてのドライブを取り外すと、そのパスワードは使用できなくなります。この状況を修正するには、元のドライブの1つをストレージアレイに再度取り付けます。
* *パスワード保護を解除する場合*--コマンドのパスワード保護を解除する場合は'現在の管理者パスワードを入力し'新しいパスワードのテキストボックスを空白のままにします


[CAUTION]
====
ストレージアレイで設定コマンドを実行すると、原因 がデータ損失などの深刻な損害を受ける可能性があります。このため、ストレージアレイには常に管理者パスワードを設定する必要があります。セキュリティを強化するには、英数字15文字以上の管理者パスワードを使用してください。

====