---
permalink: sm-interface/faq-management-interface.html 
sidebar: sidebar 
keywords:  
summary: この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。 
---
= SANtricity System Manager の管理インターフェースに関する FAQ
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。



== サポートされているブラウザ

SANtricity System Managerでは、次のバージョンのブラウザがサポートされます。

[cols="1a,1a"]
|===
| ブラウザ | 最小バージョン 


 a| 
Google Chrome
 a| 
120



 a| 
Mozilla Firefox
 a| 
120



 a| 
Safari
 a| 
16



 a| 
Microsoft Edge の場合
 a| 
120

|===


== どのようなキーボードショートカットを使用できますか？

SANtricityシステムマネージャは、キーボードだけを使用して操作できます。



=== 全体的なナビゲーション

[cols="1a,1a"]
|===
| アクション | キーボードショートカット 


 a| 
次の項目に移動する。
 a| 
タブをクリックする



 a| 
前の項目に移動する。
 a| 
Shift + Tabキーを押します



 a| 
アイテムを選択します。
 a| 
入力するコマンド



 a| 
ドロップダウンリスト--次のアイテムまたは前のアイテムに移動します
 a| 
下矢印または上矢印



 a| 
チェックボックス--アイテムを選択します
 a| 
スペースキー



 a| 
ラジオボタン--項目を切り替える
 a| 
下矢印または上矢印



 a| 
拡張可能なテキスト--項目を展開または縮小します。
 a| 
入力するコマンド

|===


=== テーブルナビゲーション

[cols="1a,1a"]
|===
| アクション | キーボードショートカット 


 a| 
行を選択します。
 a| 
Tabキーを押して行を選択し、Enterキーを押します



 a| 
上または下にスクロールします。
 a| 
下矢印/上矢印またはPage Down / Page Up



 a| 
列のソート順序を変更します。
 a| 
Tabキーを押して列見出しを選択し、Enterキーを押します

|===


=== カレンダーのナビゲーション

[cols="1a,1a"]
|===
| アクション | キーボードショートカット 


 a| 
前の月に移動する。
 a| 
ページアップしてください



 a| 
次の月に移動する。
 a| 
ページダウン



 a| 
前の年に移動する。
 a| 
Ctrl + Page Upキーを押します



 a| 
次の年に移動する。
 a| 
Ctrl + Page Downキーを押します



 a| 
閉じている場合は日付ピッカーを開きます。
 a| 
Ctrl + Homeキー



 a| 
現在の月に移動する。
 a| 
Ctrl / Command + Home



 a| 
前の日に移動する。
 a| 
Ctrl / Command +左矢印



 a| 
次の日に移動する。
 a| 
Ctrl / Command +右矢印をクリックします



 a| 
前の週に移動する。
 a| 
Ctrl / Command +上矢印



 a| 
次の週に移動する。
 a| 
Ctrl / Command +下矢印



 a| 
フォーカスした日付を選択します。
 a| 
入力するコマンド



 a| 
日付ピッカーを閉じて日付を消去します。
 a| 
Ctrl / Command + End



 a| 
選択せずに日付ピッカーを閉じます。
 a| 
エスケープ

|===


== 個々のボリュームのパフォーマンス統計と合計値との関係はどうなっていますか？

プールとボリュームグループの統計は、リザーブ容量用ボリュームを含むすべてのボリュームの集計によって計算されます。

リザーブ容量は、シンボリューム、Snapshot、非同期ミラーリングをサポートするためにストレージシステムによって内部的に使用され、I/Oホストには表示されません。そのため、プール、コントローラ、およびストレージアレイの統計は、表示可能なボリュームの合計ではない場合があります。

ただし、アプリケーションとワークロードの統計については、表示されるボリュームのみが集計されます。



== グラフや表にデータがゼロと表示されるのはなぜですか？

グラフや表のデータポイントにゼロと表示される場合は、その時点でオブジェクトのI/Oアクティビティがないことを意味します。ホストがそのオブジェクトへのI/Oを開始していないか、オブジェクト自体に問題がある可能性があります。

オブジェクトの履歴データは引き続き表示できます。オブジェクトのI/Oアクティビティが発生すると、ゼロ以外のデータがグラフと表に表示されます。

次の表に、特定のオブジェクトのデータポイント値がゼロになる最も一般的な理由を示します。

[cols="25h,~"]
|===
| アレイレベルのオブジェクトタイプ | データがゼロと表示される理由 


 a| 
ボリューム
 a| 
* ボリュームにホストが割り当てられていない。




 a| 
ボリュームグループ
 a| 
* ボリュームグループがインポート中である。
* ボリュームグループにホストに割り当てられているボリュームがありません。*_と_*のボリュームグループにリザーブ容量が含まれていません。




 a| 
ドライブ
 a| 
* ドライブで障害が発生している。
* ドライブが取り外されている。
* ドライブの状態が不明である。




 a| 
コントローラ
 a| 
* コントローラがオフラインです。
* コントローラで障害が発生している。
* コントローラが取り外されている。
* コントローラの状態が不明である。




 a| 
ストレージアレイ
 a| 
* ストレージアレイにボリュームが含まれていません。


|===


== レイテンシグラフにはどのような情報が表示されますか？

レイテンシーグラフは、ボリューム、ボリュームグループ、プール、アプリケーション、ワークロードごとのレイテンシー統計情報をミリ秒（ms）単位で表示します。このグラフは、論理ビュー、物理ビュー、アプリケーションとワークロードビューの各タブに表示されます。

レイテンシとは、データの読み取りや書き込みが行われるときに発生する遅延のことです。グラフの特定のポイントにカーソルを合わせると、その時点における次の値（ミリ秒）が表示されます。

* 読み取り時間
* 書き込み時間
* 平均I/Oサイズ




== IOPSグラフには何が表示されますか？

IOPSグラフは、1秒あたりの入出力操作数の統計情報を表示します。ホームページでは、このグラフにストレージアレイの統計情報が表示されます。パフォーマンスページの論理ビュー、物理ビュー、アプリケーションとワークロードビューの各タブでは、このグラフにストレージアレイ、ボリューム、ボリュームグループ、プール、アプリケーション、ワークロードの統計情報が表示されます。

IOPSは、1秒あたりの入出力（I/O）処理数の略です。グラフの特定のポイントにカーソルを合わせると、その時点における次の値が表示されます。

* 読み取り処理の数
* 書き込み処理の数
* 読み取り処理と書き込み処理の合計数




== MiB/秒グラフには何が表示されますか。

MiB/sグラフは、転送速度の統計情報を1秒あたりのメビバイト単位で表示します。ホームページでは、このグラフにストレージアレイの統計情報が表示されます。パフォーマンスページの論理ビュー、物理ビュー、アプリケーションとワークロードビュータブでは、このグラフにストレージアレイ、ボリューム、ボリュームグループ、プール、アプリケーション、ワークロードの統計情報が表示されます。

MiB/秒は、1秒あたりのメビバイト数、つまり1秒あたり1、048、576バイト数です。グラフの特定のポイントにカーソルを合わせると、その時点における次の値が表示されます。

* 読み取られたデータの量
* 書き込まれたデータの量
* 読み取られたデータと書き込まれたデータの合計量




== CPUのグラフは何を示していますか。

CPUグラフは、各コントローラ（コントローラAとコントローラB）の処理能力統計を表示します。CPUは_central processing unit_の略です。ホームページでは、このグラフにストレージアレイの統計情報が表示されます。パフォーマンスページの物理ビュータブには、ストレージアレイとドライブの統計情報を示すグラフが表示されます。

CPUグラフには、アレイでの処理に対して使用されているCPU処理容量の割合が表示されます。外部I/Oが発生していないときでもCPU利用率がゼロにならないことがあります。これは、ストレージオペレーティングシステムがバックグラウンドで処理や監視を実行しているためです。グラフの特定のポイントにカーソルを合わせると、その時点における使用中の処理能力の割合が表示されます。



== ヘッドルームグラフには何が表示されますか？

ヘッドルームグラフは、ストレージアレイコントローラの残存性能能力に関連しています。このグラフは、ホームページとパフォーマンスページの物理ビュータブに表示されます。

ヘッドルームグラフには、ストレージシステム内の物理オブジェクトの残りのパフォーマンス容量が表示されます。グラフの特定のポイントにカーソルを合わせると、その時点におけるコントローラAとコントローラBの残りのIOPSおよびMiB/秒容量の割合が表示されます



== 表示環境設定に関する詳しい情報は、どこで入手できますか。

使用可能な表示オプションに関する情報を検索するには、次の手順に従います。

* 容量値を表示する際のデフォルトの単位については、を参照してください link:set-default-units-for-capacity-values.html["容量値のデフォルトの単位を設定します"]。
* パフォーマンスグラフを表示する際のデフォルト期間については、を参照してください link:set-default-time-frame-for-performance-graphs.html["パフォーマンスグラフのデフォルト期間を設定します"]。

