---
permalink: sm-interface/faq-storage-system-setup.html 
sidebar: sidebar 
keywords:  
summary: この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。 
---
= SANtricity System Managerのストレージシステムセットアップに関するFAQ
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。



== 一部のハードウェア コンポーネントが表示されない場合はどうすればよいですか?

ハードウェアの検証ダイアログボックスにすべてのハードウェアコンポーネントが表示されない場合は、ドライブシェルフが正しく接続されていないか、ストレージアレイに互換性のないシェルフが設置されている可能性があります。

すべてのドライブシェルフが正しく接続されていることを確認します。互換性のあるドライブシェルフが不明な場合は、テクニカルサポートにお問い合わせください。



== すべてのホストが表示されない場合はどうすればよいですか?

接続されているホストが表示されない場合は、自動検出に失敗したか、ホストが正しく接続されていないか、または現在接続されているホストがありません。

ホストの設定は、セットアップの完了後に実行できます。ホストを手動で作成するには、次の手順を実行します。

* ホストを手動で作成し、次のメニューから適切なホストポート識別子を関連付けることができます：Storage [Hosts]。手動で作成したホストは、*初期セットアップ*ウィザードにも表示されます。
* 自動検出が機能するためには、ターゲットとホストにホストポートタイプ（iSCSIやNVMe over RoCEなど）が設定されていて、ストレージへのセッションが確立されている必要があります。




== アプリケーションを特定するとストレージアレイの管理にどのように役立ちますか？

アプリケーションを特定すると、アプリケーションタイプに基づいてストレージを最適化するボリューム構成がSANtricity System Managerによって自動的に提示されます。

アプリケーションによってボリュームを最適化することで、データストレージの処理効率を高めることができます。ボリューム構成には、I/Oタイプ、セグメントサイズ、コントローラ所有権、読み取りと書き込みのキャッシュなどの特性が含まれます。また、アプリケーションごと、ワークロードごとにパフォーマンスデータを表示して、アプリケーションおよび関連するワークロードのレイテンシ、IOPS、MiB/秒を評価できます。



== ワークロードとは何ですか？

SQL ServerやExchangeなど、ネットワーク内の一部のアプリケーションについては、そのアプリケーション用のストレージを最適化するワークロードを定義できます。

ワークロードは、アプリケーションをサポートするストレージオブジェクトです。アプリケーションごとに1つ以上のワークロードまたはインスタンスを定義できます。一部のアプリケーションでは、特性が似たボリュームで構成されるようにワークロードが設定されます。これらのボリューム特性は、ワークロードがサポートするアプリケーションのタイプに基づいて最適化されます。たとえば、Microsoft SQL Serverアプリケーションをサポートするワークロードを作成し、そのワークロード用のボリュームを作成すると、Microsoft SQL Serverをサポートするようにボリューム特性が最適化されます。

ボリュームの作成時には、ワークロードの用途について回答 から質問するプロンプトが表示されます。たとえば、Microsoft Exchange用のボリュームを作成する場合は、必要なメールボックスの数、メールボックスに必要とされる平均容量、およびデータベースのコピーをいくつ作成するかについて設定します。この情報に基づいて最適なボリューム構成が作成されるため、必要に応じて編集することができます。



== AutoSupport の配信方法を設定するにはどうすればよいですか？

AutoSupport 配信方法の設定タスクにアクセスするには、[Support]（サポートセンター）のメニューに移動し、AutoSupport *]タブをクリックします。

サポートされているプロトコルはHTTPSとSMTPです。



== 推奨されるプール構成を承認するかどうかを判断するにはどうすればよいですか？

推奨されるプール構成を承認するかどうかは、いくつかの要因によって決まります。

次の質問に答えて、要件に最も適したストレージのタイプを特定します。

* できるだけ大きいプールではなく、容量の小さいプールを複数使用することを希望しますか？
* プールよりもRAIDボリュームグループを使用することを希望しますか？
* 推奨される構成を使用するのではなく、ドライブを手動でプロビジョニングすることを希望しますか？


これらのいずれかの質問に対する「はい」と答えた場合は、推奨されるプール構成を拒否することを検討してください。



== SANtricity System Managerでホストが検出されませんでした。どうすればいいですか？

接続されているホストが表示されない場合は、自動検出に失敗したか、ホストが正しく接続されていないか、または現在接続されているホストがありません。

ホストの設定は、セットアップの完了後に実行できます。ホストを手動で作成するには、次の手順を実行します。

* ホストを手動で作成し、次のメニューから適切なホストポート識別子を関連付けることができます：Storage [Hosts]。手動で作成したホストは、*初期セットアップ*ウィザードにも表示されます。
* 自動検出が機能するためには、ターゲットとホストにホストポートタイプ（iSCSIやNVMe over RoCEなど）が設定されていて、ストレージへのセッションが確立されている必要があります。

