---
permalink: sm-interface/overview-interface-sam.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, 
summary: メインインターフェイスに移動すると、System Managerの機能やタスクにアクセスできます。 
---
= SANtricity System Managerインターフェースについて学ぶ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SANtricity System Managerは、ストレージアレイを単一のビューで管理できるWebベースのインターフェイスです。



== ホームページ

ホームページには、ストレージアレイの日々の管理を行うためのダッシュボードビューが表示されます。System Managerにログインすると、最初に表示される画面がホームページになります。

ダッシュボードビューは、ストレージアレイの状態と健全性に関する重要な情報を含む3つの概要領域で構成されています。概要領域から詳細情報を確認できます。

[cols="25h,~"]
|===
| 面積（ Area ） | 説明 


 a| 
パフォーマンス
 a| 
Performance領域では、時間の経過に伴うリソース使用量を比較したり、対比したりできます。応答時間（IOPS）、転送速度（MiB/秒）、使用中の処理能力（CPU）に関して、ストレージアレイのパフォーマンス指標を表示できます。



 a| 
容量
 a| 
容量領域には、ストレージアレイ内の割り当て済み容量、空きストレージ容量、および割り当てられていないストレージ容量のグラフが表示されます。



 a| 
ストレージ階層
 a| 
ストレージ階層領域には、ストレージアレイで管理されるさまざまなハードウェアコンポーネントとストレージオブジェクトがまとめて表示されます。ドロップダウン矢印をクリックして、そのハードウェアコンポーネントまたはストレージオブジェクトに対して特定の操作を実行します。

|===


== 通知エリア

通知エリアは、ウィンドウの右上隅にあるベルのアイコンからアクセスできます。通知エリアには、ストレージアレイとそのコンポーネントのステータスを示す問題通知が表示されます。さらに、このセクションでは、ストレージ環境の他の領域に影響が及ぶ前に問題をトラブルシューティングするのに役立つ自動アラートが表示されます。



== インターフェイスの設定

メインインターフェイスから表示環境設定やその他の設定を変更できます。



== ユーザログインとパスワード

現在システムにログインしているユーザーは、ユーザー設定に表示されます。

ユーザとパスワードの詳細については、次の項を参照してください。

* link:administrator-password-protection.html["管理者パスワード保護を設定します"]
* link:../sm-settings/change-passwords.html["パスワードを変更します"]

