---
permalink: sm-interface/overview-interface-sam.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, 
summary: メインインターフェイスに移動すると、System Managerの機能やタスクにアクセスできます。 
---
= System Managerインターフェイスの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
System ManagerはWebベースのインターフェイスで、ストレージアレイを1つのビューで管理できます。



== ホームページ

ホームページには、ストレージアレイの日々の管理を行うためのダッシュボードビューが表示されます。System Managerにログインすると、最初に表示される画面がホームページになります。

ダッシュボードビューは4つの概要領域で構成されており、ストレージアレイの状態と健常性に関する重要な情報が表示されます。詳細については、サマリー領域を参照してください。

[cols="25h,~"]
|===
| 面積（ Area ） | 説明 


 a| 
通知
 a| 
通知領域には、ストレージアレイとそのコンポーネントのステータスを示す問題通知が表示されます。また、自動アラートが表示され、ストレージ環境の他の領域に影響が及ぶ前に問題をトラブルシューティングできます。



 a| 
パフォーマンス
 a| 
Performance領域では、時間の経過に伴うリソース使用量を比較したり、対比したりできます。応答時間（IOPS）、転送速度（MiB/秒）、使用中の処理能力（CPU）に関して、ストレージアレイのパフォーマンス指標を表示できます。



 a| 
容量
 a| 
容量領域には、ストレージアレイ内の割り当て済み容量、空きストレージ容量、および割り当てられていないストレージ容量のグラフが表示されます。



 a| 
ストレージ階層
 a| 
ストレージ階層領域には、ストレージアレイで管理されるさまざまなハードウェアコンポーネントとストレージオブジェクトがまとめて表示されます。ドロップダウン矢印をクリックして、そのハードウェアコンポーネントまたはストレージオブジェクトに対して特定の操作を実行します。

|===


== インターフェイスの設定

メインインターフェイスから表示環境設定やその他の設定を変更できます。

[cols="25h,~"]
|===
| 設定 | 説明 


 a| 
表示環境設定
 a| 
インターフェイスの右上にあるPreferencesドロップダウンから容量の値と期間を変更します。



 a| 
セッションタイムアウト
 a| 
非アクティブな状態が一定の時間続いたユーザセッションは切断されるようにタイムアウトを設定します。



 a| 
ヘルプ
 a| 
インターフェイスの右上にあるドロップダウンからヘルプドキュメントやその他のリソースにアクセスできます。

|===


== ユーザログインとパスワード

システムにログインしている現在のユーザが、インターフェイスの右上に表示されます。

ユーザとパスワードの詳細については、次の項を参照してください。

* link:administrator-password-protection.html["管理者パスワード保護を設定します"]
* link:../sm-settings/change-passwords.html["パスワードを変更します"]

