---
permalink: sm-interface/recover-from-problems-using-recovery-guru.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, Recovery Guru 
summary: Recovery GuruはSystem Managerのコンポーネントです。ストレージアレイの問題を診断し、問題を修正するリカバリ手順を推奨します。 
---
= SANtricity System Manager Recovery Guruを使用して問題から回復する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Recovery GuruはSANtricity System Managerのコンポーネントです。ストレージアレイの問題を診断し、問題を解決するためのリカバリ手順を推奨します。

.手順
. 「* Home *」を選択します。
. ウィンドウの中央上部にある*Recover from_n_problems *というリンクをクリックします。
+
Recovery Guruダイアログボックスが表示されます。

. 概要リストに表示されている最初の問題を選択し、リカバリ手順 の手順に従って問題を修正します。必要に応じて、交換手順を使用して障害のあるコンポーネントを交換します。表示された問題ごとに、この手順を繰り返します。
+
ストレージアレイ内の複数の問題が関連している場合があります。この場合、問題を修正する順序が結果に影響する可能性があります。概要リストに表示されている順序で問題を選択して修正します。

+
電源装置キャニスターに複数の障害がある場合、概要リストには1つの問題としてまとめて表示されます。ファンキャニスターの複数の障害も1つの問題として表示されます。

. リカバリ手順 が正常に完了したことを確認するには、*再チェック*をクリックします。
+
非同期ミラーグループまたは非同期ミラーグループのメンバーに問題を選択した場合は、最初に* Clear *をクリックしてコントローラの障害を解消し、次に* Check *をクリックしてRecovery Guruからイベントを削除します。

+
すべての問題が修正されると、ストレージアレイのアイコンは最終的に要注意から最適に変わります。一部の問題では、再構築などの処理の実行中に修正中のアイコンが表示されます。

. *オプション：Recovery Guruの情報をファイルに保存するには、*保存*アイコンをクリックします。
+
このファイルは'recovery-guru -yyyy-mm-dd-hh-mm-smm.html'という名前でブラウザのDownloadsフォルダに保存されます

. Recovery Guruの情報を印刷するには、*印刷*アイコンをクリックします。

