---
permalink: sm-interface/setup-wizard-overview.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, setup wizard 
summary: セットアップウィザードを使用して、ハードウェア、ホスト、アプリケーション、ワークロード、 プール、アラート、およびAutoSupport 。 
---
= セットアップウィザードの概要
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
セットアップウィザードを使用して、ハードウェア、ホスト、アプリケーション、ワークロード、 プール、アラート、およびAutoSupport 。



== 初回セットアップ

System Managerを初めて開いたときは、セットアップウィザードが起動します。セットアップウィザードでは、画面の指示に従って、ストレージアレイの名前の設定、ホストの設定、アプリケーションの選択、ストレージのプールの作成など、基本的な設定タスクを実行します。


NOTE: 初期セットアップを続行する前に、アップグレードセンター（メニュー：サポート[Upgrade Center]）に移動し、SANtricity OSソフトウェアが最新であることを確認します。必要に応じて、最新バージョンにアップグレードし、ブラウザを更新してセットアップを続行します。詳細については、を参照してください link:../sm-support/overview-upgrade-center.html["Upgrade Centerの概要"]。

ウィザードをキャンセルした場合、手動で再起動することはできません。ウィザードは、 System Manager を開くかブラウザを更新したときに、次の条件の少なくとも 1 つに該当していれば自動的に再度起動されます。

* プールとボリュームグループが検出されていません。
* ワークロードが検出されていません。
* 通知が設定されていません。




== 用語集

セットアップウィザードでは、次の用語を使用します。

[cols="25h,~"]
|===
| 期間 | 説明 


 a| 
アプリケーション
 a| 
アプリケーションは、Microsoft SQL ServerやMicrosoft Exchangeなどのソフトウェアプログラムです。



 a| 
アラート
 a| 
アラートは、ストレージアレイで発生した重要なイベントについて管理者に通知します。Eメール、SNMPトラップ、またはsyslogを使用してアラートを送信できます。



 a| 
AutoSupport
 a| 
AutoSupport 機能は、ストレージアレイの健常性を監視し、テクニカルサポートに自動ディスパッチを送信します。



 a| 
ハードウェア
 a| 
ストレージシステムハードウェアには、ストレージアレイ、コントローラ、およびドライブが含まれます。



 a| 
ホスト
 a| 
ホストは、ストレージアレイ上のボリュームにI/Oを送信するサーバです。



 a| 
オブジェクト
 a| 
オブジェクトとは、任意の論理または物理ストレージコンポーネントのことです。論理オブジェクトには、ボリュームグループ、プール、ボリュームがあります。物理オブジェクトには、ストレージアレイ、アレイコントローラ、ホスト、ドライブがあります。



 a| 
プール
 a| 
プールは、論理的にグループ化された一連のドライブです。プールを使用して、ホストにアクセス可能な 1 つ以上のボリュームを作成することができます。（ボリュームはプールまたはボリュームグループから作成します）。



 a| 
ボリューム
 a| 
ボリュームは、アプリケーション、データベース、およびファイルシステムがデータを格納するコンテナです。ホストがストレージアレイのストレージにアクセスするために作成される論理コンポーネントです。

ボリュームは、プールまたはボリュームグループの使用可能な容量から作成します。ボリュームごとに容量が定義されています。ボリュームが複数のドライブで構成される場合でも、ホスト側では1つの論理コンポーネントとして認識され、



 a| 
ボリュームグループ
 a| 
ボリュームグループは、同じ特性を持つボリュームのコンテナです。ボリュームグループごとに容量とRAIDレベルが定義されています。ボリュームグループを使用して、ホストにアクセス可能な1つ以上のボリュームを作成することができます。（ボリュームはボリュームグループまたはプールから作成します）。



 a| 
ワークロード
 a| 
ワークロードは、アプリケーションをサポートするストレージオブジェクトです。アプリケーションごとに1つ以上のワークロードまたはインスタンスを定義できます。一部のアプリケーションでは、特性が似たボリュームで構成されるようにワークロードが設定されます。これらのボリューム特性は、ワークロードがサポートするアプリケーションのタイプに基づいて最適化されます。たとえば、Microsoft SQL Serverアプリケーションをサポートするワークロードを作成し、そのワークロード用のボリュームを作成すると、Microsoft SQL Serverをサポートするようにボリューム特性が最適化されます。

|===