---
permalink: sm-interface/view-storage-hierarchy.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, storage hierarchy 
summary: メインインターフェイスのストレージ階層には、ストレージアレイで管理される各種ハードウェアコンポーネントとストレージオブジェクトがまとめて表示されます。 
---
= ストレージ階層を表示します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
メインインターフェイスのストレージ階層には、ストレージアレイで管理される各種ハードウェアコンポーネントとストレージオブジェクトがまとめて表示されます。

ストレージ階層を表示するには、ホームページに移動し、ストレージアレイコンポーネントまたはストレージオブジェクトのドロップダウン矢印をクリックします。ストレージアレイは、物理コンポーネントと論理コンポーネントの両方の集合で構成されます。



== 物理コンポーネント

次の表では、ストレージアレイの物理コンポーネントについて説明します。

[cols="25h,~"]
|===
| コンポーネント | 説明 


 a| 
コントローラ
 a| 
コントローラは、ボード、ファームウェア、ソフトウェアで構成されます。ドライブを制御し、 System Manager の機能を実装します。



 a| 
シェルフ
 a| 
シェルフは、キャビネットまたはラックに設置されるエンクロージャです。ストレージアレイのハードウェアコンポーネントを収容します。シェルフには、コントローラシェルフとドライブシェルフの 2 種類があります。コントローラシェルフは、コントローラとドライブを収容します。ドライブシェルフは、入出力モジュール（ IOM ）とドライブを収容します。

[NOTE]
====
ストレージアレイのメディアタイプやインターフェイスタイプが異なる場合は、ドライブタイプごとにドライブシェルフが表示されます。

====


 a| 
ドライブ
 a| 
ドライブは、データ用の物理ストレージメディアとして使用される電磁的な機械デバイスまたはソリッドステートメモリデバイスです。



 a| 
ホスト
 a| 
ホストは、ストレージアレイ上のボリュームにI/Oを送信するサーバです。



 a| 
ホストバスアダプタ（HBA）
 a| 
ホストバスアダプタ（HBA）はホストに搭載されるボードで、1つ以上のホストポートが搭載されています。



 a| 
ホストポート
 a| 
ホストポートは、コントローラに物理的に接続されるホストバスアダプタ（HBA）のポートで、I/O処理に使用されます。



 a| 
管理クライアント
 a| 
管理クライアントは、System Managerにアクセスするためのブラウザがインストールされたコンピュータです。

|===


== 論理構成要素

ストレージアレイ内のドライブは、データに対して物理ストレージ容量を提供します。System Managerを使用して、プール、ボリュームグループ、ボリュームなどの論理コンポーネントに物理容量を割り当てます。これらのコンポーネントは、ストレージアレイ上のデータの設定、格納、メンテナンス、および保持に使用するツールです。次の表では、ストレージアレイの論理コンポーネントについて説明します。

[cols="25h,~"]
|===
| コンポーネント | 説明 


 a| 
プール
 a| 
プールは、論理的にグループ化された一連のドライブです。プールを使用して、ホストにアクセス可能な 1 つ以上のボリュームを作成することができます。（ボリュームはプールまたはボリュームグループから作成します）。



 a| 
ボリュームグループ
 a| 
ボリュームグループは、同じ特性を持つボリュームのコンテナです。ボリュームグループごとに容量とRAIDレベルが定義されています。ボリュームグループを使用して、ホストにアクセス可能な1つ以上のボリュームを作成することができます。（ボリュームはボリュームグループまたはプールから作成します）。



 a| 
ボリューム
 a| 
ボリュームは、アプリケーション、データベース、およびファイルシステムがデータを格納するコンテナです。ホストがストレージアレイのストレージにアクセスするために作成される論理コンポーネントです。



 a| 
Logical Unit Number（LUN；論理ユニット番号）
 a| 
Logical Unit Number（LUN；論理ユニット番号）は、ホストがボリュームへのアクセスに使用する番号で、アドレススペースに割り当てられます。ボリュームは、LUNの形式でホストに容量として提示されます。

各ホストには独自のLUNアドレススペースがあります。したがって、同じLUNを複数のホストで使用して、異なるボリュームにアクセスできます。

|===