---
permalink: sm-hardware/allow-remote-login.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, remote, login, 
summary: リモートログインを使用すると、ローカルエリアネットワーク外のユーザがコントローラ上でSSHセッションを開始し、設定を変更できます。 
---
= リモートログイン（SSH）の設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
リモートログインを有効にすると、ローカルエリアネットワーク外のユーザがコントローラ上でSSHセッションを開始し、設定にアクセスできるようになります。

SANtricity バージョン11.74以降では、SSHキーやSSHパスワードの入力をユーザに求めることで、多要素認証（MFA）を設定することもできます。SANtricity バージョン11.73以前の場合、この機能には、SSHキーとパスワードを使用した多要素認証のオプションは含まれません。

[CAUTION]
====
*セキュリティ上のリスク*--セキュリティ上の理由から、リモートログイン機能を使用するのはテクニカルサポート担当者だけにしてください。

====
.手順
. 「 * ハードウェア * 」を選択します。
. 図にドライブが表示されている場合は、 * シェルフの背面を表示 * をクリックします。
+
図の表示が切り替わり、ドライブではなくコントローラが表示されます。

. リモートログインを設定するコントローラをクリックします。
+
コントローラのコンテキストメニューが表示されます。

. Configure remote login (SSH)*を選択します。（SANtricity バージョン11.73以前の場合、このメニュー項目は*リモートログインの変更*です）。
+
リモートログインを有効にするためのダイアログボックスが表示されます。

. [リモートログインを有効にする*]チェックボックスをオンにします。
+
この設定では、リモートログインに次の3つの許可オプションが提供されます。

+
** *パスワードのみ*。このオプションでは、完了し、[保存（Save）]をクリックできます。デュプレックスシステムの場合は、前の手順に従って、2台目のコントローラでリモートログインを有効にできます。
** * SSHキーまたはパスワード*。このオプションについては、次の手順に進みます。
** *パスワードとSSHキー*の両方。このオプションでは、[リモートログインに許可された公開鍵とパスワードを要求する*]チェックボックスをオンにして、次の手順に進みます。


. [*Authorized public key*]フィールドに値を入力します。このフィールドには、OpenSSH * authorized_keys *ファイルの形式の、許可された公開鍵のリストが含まれます。
+
[*Authorized public key*]フィールドに入力する場合は、次のガイドラインに注意してください。

+
** Authorized Public Key *フィールド環境 は両方のコントローラを対象としており、1台目のコントローラでのみ構成する必要があります。
** authorized_keys *ファイルには、1行に1つのキーのみを含める必要があります。#で始まる行と空白行は無視されます。ファイル形式の詳細については、を参照してください link:https://www.ssh.com/academy/ssh/authorized-keys-openssh["OpenSSHの認証済みキーの設定"^]。
** *authorized_keys *ファイルは、次の例のようになります。
+
[listing]
----
ssh-rsa
AAAAB3NzaC1yc2EAAAADAQABAAABAQDJlG20rYTk4ok+xFjkPHYp/R0LfJqEYDLXA5AJ49w3DvAWLrUg+1CpNq76WSqmQBmoG9jgbcAB5ABGdswdeMQZHilJcu29iJ3OKKv6SlCulAj1tHymwtbdhPuipd2wIDAQAB
----


. 完了したら、*保存*をクリックします。
. デュプレックスシステムでは、上記の手順に従って、2台目のコントローラでリモートログインを有効にできます。パスワードとSSHキーの両方のオプションを設定する場合は、「*リモートログインに許可された公開鍵とパスワードを要求する*」チェックボックスを再度選択してください。
. テクニカルサポートのトラブルシューティングが完了したら、リモートログインの設定ダイアログボックスに戻り、*リモートログインを有効にする*チェックボックスの選択を解除することで、リモートログインを無効にできます。2台目のコントローラでリモートログインが有効になっている場合は、確認ダイアログが開き、2台目のコントローラでもリモートログインを無効にできます。
+
リモートログインを無効にすると、現在のSSHセッションがすべて終了し、新しいログイン要求はすべて拒否されます。


