---
permalink: sm-hardware/configure-iscsi-ports-hardware.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, iscsi, ports, 
summary: コントローラにiSCSIホスト接続が搭載されている場合は、ハードウェアページでiSCSIポートを設定できます。 
---
= iSCSIポートを設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コントローラにiSCSIホスト接続が搭載されている場合は、ハードウェアページでiSCSIポートを設定できます。

.作業を開始する前に
* コントローラにiSCSIポートが搭載されている必要があります。そうでない場合、iSCSI設定は使用できません。
* ネットワーク速度（ポートとホストの間のデータ転送率）を把握しておく必要があります。


[NOTE]
====
iSCSIの設定および機能は、ストレージアレイでiSCSIがサポートされている場合にのみ表示されます。

====
.手順
. 「 * ハードウェア * 」を選択します。
. 図にドライブが表示されている場合は、 * シェルフの背面を表示 * をクリックします。
+
図の表示が切り替わり、ドライブではなくコントローラが表示されます。

. iSCSI ポートを設定するコントローラをクリックします。
+
コントローラのコンテキストメニューが表示されます。

. Configure iSCSI Port* （ iSCSI ポートの設定）を選択します。
+
[NOTE]
====
Configure iSCSI Ports *オプションは、System ManagerがコントローラでiSCSIポートを検出した場合にのみ表示されます。

====
+
Configure iSCSI Ports （ iSCSI ポートの設定）ダイアログボックスが開きます。

. ドロップダウンリストで、設定するポートを選択し、 * Next * をクリックします。
. 構成ポートの設定を選択し、 * 次へ * をクリックします。
+
すべてのポート設定を表示するには、ダイアログボックスの右側にある * Show more port settings * リンクをクリックします。

+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| ポートの設定 | 説明 


 a| 
設定されたイーサネットポート速度（特定のタイプのホストインターフェイスカードでのみ表示）
 a| 
ポートのSFPの速度と同じ速度を選択します。



 a| 
Forward Error Correction（FEC;前方誤り訂正）モード（特定のタイプのホストインターフェイスカードでのみ表示）
 a| 
必要に応じて、指定したホストポートのいずれかのFECモードを選択します。


NOTE: Reed Solomonモードは、25Gbpsポート速度をサポートしていません。



 a| 
IPv4 を有効にする / IPv6 を有効にする
 a| 
一方または両方のオプションを選択して、 IPv4 ネットワークと IPv6 ネットワークのサポートを有効にします。


NOTE: ポートへのアクセスを無効にする場合は、両方のチェックボックスを選択解除します。



 a| 
TCP リスニングポート（ [Show more port settings] をクリックすると使用可能）
 a| 
必要に応じて、新しいポート番号を入力します。

リスニングポートは、コントローラがホスト iSCSI イニシエータからの iSCSI ログインをリスンするために使用する TCP ポート番号です。デフォルトのリスニングポートは 3260 です。3260 、または 49152~65535 の値を入力する必要があります。



 a| 
MTU サイズ（ * Show more port settings* をクリックすると使用可能）
 a| 
必要に応じて、 Maximum Transmission Unit （ MTU ；最大伝送ユニット）の新しいサイズをバイト単位で入力します。

デフォルトの Maximum Transmission Unit （ MTU ；最大転送単位）サイズは 1500 バイト / フレームです。1500~9000 の値を入力する必要があります。



 a| 
ICMP PING 応答を有効にします
 a| 
Internet Control Message Protocol （ ICMP ）を有効にする場合は、このオプションを選択します。ネットワーク接続されたコンピュータのオペレーティングシステムは、このプロトコルを使用してメッセージを送信します。ICMP メッセージを送信することで、ホストに到達できるかどうかや、そのホストとのパケットの送受信にどれくらいの時間がかかるかが確認されます。

|===
====
+
[*IPv4 を有効にする *] を選択した場合は、 [ 次へ *] をクリックすると、 IPv4 設定を選択するためのダイアログボックスが開きます。[*IPv6 を有効にする *] を選択した場合、 [ 次へ *] をクリックすると、 IPv6 設定を選択するためのダイアログボックスが開きます。両方のオプションを選択した場合は、 IPv4 設定のダイアログボックスが最初に開き、 * 次へ * をクリックすると、 IPv6 設定のダイアログボックスが開きます。

. IPv4 と IPv6 、またはその両方を自動または手動で設定します。すべてのポート設定を表示するには、ダイアログボックスの右側にある * Show more settings * リンクをクリックします。
+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| ポートの設定 | 説明 


 a| 
自動的に設定を取得します
 a| 
設定を自動的に取得するには、このオプションを選択します。



 a| 
静的な設定を手動で指定します
 a| 
このオプションを選択した場合は、フィールドに静的アドレスを入力します。（必要に応じて、住所をカットアンドペーストしてフィールドに貼り付けることもできます）。 IPv4の場合は、ネットワークのサブネットマスクとゲートウェイも指定します。IPv6 の場合は、ルーティング可能な IP アドレスとルータの IP アドレスも指定します。



 a| 
VLAN サポートを有効にします（ * Show more settings * をクリックして使用可能）。
 a| 
VLAN を有効にしてその ID を入力する場合は、このオプションを選択します。VLAN は、同じスイッチ、同じルータ、またはその両方でサポートされる他の物理 LAN （ローカルエリアネットワーク）および仮想 LAN から物理的に分離されたように動作する論理ネットワークです。



 a| 
イーサネットの優先順位を有効にする（ [ 詳細設定を表示する *] をクリックして使用可能）。
 a| 
ネットワークアクセスの優先度を決定するパラメータを有効にする場合は、このオプションを選択します。スライダを使用して優先度を1（最も低い）から7（最も高い）の間で選択します。

共有 LAN 環境（イーサネットなど）では、多数のステーションがネットワークアクセスで競合する可能性があります。アクセスは先に行われたものから順に処理されます。2 つのステーションが同時にネットワークにアクセスしようとすると、両方のステーションがオフになり、再試行するまで待機します。スイッチイーサネットでは、 1 つのステーションだけがスイッチポートに接続されるため、このプロセスは最小限に抑えられます。

|===
====
. [ 完了 ] をクリックします。

