---
permalink: sm-hardware/configure-dns-server-addresses.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, dns, server, addresses, 
summary: ドメインネームシステム（DNS）は、コントローラとネットワークタイムプロトコル（NTP）サーバの完全修飾ドメイン名を解決するために使用されます。ストレージアレイの管理ポートは、IPv4プロトコルとIPv6プロトコルを同時にサポートできます。 
---
= SANtricity System ManagerでDNSサーバーアドレスを構成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ドメインネームシステム（DNS）は、コントローラとネットワークタイムプロトコル（NTP）サーバの完全修飾ドメイン名を解決するために使用されます。ストレージアレイの管理ポートは、IPv4プロトコルとIPv6プロトコルを同時にサポートできます。

.作業を開始する前に
* ネットワークにDNSサーバをインストールし、設定する必要があります。
* プライマリDNSサーバとオプションのバックアップDNSサーバのアドレスを確認しておきます。IPv4アドレスでもIPv6アドレスでもかまいません。


.このタスクについて
この手順 では、プライマリおよびバックアップのDNSサーバアドレスを指定する方法について説明します。バックアップDNSサーバは、プライマリDNSサーバで障害が発生した場合に使用するようにオプションで設定できます。

[NOTE]
====
ストレージアレイの管理ポートを動的ホスト構成プロトコル（DHCP）ですでに設定し、かつ1つ以上のDNSサーバまたはNTPサーバをDHCPセットアップに関連付けている場合は、DNSまたはNTPを手動で設定する必要がありません。この場合、DNS / NTPサーバのアドレスはストレージアレイによってすでに自動的に検出されているはずです。ただし、次の手順に従ってダイアログボックスを開き、正しいアドレスが検出されていることを確認してください。

====
.手順
. 「 * ハードウェア * 」を選択します。
. 図にドライブが表示された場合は、*[コントローラとコンポーネント]*タブをクリックします。
+
図の表示が切り替わり、ドライブではなくコントローラが表示されます。

. 設定するコントローラを選択します。
+
コントローラのコンテキストメニューが表示されます。

. [Configure DNS server*]を選択します。
+
ドメインネームシステム（DNS）サーバの設定ダイアログボックスが開きます。

. 次のいずれかのオプションを選択します。
+
** *DHCPサーバから自動的にDNSサーバアドレスを取得*--検出されたDNSサーバアドレスが表示されます
+
[NOTE]
====
静的DNSアドレスを使用するようにストレージアレイが設定されている場合、DNSサーバは表示されません。

====
** *DNSサーバアドレスを手動で指定する*--プライマリDNSサーバのアドレスとバックアップDNSサーバのアドレスを入力しますバックアップサーバはオプションです。（これらのアドレスフィールドは、ラジオボタンを選択すると表示されます）。 IPv4アドレスでもIPv6アドレスでもかまいません。


. [ 保存（ Save ） ] をクリックします。
. もう一方のコントローラに対して上記の手順を繰り返します。


.結果
DNS設定は、コントローラ設定の* DNS/NTP *タブに表示されます。
