---
permalink: sm-hardware/configure-ntp-server-addresses.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, ntp, server, addresses, network, time, protocol, 
summary: ネットワークタイムプロトコル（NTP）サーバへの接続を設定すると、コントローラがNTPサーバを定期的に照会して内部のクロックを更新できるようになります。 
---
= NTPサーバアドレスを設定する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ネットワークタイムプロトコル（NTP）サーバへの接続を設定すると、コントローラがNTPサーバを定期的に照会して内部のクロックを更新できるようになります。

.作業を開始する前に
* ネットワークにNTPサーバをインストールし、設定する必要があります。
* プライマリNTPサーバとオプションのバックアップNTPサーバのアドレスを確認しておく必要があります。これらのアドレスには、完全修飾ドメイン名、IPv4アドレス、またはIPv6アドレスを使用できます。


[NOTE]
====
NTPサーバのドメイン名を1つ以上入力した場合は、NTPサーバアドレスを解決するようにDNSサーバも設定する必要があります。DNSサーバの設定が必要となるのは、NTPを設定してドメイン名を指定したコントローラだけです。

====
.このタスクについて
NTPを設定すると、ストレージアレイがSimple Network Time Protocol（SNTP）を使用してコントローラのクロックを外部ホストと自動的に同期できるようになります。コントローラは設定されたNTPサーバを定期的に照会し、その結果を使用して内部のクロックを更新します。一方のコントローラだけでNTPが有効になっている場合、代替コントローラのクロックはNTPが有効なコントローラと定期的に同期されます。どちらのコントローラでもNTPが有効になっていない場合は、定期的にコントローラ間で相互にクロックが同期されます。

[NOTE]
====
両方のコントローラでNTPを設定する必要はありませんが、設定しておくことで、ハードウェア障害や通信障害が発生した場合にストレージアレイの同期度が向上します。

====
.手順
. 「 * ハードウェア * 」を選択します。
. 図にドライブが表示されている場合は、 * シェルフの背面を表示 * をクリックします。
+
図の表示が切り替わり、ドライブではなくコントローラが表示されます。

. 設定するコントローラをクリックします。
+
コントローラのコンテキストメニューが表示されます。

. Configure NTP server（NTPサーバーの設定）*を選択します。
+
Configure Network Time Protocol（NTP）Server（ネットワークタイムプロトコル（NTP）サーバの設定）ダイアログボックスが開きます。

. [* I want to enable NTP on Controller *（* A * or * B *）]を選択します。
+
ダイアログボックスにその他の選択項目が表示されます。

. 次のいずれかのオプションを選択します。
+
** * DHCPサーバからNTPサーバアドレスを自動的に取得*--検出されたNTPサーバアドレスが表示されます
+
[NOTE]
====
静的なNTPアドレスを使用するようにストレージアレイが設定されている場合、NTPサーバは表示されません。

====
** * NTPサーバ・アドレスを手動で指定*--プライマリNTPサーバ・アドレスとバックアップNTPサーバ・アドレスを入力しますバックアップサーバはオプションです。（これらのアドレスフィールドは、ラジオボタンを選択すると表示されます）。 サーバアドレスは、完全修飾ドメイン名、IPv4アドレス、またはIPv6アドレスのいずれかで指定できます。


. *オプション：*バックアップNTPサーバのサーバ情報と認証クレデンシャルを入力します。
. [ 保存（ Save ） ] をクリックします。


.結果
NTPサーバの設定は、コントローラの設定の* DNS/NTP *タブに表示されます。
