---
permalink: sm-hardware/considerations-for-assigning-ip-addresses.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, considerations, assigning, ip, addresses 
summary: デフォルトでは、コントローラは両方のネットワークポートでDHCPを有効にした状態で出荷されます。静的IPアドレスを割り当てるか、デフォルトの静的IPアドレスを使用するか、またはDHCPによって割り当てられたIPアドレスを使用できます。IPv6のステートレス自動設定を使用することもできます。 
---
= IPアドレスの割り当てに関する考慮事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
デフォルトでは、コントローラは両方のネットワークポートでDHCPを有効にした状態で出荷されます。静的IPアドレスを割り当てるか、デフォルトの静的IPアドレスを使用するか、またはDHCPによって割り当てられたIPアドレスを使用できます。IPv6のステートレス自動設定を使用することもできます。

[NOTE]
====
IPv6は新しいコントローラではデフォルトで無効になっています。ただし、別の方法で管理ポートのIPアドレスを設定し、そのあとにSystem Managerを使用して管理ポートで有効にすることができます。

====
ネットワークポートが「リンク停止」状態（LANから切断された状態）の場合、システムは設定を静的と報告してIPアドレスとして0.0.0.0を表示するか（以前のリリース）、DHCPが有効と報告してIPアドレスを表示しないか（新しいリリース）のどちらかです。ネットワークポートが「リンク稼働」状態（LANに接続されている状態）になると、DHCP経由でIPアドレスの取得が試行されます。

コントローラの特定のネットワークポートでDHCPアドレスを取得できない場合はデフォルトのIPアドレスに戻りますが、これには最大3分かかることがあります。デフォルトのIPアドレスは次のとおりです。

[listing]
----
Controller 1 (port 1): IP Address: 192.168.128.101
----
[listing]
----
Controller 1 (port 2): IP Address: 192.168.129.101
----
[listing]
----
Controller 2 (port 1): IP Address: 192.168.128.102
----
[listing]
----
Controller 2 (port 2): IP Address: 192.168.129.102
----
IPアドレスを割り当てる場合は、次の点に

* コントローラのポート2はカスタマーサポート用に予約します。デフォルトのネットワーク設定（DHCPが有効な状態）を変更しないでください。
* E2800およびE5700のコントローラに静的IPアドレスを設定するには、SANtricity System Managerを使用します。E2700およびE5600のコントローラに静的IPアドレスを設定するには、SANtricity Storage Managerを使用します。静的IPアドレスの設定後は、リンク停止/稼働イベントが発生しても設定が維持されます。
* DHCPを使用してコントローラのIPアドレスを割り当てるには、DHCP要求を処理できるネットワークにコントローラを接続します。永続的なDHCPリースを使用してください。
+
[NOTE]
====
デフォルトアドレスは、リンク停止イベントが発生すると失われます。コントローラのネットワークポートがDHCPを使用するように設定されている場合、ケーブルの差し込み、リブート、電源の再投入など、リンク稼働イベントのたびにDHCPアドレスの取得が試行されます。DHCPの試行に失敗した場合は、そのポートのデフォルトの静的IPアドレスが使用されます。

====

