---
permalink: sm-hardware/controller-states.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, controller, states, 
summary: コントローラには、オンライン、オフライン、およびサービスモードの3種類の状態があります。 
---
= コントローラの状態
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コントローラには、オンライン、オフライン、およびサービスモードの3種類の状態があります。



== オンライン状態です

オンライン状態は、コントローラの通常動作時の状態です。これは、コントローラが正常に動作しており、I/O処理に使用できることを意味します。

コントローラをオンラインにすると、ステータスが最適になります。



== オフライン状態です

オフライン状態は、通常、コントローラが2台あるストレージアレイでコントローラの交換を準備するときに使用します。コントローラがオフライン状態になるのは、明示的なコマンドを問題 に設定した場合、またはコントローラで障害が発生した場合です。コントローラのオフライン状態は、別の明示的なコマンドを実行するか、障害が発生したコントローラを交換するまで解消されません。コントローラをオフラインにできるのは、ストレージアレイにコントローラが2台ある場合のみです。

コントローラがオフライン状態のときは次の状況になります。

* そのコントローラをI/Oに使用できません
* そのコントローラを使用してストレージアレイを管理することはできません。
* そのコントローラが現在所有しているボリュームはもう一方のコントローラに移動されます。
* キャッシュミラーリングは無効になり、すべてのボリュームがライトスルーキャッシュモードになります。




== サービスモード

サービスモードは、通常はテクニカルサポートのみが使用するモードです。コントローラを診断できるように、ストレージアレイのすべてのボリュームを1台のコントローラに移動します。コントローラのサービスモードへの切り替えは手動で行う必要があり、サービスの処理が完了したら手動でオンラインに戻す必要があります。

コントローラがサービスモードのときは次の状況になります。

* そのコントローラをI/Oに使用できません
* テクニカルサポートは、シリアルポートまたはネットワーク接続を介してコントローラにアクセスし、潜在的な問題を分析できます。
* そのコントローラが現在所有しているボリュームはもう一方のコントローラに移動されます。
* キャッシュミラーリングは無効になり、すべてのボリュームがライトスルーキャッシュモードになります。

