---
permalink: sm-hardware/drive-states.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, drive, states, 
summary: System Managerでは、ドライブのさまざまな状態が報告されます。 
---
= ドライブの状態
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SANtricity System Managerでは、ドライブについてさまざまな状態が報告されます。



== アクセスの状態

[cols="25h,~"]
|===
| 状態 | 定義（ Definition ） 


 a| 
バイパス
 a| 
ドライブは物理的に存在しますが、コントローラがどちらかのポートで通信できません。



 a| 
互換性なし
 a| 
次のいずれかの状況に該当します。

* ストレージアレイでの使用が認定されていないドライブです。
* ドライブのセクターサイズが異なります。
* ドライブの設定データが古いバージョンまたは新しいバージョンのファームウェアで使用できません。




 a| 
削除されました
 a| 
ドライブがストレージアレイから取り外されています。



 a| 
あり
 a| 
コントローラは両方のポートでドライブと通信できます。



 a| 
応答しません
 a| 
ドライブがコマンドに応答していません。

|===


== ロールの状態

[cols="25h,~"]
|===
| 状態 | 定義（ Definition ） 


 a| 
割り当て済み
 a| 
プールまたはボリュームグループのメンバーです。



 a| 
使用中のホットスペア
 a| 
障害が発生したドライブの交換用ドライブとして使用中です。ホットスペアはボリュームグループでのみ使用され、プールでは使用されません。



 a| 
スタンバイホットスペア
 a| 
障害が発生したドライブの交換用ドライブとして使用可能な状態です。ホットスペアはボリュームグループでのみ使用され、プールでは使用されません。



 a| 
未割り当て
 a| 
プールまたはボリュームグループのメンバーでありません。

|===


== 可用性の状態

[cols="25h,~"]
|===
| 状態 | 定義（ Definition ） 


 a| 
失敗しました
 a| 
ドライブは動作していません。ドライブ上のデータを使用できません。



 a| 
障害の兆候
 a| 
ドライブで障害の前兆が検出されています。ドライブ上のデータはまだ使用できます。



 a| 
オフラインです
 a| 
ドライブをデータの格納に使用できません。通常は、ドライブがエクスポート中のボリュームグループに属しているか、ファームウェアのアップグレードを実行中であることが原因です。



 a| 
最適
 a| 
ドライブは正常に動作しています。

|===