---
permalink: sm-hardware/erase-drive.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, erase, drives, removal, 
summary: 消去オプションを使用して、未割り当てのドライブをシステムから取り外す準備を行うことができます。この手順 はデータを完全に削除し、データを二度と読み取れないようにします。 
---
= ドライブを消去します
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
消去オプションを使用して、未割り当てのドライブをシステムから取り外す準備を行うことができます。この手順 はデータを完全に削除し、データを二度と読み取れないようにします。

.作業を開始する前に
ドライブは未割り当て状態である必要があります。

.このタスクについて
ドライブ上のすべてのデータを完全に削除する場合にのみ、[消去]オプションを使用します。セキュリティ有効ドライブの場合、消去オプションは暗号化の消去を実行し、ドライブのセキュリティ属性をセキュリティ対応にリセットします。

[NOTE]
====
消去機能では、一部の古いドライブモデルはサポートされていません。これらの古いモデルのいずれかを消去しようとすると、エラーメッセージが表示されます。

====
.手順
. 「 * ハードウェア * 」を選択します。
. 図にコントローラが表示された場合は、*[ドライブ]*タブをクリックします。
+
図の表示が切り替わり、コントローラではなくドライブが表示されます。

. 必要に応じて、フィルタフィールドを使用して、シェルフ内の未割り当てのドライブをすべて表示できます。[Show drives that are ...*]ドロップダウンリストから、[*Unassigned *]を選択します。
+
シェルフビューには未割り当てのドライブのみが表示され、それ以外はすべてグレー表示になります。

. ドライブのコンテキストメニューを開くには、消去するドライブをクリックします。（複数のドライブを選択する場合は、ドライブの消去ダイアログボックスで選択できます）。
+
[CAUTION]
====
*データ損失の可能性*--消去操作は取り消せません。手順 で正しいドライブを選択していることを確認してください。

====
. コンテキストメニューから*消去*を選択します。
+
ドライブの消去ダイアログボックスが開き、消去処理に使用できるすべてのドライブが表示されます。

. 必要に応じて、表から追加のドライブを選択します。_all_drivesを選択することはできません。1つのドライブの選択が解除されたままになっていることを
. 「erase」と入力して操作を確定し、「* Erase *」をクリックします。
+
[CAUTION]
====
この処理を続行しますか？次のダイアログで[はい（Yes）]をクリックすると、操作を中止できません。

====
. 推定完了時間（Estimated Completion Time）ダイアログボックスで、*はい*（* Yes）をクリックして消去操作を続行します。


.結果
消去処理には数分または数時間かかることがあります。ステータスは、ホーム[進行中の処理を表示]メニューで確認できます。消去処理が完了すると、そのドライブは別のボリュームグループまたはディスクプール、あるいは別のストレージアレイで使用できるようになります。

.完了後
ドライブを再度使用する場合は、最初に初期化する必要があります。これを行うには、ドライブのコンテキストメニューから* Initialize *（初期化）を選択します。
