---
permalink: sm-hardware/fail-drive.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, fail, drive, 
summary: 指示があった場合は、ドライブを手動で使用停止できます。 
---
= ドライブを使用停止にする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
指示があった場合は、ドライブを手動で使用停止できます。

.このタスクについて
System Managerは、ストレージアレイ内のドライブを監視します。あるドライブが多数のエラーを生成していることを検出すると、近いうちにドライブ障害が発生する可能性があることがRecovery Guruから通知されます。この状況が発生し、交換用ドライブがある場合は、ドライブを使用停止して予防的措置を講じることができます。交換用ドライブがない場合は、ドライブが自動的に障害状態になるまで待つことができます。

[CAUTION]
====
*データアクセスが失われる可能性*-この操作により、データの損失やデータの冗長性の喪失が発生する可能性があります。この処理は、テクニカルサポートまたは Recovery Guru から指示があった場合にのみ実行してください。

====
.手順
. 「 * ハードウェア * 」を選択します。
. 図にコントローラが表示されている場合は、*シェルフの前面を表示*をクリックします。
+
図の表示が切り替わり、コントローラではなくドライブが表示されます。

. 使用停止するドライブをクリックします。
+
ドライブのコンテキストメニューが表示されます。

. 「* Fail *」を選択します。
. Copy contents of drive before failing *チェックボックスを選択したままにします。
+
コピーオプションは、割り当てられたドライブおよびRAID 0以外のボリュームグループにのみ表示されます。

+
ドライブを使用停止する前に、ドライブの内容をコピーしてください。構成によっては、ドライブの内容を最初にコピーしないと、関連付けられているプールまたはボリュームグループ上のすべてのデータまたはデータの冗長性が失われる可能性があります。

+
コピーオプションを使用すると、再構築よりも短時間でドライブをリカバリできるため、コピー処理中に別のドライブで障害が発生した場合のボリューム障害の可能性を低減できます。

. ドライブを使用停止することを確定します。
+
ドライブを使用停止したら、30秒以上待ってから取り外します。


