---
permalink: sm-hardware/faq-storage-controller.html 
sidebar: sidebar 
keywords:  
summary: この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。 
---
= SANtricity System Manager のストレージ コントローラに関する FAQ
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。



== 自動ネゴシエーションとは何ですか？

自動ネゴシエーションは、ネットワークインターフェイスが、自身の接続パラメータ（速度とデュプレックスモード）を別のネットワークインターフェイスと自動的に調整する機能です。

通常、管理ポートを設定する際には自動ネゴシエーションが推奨されますが、ネゴシエーションが失敗してネットワークインターフェイスの設定が一致しなくなった場合、ネットワークパフォーマンスが大幅に低下することがあります。この状況が許容されない場合は、ネットワークインターフェイスを手動で正しく設定する必要があります。自動ネゴシエーションは、コントローラのイーサネット管理ポートによって実行されます。自動ネゴシエーションはiSCSIホストバスアダプタでは実行されません。

[NOTE]
====
自動ネゴシエーションが失敗すると、コントローラは最も低レベルの共通設定である半二重の10BASE-Tで接続を確立しようとします。

====


== IPv6ステートレスアドレス自動設定とは何ですか。

ステートレス自動設定を使用すると、ホストはアドレスやその他の設定情報をサーバから取得しません。

IPv6のステートレス自動設定には、リンクローカルアドレス、マルチキャスト、近接探索（ND）プロトコルなどの機能があります。IPv6では、アドレスのインターフェイスIDが基盤のデータリンクレイヤアドレスから生成されます。

ステートレス自動設定とステートフル自動設定は、相互に補完しあう機能です。たとえば、ホストはステートレス自動設定を使用して自身のアドレスを設定できますが、その他の情報はステートフル自動設定を使用して取得します。ステートフル自動設定を使用すると、ホストはサーバからアドレスやその他の設定情報を取得できます。IPv6は、ネットワーク上のすべてのIPアドレスを一度に再割り当てする方法も定義します。IPv6では、ネットワーク上のデバイスがIPアドレスやその他のパラメータをサーバなしで自動的に設定する方法を定義しています。

ステートレス自動設定を使用する場合、デバイスは次の手順を実行します。

. *リンクローカルアドレスを生成*--デバイスは10ビットのリンクローカルアドレスを生成し、その後に54個のゼロと64ビットのインターフェイスIDを生成します。
. *リンクローカルアドレスの一意性をテスト*--生成されるリンクローカルアドレスがローカルネットワークでまだ使用されていないことをテストしますデバイスがNDプロトコルを使用して近接要求メッセージを送信します。これに応答して、ローカルネットワークはネイバーアドバタイズメントメッセージをリスンします。このメッセージは、別のデバイスがすでにリンクローカルアドレスを使用していることを示します。その場合は、新しいリンクローカルアドレスを生成する必要があるか、自動設定が失敗して別の方法を使用する必要があります。
. *リンクローカルアドレスの割り当て*--一意性テストに合格すると、デバイスは自身のIPインタフェースにリンクローカルアドレスを割り当てます。リンクローカルアドレスは、ローカルネットワーク上での通信には使用できますが、インターネット上では使用できません。
. *ルータに連絡*--ノードは、設定の続行の詳細についてローカルルータへの接続を試みます。具体的には、ルータから定期的に送信されるルータ通知メッセージをリスンするか、または次に必要な作業についてルータに問い合わせるルータ要求メッセージをルータに送信します。
. *ノードへの指示*--ルーターは自動設定の続行方法をノードに指示します。または、ルータは、グローバルインターネットアドレスの決定方法をホストに指示します。
. *グローバルアドレスを設定*--ホストは、グローバルに一意なインターネットアドレスを自身に設定します。このアドレスは、通常、ルータからホストに提供されるネットワークプレフィックスから形成されます。




== DHCP と手動構成のどちらを選択すればよいですか?

ネットワーク設定のデフォルトの方法は、Dynamic Host Configuration Protocol（DHCP；動的ホスト構成プロトコル）です。ネットワークにDHCPサーバがない場合を除き、必ずこのオプションを使用してください。



== DHCPサーバとは何ですか。

動的ホスト構成プロトコル（DHCP）は、インターネットプロトコル（IP）アドレスの割り当てタスクを自動化するプロトコルです。

TCP / IPネットワークに接続されている各デバイスには、一意のIPアドレスを割り当てる必要があります。これらのデバイスにはストレージアレイ内のコントローラも含まれます。

DHCPを使用しない場合は、ネットワーク管理者がこれらのIPアドレスを手動で入力します。DHCPを使用する場合は、クライアントがTCP / IP処理を開始する必要があるときにアドレス情報の要求を送信します。DHCPサーバは、要求を受信し、リース期間と呼ばれる指定された時間だけ新しいアドレスを割り当てて、アドレスをクライアントに送信します。DHCPを使用すると、ネットワークに接続するたびにデバイスのIPアドレスが変わる可能性があります。一部のシステムでは、デバイスが接続されている間でもデバイスのIPアドレスが変わる場合があります。



== DHCPサーバを設定するにはどうすればよいですか。

ストレージアレイのコントローラに静的インターネットプロトコル（IP）アドレスを使用するには、動的ホスト構成プロトコル（DHCP）サーバを設定する必要があります。

DHCPサーバが割り当てるIPアドレスは一般に動的で、有効期限が切れるリース期間があるため変更できます。サーバやルータなどの一部のデバイスは、静的アドレスを使用する必要があります。ストレージアレイ内のコントローラにも、静的IPアドレスが必要です。

静的アドレスの割り当て方法については、DHCPサーバのドキュメントを参照してください。



== コントローラのネットワーク設定を変更する必要があるのはなぜですか？

アウトオブバンド管理を使用する場合は、各コントローラのネットワーク設定（IPアドレス、サブネットワークマスク、ゲートウェイ）を設定する必要があります。

ネットワーク設定は、動的ホスト構成プロトコル（DHCP）サーバを使用して設定できます。DHCPサーバを使用しない場合は、ネットワーク設定を手動で入力する必要があります。



== ネットワーク設定はどこで入手できますか。

インターネットプロトコル（IP）アドレス、サブネットワークマスク（サブネットマスク）、およびゲートウェイの情報は、ネットワーク管理者から入手できます。

この情報は、コントローラでポートを設定する際に必要となります。



== ICMP PING応答とは何ですか？

Internet Control Message Protocol（ICMP）は、TCP / IPスイートのプロトコルの1つです。

「ICMPエコー要求」および「ICMPエコー応答」メッセージは、一般的に「ping」メッセージと呼ばれます。Pingは'システム管理者がネットワーク・デバイス間の接続を手動でテストするために使用するトラブルシューティング・ツールであり'ネットワーク遅延やパケット損失をテストするためにも使用されますpingコマンドは'ICMPエコー要求をネットワーク上のデバイスに送信し'デバイスはただちにICMPエコー応答で応答します企業のネットワークセキュリティポリシーでは、許可されていない人が検出しにくいように、すべてのデバイスで「ping」（「ICMPエコー応答」）を無効にする必要がある場合があります。



== ポート設定を更新する必要があるのはいつですか？

DHCPサーバは、サーバを変更またはアップグレードしたとき、および現在のストレージアレイと使用するストレージアレイに関連するDHCP情報が変更されたときに更新します。

具体的には、DHCPサーバが別のアドレスを割り当てることがわかったときに、DHCPサーバからポート設定またはiSNSサーバを更新します。

[NOTE]
====
ポート設定を更新すると、そのポート上のすべてのiSCSI接続が停止します。

====


== 管理ポートを設定したあとに何をすればよいですか？

ストレージアレイのIPアドレスを変更した場合は、SANtricity Unified Managerでグローバルアレイビューを更新できます。

Unified Managerでグローバルアレイビューを更新するには、インターフェイスを開き、メニューから「Manage [Discover]」に移動します。

SANtricity Storage Managerをまだ使用している場合は、Enterprise Management Window（EMW）に移動し、IPアドレスを削除してから、新しいIPアドレスを再度追加する必要があります。



== ストレージシステムが最適モードでないのはなぜですか？

ストレージシステムが最適モードでないのは、Invalid System Configuration状態が原因です。この状態でも既存のボリュームへの通常のI/Oアクセスは完全にサポートされますが、SANtricityシステムマネージャでは一部の処理が禁止されます。

ストレージシステムがInvalid System Configurationに移行する理由には、次のいずれかが考えられます。

* コントローラが準拠していません。間違ったサブモデルID（SMID）コードを持っているか、プレミアム機能の制限を超えている可能性があります。
* ドライブファームウェアのダウンロードなどの内部サービス処理が実行中です。
* コントローラがパリティエラーのしきい値を超えたためロックダウン状態になりました。
* 一般的なロックダウン状態が発生しました。

