---
permalink: sm-hardware/faq-storage-shelf.html 
sidebar: sidebar 
keywords:  
summary: この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。 
---
= SANtricity System Managerのストレージシェルフに関するFAQ
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。



== シェルフ損失の保護およびドロワー損失の保護とは何ですか？

シェルフ損失の保護とドロワー損失の保護は、シェルフまたはドロワーで単一障害が発生した場合にデータアクセスを維持するためのプールとボリュームグループの属性です。



=== シェルフ損失の保護

シェルフは、ドライブまたはドライブとコントローラを格納するエンクロージャです。シェルフ損失の保護が有効な場合、1台のドライブシェルフとの通信が完全に失われた場合でもプールまたはボリュームグループ内のボリューム上のデータへのアクセスが保証されます。通信が完全に失われるケースには、ドライブシェルフの電源喪失や、両方のI/Oモジュール（IOM）の障害などがあります。

[NOTE]
====
プールまたはボリュームグループですでにドライブに障害が発生している場合は、シェルフ損失の保護は保証されません。この状況で、ドライブシェルフへのアクセス、さらにその結果プールまたはボリュームグループ内の別のドライブへのアクセスを失うと、データが失われます。

====
シェルフ損失の保護の条件は、次の表で説明するように、保護の手法によって異なります。

[cols="1a,1a,1a"]
|===
| レベル | シェルフ損失の保護の条件 | 必要なシェルフの最小数 


 a| 
プール
 a| 
プールには少なくとも5つのシェルフのドライブが含まれている必要があり、各シェルフで同じ数のドライブが必要です。シェルフ損失の保護は大容量シェルフには適用されません。大容量シェルフがあるシステムの場合は、ドロワー損失の保護を参照してください。
 a| 
5.



 a| 
RAID 6
 a| 
ボリュームグループに同じシェルフのドライブが3本以上含まれない。
 a| 
3.



 a| 
RAID 3またはRAID 5
 a| 
ボリュームグループ内のドライブがすべて別々のシェルフに配置されている。
 a| 
3.



 a| 
RAID 1
 a| 
RAID 1ペアのドライブがそれぞれ別のシェルフに配置されている。
 a| 
2.



 a| 
RAID 0
 a| 
シェルフ損失の保護は実現できない。
 a| 
該当なし

|===


=== ドロワー損失の保護

ドロワーはシェルフのコンパートメントの1つで、引き出してドライブを設置します。ドロワーを備えているのは大容量シェルフのみです。ドロワー損失の保護が有効な場合、1つのドロワーとの通信が完全に失われた場合でもプールまたはボリュームグループ内のボリューム上のデータへのアクセスが保証されます。通信が完全に失われるケースには、ドロワーの電源喪失や、ドロワー内のコンポーネント障害などがあります。

[NOTE]
====
プールまたはボリュームグループですでにドライブに障害が発生している場合は、ドロワー損失の保護は保証されません。この状況でドロワーにアクセスできなくなると（その結果プールまたはボリュームグループ内の別のドライブにアクセスできなくなると）、データが失われます。

====
ドロワー損失の保護の条件は、次の表で説明するように、保護の手法によって異なります。

[cols="1a,1a,1a"]
|===
| レベル | ドロワー損失の保護の基準 | 必要なドロワーの最小数 


 a| 
プール
 a| 
プール候補にはすべてのドロワーのドライブを含める必要があり、各ドロワーに同じ数のドライブが必要です。

プールには少なくとも5つのドロワーのドライブが含まれている必要があり、各ドロワーに同じ数のドライブが必要です。

60ドライブのシェルフでは、プールに含まれる15、20、25、30、35でドロワー損失の保護を実現できます。 40、45、50、55、または60ドライブ。初回作成後に、5の倍数でプールに追加できます。
 a| 
5.



 a| 
RAID 6
 a| 
ボリュームグループに同じドロワーのドライブが3本以上含まれない。
 a| 
3.



 a| 
RAID 3またはRAID 5
 a| 
ボリュームグループ内のドライブがすべて別々のドロワーに配置されている。
 a| 
3.



 a| 
RAID 1
 a| 
ミラーペアのドライブがそれぞれ別のドロワーに配置されている。
 a| 
2.



 a| 
RAID 0
 a| 
ドロワー損失の保護は実現できない。
 a| 
該当なし

|===


== バッテリ学習サイクルとは何ですか？

学習サイクルは、スマートバッテリゲージを調整する自動サイクルです。

学習サイクルは次のフェーズで構成されます。

* 制御バッテリの放電
* 休息期間
* 充電


バッテリは事前に設定したしきい値まで放電されます。このフェーズでは、バッテリゲージが調整されます。

学習サイクルを実行するには、次のパラメータが必要です。

* フル充電されたバッテリ
* 過熱していないバッテリ


デュプレックスコントローラシステムでは、学習サイクルが同時に実行されます。複数のバッテリまたは一連のバッテリセルからのバックアップ電源を備えたコントローラの場合は、学習サイクルがシーケンシャルに実行されます。

学習サイクルは、一定の間隔で、同じ曜日の同じ時刻に自動的に開始されるようにスケジュール設定されます。サイクルの間隔は週単位で記述されます。

[NOTE]
====
学習サイクルの完了には数時間かかることがあります。

====