---
permalink: sm-hardware/hardware-page-overview.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, hardware, page, components, 
summary: Hardware（ハードウェア）ページには、ストレージアレイの物理コンポーネントの図が表示されます。ここから、コンポーネントのステータスを確認し、それらのコンポーネントに関連するいくつかの機能を実行できます。 
---
= ハードウェアのページとコンポーネント
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ハードウェアページには、ストレージアレイの物理コンポーネントの図が表示されます。ここから、コンポーネントのステータスを確認し、それらのコンポーネントに関連するいくつかの機能を実行できます。



== シェルフ

シェルフは、ストレージアレイ用のハードウェア（コントローラ、電源/ファンキャニスター、ドライブ）が搭載されたコンポーネントです。シェルフには次の2種類があります。

* *コントローラシェルフ*-ドライブ、電源/ファンキャニスター、コントローラが搭載されています。
* *ドライブシェルフ*（または*拡張シェルフ*）--ドライブ、電源/ファンキャニスター、および入出力モジュール（IOM）2台が搭載されています。IOMは環境サービスモジュール（ESM）とも呼ばれ、ドライブシェルフをコントローラシェルフに接続するSASポートが搭載されています。


シェルフのサイズは3つあり、それぞれ最大で12本、24本、60本のドライブを収容できます。各シェルフには、コントローラファームウェアによってID番号が割り当てられます。IDはシェルフビューの左上に表示されます。

ハードウェアページのシェルフビューには、前面または背面のコンポーネントが表示されます。2つのビューを切り替えるには、シェルフビューの右上から* Show back of shelf *または* Show front of shelf *のいずれかを選択します。また、ページの下部から* Show all front *または* Show all back *を選択することもできます。前面ビューと背面ビューには次の情報が表示されます。

* *前面コンポーネント*--ドライブおよび空のドライブベイ。
* *背面コンポーネント*--コントローラと電源/ファンキャニスター(コントローラシェルフ用)、またはIOMと電源/ファンキャニスター(ドライブシェルフ用)。


シェルフに関連して次の機能を実行できます。

* キャビネットまたはラック内でシェルフの場所を確認しやすいように、シェルフのロケーターライトをオンにします。
* シェルフビューの左上に表示されるID番号を変更します。
* 設置されているドライブのタイプやシリアル番号など、シェルフの設定を表示します。
* シェルフビューを上下に移動して、ストレージアレイ内の物理的なレイアウトと一致させます。




== コントローラ

コントローラは、ハードウェアとファームウェアを組み合わせたものであり、ストレージアレイと管理機能を実装します。キャッシュメモリ、ドライブのサポート、およびホストインターフェイスのサポートが含まれています。

コントローラに関連して次の機能を実行できます。

* 管理ポートのIPアドレスと速度を設定します。
* iSCSIホスト接続を設定します（iSCSIホストがある場合）。
* ネットワークタイムプロトコル（NTP）サーバおよびドメインネームシステム（DNS）サーバを設定する。
* コントローラのステータスと設定を表示します。
* ローカルエリアネットワーク外のユーザがコントローラ上でSSHセッションを開始し、設定を変更できるようにします。
* コントローラをオフライン、オンライン、またはサービスモードにします。




== ドライブ

ストレージアレイには、ハードディスクドライブ（HDD）またはソリッドステートドライブ（SSD）を搭載できます。シェルフのサイズに応じて、最大12本、24本、または60本のドライブをシェルフに設置できます。

ドライブに関連して次の機能を実行できます。

* シェルフ内でドライブの場所を確認できるように、ドライブのロケーターライトをオンにします。
* ドライブのステータスと設定を表示します。
* ドライブを再割り当て（障害が発生したドライブを未割り当てのドライブに論理的に交換）し、必要に応じてドライブを手動で再構築します。
* 交換できるように、ドライブを手動で使用停止します。（ドライブを使用停止にすると、交換前にドライブの内容をコピーできます）。
* ホットスペアを割り当てまたは割り当て解除します。
* ドライブを消去します。

