---
permalink: sm-hardware/hardware-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, hardware, terms 
summary: ストレージアレイに関連するハードウェアの用語を次に示します。 
---
= ハードウェアの用語
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイに関連するハードウェアの用語を次に示します。

.一般的なハードウェア用語：
====
[cols="25h,~"]
|===
| コンポーネント | 説明 


 a| 
ベイ
 a| 
ベイは、ドライブやその他のコンポーネントを取り付けるシェルフのスロットです。



 a| 
コントローラ
 a| 
コントローラは、ボード、ファームウェア、ソフトウェアで構成されます。ドライブを制御し、 System Manager の機能を実装します。



 a| 
コントローラシェルフ
 a| 
コントローラシェルフには、一連のドライブと1つ以上のコントローラキャニスターが搭載されています。コントローラキャニスターには、コントローラ、ホストインターフェイスカード（HIC）、バッテリが搭載されます。



 a| 
ドライブ
 a| 
ドライブは、データ用の物理ストレージメディアとして使用される電磁的な機械デバイスまたはソリッドステートメモリデバイスです。



 a| 
ドライブシェルフ
 a| 
ドライブシェルフは、拡張シェルフとも呼ばれ、一連のドライブと2つの入出力モジュール（IOM）が搭載されます。IOMには、ドライブシェルフをコントローラシェルフまたはその他のドライブシェルフに接続するSASポートが搭載されています。



 a| 
IOM（ESM）
 a| 
IOMは、ドライブシェルフをコントローラシェルフに接続するためのSASポートを含む入出力モジュールです。以前のコントローラモデルでは、IOMは環境サービスモジュール（ESM）と呼ばれていました。



 a| 
電源/ファンキャニスター
 a| 
電源 / ファンキャニスターは、シェルフに搭載されるアセンブリです。電源装置と一体型ファンで構成されます。



 a| 
SFP
 a| 
SFPは、Small Form-factor Pluggable（SFP）トランシーバです。



 a| 
シェルフ
 a| 
シェルフは、キャビネットまたはラックに設置されるエンクロージャです。ストレージアレイのハードウェアコンポーネントを収容します。シェルフには、コントローラシェルフとドライブシェルフの 2 種類があります。コントローラシェルフは、コントローラとドライブを収容します。ドライブシェルフは、入出力モジュール（ IOM ）とドライブを収容します。



 a| 
ストレージアレイ
 a| 
ストレージアレイには、シェルフ、コントローラ、ドライブ、ソフトウェア、およびファームウェアが含まれます。

|===
====
.コントローラの用語：
====
[cols="25h,~"]
|===
| コンポーネント | 説明 


 a| 
コントローラ
 a| 
コントローラは、ボード、ファームウェア、ソフトウェアで構成されます。ドライブを制御し、 System Manager の機能を実装します。



 a| 
コントローラシェルフ
 a| 
コントローラシェルフには、一連のドライブと1つ以上のコントローラキャニスターが搭載されています。コントローラキャニスターには、コントローラ、ホストインターフェイスカード（HIC）、バッテリが搭載されます。



 a| 
DHCP
 a| 
動的ホスト構成プロトコル（DHCP）は、インターネットプロトコル（IP）ネットワークでIPアドレスなどのネットワーク設定パラメータを動的に配布するために使用されるプロトコルです。



 a| 
DNS
 a| 
Domain Name System（DNS；ドメインネームシステム）は、インターネットまたはプライベートネットワークに接続されたデバイスの命名システムです。DNSサーバはドメイン名のディレクトリを保持し、IPアドレスに変換します。



 a| 
デュプレックス構成
 a| 
デュプレックスは、ストレージアレイ内に 2 台のコントローラモジュールを配置した構成です。デュプレックスシステムでは、コントローラ、論理ボリュームパス、およびディスクパスが完全に冗長化されます。一方のコントローラで障害が発生した場合、そのI/Oがもう一方のコントローラに引き継がれて可用性が維持されます。デュプレックスシステムでは、ファンと電源装置も冗長構成になっています。



 a| 
全二重/半二重接続
 a| 
全二重と半二重は、接続モードを指します。全二重モードでは、2つのデバイスが双方向で同時に通信できます。半二重モードでは、デバイスは一度に一方向で通信できます（一方のデバイスがメッセージを送信し、他方のデバイスがメッセージを受信します）。



 a| 
HIC
 a| 
ホストインターフェイスカード（ HIC ）は、コントローラキャニスターにオプションで取り付けることができます。コントローラに搭載されたホストポートのことをベースボードホストポートと呼び、HIC に搭載されたホストポートのことを HIC ポートと呼びます。



 a| 
ICMP PING応答
 a| 
Internet Control Message Protocol（ICMP）は、ネットワークに接続されたコンピュータのオペレーティングシステムでメッセージの送信に使用されるプロトコルです。ICMPメッセージを送信することで、ホストに到達できるかどうかや、そのホストとのパケットの送受信にどれくらいの時間がかかるかが確認されます。



 a| 
MAC アドレス
 a| 
メディアアクセス制御（MAC）アドレスはイーサネットで使用される識別子で、同じ物理トランスポートネットワークインターフェイス上の2つのポートを接続する別々の論理チャネルを区別します。



 a| 
管理クライアント
 a| 
管理クライアントは、System Managerにアクセスするためのブラウザがインストールされたコンピュータです。



 a| 
MTU
 a| 
Maximum Transmission Unit（MTU；最大転送単位）は、ネットワークで送信可能なパケットまたはフレームの最大サイズです。



 a| 
NTP
 a| 
Network Time Protocol（NTP；ネットワークタイムプロトコル）は、データネットワーク内のコンピュータシステム間でクロック同期を行うためのネットワークプロトコルです。



 a| 
シンプレックス構成です
 a| 
シンプレックスは、ストレージアレイ内に1つのコントローラモジュールを配置した構成です。シンプレックスシステムでは、コントローラやディスクパスは冗長化されませんが、ファンと電源装置は冗長構成になります。



 a| 
VLAN
 a| 
仮想ローカルエリアネットワーク（VLAN）は、同じデバイス（スイッチやルータなど）でサポートされる他のネットワークと物理的に分離されているかのように動作する論理ネットワークです。

|===
====
.ドライブの用語：
====
[cols="25h,~"]
|===
| コンポーネント | 説明 


 a| 
ダ
 a| 
Data Assurance（DA）は、データがコントローラ経由でドライブに転送される際に発生する可能性があるエラーをチェックして修正する機能です。Data Assuranceは、Fibre ChannelなどのDAに対応したI/Oインターフェイスを使用するホストで、プールまたはボリュームグループのレベルで有効にすることができます。



 a| 
ドライブセキュリティ機能
 a| 
ドライブセキュリティは、 Full Disk Encryption （ FDE ）ドライブまたは連邦情報処理標準（ FIPS ）ドライブを使用してセキュリティを強化するストレージアレイの機能です。これらのドライブにドライブセキュリティ機能を使用すると、データにアクセスするためのセキュリティキーが必要になります。ドライブをアレイから物理的に取り外した場合、別のアレイに取り付けるまでは動作しなくなり、取り付けた時点で正しいセキュリティキーが提供されるまではセキュリティロック状態になります。



 a| 
ドライブシェルフ
 a| 
ドライブシェルフは、拡張シェルフとも呼ばれ、一連のドライブと2つの入出力モジュール（IOM）が搭載されます。IOMには、ドライブシェルフをコントローラシェルフまたはその他のドライブシェルフに接続するSASポートが搭載されています。



 a| 
DULBE
 a| 
Deallocated or Unwritten Logical Block Error（DULBE）はNVMeドライブのオプションです。このオプションにより、EF300またはEF600ストレージアレイでリソースプロビジョニングボリュームをサポートできます。



 a| 
FDEドライブ
 a| 
Full Disk Encryption（FDE）ドライブは、ハードウェアレベルでディスクドライブの暗号化を実行します。ハードドライブに搭載されたASICチップにより、書き込み時にデータが暗号化され、読み取り時に復号化されます。



 a| 
FIPSドライブ
 a| 
FIPSドライブは、連邦情報処理標準（FIPS）140-2レベル2に準拠しています。基本的な概念はFDEドライブと同じですが、米国政府の基準に従って強力な暗号化アルゴリズムと暗号化方式を実装しています。FIPSドライブにはFDEドライブよりも高度なセキュリティ基準が採用されています。



 a| 
HDD
 a| 
ハードディスクドライブ（ HDD ）は、磁気コーティングを施した金属製の回転式ディスクを使用するデータストレージデバイスです。



 a| 
ホットスペアドライブ
 a| 
ホットスペアは、RAID 1、RAID 5、またはRAID 6のボリュームグループで、スタンバイドライブとして機能します。問題なく動作するドライブですが、データは格納されていません。ボリュームグループ内のドライブで障害が発生すると、障害が発生したドライブのデータがホットスペアに自動的に再構築されます。



 a| 
NVMe
 a| 
Non-Volatile Memory Express（NVMe）は、SSDドライブなどのフラッシュベースのストレージデバイス向けに設計されたインターフェイスです。以前の論理デバイスインターフェイスに比べ、I/Oオーバーヘッドが少なく、パフォーマンスも向上しています。



 a| 
（ SAS ）。
 a| 
Serial Attached SCSI （ SAS ）は、コントローラをディスクドライブに直接リンクするポイントツーポイントのシリアルプロトコルです。



 a| 
セキュリティ対応ドライブ
 a| 
セキュリティ対応ドライブには、Full Disk Encryption（FDE）ドライブと連邦情報処理標準（FIPS）ドライブがあります。これらのドライブでは、書き込み時にデータが暗号化され、読み取り時に復号化されます。ドライブセキュリティ機能を使用したセキュリティの強化に使用できるため、これらのドライブはsecured_capable_とみなされます。これらのドライブを使用するボリュームグループやプールでドライブセキュリティ機能を有効にすると、ドライブはsecure-_enabled_になります。



 a| 
セキュリティ有効ドライブ
 a| 
セキュリティ有効ドライブは、ドライブセキュリティ機能で使用されます。ドライブセキュリティ機能を有効にし、かつsecured_caped_drivesのプールまたはボリュームグループにドライブセキュリティを適用すると、ドライブはsecure__enable__になります。読み取りおよび書き込みアクセスは、正しいセキュリティキーが設定されたコントローラからしか実行できません。この追加のセキュリティ機能により、ストレージアレイから物理的に取り外されたドライブ上のデータへの不正アクセスを防止できます。



 a| 
SSD の場合
 a| 
ソリッドステートディスク（ SSD ）は、ソリッドステートメモリ（フラッシュ）を使用してデータを永続的に格納するデータストレージデバイスです。SSD は従来のハードドライブをエミュレートしたものであり、ハードドライブと同じインターフェイスで利用できます。

|===
====
.iSCSIの用語：
====
[cols="25h,~"]
|===
| 期間 | 説明 


 a| 
CHAP
 a| 
チャレンジハンドシェイク認証プロトコル（CHAP）方式では、初回のリンク確立時にターゲットとイニシエータのIDを検証します。認証は、CHAP_secret__という共有セキュリティキーに基づいて行われます。



 a| 
コントローラ
 a| 
コントローラは、ボード、ファームウェア、ソフトウェアで構成されます。ドライブを制御し、 System Manager の機能を実装します。



 a| 
DHCP
 a| 
動的ホスト構成プロトコル（DHCP）は、インターネットプロトコル（IP）ネットワークでIPアドレスなどのネットワーク設定パラメータを動的に配布するために使用されるプロトコルです。



 a| 
IB
 a| 
InfiniBand （ IB ）は、ハイパフォーマンスのサーバとストレージシステムの間のデータ転送用の通信標準です。



 a| 
ICMP PING応答
 a| 
Internet Control Message Protocol（ICMP）は、ネットワークに接続されたコンピュータのオペレーティングシステムでメッセージの送信に使用されるプロトコルです。ICMPメッセージを送信することで、ホストに到達できるかどうかや、そのホストとのパケットの送受信にどれくらいの時間がかかるかが確認されます。



 a| 
IQN
 a| 
iSCSI Qualified Name（IQN）は、iSCSIイニシエータまたはiSCSIターゲットの一意の名前です。



 a| 
iSER
 a| 
iSCSI Extensions for RDMA（iSER）は、InfiniBandやイーサネットなどのRDMAトランスポートを使用する処理用にiSCSIプロトコルを拡張したプロトコルです。



 a| 
iSNS
 a| 
Internet Storage Name Service（iSNS）は、TCP / IPネットワーク上のiSCSIデバイスとFibre Channelデバイスの自動検出、管理、構成が可能なプロトコルです。



 a| 
MAC アドレス
 a| 
メディアアクセス制御（MAC）アドレスはイーサネットで使用される識別子で、同じ物理トランスポートネットワークインターフェイス上の2つのポートを接続する別々の論理チャネルを区別します。



 a| 
管理クライアント
 a| 
管理クライアントは、System Managerにアクセスするためのブラウザがインストールされたコンピュータです。



 a| 
MTU
 a| 
Maximum Transmission Unit（MTU；最大転送単位）は、ネットワークで送信可能なパケットまたはフレームの最大サイズです。



 a| 
RDMA
 a| 
Remote Direct Memory Access（RDMA）は、ネットワークコンピュータ同士が、それぞれのオペレーティングシステムを介さずにメインメモリ内でデータを交換できるテクノロジです。



 a| 
名前のない検出セッション
 a| 
名前のない検出セッションのオプションが有効な場合、iSCSIイニシエータは、コントローラの情報を取得するためにターゲットIQNを指定する必要はありません。

|===
====
.NVMeの用語：
====
[cols="25h,~"]
|===
| 期間 | 説明 


 a| 
InfiniBandの略
 a| 
InfiniBand （ IB ）は、ハイパフォーマンスのサーバとストレージシステムの間のデータ転送用の通信標準です。



 a| 
ネームスペース
 a| 
ネームスペースは、ブロックアクセス用にフォーマットされたNVMストレージです。SCSIの論理ユニットに相当し、ストレージアレイではボリュームに関連します。



 a| 
ネームスペースID
 a| 
ネームスペースIDは、NVMeコントローラのネームスペースの一意の識別子です。1~255の値を設定できます。SCSIの論理ユニット番号（LUN）に相当します。



 a| 
NQN
 a| 
NVMe Qualified Name（NQN）は、リモートストレージターゲット（ストレージアレイ）を識別するために使用します。



 a| 
NVM
 a| 
非揮発性メモリ（NVM）は、多くのタイプのストレージデバイスで使用されている永続的メモリです。



 a| 
NVMe
 a| 
Non-Volatile Memory Express（NVMe）は、SSDドライブなどのフラッシュベースのストレージデバイス向けに設計されたインターフェイスです。以前の論理デバイスインターフェイスに比べ、I/Oオーバーヘッドが少なく、パフォーマンスも向上しています。



 a| 
NVMe-oF
 a| 
Non-Volatile Memory Express over Fabrics（NVMe-oF）は、NVMeコマンドとデータをホストとストレージ間でネットワーク経由で転送するための仕様です。



 a| 
NVMeコントローラ
 a| 
NVMeコントローラはホストの接続プロセス中に作成されます。ホストとストレージアレイ内のネームスペースの間のアクセスパスを提供します。



 a| 
NVMeキューです
 a| 
NVMeインターフェイス経由でのコマンドやメッセージの受け渡しに使用されるキューです。



 a| 
NVMe サブシステム
 a| 
NVMeホストに接続されているストレージアレイです。



 a| 
RDMA
 a| 
Remote Direct Memory Access（RDMA）を使用すると、ネットワークインターフェイスカード（NIC）ハードウェアに転送プロトコルを実装することで、サーバとの間でより直接的なデータ移動を実現できます。



 a| 
RoCE
 a| 
RDMA over Converged Ethernet （ RoCE ）は、イーサネットネットワークを介したリモートダイレクトメモリアクセス（ RDMA ）を可能にするネットワークプロトコルです。



 a| 
SSD の場合
 a| 
ソリッドステートディスク（ SSD ）は、ソリッドステートメモリ（フラッシュ）を使用してデータを永続的に格納するデータストレージデバイスです。SSD は従来のハードドライブをエミュレートしたものであり、ハードドライブと同じインターフェイスで利用できます。

|===
====