---
permalink: sm-hardware/hot-spare-drives.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, hot, spare, drives, raid1, raid6, raid5 
summary: ホットスペアは、System ManagerのRAID 1、RAID 5、またはRAID 6のボリュームグループで、スタンバイドライブとして機能します。 
---
= ホットスペアドライブの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ホットスペアは、System ManagerのRAID 1、RAID 5、またはRAID 6のボリュームグループで、スタンバイドライブとして機能します。

問題なく動作するドライブですが、データは格納されていません。ボリュームグループ内のドライブで障害が発生すると、障害が発生したドライブのデータがホットスペアとして割り当てられているドライブに自動的に再構築されます。

ホットスペアは、特定のボリュームグループ専用ではありません。ストレージアレイ内で障害が発生したどのドライブにも使用できますが、ホットスペアとドライブで次の属性が共有されている必要があります。

* 容量（またはホットスペアの方が大きい）
* メディアタイプ（HDD、SSDなど）が同じ
* インターフェイスタイプ（SASなど）




== ホットスペアの識別方法

ホットスペアは、初期セットアップウィザードまたはハードウェアページから割り当てることができます。ホットスペアが割り当てられているかどうかを確認するには、ハードウェアページで、ピンクで示されたドライブベイを探します。



== ホットスペアの適用方法

ホットスペアの適用範囲は次のとおりです。

* RAID 1、RAID 5、またはRAID 6のボリュームグループのホットスペアとして、未割り当てのドライブを予約します。
+
[NOTE]
====
データ保護の方法が異なるため、ホットスペアはプールには使用できません。プールでは、追加のドライブを予約する代わりに、プール内の各ドライブにスペア容量（_予約済み容量_）を予約します。プール内のドライブに障害が発生した場合、コントローラはそのスペア容量内にデータを再構築します。

====
* RAID 1、RAID 5、またはRAID 6のボリュームグループ内のドライブに障害が発生した場合、コントローラは冗長性データを使用して、障害が発生したドライブのデータを自動的に再構築します。障害が発生したドライブからホットスペアに自動的に切り替わります。物理的にドライブを交換する必要はありません。
* 障害が発生したドライブを物理的に交換すると、ホットスペアドライブから交換したドライブへと、コピーバック処理が実行されます。ホットスペアドライブをボリュームグループの永続的メンバーとして指定している場合は、コピーバック処理は不要です。
* ボリュームグループのトレイ損失の保護およびドロワー損失の保護が可能かどうかは、ボリュームグループを構成するドライブの場所によって異なります。ドライブの障害とホットスペアドライブの場所によっては、トレイ損失の保護とドロワー損失の保護が失われる場合があります。トレイ損失の保護とドロワー損失の保護が影響を受けないようにするには、障害が発生したドライブを交換してコピーバックプロセスを開始する必要があります。
* 障害が発生したドライブからホットスペアドライブに自動的に切り替わるため、障害が発生したドライブの交換中もストレージアレイボリュームはオンラインのままアクセス可能です。




== ホットスペアドライブの容量に関する考慮事項

保護するドライブの合計容量以上の容量があるドライブを選択します。たとえば、8GiBの容量が設定されている18GiBドライブがある場合は、9GiB以上のドライブをホットスペアとして使用できます。通常は、ストレージアレイ内で最大のドライブの容量以上の容量がないドライブは、ホットスペアとして割り当てないでください。

[NOTE]
====
同じ物理容量のホットスペアがない場合は、ドライブの「使用済み容量」がホットスペアドライブの容量以下であれば、容量の少ないドライブをホットスペアとして使用できます。

====


== メディアおよびインターフェイスタイプに関する考慮事項

ホットスペアとして使用するドライブは、保護対象のドライブと同じメディアタイプおよびインターフェイスタイプである必要があります。たとえば、HDDドライブをSSDドライブのホットスペアとして使用することはできません。



== セキュリティ対応ドライブに関する考慮事項

セキュリティ対応ドライブ（FDEやFIPSなど）は、セキュリティ機能の有無に関係なく、ドライブのホットスペアとして使用できます。ただし、セキュリティ対応でないドライブは、セキュリティ機能のあるドライブのホットスペアとしては使用できません。

セキュリティ有効ドライブをホットスペアとして使用するよう選択すると、完全消去を実行してから続行するようにSystem Managerから求められます。完全消去では、ドライブのセキュリティ属性はセキュリティ有効ではなくセキュリティ対応にリセットされます。

[NOTE]
====
ドライブセキュリティ機能を有効にし、セキュリティ対応ドライブで構成されるプールまたはボリュームグループを作成すると、ドライブは_secure-enabled _になります。読み取りおよび書き込みアクセスは、正しいセキュリティキーが設定されたコントローラからしか実行できません。この追加のセキュリティ機能により、ストレージアレイから物理的に取り外されたドライブ上のデータへの不正アクセスを防止できます。

====


== 推奨されるホットスペアドライブの数

初期セットアップウィザードを使用してホットスペアを自動的に作成した場合、System Managerでは、特定のメディアタイプおよびインターフェイスタイプのドライブ30本ごとに1つのホットスペアが作成されます。ホットスペアドライブがない場合は、ストレージアレイのボリュームグループ間に手動でホットスペアドライブを作成できます。
