---
permalink: sm-hardware/solid-state-disks-ssds.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, solid, state, disk, SSD 
summary: ソリッドステートディスク（ SSD ）は、ソリッドステートメモリ（フラッシュ）を使用してデータを永続的に格納するデータストレージデバイスです。SSD は従来のハードドライブをエミュレートしたものであり、ハードドライブと同じインターフェイスで利用できます。 
---
= ソリッドステートディスク（SSD）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ソリッドステートディスク（ SSD ）は、ソリッドステートメモリ（フラッシュ）を使用してデータを永続的に格納するデータストレージデバイスです。SSD は従来のハードドライブをエミュレートしたものであり、ハードドライブと同じインターフェイスで利用できます。



== SSDの利点

ハードドライブに比べてSSDを使用する利点は次のとおりです。

* 高速起動（スピンアップなし）
* レイテンシの低減
* IOPS（1秒あたりのI/O処理数）が高い
* 少ない可動部品で高い信頼性を実現
* 消費電力の削減
* 熱の発生を抑え、冷却コストを削減します




== SSDの識別

ハードウェアページでは、前面シェルフビューでSSDを特定できます。稲妻アイコンが表示されているドライブベイを探します。このアイコンはSSDが取り付けられていることを示します。



== ボリュームグループ

ボリュームグループ内のすべてのドライブのメディアタイプ（すべてのSSDまたはすべてのハードドライブ）が同じである必要があります。ボリュームグループのメディアタイプやインターフェイスタイプを混在させることはできません。



== キャッシュ

コントローラの書き込みキャッシュは常にSSDに対して有効になります。書き込みキャッシュによってパフォーマンスが向上し、SSDの寿命が延びます。

コントローラキャッシュに加えてSSDキャッシュ機能を実装することで、システム全体のパフォーマンスを向上させることができます。SSDキャッシュでは、データはボリュームからコピーされ、2つの内部RAIDボリューム（コントローラごとに1つ）に格納されます。
