---
permalink: sm-hardware/solid-state-disks-ssds.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, solid, state, disk, SSD 
summary: ソリッドステートディスク（ SSD ）は、ソリッドステートメモリ（フラッシュ）を使用してデータを永続的に格納するデータストレージデバイスです。SSD は従来のハードドライブをエミュレートしたものであり、ハードドライブと同じインターフェイスで利用できます。 
---
= SANtricity System Manager のソリッド ステート ディスク (SSD) について学習します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ソリッドステートディスク（ SSD ）は、ソリッドステートメモリ（フラッシュ）を使用してデータを永続的に格納するデータストレージデバイスです。SSD は従来のハードドライブをエミュレートしたものであり、ハードドライブと同じインターフェイスで利用できます。



[[advantages-of-ssds]]
== SSDの利点

ハードドライブに比べてSSDを使用する利点は次のとおりです。

* 高速起動（スピンアップなし）
* レイテンシの低減
* IOPS（1秒あたりのI/O処理数）が高い
* 少ない可動部品で高い信頼性を実現
* 消費電力の削減
* 熱の発生を抑え、冷却コストを削減します




[[identifying-ssds]]
== SSDの識別

Hardware > Drives ページから、前面シェルフビューで SSD の位置を確認できます。稲妻アイコンが表示されているドライブベイを探してください。これは SSD が取り付けられていることを示しています。



[[volume-groups]]
== ボリュームグループ

ボリュームグループ内のすべてのドライブのメディアタイプ（すべてのSSDまたはすべてのハードドライブ）が同じである必要があります。ボリュームグループのメディアタイプやインターフェイスタイプを混在させることはできません。



[[caching]]
== キャッシュ

コントローラの書き込みキャッシュは常にSSDに対して有効になります。書き込みキャッシュによってパフォーマンスが向上し、SSDの寿命が延びます。

コントローラキャッシュに加えてSSDキャッシュ機能を実装することで、システム全体のパフォーマンスを向上させることができます。SSDキャッシュでは、データはボリュームからコピーされ、2つの内部RAIDボリューム（コントローラごとに1つ）に格納されます。
