---
permalink: sm-hardware/view-drive-status-and-settings.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, drive, status, settings, media, 
summary: メディアタイプ、インターフェイスタイプ、容量などのドライブのステータスと設定を表示できます。 
---
= ドライブのステータスと設定を表示します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
メディアタイプ、インターフェイスタイプ、容量などのドライブのステータスと設定を表示できます。

.手順
. 「 * ハードウェア * 」を選択します。
. 図にコントローラが表示されている場合は、*シェルフの前面を表示*をクリックします。
+
図の表示が切り替わり、コントローラではなくドライブが表示されます。

. ステータスおよび設定を表示するドライブを選択します。
+
ドライブのコンテキストメニューが開きます。

. 「 * 表示設定 * 」を選択します。
+
Drive Settings（ドライブ設定）ダイアログボックスが開きます。

. すべての設定を表示するには、ダイアログボックスの右上にある*詳細設定を表示*をクリックします。
+
.フィールドの詳細
====
[cols="25h,~"]
|===
| 設定 | 説明 


 a| 
ステータス
 a| 
最適、オフライン、重大でない障害、失敗のいずれかが表示されます。「最適」ステータスは、必要な稼働状態を示します。



 a| 
モード
 a| 
割り当て済み、未割り当て、ホットスペアスタンバイ、ホットスペア使用中のいずれかが表示されます。



 a| 
場所
 a| 
ドライブが配置されているシェルフおよびベイの番号が表示されます。



 a| 
割り当て先/保護対象/保護対象
 a| 
ドライブがプール、ボリュームグループ、またはSSDキャッシュに割り当てられている場合、このフィールドには「割り当て先」と表示されます。 指定できる値は、プール名、ボリュームグループ名、またはSSDキャッシュ名です。ドライブがスタンバイモードのホットスペアに割り当てられている場合、このフィールドには「保護対象」と表示されます。 1つ以上のボリュームグループをホットスペアで保護できる場合は、ボリュームグループ名が表示されます。ボリュームグループを保護できない場合は、0個のボリュームグループが表示されます。

ドライブが使用中モードのホットスペアに割り当てられている場合、このフィールドには「保護」と表示されます。 は、影響を受けるボリュームグループの名前です。

ドライブが未割り当ての場合、このフィールドは表示されません。



 a| 
メディアタイプ
 a| 
ドライブが使用する記録メディアのタイプが表示されます。ハードディスクドライブ（HDD）またはソリッドステートディスク（SSD）のいずれかです。



 a| 
使用済み寿命の割合（SSDドライブが存在する場合にのみ表示）
 a| 
これまでにドライブに書き込まれたデータ量を理論上の合計書き込み制限値で割った値。



 a| 
インターフェイスタイプ
 a| 
ドライブが使用しているインターフェイスのタイプ（SASなど）が表示されます。



 a| 
ドライブパスの冗長性
 a| 
ドライブとコントローラ間の接続が冗長であるかどうか（「はい」または「いいえ」）が表示されます。



 a| 
容量（GiB）
 a| 
ドライブの使用可能容量（設定済みの合計容量）が表示されます。



 a| 
速度（ RPM ）
 a| 
速度がRPM単位で表示されます（SSDの場合は表示されません）。



 a| 
現在のデータ速度
 a| 
ドライブとストレージアレイ間のデータ転送率が表示されます。



 a| 
論理セクターサイズ（バイト）
 a| 
ドライブが使用する論理セクターサイズが表示されます。



 a| 
物理セクターサイズ（バイト）
 a| 
ドライブが使用する物理セクターサイズが表示されます。通常、ハードディスクドライブの物理セクターサイズは4096バイトです。



 a| 
ドライブファームウェアのバージョン
 a| 
ドライブファームウェアのリビジョンレベルが表示されます。



 a| 
ワールドワイド識別子
 a| 
ドライブの一意の16進数の識別子が表示されます。



 a| 
製品ID
 a| 
メーカーによって割り当てられた製品IDが表示されます。



 a| 
シリアル番号
 a| 
ドライブのシリアル番号が表示されます。



 a| 
製造元
 a| 
ドライブのベンダーが表示されます。



 a| 
製造日
 a| 
ドライブがビルドされた日付が表示されます。


NOTE: NVMeドライブでは使用できません。



 a| 
セキュリティ対応
 a| 
セキュリティ対応ドライブであるかどうか（「はい」または「いいえ」）が表示されます。セキュリティ対応ドライブには、Full Disk Encryption（FDE）ドライブと連邦情報処理標準（FIPS）ドライブ（レベル140-2または140-3）があります。これらのドライブでは、書き込み時にデータが暗号化され、読み取り時に復号化されます。ドライブセキュリティ機能を使用したセキュリティの強化に使用できるため、これらのドライブはsecured_capable_とみなされます。これらのドライブを使用するボリュームグループやプールでドライブセキュリティ機能を有効にすると、ドライブはsecure-_enabled_になります。



 a| 
セキュリティ有効
 a| 
セキュリティ有効ドライブであるかどうか（「はい」または「いいえ」）が表示されます。セキュリティ有効ドライブは、ドライブセキュリティ機能で使用されます。ドライブセキュリティ機能を有効にし、かつsecure-_enabled_drivesにあるプールまたはボリュームグループにドライブセキュリティを適用すると、ドライブはsecure-_enabled_になります。読み取りおよび書き込みアクセスは、正しいセキュリティキーが設定されたコントローラからしか実行できません。この追加のセキュリティ機能により、ストレージアレイから物理的に取り外されたドライブ上のデータへの不正アクセスを防止できます。



 a| 
読み取り/書き込みアクセス
 a| 
読み取り/書き込みアクセス可能なドライブであるかどうか（「はい」または「いいえ」）が表示されます。



 a| 
ドライブセキュリティキー識別子
 a| 
セキュリティ有効ドライブのセキュリティキーが表示されます。ドライブセキュリティは、 Full Disk Encryption （ FDE ）ドライブまたは連邦情報処理標準（ FIPS ）ドライブを使用してセキュリティを強化するストレージアレイの機能です。これらのドライブにドライブセキュリティ機能を使用すると、データにアクセスするためのセキュリティキーが必要になります。ドライブをアレイから物理的に取り外した場合、別のアレイに取り付けるまでは動作しなくなり、取り付けた時点で正しいセキュリティキーが提供されるまではセキュリティロック状態になります。



 a| 
Data Assurance（DA）対応
 a| 
Data Assurance（DA）機能が有効かどうか（「はい」または「いいえ」）が表示されます。Data Assurance（DA）は、データがコントローラ経由でドライブに転送される際に発生する可能性があるエラーをチェックして修正する機能です。Data Assuranceは、Fibre ChannelなどのDAに対応したI/Oインターフェイスを使用するホストで、プールまたはボリュームグループのレベルで有効にすることができます。



 a| 
DULBE対応
 a| 
Deallocated or Unwritten Logical Block Error（DULBE）のオプションが有効かどうか（「はい」または「いいえ」）を示します。DULBEはNVMeドライブのオプションです。このオプションにより、EF300またはEF600ストレージアレイでリソースプロビジョニングボリュームをサポートできます。

|===
====
. [* 閉じる * ] をクリックします。

