---
permalink: sm-hardware/view-hardware-components.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, hardware, components, filtering, 
summary: '[ハードウェア]ページには、コンポーネントの検索を容易にするソートおよびフィルタリング機能があります。' 
---
= SANtricity System Managerでハードウェアコンポーネントを表示する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
[ハードウェア]ページには、コンポーネントの検索を容易にするソートおよびフィルタリング機能があります。

.手順
. 「 * ハードウェア * 」を選択します。
. 次の表に示す機能を使用して、ハードウェアコンポーネントを表示します。


[cols="25h,~"]
|===
| 機能 | 説明 


 a| 
ドライブ、コントローラ、およびコンポーネントのビュー
 a| 
シェルフ前面ビューと背面ビューを切り替えるには、右端から*[ドライブ]*または*[コントローラとコンポーネント]*を選択します（表示されるリンクは現在のビューによって異なります）。[ドライブ]ビューには、ドライブと空のドライブベイが表示されます。[コントローラとコンポーネント]*ビューには、コントローラ、IOM（ESM）モジュール、電源/ファンキャニスター、または空のコントローラベイが表示されます。ページの下部で、*[すべてのドライブを表示]*を選択することもできます。



 a| 
ドライブ表示のフィルタ
 a| 
ストレージアレイに物理属性と論理属性が異なるドライブが含まれている場合、*ハードウェア*ページにはドライブ表示フィルタが含まれています。これらのフィルタフィールドを使用すると、ページに表示するドライブのタイプを制限することで特定のドライブをすばやく特定できます。[Show drives that are…*]で、左側のフィルタフィールド(デフォルトでは*any drive type*)をクリックすると、物理属性(容量や速度など)のドロップダウンリストが表示されます。右側のフィルタフィールド（デフォルトではストレージアレイ内に「* Anywhere」と表示されます）をクリックすると、論理属性（ボリュームグループ割り当てなど）のドロップダウンリストが表示されます。これらのフィルタは、一緒に使用することも、個別に使用することもでき

[NOTE]
====
ストレージアレイに同じ物理属性を共有するドライブがすべて含まれている場合、左側の*いずれかのドライブタイプ*フィールドは表示されません。すべてのドライブが同じ論理的な場所にある場合、右側のストレージアレイ*フィールドに「* Anywhere」と表示されません。

====


 a| 
凡例
 a| 
各コンポーネントは、ロールの状態を示すために特定の色で表示されます。これらの状態の説明を展開または折りたたむには、*凡例*をクリックします。



 a| 
ステータスアイコンの詳細を表示します
 a| 
ステータスインジケータには、可用性の状態の説明を含めることができます。[ステータスアイコンの詳細を表示する*]をクリックして、このステータステキストを表示または非表示にします。



 a| 
シェルフ/シェルフアイコン
 a| 
各シェルフビューには、関連コマンドのリスト、およびプロパティとステータスが表示されます。[*Shelf-*]をクリックすると、コマンドのドロップダウンリストが表示されます。上部のアイコンを選択して、各コンポーネントのステータスとプロパティを確認することもできます。コントローラ、IOM（ESM）、電源装置、ファン、温度、 バッテリ、SFP。



 a| 
シェルフの順序
 a| 
シェルフはハードウェアページで再配置できます。各シェルフビューの右上にある上下の矢印を使用して、シェルフの上下の順序を変更できます。

|===