---
permalink: sm-hardware/view-controller-settings.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, controller, settings 
summary: ホストインターフェイス、ドライブインターフェイス、管理ポートのステータスなど、コントローラに関する情報を確認できます。 
---
= コントローラの設定を表示します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ホストインターフェイス、ドライブインターフェイス、管理ポートのステータスなど、コントローラに関する情報を確認できます。

.手順
. 「 * ハードウェア * 」を選択します。
. 図にドライブが表示されている場合は、 * シェルフの背面を表示 * をクリックします。
+
図の表示が切り替わり、ドライブではなくコントローラが表示されます。

. 次のいずれかを実行してコントローラの設定を表示します。
+
** コントローラをクリックしてコンテキストメニューを表示し、*設定の表示*を選択します。
** コントローラアイコン（「* Shelf *」ドロップダウン・リストの横）を選択します。デュプレックス構成の場合は、ダイアログボックスから* Controller A*または* Controller B*を選択し、* Next *をクリックします。
+
Controller Settings（コントローラ設定）ダイアログボックスが開きます。



. タブを選択して、プロパティ設定間を移動します。
+
一部のタブには、右上に[詳細設定を表示]*のリンクがあります。

+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| タブをクリックする | 説明 


 a| 
ベース（ Base ）
 a| 
コントローラのステータス、モデル名、交換パーツ番号、現在のファームウェアバージョン、不揮発性静的ランダムアクセスメモリ（NVSRAM）バージョンが表示されます。



 a| 
キャッシュ
 a| 
コントローラのキャッシュ設定が表示されます。これには、データキャッシュ、プロセッサキャッシュ、およびキャッシュバックアップデバイスが含まれます。キャッシュバックアップデバイスは、コントローラへの電源が喪失した場合にデータをキャッシュにバックアップするために使用されます。ステータスは最適、失敗、取り外し、不明、書き込み禁止、 または互換性なし。



 a| 
ホストインターフェイス
 a| 
ホストインターフェイスの情報と各ポートのリンクステータスが表示されます。ホストインターフェイスは、Fibre ChannelやiSCSIなど、コントローラとホストの間の接続です。


NOTE: ホストインターフェイスカード（HIC）の場所は、ベースボード内またはスロット（ベイ）内のいずれかです。「Baseboard」は、HICポートがコントローラに組み込まれていることを示します。「Slot」ポートはオプションのHICに搭載されています。



 a| 
ドライブインターフェイス
 a| 
ドライブインターフェイスの情報と各ポートのリンクステータスが表示されます。ドライブインターフェイスは、コントローラとドライブ（SASなど）の間の接続です。



 a| 
管理ポート
 a| 
コントローラへのアクセスに使用されるホスト名、リモートログインが有効になっているかどうかなど、管理ポートの詳細が表示されます。管理ポートは、コントローラと管理クライアントを接続します。このポートには、System Managerにアクセスするためのブラウザがインストールされています。



 a| 
DNS / NTP
 a| 
は、DNSサーバとNTPサーバがSystem Managerで設定されている場合のアドレス指定方法とIPアドレスを示しています。

Domain Name System（DNS；ドメインネームシステム）は、インターネットまたはプライベートネットワークに接続されたデバイスの命名システムです。DNSサーバはドメイン名のディレクトリを保持し、IPアドレスに変換します。

Network Time Protocol（NTP；ネットワークタイムプロトコル）は、データネットワーク内のコンピュータシステム間でクロック同期を行うためのネットワークプロトコルです。

|===
====
. [* 閉じる * ] をクリックします。

