---
permalink: sm-hardware/view-controller-settings.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, controller, settings 
summary: ホストインターフェイス、ドライブインターフェイス、管理ポートのステータスなど、コントローラに関する情報を確認できます。 
---
= SANtricity System Managerでコントローラ設定を表示する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ホストインターフェイス、ドライブインターフェイス、管理ポートのステータスなど、コントローラに関する情報を確認できます。

.手順
. 左側のパネルから、menu:Hardware[Controllers and components]を選択します。
. 次のいずれかを実行してコントローラの設定を表示します。
+
** コントローラをクリックしてコンテキストメニューを表示し、*設定の表示*を選択します。
** コントローラアイコン（「* Shelf *」ドロップダウン・リストの横）を選択します。デュプレックス構成の場合は、ダイアログボックスから* Controller A*または* Controller B*を選択し、* Next *をクリックします。
+
コントローラー設定のスライドメニューが開きます。



. コントローラーのプロパティ設定間を移動するには、該当セクションを確認してください。
+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| セクション | 説明 


 a| 
詳細
 a| 
コントローラーの状態、日付/時刻、モデル名、交換部品番号を表示します。



 a| 
現状の構成
 a| 
現在のファームウェアバージョンとNVRAMバージョンを表示します。



 a| 
データキャッシュ
 a| 
データキャッシュの合計値を表示します。



 a| 
データキャッシュモジュール
 a| 
キャッシュモジュールの位置、状態、容量を表示します。



 a| 
プロセッサキャッシュ
 a| 
プロセッサキャッシュの合計値を表示します。



 a| 
キャッシュバックアップデバイス
 a| 
キャッシュバックアップデバイスの場所、状態、および容量を表示します。



 a| 
ホスト インターフェイス
 a| 
各ポートのホスト インターフェイス情報とリンクステータスを表示します。



 a| 
ドライブインターフェース
 a| 
各ポートのドライブインターフェース情報とリンク状態を表示します。



 a| 
管理ポート設定
 a| 
コントローラーのホスト名、リモートログイン情報、IPネットワーク設定など、管理ポートの詳細を表示します。



 a| 
ドメインネームシステム（DNS）サーバー設定
 a| 
DNS構成、プライマリDNSサーバー、およびバックアップDNSサーバーを表示します。



 a| 
ネットワークタイムプロトコル（NTP）サーバーの設定
 a| 
NTPサービスおよびNTPサーバーの設定詳細を表示します。

|===
====
. [* 閉じる * ] をクリックします。

