---
permalink: sm-hardware/what-is-ipv6-stateless-address-auto-configuration.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, ipv6, stateless, address, auto, configuration, 
summary: ステートレス自動設定を使用すると、ホストはアドレスやその他の設定情報をサーバから取得しません。 
---
= IPv6ステートレスアドレス自動設定とは何ですか。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ステートレス自動設定を使用すると、ホストはアドレスやその他の設定情報をサーバから取得しません。

IPv6のステートレス自動設定には、リンクローカルアドレス、マルチキャスト、近接探索（ND）プロトコルなどの機能があります。IPv6では、アドレスのインターフェイスIDが基盤のデータリンクレイヤアドレスから生成されます。

ステートレス自動設定とステートフル自動設定は、相互に補完しあう機能です。たとえば、ホストはステートレス自動設定を使用して自身のアドレスを設定できますが、その他の情報はステートフル自動設定を使用して取得します。ステートフル自動設定を使用すると、ホストはサーバからアドレスやその他の設定情報を取得できます。IPv6は、ネットワーク上のすべてのIPアドレスを一度に再割り当てする方法も定義します。IPv6では、ネットワーク上のデバイスがIPアドレスやその他のパラメータをサーバなしで自動的に設定する方法を定義しています。

ステートレス自動設定を使用する場合、デバイスは次の手順を実行します。

. *リンクローカルアドレスを生成*--デバイスは10ビットのリンクローカルアドレスを生成し、その後に54個のゼロと64ビットのインターフェイスIDを生成します。
. *リンクローカルアドレスの一意性をテスト*--生成されるリンクローカルアドレスがローカルネットワークでまだ使用されていないことをテストしますデバイスがNDプロトコルを使用して近接要求メッセージを送信します。これに応答して、ローカルネットワークはネイバーアドバタイズメントメッセージをリスンします。このメッセージは、別のデバイスがすでにリンクローカルアドレスを使用していることを示します。その場合は、新しいリンクローカルアドレスを生成する必要があるか、自動設定が失敗して別の方法を使用する必要があります。
. *リンクローカルアドレスの割り当て*--一意性テストに合格すると、デバイスは自身のIPインタフェースにリンクローカルアドレスを割り当てます。リンクローカルアドレスは、ローカルネットワーク上での通信には使用できますが、インターネット上では使用できません。
. *ルータに連絡*--ノードは、設定の続行の詳細についてローカルルータへの接続を試みます。具体的には、ルータから定期的に送信されるルータ通知メッセージをリスンするか、または次に必要な作業についてルータに問い合わせるルータ要求メッセージをルータに送信します。
. *ノードへの指示*--ルーターは自動設定の続行方法をノードに指示します。または、ルータは、グローバルインターネットアドレスの決定方法をホストに指示します。
. *グローバルアドレスを設定*--ホストは、グローバルに一意なインターネットアドレスを自身に設定します。このアドレスは、通常、ルータからホストに提供されるネットワークプレフィックスから形成されます。

