---
permalink: um-manage/considerations-for-discovering-arrays.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, considerations, discovering, arrays 
summary: Unified Managerでストレージリソースを表示および管理するには、組織のネットワークで管理するストレージアレイを検出する必要があります。複数のアレイを検出することも、単一のアレイを検出することもできます。 
---
= アレイの検出に関する考慮事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SANtricity Unified Managerでストレージリソースを表示して管理するには、組織のネットワークから管理対象のストレージアレイを検出する必要があります。複数のアレイを検出することも、単一のアレイを検出することもできます。



== 複数のストレージアレイを検出しています

複数のアレイを検出する場合は、ネットワークIPアドレスの範囲を入力すると、その範囲の各IPアドレスへの接続がUnified Managerで個別に試行されます。到達したストレージアレイが検出ページに表示され、管理ドメインに追加されることがあります。



== 単一のストレージアレイを検出しています

単一のアレイを検出する場合は、ストレージアレイのいずれかのコントローラのIPアドレスを1つ入力すると、そのストレージアレイが追加されます。

[NOTE]
====
Unified Managerは、あるコントローラに割り当てられている1つのIPアドレスまたは範囲内のIPアドレスのみを検出して表示します。代替のコントローラまたはそれらのコントローラに割り当てられているIPアドレスがあっても、この1つのIPアドレスまたはIPアドレス範囲に含まれていなければ、Unified Managerでは検出または表示されません。ただし、ストレージアレイを追加すると、関連付けられているすべてのIPアドレスが検出され、管理ビューに表示されます。

====


== ユーザクレデンシャル

検出プロセスでは、追加する各ストレージアレイの管理者パスワードが必要になります。



== Webサービスの証明書

検出プロセスでは、検出されたストレージアレイに信頼できるソースからの証明書があるかどうかがUnified Managerで確認されます。Unified Managerでは、ブラウザで確立するすべての接続に対して2種類の証明書ベースの認証を使用します。

* *信頼された証明書*
+
Unified Managerで検出されたアレイについては、認証局が発行する信頼された証明書が追加で必要となる場合があります。

+
これらの証明書をインポートするには、* Import *ボタンを使用します。このアレイに前に接続したことがある場合は、一方または両方のコントローラの証明書が期限切れになっているか、失効しているか、証明書チェーンにルート証明書または中間証明書がない可能性があります。ストレージアレイの管理を開始する前に、期限切れまたは失効した証明書を差し替えるか、不足しているルート証明書または中間証明書を追加する必要があります。

* *自己署名証明書*
+
自己署名証明書を使用することもできます。署名済みの証明書をインポートせずにアレイを検出しようとすると、Unified Managerにエラーダイアログボックスが表示されます。このダイアログボックスで自己署名証明書を承認することができます。自己署名証明書が信頼済みとしてマークされ、Unified Managerにストレージアレイが追加されます。

+
ストレージアレイへの接続を信頼しない場合は、Unified Managerにストレージアレイを追加する前に* Cancel *を選択し、ストレージアレイのセキュリティ証明書戦略を検証します。


