---
permalink: um-manage/create-synchronous-mirrored-pair-um.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, create, synchronous, mirrored, pair 
summary: 同期ミラーリングを設定するには、ローカルアレイのプライマリボリュームとリモートアレイのセカンダリボリュームを含むミラーペアを作成します。 
---
= 同期ミラーペアを作成する
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
同期ミラーリングを設定するには、ローカルアレイのプライマリボリュームとリモートアレイのセカンダリボリュームを含むミラーペアを作成します。

[NOTE]
====
この機能は、EF600またはEF300ストレージシステムでは使用できません。

====
.作業を開始する前に
ミラーペアを作成する前に、Unified Managerに関する次の要件を満たしている必要があります。

* Web Services Proxyサービスが実行されている必要があります。
* Unified ManagerがHTTPS接続経由でローカルホストで実行されている必要があります。
* Unified Managerにストレージアレイの有効なSSL証明書が表示されている必要があります。Unified Managerのメニューから「Certificate Management」に移動し、自己署名証明書を受け入れるか、独自のセキュリティ証明書をインストールできます。


また、ストレージアレイとボリュームに関する次の要件を満たしていることも確認してください。

* ミラーリングに使用する2つのストレージアレイがUnified Managerで検出されている必要があります。
* 各ストレージアレイに2台のコントローラが必要です。
* プライマリアレイとセカンダリアレイの各コントローラにイーサネット管理ポートが設定されていて、各コントローラがネットワークに接続されている必要があります。
* ストレージアレイに必要なファームウェアの最小バージョンは7.84です（それぞれ異なるバージョンのOSを実行できます）。
* ローカルとリモートのストレージアレイのパスワードを確認しておく必要があります。
* ローカルとリモートのストレージアレイをFibre Channelファブリックを介して接続します。
* 同期ミラー関係で使用するプライマリボリュームとセカンダリボリュームの両方を作成しておきます。
* プライマリボリュームは標準ボリュームである必要があります。シンボリュームやSnapshotボリュームは使用できません。
* セカンダリボリュームは標準ボリュームである必要があります。シンボリュームやSnapshotボリュームは使用できません。
* セカンダリボリュームには、プライマリボリュームと同等以上のサイズが必要です。


.このタスクについて
同期ミラーペアを作成するプロセスは複数の手順で構成される手順 です。



== 手順1：プライマリボリュームを選択します

この手順では、同期ミラー関係で使用するプライマリボリュームを選択します。ローカルストレージアレイのプライマリボリュームを選択すると、そのミラーペアに対応するすべてのボリュームのリストが表示されます。使用できないボリュームはリストに表示されません。選択するボリュームには、ミラー関係のプライマリロールが割り当てられます。

.手順
. [* Manage *（管理）]ページで、ソースに使用するローカルストレージアレイを選択します。
. メニューを選択します。アクション[同期ミラーペアの作成]。
+
同期ミラーペアの作成ウィザードが開きます。

. 対応するボリュームのリストから、ミラーのプライマリボリュームとして使用するボリュームを選択します。
. [次へ]を選択し、に進みます <<手順2：セカンダリボリュームを選択する>>。




== 手順2：セカンダリボリュームを選択する

この手順では、ミラー関係で使用するセカンダリボリュームを選択します。リモートストレージアレイのセカンダリボリュームを選択すると、そのミラーペアに対応するすべてのボリュームのリストが表示されます。使用できないボリュームはリストに表示されません。選択するボリュームには、ミラー関係のセカンダリロールが割り当てられます。

.手順
. ローカルストレージアレイとの間でミラー関係を確立するリモートストレージアレイを選択します。
+
[NOTE]
====
リモートストレージアレイがパスワードで保護されている場合は、パスワードの入力を求められます。

====
+
** ストレージアレイは、対応するストレージアレイ名別に表示されます。ストレージアレイに名前を付けていない場合は、「unnamed」と表示されます。
** 使用するストレージアレイがリストにない場合は、Unified Managerでそのストレージアレイが検出されていることを確認してください。


. 対応するボリュームのリストから、ミラーのセカンダリボリュームとして使用するボリュームを選択します。
+
[NOTE]
====
選択したセカンダリボリュームの容量がプライマリボリュームよりも大きい場合、使用可能な容量はプライマリボリュームのサイズまでに制限されます。

====
. 「*次へ*」をクリックして、に進みます <<手順3：同期設定を選択します>>。




== 手順3：同期設定を選択します

この手順では、通信中断後のデータの同期方法を決定する設定を選択します。通信が中断した場合に、プライマリボリュームの所有コントローラがセカンダリボリュームとの間でデータを再同期する優先度を設定できます。また、再同期ポリシーとして、手動または自動のどちらかを選択する必要があります。

.手順
. スライダバーを使用して同期優先度を設定します。
+
同期優先度は、I/O要求の処理と比較して、初期同期および通信中断後の再同期処理を完了するためにどの程度のシステムリソースが使用されるかを決定するものです。

+
このダイアログ環境 で設定した優先度。プライマリボリュームとセカンダリボリュームの両方に適用されます。プライマリボリュームの速度は、あとからSystem Managerでメニューを選択して変更できます。Storage [Synchronous Mirroring > More > Edit Settings]を選択します。

+
同期優先度は5段階で設定できます。

+
** 最低
** 低
** 中
** 高
** 最高
+
同期優先度を最低に設定すると、I/Oアクティビティが優先され、再同期処理にかかる時間が長くなります。同期優先度が最高に設定されている場合は再同期処理が優先されますが、ストレージアレイのI/Oアクティビティに影響する可能性があります。



. リモートストレージアレイのミラーペアの再同期を手動で行うか自動で行うかを選択します。
+
** *手動*（推奨オプション）-ミラーペアとの通信が回復したあとに同期を手動で再開する場合に選択します。このオプションを選択すると、最適なタイミングでデータをリカバリできます。
** *自動*--ミラーペアとの通信が回復した後、再同期を自動的に開始する場合に選択します。
+
同期を手動で再開するには、System Managerでメニューから「Storage [Synchronous Mirroring]（ストレージ同期ミラーリング）を選択し、テーブルでミラーペアを強調表示して、「* More *」（詳細*）で「Resume *」（続行）を選択します。



. 完了*をクリックして、同期ミラーリングを完了します。


.結果
ミラーリングがアクティブ化されると、システムは次の処理を実行します。

* ローカルストレージアレイとリモートストレージアレイの間で初期同期を開始します。
* 同期優先度と再同期ポリシーを設定します。
* コントローラのHICで最も大きい番号のポートをデータ送信のミラーリング用に予約します。
+
このポートで受信したI/O要求は、ミラーペアに含まれるセカンダリボリュームのリモートの優先コントローラ所有者からのみ承認されます。（プライマリボリュームにおける予約が許可されます）。

* コントローラごとに1つずつ、リザーブ容量用ボリュームを2つ作成します。これは、コントローラのリセットおよびその他の一時的な中断からリカバリするための書き込み情報のロギングに使用されます。
+
各ボリュームの容量は128MiBです。ただし、ボリュームがプールに配置されている場合は、ボリュームごとに4GiBが予約されます。



.完了後
System Managerに移動して、メニューHome（View Operations in Progress）を選択し、同期ミラーリング処理の進捗状況を表示します。この処理には時間がかかることがあり、システムのパフォーマンスに影響する可能性があります。
