---
permalink: um-manage/create-asynchronous-mirrored-pair-um.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, create, asynchronous, mirrored, pair 
summary: 非同期ミラーリングを設定するには、ローカルアレイのプライマリボリュームとリモートアレイのセカンダリボリュームを含むミラーペアを作成します。 
---
= 非同期ミラーペアを作成する
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
非同期ミラーリングを設定するには、ローカルアレイのプライマリボリュームとリモートアレイのセカンダリボリュームを含むミラーペアを作成します。

[NOTE]
====
この機能は、EF600またはEF300ストレージシステムでは使用できません。

====
.作業を開始する前に
ミラーペアを作成する前に、Unified Managerに関する次の要件を満たしている必要があります。

* Web Services Proxyサービスが実行されている必要があります。
* Unified ManagerがHTTPS接続経由でローカルホストで実行されている必要があります。
* Unified Managerにストレージアレイの有効なSSL証明書が表示されている必要があります。Unified Managerのメニューから「Certificate Management」に移動し、自己署名証明書を受け入れるか、独自のセキュリティ証明書をインストールできます。


また、ストレージアレイとボリュームに関する次の要件を満たしていることも確認してください。

* 各ストレージアレイに2台のコントローラが必要です。
* Unified Managerで2つのストレージアレイが検出されている必要があります。
* プライマリアレイとセカンダリアレイの各コントローラにイーサネット管理ポートが設定されていて、各コントローラがネットワークに接続されている必要があります。
* ストレージアレイに必要なファームウェアの最小バージョンは7.84です（それぞれ異なるバージョンのOSを実行できます）。
* ローカルとリモートのストレージアレイのパスワードを確認しておく必要があります。
* ミラーリングするプライマリボリューム以上のセカンダリボリュームを作成するには、リモートストレージアレイに十分な空き容量が必要です。
* ローカルとリモートのストレージアレイをFibre ChannelファブリックまたはiSCSIインターフェイスを介して接続します。
* 非同期ミラー関係で使用するプライマリボリュームとセカンダリボリュームの両方を作成しておきます。
* セカンダリボリュームには、プライマリボリュームと同等以上のサイズが必要です。


.このタスクについて
非同期ミラーペアを作成するプロセスは複数の手順で構成される手順 です。



== 手順1：ミラー整合性グループを作成または選択します

この手順では、新しいミラー整合性グループを作成するか、既存のグループを選択します。ミラー整合性グループは、プライマリボリュームとセカンダリボリューム（ミラーペア）のコンテナであり、グループ内のすべてのペアに対して必要な再同期方法（手動または自動）を指定します。

.手順
. [* Manage *（管理）]ページで、ソースに使用するローカルストレージアレイを選択します。
. メニューを選択します。アクション[非同期ミラーペアの作成]。
+
非同期ミラーペアの作成ウィザードが開きます。

. 既存のミラー整合性グループを選択するか、新規に作成します。
+
既存のグループを選択するには、「*既存のミラー整合グループ*」が選択されていることを確認してから、表からグループを選択してください。整合性グループには複数のミラーペアを含めることができます。

+
新しいグループを作成するには、次の手順を実行します。

+
.. 新しいミラー整合性グループを選択*し、*次へ*をクリックします。
.. 2つのストレージアレイ間でミラーリングするボリュームのデータを表す、一意の名前を入力します。名前に使用できる文字は、アルファベット、数字、およびアンダースコア（_）、ダッシュ（-）、ハッシュ記号（#）のみです。最大文字数は30文字で、スペースは使用できません。
.. ローカルストレージアレイとの間でミラー関係を確立するリモートストレージアレイを選択します。
+
[NOTE]
====
リモートストレージアレイがパスワードで保護されている場合は、パスワードの入力を求められます。

====
.. ミラーペアの同期を手動で行うか自動で行うかを選択します。
+
*** *手動*-このオプションは、グループ内のすべてのミラーペアの同期を手動で開始する場合に選択します。再同期をあとで実行する場合は、プライマリストレージアレイのSystem Managerを起動して、メニューから「Storage [Asynchronous Mirroring]」に移動し、「Mirror Consistency Groups *」タブでグループを選択して、メニューから「More [Manually resynchronize ]」を選択する必要があります。
*** *自動*--前回の更新の開始から次の更新の開始までの間隔を*分*、*時間*、または*日*で選択します。たとえば、同期間隔を30分に設定し、同期プロセスを午後4時に開始すると、次のプロセスは午後4時30分に開始されます


.. 必要なアラート設定を選択します。
+
*** 手動同期の場合は、アラートを受信するときのしきい値（残りの容量の割合によって定義）を指定します。
*** 自動同期の場合は、次の3つのアラート方法を設定できます。 同期が特定の時間内に完了していない場合、リモートアレイのリカバリポイントデータが特定の期限よりも古くなった場合、およびリザーブ容量が特定のしきい値（残りの容量の割合によって定義）に近づいている場合。




. [次へ]を選択し、に進みます <<手順2：プライマリボリュームを選択する>>。
+
新しいミラー整合性グループを定義した場合は、Unified Managerによって、最初にローカルストレージアレイに、続いてリモートストレージアレイにミラー整合性グループが作成されます。各アレイのSystem Managerを起動すると、ミラー整合性グループを表示および管理できます。

+
[NOTE]
====
Unified Managerによるミラー整合性グループの作成がローカルストレージアレイで成功したあと、リモートストレージアレイで失敗した場合は、ローカルストレージアレイからミラー整合性グループが自動的に削除されます。Unified Managerによるミラー整合性グループの削除でエラーが発生した場合は、手動で削除する必要があります。

====




== 手順2：プライマリボリュームを選択する

この手順では、ミラー関係で使用するプライマリボリュームを選択し、リザーブ容量を割り当てます。ローカルストレージアレイのプライマリボリュームを選択すると、そのミラーペアに対応するすべてのボリュームのリストが表示されます。使用できないボリュームはリストに表示されません。

ローカルストレージアレイのミラー整合性グループに追加するボリュームには、ミラー関係のプライマリロールが割り当てられます。

.手順
. 対応するボリュームのリストからプライマリボリュームとして使用するボリュームを選択し、* Next *をクリックしてリザーブ容量を割り当てます。
. 対応する候補のリストから、プライマリボリュームのリザーブ容量を選択します。
+
次のガイドラインに注意してください。

+
** リザーブ容量のデフォルト設定はベースボリュームの容量の20%であり、通常はこの容量で十分です。割合を変更する場合は、[*候補の更新*]をクリックします。
** 必要な容量は、プライマリボリュームに対するI/O書き込みの頻度とサイズ、およびその容量を維持する必要がある期間によって異なります。
** 一般に、次のいずれかまたは両方に該当する場合は、リザーブ容量を大きくします。
+
*** ミラーペアを長期にわたって維持する場合。
*** 大量のI/Oアクティビティにより、プライマリボリュームのデータブロックの大部分で変更が発生する場合。プライマリボリュームに対する一般的なI/Oアクティビティを判断するには、過去のパフォーマンスデータやその他のオペレーティングシステムユーティリティを使用します。




. [次へ]を選択し、に進みます <<手順3：セカンダリボリュームを選択する>>。




== 手順3：セカンダリボリュームを選択する

この手順では、ミラー関係で使用するセカンダリボリュームを選択し、リザーブ容量を割り当てます。リモートストレージアレイのセカンダリボリュームを選択すると、そのミラーペアに対応するすべてのボリュームのリストが表示されます。使用できないボリュームはリストに表示されません。

リモートストレージアレイのミラー整合性グループに追加するボリュームには、ミラー関係のセカンダリロールが割り当てられます。

.手順
. 対応するボリュームのリストから、ミラーペアのセカンダリボリュームとして使用するボリュームを選択し、* Next *をクリックしてリザーブ容量を割り当てます。
. 対応する候補のリストから、セカンダリボリュームのリザーブ容量を選択します。
+
次のガイドラインに注意してください。

+
** リザーブ容量のデフォルト設定はベースボリュームの容量の20%であり、通常はこの容量で十分です。割合を変更する場合は、[*候補の更新*]をクリックします。
** 必要な容量は、プライマリボリュームに対するI/O書き込みの頻度とサイズ、およびその容量を維持する必要がある期間によって異なります。
** 一般に、次のいずれかまたは両方に該当する場合は、リザーブ容量を大きくします。
+
*** ミラーペアを長期にわたって維持する場合。
*** 大量のI/Oアクティビティにより、プライマリボリュームのデータブロックの大部分で変更が発生する場合。プライマリボリュームに対する一般的なI/Oアクティビティを判断するには、過去のパフォーマンスデータやその他のオペレーティングシステムユーティリティを使用します。




. 「* Finish *」を選択して、非同期ミラーリングのシーケンスを完了します。


.結果
Unified Managerは次の処理を実行します。

* ローカルストレージアレイとリモートストレージアレイの間で初期同期を開始します。
* ローカルストレージアレイとリモートストレージアレイにミラーペア用のリザーブ容量を作成します。



NOTE: ミラーリングしているボリュームがシンボリュームの場合、初期同期では、プロビジョニングされたブロック（レポート容量ではなく割り当て容量）のみがセカンダリボリュームに転送されます。これにより、初期同期を完了するために転送する必要があるデータの量が削減されます。
