---
permalink: um-manage/discover-multiple-arrays.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, discover, multiple, storage, arrays 
summary: 複数のアレイの検出では、管理サーバが配置されているサブネット全体からすべてのストレージアレイを検出し、検出されたアレイを管理ドメインに自動的に追加します。 
---
= 複数のストレージアレイを検出する
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
複数のアレイの検出では、管理サーバが配置されているサブネット全体からすべてのストレージアレイを検出し、検出されたアレイを管理ドメインに自動的に追加します。

.作業を開始する前に
* Security Adminの権限を含むユーザプロファイルでログインする必要があります。
* ストレージアレイが正しくセットアップおよび設定されている必要があります。
* ストレージアレイのパスワードは、System Managerのアクセス管理タイルを使用して設定する必要があります。
* 信頼されていない証明書を解決するには、認証局（CA）の信頼された証明書ファイルが必要です。証明書ファイルはローカルシステムにあります。


アレイの検出は、複数の手順からなる手順 です。



== 手順1：ネットワークアドレスを入力します

ローカルのサブネットワーク全体を検索するには、ネットワークアドレス範囲を入力します。到達したストレージアレイが検出ページに表示され、管理ドメインに追加されることがあります。

何らかの理由で検出操作を停止する必要がある場合は、*検出の停止*をクリックします。

.手順
. [ 管理 ] ページで、 [ * 追加 / 検出 * ] を選択します。
+
Add/Discoverダイアログボックスが表示されます。

. [*ネットワーク範囲内のすべてのストレージアレイを検出する*]ラジオボタンを選択します。
. 開始ネットワークアドレスと終了ネットワークアドレスを入力して、ローカルサブネットワーク全体を検索し、*検出の開始*をクリックします。
+
検出プロセスが開始されます。この検出プロセスが完了するまでに数分かかることがあります。ストレージアレイが検出されると、検出ページの表にデータが表示されます。

+
[NOTE]
====
管理可能なアレイが検出されない場合は、ストレージアレイがネットワークに適切に接続されていて、割り当てられたアドレスが範囲内にあることを確認してください。[ 新規検出パラメータ * ] をクリックして、 [ 追加 / 検出 ] ページに戻ります。

====
. 検出されたストレージアレイのリストを確認します。
. 管理ドメインに追加するストレージアレイの横にあるチェックボックスをオンにし、[*次へ*]をクリックします。
+
管理ドメインに追加する各アレイについて、Unified Managerでクレデンシャルのチェックが実行されます。そのアレイに関連付けられている自己署名証明書や信頼されていない証明書の解決が必要になる場合があります。

. 「 * 次へ * 」をクリックして、ウィザードの次の手順に進みます。




== 手順2：検出時に自己署名証明書を解決する

検出プロセスでは、ストレージアレイに信頼できるソースからの証明書があるかどうかが確認されます。

.手順
. 次のいずれかを実行します。
+
** 検出されたストレージアレイへの接続を信頼する場合は、ウィザードの次のカードに進みます。自己署名証明書は信頼済みとしてマークされ、Unified Managerにストレージアレイが追加されます。
** ストレージアレイへの接続を信頼しない場合は、*キャンセル*を選択し、各ストレージアレイのセキュリティ証明書戦略を検証してからUnified Managerに追加してください。


. 「 * 次へ * 」をクリックして、ウィザードの次の手順に進みます。




== 手順3：検出時に信頼されていない証明書を解決する

信頼されていない証明書の問題は、ストレージアレイからUnified Managerへのセキュアな接続を確立しようとしたときに、接続がセキュアであることが確認できないと発生します。アレイの検出プロセスでは、信頼されていない証明書を解決するために、信頼できる第三者機関が発行した認証局（CA）証明書（CA署名証明書）をインポートします。

信頼された追加のCA証明書のインストールが必要になる可能性があるのは、次のいずれかに該当する場合です。

* ストレージアレイを新たに追加した。
* 一方または両方の証明書の期限が切れている。
* 一方または両方の証明書が失効している。
* 一方または両方の証明書のルート証明書または中間証明書がない。


.手順
. 信頼されていない証明書を解決するストレージアレイの横にあるチェックボックスをオンにして、[**インポート**]ボタンを選択します。
+
信頼された証明書ファイルをインポートするためのダイアログボックスが表示されます。

. Browse（参照）*をクリックして、ストレージアレイの証明書ファイルを選択します。
+
ダイアログボックスにファイル名が表示されます。

. [* インポート * ] をクリックします。
+
ファイルがアップロードされて検証されます。

+
[NOTE]
====
信頼されていない証明書の問題が未解決のストレージアレイはUnified Managerに追加されません。

====
. 「 * 次へ * 」をクリックして、ウィザードの次の手順に進みます。




== 手順4：パスワードを入力する

管理ドメインに追加するストレージアレイのパスワードを入力する必要があります。

.手順
. Unified Managerに追加する各ストレージアレイのパスワードを入力します。
. *オプション：*ストレージアレイをグループに関連付けます。ドロップダウンリストから、選択したストレージアレイを関連付ける目的のグループを選択します。
. [ 完了 ] をクリックします。


.完了後
ストレージアレイが管理ドメインに追加され、指定した場合は選択したグループに関連付けられます。

[NOTE]
====
Unified Managerから指定のストレージアレイへの接続が確立されるまでに数分かかることがあります。

====