---
permalink: um-manage/faq-storage-mirroring.html 
sidebar: sidebar 
keywords:  
summary: この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。 
---
= SANtricity Unified Manager のストレージミラーリングに関する FAQ
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。



== ミラー整合性グループを作成するときは、どのような点に注意する必要がありますか？

ミラー整合性グループを作成する際は、次のガイドラインに従ってください。

Unified Managerに関する次の要件を満たしている必要があります。

* Web Services Proxyサービスが実行されている必要があります。
* Unified ManagerがHTTPS接続経由でローカルホストで実行されている必要があります。
* Unified Managerにストレージアレイの有効なSSL証明書が表示されている必要があります。Unified Managerのメニューから「Certificate Management」に移動し、自己署名証明書を受け入れるか、独自のセキュリティ証明書をインストールできます。


また、ストレージアレイに関する次の要件を満たしていることも確認してください。

* Unified Managerで2つのストレージアレイが検出されている必要があります。
* 各ストレージアレイに2台のコントローラが必要です。
* プライマリアレイとセカンダリアレイの各コントローラにイーサネット管理ポートが設定されていて、各コントローラがネットワークに接続されている必要があります。
* ストレージアレイに必要なファームウェアの最小バージョンは7.84です（それぞれ異なるバージョンのOSを実行できます）。
* ローカルとリモートのストレージアレイのパスワードを確認しておく必要があります。
* ローカルとリモートのストレージアレイをFibre ChannelファブリックまたはiSCSIインターフェイスを介して接続します。


[NOTE]
====
同期ミラーリングは、EF600 / EF600CまたはEF300 / EF300Cストレージシステムでは使用できません。

====


== ミラーペアを作成するときは、どのような点に注意する必要がありますか？

ミラーペアを作成する際は、次のガイドラインに従ってください。

* 2つのストレージアレイが必要です。
* 各ストレージアレイに2台のコントローラが必要です。
* Unified Managerで2つのストレージアレイが検出されている必要があります。
* プライマリアレイとセカンダリアレイの各コントローラにイーサネット管理ポートが設定されていて、各コントローラがネットワークに接続されている必要があります。
* ストレージアレイに必要なファームウェアの最小バージョンは7.84です（それぞれ異なるバージョンのOSを実行できます）。
* ローカルとリモートのストレージアレイのパスワードを確認しておく必要があります。
* ミラーリングするプライマリボリューム以上のセカンダリボリュームを作成するには、リモートストレージアレイに十分な空き容量が必要です。
* 非同期ミラーリングはFibre Channel（FC）またはiSCSIホストポートを搭載したコントローラでサポートされますが、同期ミラーリングはFCホストポートを搭載したコントローラでのみサポートされます。


[NOTE]
====
同期ミラーリングは、EF600 / EF600CまたはEF300 / EF300Cストレージシステムでは使用できません。

====


== この割合を変更するのはどのような場合ですか？

非同期ミラーリング処理用のリザーブ容量は、一般にベースボリュームの20%です。通常はこの容量で十分です。

必要な容量は、ベースボリュームに対するI/O書き込みの頻度とサイズ、およびストレージオブジェクトのコピーサービス処理を使用する期間によって異なります。一般に、次のいずれかまたは両方に該当する場合は、リザーブ容量の割合を大きくします。

* 特定のストレージオブジェクトのコピーサービス処理の期間が非常に長い場合。
* 大量のI/Oアクティビティにより、ベースボリュームのデータブロックの大部分で変更が発生する場合。ベースボリュームに対する一般的なI/Oアクティビティを判断するには、過去のパフォーマンスデータやその他のオペレーティングシステムユーティリティを使用します。




== リザーブ容量の候補が複数表示されるのはなぜですか？

プールまたはボリュームグループ内にストレージオブジェクトに対して選択した容量の割合を満たす複数のボリュームがある場合は、複数の候補が表示されます。

ベースボリューム上でコピーサービス処理用にリザーブする物理ドライブスペースの割合を変更すると、推奨される候補の一覧が更新されます。選択内容に基づいて最適な候補が表示されます。



== ボリュームが一部表示されないのはなぜですか?

ミラーペアのプライマリボリュームを選択すると、対応するすべてのボリュームのリストが表示されます。

使用できないボリュームはリストに表示されません。次のいずれかの理由で、ボリュームが対象外になっている可能性があります。

* 最適状態でない。
* すでにミラー関係に参加している。
* 同期ミラーリングの場合、ミラーペアのプライマリボリュームとセカンダリボリュームは標準ボリュームである必要があります。シンボリュームやSnapshotボリュームは使用できません。
* 非同期ミラーリングの場合は、シンボリュームで自動拡張が有効になっている必要があります。



NOTE: EF600およびEF300コントローラでは、非同期ミラーペアのプライマリボリュームとセカンダリボリュームのプロトコル、トレイレベル、セグメントサイズ、セキュリティタイプ、およびRAIDレベルが同じである必要があります。対応していない非同期ミラーペアは、使用可能なボリュームのリストに表示されません。



== リモート ストレージ アレイのボリュームが一部表示されないのはなぜですか?

リモートストレージアレイ上のセカンダリボリュームを選択すると、そのミラーペアに対応するすべてのボリュームのリストが表示されます。

使用できないボリュームはリストに表示されません。次のいずれかの理由で、ボリュームが対象外になっている可能性があります。

* ボリュームが、Snapshotボリュームなどの標準以外のボリュームである。
* 最適状態でない。
* すでにミラー関係に参加している。
* 非同期ミラーリングでは、プライマリボリュームとセカンダリボリュームの間のシンボリューム属性が一致しません。
* Data Assurance（DA）を使用する場合、プライマリボリュームとセカンダリボリュームでDA設定を同じにする必要があります。
+
** プライマリボリュームでDAを有効にする場合、セカンダリボリュームでもDAを有効にする必要があります。
** プライマリボリュームでDAを有効にしない場合、セカンダリボリュームでもDAを無効にする必要があります。


* 非同期ミラーリングを使用する場合は、プライマリボリュームとセカンダリボリュームでドライブセキュリティ機能が同じでなければなりません。
+
** プライマリボリュームがFIPSに対応している場合、セカンダリボリュームはFIPSに対応している必要があります。
** プライマリボリュームがFDEに対応している場合、セカンダリボリュームはFDEに対応している必要があります。
** プライマリボリュームでドライブセキュリティを使用していない場合、セカンダリボリュームでドライブセキュリティを使用していない必要があります。






== 同期優先度は同期速度にどのような影響を与えますか？

同期優先度は、同期アクティビティに割り当てられる処理時間をシステムパフォーマンスと比較して決定します。

プライマリボリュームのコントローラ所有者は、この処理をバックグラウンドで実行します。同時にコントローラ所有者は、プライマリボリュームへのローカルのI/O書き込みと、対応するセカンダリボリュームへのリモートの書き込みを処理します。再同期には、I/Oアクティビティに使用されるはずのコントローラの処理リソースが使用されるため、再同期がホストアプリケーションのパフォーマンスに影響する可能性があります。

同期優先度に応じた所要時間や、同期優先度がシステムパフォーマンスに与える影響を特定する際には、次のガイドラインに注意してください。

優先度は次のとおりです。

* 最低
* 低
* 中
* 高
* 最高


最低ではシステムパフォーマンスが優先されますが、再同期化に時間がかかります。最高では再同期化が優先されますが、システムパフォーマンスが低下する可能性があります。

これらのガイドラインは、各優先度の大まかな違いを示しています。

[cols="45h,~"]
|===
| 完全同期の優先度 | 最高の同期速度と比較した経過時間 


 a| 
最低
 a| 
最高の優先度であれば、約8倍の時間を要します。



 a| 
低
 a| 
最高の優先度であれば、約6回。



 a| 
中
 a| 
最高の優先度であれば、約3倍から半分。



 a| 
高
 a| 
優先度が最高の場合は、約2倍です。

|===
同期の所要時間には、ボリュームサイズとホストのI/O速度が影響します。



== 手動同期ポリシーの使用が推奨されるのはなぜですか？

手動再同期が推奨されるのは、データがリカバリされる可能性が最も高い方法で再同期プロセスを管理できるためです。

自動再同期ポリシーを使用していて、再同期中に通信が中断する問題が発生した場合は、セカンダリボリューム上のデータが一時的に破損する可能性があります。再同期が完了すると、データは修正されます。
