---
permalink: um-manage/faq-import-settings.html 
sidebar: sidebar 
keywords:  
summary: この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。 
---
= SANtricity Unified Manager のインポート設定に関する FAQ
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。



== どの設定がインポートされますか？

設定のインポート機能は、1つのストレージアレイから複数のストレージアレイに構成をロードするバッチ処理です。この処理でインポートされる設定は、SANtricity System Managerでソースストレージアレイがどのように設定されているかによって異なります。

複数のストレージアレイにインポートできる設定は次のとおりです。

* *Email alerts*--メールサーバのアドレスとアラート受信者の電子メールアドレスを設定します
* *Syslogアラート*-- syslogサーバのアドレスとUDPポートを含む設定。
* *snmp alerts *-- SNMPサーバのコミュニティ名とIPアドレスを含む設定。
* * AutoSupport *--個別の機能（Basic AutoSupport 、AutoSupport OnDemand、Remote Diagnostics）、メンテナンス時間、配信方法、 およびディスパッチスケジュール。
* *ディレクトリサービス*-- LDAP (Lightweight Directory Access Protocol)サーバーのドメイン名とURL、およびLDAPサーバーのユーザーグループとストレージアレイの定義済みロールとのマッピングが含まれます。
* *ストレージ構成*--ボリューム(リポジトリボリューム以外のシックボリュームのみ)、ボリュームグループ、プール、およびホットスペアドライブの割り当てが含まれます。
* *システム設定*--ボリュームのメディアスキャン設定、コントローラのSSDキャッシュ、および自動ロードバランシングが含まれます(ホスト接続レポートは含まれません)。




== ストレージ アレイが一部表示されないのはなぜですか?

設定のインポート処理の際、ターゲットの選択ダイアログボックスに一部のストレージアレイが表示されないことがあります。

ストレージアレイが表示されない理由は次のとおりです。

* ファームウェアのバージョンが8.50未満である。
* ストレージアレイがオフラインになっている。
* システムがそのアレイと通信できません（アレイに証明書、パスワード、ネットワークの問題がある場合など）。

