---
permalink: um-manage/how-upgrades-work.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, upgrades, 
summary: Unified Managerを使用して、同じタイプの複数のストレージアレイのSANtricity OSソフトウェアを新しいバージョンにアップグレードできます。 
---
= アップグレードの仕組み
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SANtricity Unified Managerを使用して、同じタイプの複数のストレージアレイのSANtricity OSソフトウェアを新しいバージョンにアップグレードできます。



== アップグレードワークフロー

以下に、ソフトウェアのアップグレードを実行するための大まかなワークフローを示します。

. 最新のSANtricity OSソフトウェアファイルをサポートサイトからダウンロードします（サポート*ページのUnified Managerからリンクできます）。管理ホストシステム（ブラウザでUnified Managerにアクセスするホスト）にファイルを保存し、ファイルを解凍します。
. Unified Managerで、SANtricity OSソフトウェアファイルとNVSRAMファイルをリポジトリ（ファイルが格納されているWebサービスプロキシサーバの領域）にロードします。ファイルは、メニューから追加できます。[Upgrade SANtricity OS Software]または[Upgrade Center]>[Manage Software Repository]から選択します。
. リポジトリにファイルをロードしたら、アップグレードに使用するファイルを選択できます。SANtricity OSソフトウェアのアップグレードページ（メニュー：アップグレードセンター[Upgrade SANtricity OS software]）から、SANtricity OSソフトウェアファイルとNVSRAMファイルを選択します。ソフトウェアファイルを選択すると、互換性があるストレージアレイのリストがこのページに表示されます。次に、新しいソフトウェアでアップグレードするストレージアレイを選択します。（互換性のないアレイは選択できません）。
. ソフトウェアの転送とアクティブ化をすぐに開始することも、ファイルをステージングしてあとでアクティブ化することもできます。アップグレードプロセスを実行すると、Unified Managerで次の処理が実行されます。
+
.. ストレージアレイの健全性チェックが実行され、アップグレードの完了の妨げとなる状況がないかどうかが確認されます。健全性チェックでいずれかのアレイに問題が見つかった場合は、そのアレイをスキップして他のアレイのアップグレードを続行するか、プロセス全体を停止して該当するアレイのトラブルシューティングを行うことができます。
.. 各コントローラにアップグレードファイルが転送されます。
.. コントローラが一度に1台ずつリブートされ、新しいSANtricity OSソフトウェアがアクティブ化されます。アクティブ化では、既存のSANtricity OSファイルが新しいファイルに置き換えられます。
+
[NOTE]
====
ソフトウェアをあとでアクティブ化するように指定することもできます。

====






== 即時アップグレードまたは段階的アップグレード

アップグレードはただちにアクティブ化することも、ステージングしてあとでアクティブ化することもできます。あとでアクティブ化する理由は次のとおりです。

* * 時間帯 * -- ソフトウェアのアクティブ化には時間がかかることがあるため、 I/O 負荷の低い時間帯に実行できます。I/O 負荷とキャッシュサイズによっては、コントローラのアップグレードに通常 15~25 分かかります。アクティブ化の際にはコントローラがリブートしてフェイルオーバーするため、アップグレードが完了するまではパフォーマンスが通常よりも低下する可能性があります。
* * パッケージのタイプ * -- 他のストレージアレイ上のファイルをアップグレードする前に ' 新しいソフトウェアとファームウェアを 1 つのストレージアレイでテストすることをお勧めします


ステージング済みソフトウェアをアクティブにするには、メニューサポート[Upgrade Center]に移動し、SANtricity OSコントローラソフトウェアのアップグレードというラベルの付いた領域で[Activate *（有効化*）]をクリックします。



== ヘルスチェック

健全性チェックはアップグレードプロセスの一環として実行されますが、開始する前に別途実行することもできます（メニュー：Upgrade Center [Pre-Upgrade Health Check]に移動）。

健全性チェックでは、ストレージシステムのすべてのコンポーネントについて、アップグレードを実行できる状態であるかがチェックされます。次の状況に該当する場合、アップグレードを実行できないことがあり

* 割り当てられたドライブで障害が発生し
* ホットスペアを使用中です
* 不完全なボリュームグループです
* 同時に実行できません
* ボリュームが見つからない
* コントローラのステータスが最適でない
* イベントログイベントが多すぎます
* 構成データベースの検証に失敗しました
* ドライブの DACstore のバージョンが古い

