---
permalink: um-manage/how-import-settings-works.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, import, settings, 
summary: Unified Managerを使用して、1つのストレージアレイから複数のストレージアレイに設定をインポートできます。設定のインポート機能は、ネットワーク内で複数のアレイを設定する必要がある場合に時間を節約するバッチ処理です。 
---
= 設定のインポートの仕組み
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Managerを使用して、1つのストレージアレイから複数のストレージアレイに設定をインポートできます。設定のインポート機能は、ネットワーク内で複数のアレイを設定する必要がある場合に時間を節約するバッチ処理です。



== インポートできる設定

複数のアレイにインポートできる構成は次のとおりです。

* *アラート*--電子メール、syslogサーバ、またはSNMPサーバを使用して、管理者に重要なイベントを送信するためのアラート方法。
* * AutoSupport *--ストレージ・アレイの状態を監視し'テクニカル・サポートに自動ディスパッチを送信する機能
* *ディレクトリサービス*-- LDAP (Lightweight Directory Access Protocol)サーバとディレクトリサービス(MicrosoftのActive Directoryなど)を介して管理されるユーザー認証の方法。
* *ストレージ構成*--以下に関連する構成。
+
** ボリューム（リポジトリボリュームでないシックボリュームのみ）
** ボリュームグループとプール
** ホットスペアドライブの割り当て


* *システム設定*--以下に関連する設定。
+
** ボリュームのメディアスキャン設定
** SSD設定
** 自動ロードバランシング（ホスト接続レポートは含まれません）






== 設定ワークフロー

設定をインポートするワークフローは次のとおりです。

. ソースとして使用するストレージアレイで、System Managerを使用して設定を行います。
. ターゲットとして使用するストレージアレイで、System Managerを使用して設定をバックアップします。
. Unified Managerの* Manage *ページに移動して、設定をインポートします。
. [* Operations]ページで、設定のインポート操作の結果を確認します。

