---
permalink: um-manage/import-autosupport-settings.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, import, autosupport, settings 
summary: ストレージアレイから別のストレージアレイにAutoSupport 構成をインポートできます。このバッチ処理により、ネットワーク内に複数のアレイを設定する必要がある場合に時間を節約できます。 
---
= AutoSupport 設定をインポートします
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイから別のストレージアレイにAutoSupport 構成をインポートできます。このバッチ処理により、ネットワーク内に複数のアレイを設定する必要がある場合に時間を節約できます。

.作業を開始する前に
* AutoSupport は、ソースとして使用するストレージアレイ（メニュー：サポート[サポートセンター]）に対してSystem Managerで設定します。
* ターゲットストレージアレイの既存の構成は、System Managerでバックアップされます（メニュー：[設定][システム]>[ストレージアレイ構成の保存]）。


.このタスクについて
インポートされる設定には、個別の機能（Basic AutoSupport 、AutoSupport OnDemand、Remote Diagnostics）、メンテナンス期間、配信方法、 およびディスパッチスケジュール。

.手順
. [管理]ページで、[設定のインポート*]をクリックします。
+
設定のインポートウィザードが開きます。

. 設定の選択ダイアログボックスで、「* AutoSupport *」を選択し、「*次へ*」をクリックします。
+
ソースアレイを選択するためのダイアログボックスが開きます。

. [ソースの選択]ダイアログボックスで、インポートする設定のアレイを選択し、[次へ]をクリックします。
. [Select Targets]ダイアログ・ボックスで'新しい設定を受信するアレイを1つ以上選択します
+
[NOTE]
====
ファームウェアが8.50未満のストレージアレイは選択できません。また、Unified Managerが通信できないアレイ（オフラインのアレイや、証明書、パスワード、ネットワークに問題があるアレイなど）は、このダイアログボックスに表示されません。

====
. [ 完了 ] をクリックします。
+
Operationsページには、インポート処理の結果が表示されます。処理が失敗した場合は、その行をクリックすると詳細を確認できます。



.結果
ターゲットストレージアレイのAutoSupport 設定がソースアレイと同じに設定されます。
