---
permalink: um-manage/import-alert-settings.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, import, alert, settings 
summary: ストレージアレイから別のストレージアレイにアラート設定をインポートできます。このバッチ処理により、ネットワーク内に複数のアレイを設定する必要がある場合に時間を節約できます。 
---
= アラート設定をインポートします
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイから別のストレージアレイにアラート設定をインポートできます。このバッチ処理により、ネットワーク内に複数のアレイを設定する必要がある場合に時間を節約できます。

.作業を開始する前に
* アラートは、ソースとして使用するストレージアレイのSystem Managerで設定します（メニュー：Settings [Alerts]）。
* ターゲットストレージアレイの既存の構成は、System Managerでバックアップされます（メニュー：[設定][システム]>[ストレージアレイ構成の保存]）。


.このタスクについて
インポート処理では、Eメール、SNMP、またはsyslogのいずれかのアラートを選択できます。インポートされる設定は次のとおりです。

* *Email alerts *--メールサーバのアドレスとアラート受信者の電子メールアドレス。
* *Syslogアラート*-- syslogサーバのアドレスとUDPポート。
* *snmp alerts *-- SNMPサーバのコミュニティ名とIPアドレス。


.手順
. [管理]ページで、[設定のインポート*]をクリックします。
+
設定のインポートウィザードが開きます。

. 設定の選択ダイアログボックスで、*電子メールアラート*、* SNMPアラート*、または* Syslogアラート*のいずれかを選択し、*次へ*をクリックします。
+
ソースアレイを選択するためのダイアログボックスが開きます。

. [ソースの選択]ダイアログボックスで、インポートする設定のアレイを選択し、[次へ]をクリックします。
. [Select Targets]ダイアログ・ボックスで'新しい設定を受信するアレイを1つ以上選択します
+
[NOTE]
====
ファームウェアが8.50未満のストレージアレイは選択できません。また、Unified Managerが通信できないアレイ（オフラインのアレイや、証明書、パスワード、ネットワークに問題があるアレイなど）は、このダイアログボックスに表示されません。

====
. [ 完了 ] をクリックします。
+
Operationsページには、インポート処理の結果が表示されます。処理が失敗した場合は、その行をクリックすると詳細を確認できます。



.結果
Eメール、SNMP、またはsyslogを使用して管理者にアラートを送信するようにターゲットストレージアレイが設定されます。
