---
permalink: um-manage/mirroring-configuration-workflow.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, mirroring, configuration, workflow 
summary: Unified Managerで非同期ミラーリングまたは同期ミラーリングを設定し、System Managerを使用して同期を管理します。 
---
= ミラーリングの設定ワークフロー
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Managerで非同期ミラーリングまたは同期ミラーリングを設定し、System Managerを使用して同期を管理します。



== 非同期ミラーリングのワークフロー

非同期ミラーリングのワークフローは次のとおりです。

. Unified Managerで初期設定を実行します。
+
.. データ転送元としてローカルストレージアレイを選択します。
.. ミラー整合性グループを作成するか、既存のミラー整合性グループを選択します。ミラー整合性グループは、ローカルアレイのプライマリボリュームとリモートアレイのセカンダリボリュームのコンテナです。プライマリボリュームとセカンダリボリュームは「ミラーペア」と呼ばれます。 ミラー整合性グループを初めて作成する場合は、手動同期とスケジュールされた同期のどちらを実行するかを指定します。
.. ローカルストレージアレイからプライマリボリュームを選択し、リザーブ容量を確認します。リザーブ容量は、コピー処理に使用される物理割り当て容量です。
.. 転送先としてリモートストレージアレイを選択し、セカンダリボリュームを選択して、リザーブ容量を確認します。
.. プライマリボリュームからセカンダリボリュームへの初回のデータ転送を開始します。ボリュームサイズによっては、この初回転送に数時間かかることがあります。


. 初期同期の進捗状況を確認します。
+
.. Unified Managerで、ローカルアレイのSystem Managerを起動します。
.. System Managerで、ミラーリング処理のステータスを確認します。ミラーリングが完了すると、ミラーペアのステータスは「最適」になります。


. 必要に応じて、System Managerで後続のデータ転送のスケジュールを再設定したり、手動で実行したりできます。新しいブロックと変更されたブロックのみがプライマリボリュームからセカンダリボリュームに転送されます。
+
[NOTE]
====
非同期レプリケーションは定期的に行われるため、システムでは変更されたブロックを統合してネットワーク帯域幅を節約できます。書き込みスループットと書き込みレイテンシへの影響は最小限に抑えられます。

====




== 同期ミラーリングのワークフロー

同期ミラーリングのワークフローは次のとおりです。

. Unified Managerで初期設定を実行します。
+
.. データ転送元としてローカルストレージアレイを選択します。
.. ローカルストレージアレイからプライマリボリュームを選択します。
.. データ転送先としてリモートストレージアレイを選択し、セカンダリボリュームを選択します。
.. 同期と再同期の優先度を選択します。
.. プライマリボリュームからセカンダリボリュームへの初回のデータ転送を開始します。ボリュームサイズによっては、この初回転送に数時間かかることがあります。


. 初期同期の進捗状況を確認します。
+
.. Unified Managerで、ローカルアレイのSystem Managerを起動します。
.. System Managerで、ミラーリング処理のステータスを確認します。ミラーリングが完了すると、ミラーペアのステータスは「最適」になります。 2つのアレイは、通常の動作を行って同期を維持しようとします。新しいブロックと変更されたブロックのみがプライマリボリュームからセカンダリボリュームに転送されます。


. 必要に応じて、System Managerで同期設定を変更できます。
+
[NOTE]
====
同期レプリケーションは継続的に行われるため、2つのサイト間のレプリケーションリンクで十分な帯域幅を確保する必要があります。

====

