---
permalink: um-manage/mirroring-overview.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, mirroring, 
summary: Unified ManagerにはSANtricity ミラーリング機能の設定オプションが用意されており、管理者は2つのストレージアレイ間でデータをレプリケートしてデータを保護できます。 
---
= ミラーリングの仕組み
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified ManagerにはSANtricity ミラーリング機能の設定オプションが用意されており、管理者は2つのストレージアレイ間でデータをレプリケートしてデータを保護できます。

[NOTE]
====
この機能は、EF600またはEF300ストレージシステムでは使用できません。

====


== ミラーリングのタイプ

SANtricity アプリケーションには、非同期と同期の2種類のミラーリングがあります。

非同期ミラーリングでは、データボリュームをオンデマンドで、またはスケジュールに基づいてコピーします。これにより、データの破損や損失が原因で発生するダウンタイムを回避または最小限に抑えることができます。非同期ミラーリングでは、特定の時点におけるプライマリボリュームの状態がキャプチャされ、前回のイメージキャプチャ以降に変更されたデータだけがコピーされます。プライマリサイトはただちに更新でき、セカンダリサイトは帯域幅に余裕があれば更新できます。情報はキャッシュされ、あとでネットワークリソースが利用可能になったときに送信されます。このタイプのミラーリングは、バックアップやアーカイブなどの定期的なプロセスに最適です。

同期ミラーリングでは、データボリュームをリアルタイムでレプリケートして、継続的な可用性を確保します。目的は、2つのストレージアレイのいずれかで災害が発生した場合に重要なデータのコピーを確保しておくことで、データ損失ゼロの目標復旧時点（RPO）を達成することです。プライマリボリュームに書き込みが行われるたびにセカンダリボリュームにも書き込みが行われるため、どの時点においてもコピーは本番環境のデータと同一です。プライマリボリュームで行われた変更でセカンダリボリュームが更新されるまで、ホストは書き込みが成功したという確認応答を受信しません。このタイプのミラーリングは、ディザスタリカバリなどのビジネス継続性の確保に最適です。



== ミラーリングのタイプの違い

次の表に、2種類のミラーリングの主な違いを示します。

[cols="1a,1a,1a"]
|===
| 属性 | 非同期 | 同期 


 a| 
レプリケーション方法
 a| 
ポイントインタイム-ミラーリングはオンデマンドで、またはユーザ定義のスケジュールに従って自動的に実行されます。
 a| 
連続--ミラーリングは継続して自動的に実行され、ホストに書き込みがあるたびにデータがコピーされます。



 a| 
距離（Distance）
 a| 
アレイ間の長距離をサポートします。通常、この距離は、ネットワークとチャネル拡張テクノロジーの機能によってのみ制限されます。
 a| 
アレイ間の距離は短い距離に制限されています。レイテンシおよびアプリケーションパフォーマンスの要件を満たすために、通常はローカルストレージアレイから約10km（6.2マイル）以内の距離にする必要があります。



 a| 
通信方法
 a| 
標準のIPまたはFibre Channelネットワーク。
 a| 
Fibre Channelネットワークのみ。



 a| 
ボリュームタイプ
 a| 
標準またはシン。
 a| 
標準のみ。

|===