---
permalink: um-manage/requirements-for-replicating-storage-configurations.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, requirements, replicating, storage, configurations 
summary: ストレージアレイ間でストレージ構成をインポートする前に、要件およびガイドラインを確認してください。 
---
= ストレージ構成のレプリケートに関する要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイ間でストレージ構成をインポートする前に、要件およびガイドラインを確認してください。



== シェルフ

* コントローラが配置されているシェルフがソースとターゲットのアレイで同一である。
* シェルフIDがソースとターゲットのアレイで同じである。
* 拡張シェルフの同一のスロットに同じドライブタイプが搭載されている必要があります（ドライブが構成で使用されている場合、未使用ドライブの場所は問題になりません）。




== コントローラ

* コントローラタイプはソースとターゲットのアレイで同一である必要はない（E2800からE5700にインポートする場合など）が、RBODエンクロージャのタイプは同一である必要がある。
* ホストのDA機能を含むHICが、ソースとターゲットのアレイで同じである必要があります。
* デュプレックス構成からシンプレックス構成へのインポートはサポートされていませんが、シンプレックス構成からデュプレックス構成へのインポートは可能です。
* FDE設定はインポートプロセスに含まれない。




== ステータス

* ターゲットアレイのステータスが最適lである必要があります。
* ソースアレイのステータスが「最適」である必要はありません。




== ストレージ

* ターゲットのボリューム容量がソースよりも大きいかぎり、ソースとターゲットのアレイでドライブ容量が異なることがあります。（ターゲットアレイには容量の大きい新しいドライブが搭載されている場合、それらのドライブはレプリケーション処理によってボリュームに完全には構成されない可能性があります）。
* ソースアレイのディスクプールのボリュームが64TB以上の場合、ターゲットでインポートプロセスを実行できない。
* シンボリュームはインポートプロセスに含まれません。

