---
permalink: um-manage/upgrade-considerations.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, upgrade, considerations 
summary: Unified Managerを使用して複数のストレージアレイをアップグレードする場合に、計画段階で確認が必要な主な考慮事項を以下に記載します。 
---
= アップグレード時の考慮事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SANtricity Unified Managerを使用して複数のストレージアレイをアップグレードする場合に、計画段階で確認が必要な考慮事項を以下に記載します。



== 現在のバージョン

検出された各ストレージアレイについて、Unified Managerの管理ページからSANtricity OSの現在のソフトウェアバージョンを表示できます。バージョンはSANtricity OSソフトウェア列に表示されます。各行の SANtricity OS のバージョンをクリックするとポップアップダイアログボックスが表示され、コントローラのファームウェアと NVSRAM の情報を確認できます。



== アップグレードが必要なその他のコンポーネント

アップグレードプロセスの一環として、ホストがコントローラと正しく連携するように、ホストのマルチパス/フェイルオーバードライバやHBAドライバのアップグレードも必要になることがあります。

互換性の情報については、を参照してください https://imt.netapp.com/matrix/#welcome["NetApp Interoperability Matrix を参照してください"^]。手順については、使用するオペレーティングシステムに対応したエクスプレスガイドを参照してください。エクスプレスガイドは、から入手できます https://docs.netapp.com/us-en/e-series/index.html["E シリーズおよび SANtricity に関するドキュメント"^]。



== デュアルコントローラ

ストレージアレイにコントローラが 2 台あり、マルチパスドライバがインストールされている場合は、アップグレードの実行中もストレージアレイで I/O の処理を継続できます。アップグレードの実行中は、次の処理が実行されます。

. コントローラ A のすべての LUN がコントローラ B にフェイルオーバーされます
. コントローラ A でアップグレードが実行されます
. コントローラ A に LUN が戻され、コントローラ B の LUN もすべて移されます。
. コントローラ B でアップグレードが実行されます


アップグレードの完了後、所有権のある正しいコントローラにボリュームが配置されるように、コントローラ間で手動でのボリュームの再配置が必要になることがあります。
