---
permalink: sm-settings/access-management-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, access management, terms 
summary: ストレージアレイに関連するアクセス管理の用語を次に示します。 
---
= アクセス管理の用語
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイに関連するアクセス管理の用語を次に示します。

[cols="25h,~"]
|===
| 期間 | 説明 


 a| 
アクセストークン
 a| 
アクセストークンは、ユーザ名とパスワードの代わりに、REST APIまたはコマンドラインインターフェイス（CLI）での認証に使用されます。トークンは特定のユーザ（LDAPユーザを含む）に関連付けられており、一連の権限と有効期限が含まれています。



 a| 
Active Directory
 a| 
Active Directory（AD）は、Windowsドメインネットワーク用のLDAPを使用するMicrosoftのディレクトリサービスです。



 a| 
結合
 a| 
バインド処理は、ディレクトリサーバに対するクライアントの認証に使用されます。通常はアカウントとパスワードのクレデンシャルが必要ですが、匿名のバインド処理が可能なサーバもあります。



 a| 
できます
 a| 
認証局（CA）は、インターネットセキュリティのためにデジタル証明書と呼ばれる電子文書を発行する信頼されたエンティティです。証明書でWebサイトの所有者を識別することにより、クライアントとサーバの間のセキュアな接続が確立されます。



 a| 
証明書
 a| 
証明書はセキュリティ上の目的でサイトの所有者を識別するもので、攻撃者による偽装を防止します。証明書には、サイトの所有者に関する情報と、その情報について証明（署名）する信頼されたエンティティのIDが含まれます。



 a| 
IdP
 a| 
アイデンティティプロバイダ（IdP）は、ユーザにクレデンシャルを要求して認証されたユーザかどうかを確認するために使用される外部のシステムです。多要素認証にも対応し、Active Directoryなどの任意のユーザデータベースを使用するように設定できます。IdPの保守はセキュリティチームが行います。



 a| 
LDAP
 a| 
Lightweight Directory Access Protocol（LDAP）は、分散型のディレクトリ情報サービスへのアクセスと管理に使用されるアプリケーションプロトコルです。このプロトコルを使用すると、さまざまなアプリケーションやサービスがLDAPサーバに接続してユーザを検証できます。



 a| 
RBAC
 a| 
ロールベースアクセス制御（RBAC）は、コンピュータやネットワークリソースへのアクセスを個々のユーザのロールに基づいて制御する手法です。ストレージアレイにはRBACが適用され、事前定義されたロールが用意されています。



 a| 
SAML
 a| 
Security Assertion Markup Language（SAML）は、2つのエンティティ間の認証と許可に使用されるXMLベースの標準規格です。SAMLは、ユーザの認証時に複数の項目（パスワードとフィンガープリントなど）を求める多要素認証に対応しています。ストレージアレイに組み込みのSAML機能は、SAML2.0のアイデンティティアサーション、認証、および許可に準拠しています。



 a| 
SP
 a| 
サービスプロバイダ（SP）は、ユーザの認証とアクセスを制御するシステムです。アクセス管理にSAMLを設定すると、ストレージアレイがアイデンティティプロバイダに認証を要求するサービスプロバイダとして機能します。



 a| 
SSO
 a| 
シングルサインオン（SSO）は、1組のログインクレデンシャルで複数のアプリケーションにアクセスできるようにする認証サービスです。

|===