---
permalink: sm-settings/access-management-tokens.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, access management, tokens 
summary: アクセストークンは、ユーザー名とパスワードを公開することなくアレイへのアクセスを提供します。 
---
= アクセストークン
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アクセストークンは、ユーザ名やパスワードを公開することなく、REST APIまたはコマンドラインインターフェイス（CLI）を使用して認証する手段を提供します。トークンは特定のユーザ（LDAPユーザを含む）に関連付けられ、一連の権限と有効期限が含まれます。



== SAMLとJSON Webトークンアクセス

デフォルトでは、SAMLが有効になっているシステムで従来のコマンドラインツールにアクセスすることはできません。MFAワークフローで認証用にアイデンティティプロバイダサーバへのリダイレクトが必要なため、REST APIとCLIは実質的に操作不能になります。そのため、ユーザがMFAで認証されることを求めるトークンをSystem Managerで生成する必要があります。


NOTE: Webトークンを使用するためにSAMLを有効にする必要はありませんが、最高レベルのセキュリティを確保するにはSAMLを推奨します。



== トークンを作成および使用するためのワークフロー

. System Managerでトークンを作成し、有効期限を確認します。
. トークンテキストをクリップボードにコピーするかファイルにダウンロードして、トークンテキストを安全な場所に保存します。
. トークンは次のように使用します。
+
** * REST API *：REST API要求でトークンを使用するには、要求にHTTPヘッダーを追加します。例：
`Authorization: Bearer _<access-token-value>_`
** * Secure CLI *：CLIでトークンを使用するには、コマンドラインでトークン値を追加するか、トークン値を含むファイルへのパスを使用します。例：
+
*** コマンドラインのトークン値： `-t _access-token-value_`
*** トークン値を含むファイルへのパス： `-T _access-token-file_`






詳細はこちら。

* link:access-management-tokens-create.html["アクセストークンを作成します"]
* link:access-management-tokens-edit.html["アクセストークンを編集します"]
* link:access-management-tokens-revoke.html["アクセストークンを取り消します"]

