---
permalink: sm-settings/add-trap-destinations-for-snmp-alerts.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, add, trap, destinations, SNMP, alerts, 
summary: SNMPトラップの送信に使用するサーバは最大10台まで追加できます。 
---
= SANtricity System Manager で SNMP アラートのトラップ送信先を追加する
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SNMPトラップの送信に使用するサーバは最大10台まで追加できます。

.作業を開始する前に
* 追加するネットワークサーバにSNMPサービスアプリケーションが設定されている必要があります。イベントモニタからトラップメッセージを送信するためには、このサーバのネットワークアドレス（IPv4アドレスまたはIPv6アドレス）が必要です。複数のサーバを使用できます（最大10台のサーバを使用できます）。
* SNMPサービスアプリケーションがインストールされたサーバに管理情報ベース（MIB）ファイルをコピーしてコンパイルしておきます。このMIBファイルは、監視および管理されるデータを定義します。
+
MIBファイルがない場合は、ネットアップサポートサイトから入手できます。

+
** に進みます https://mysupport.netapp.com/site/global/dashboard["ネットアップサポート"^]。
** [* Downloads（ダウンロード）]をクリックし、[* Downloads（ダウンロード）]を選択します。
** EシリーズSANtricity OSコントローラソフトウェア*をクリックします。
** [最新リリースのダウンロード]を選択します。
** ログインします。
** 注意事項および使用許諾契約に同意します。
** コントローラタイプのMIBファイルが表示されるまで下にスクロールし、リンクをクリックしてファイルをダウンロードします。




.手順
. メニューを選択します。Settings [Alerts]（設定[Alerts]）。
. [*SNMP*]タブを選択します。
+
現在定義されているトラップ送信先が表に表示されます。

. 「トラップのディスペションを追加」*を選択します。
+
トラップ送信先の追加ダイアログボックスが開きます。

. 1つ以上のトラップ送信先を入力し、関連付けられているコミュニティ名またはユーザ名を選択して、* Add *をクリックします。
+
** *Trap Destination*-- SNMPサービスを実行しているサーバーのIPv4またはIPv6アドレスを入力します
** *コミュニティ名またはユーザー名*--ドロップダウンから、このトラップの送信先のコミュニティ名（SNMPv2c）またはユーザー名（SNMPv3）を選択します。（定義したのが1つだけの場合は、このフィールドにはすでに名前が表示されます）。
** *認証失敗トラップを送信*--コミュニティ名またはユーザ名が認識されないためにSNMP要求が拒否された場合にトラップの送信先にアラートを送信するには、このオプション（チェックボックス）を選択します。「*追加」をクリックすると、トラップの送信先と関連するコミュニティ名またはユーザ名が表に表示されます。


. トラップが有効であることを確認するには、テーブルからトラップの送信先を選択し、*トラップの送信先のテスト*をクリックして、設定したアドレスにテストトラップを送信します。


.結果
アラート対象のイベントが発生するたびに、イベントモニタからサーバにSNMPトラップが送信されます。
