---
permalink: sm-settings/alerts-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, alerts, terms, 
summary: ストレージアレイに関連するアラートの用語を次に示します。 
---
= アラートの用語
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイに関連するアラートの用語を次に示します。

[cols="25h,~"]
|===
| コンポーネント | 説明 


 a| 
イベントモニタ
 a| 
イベントモニタはストレージアレイに常駐し、バックグラウンドタスクとして実行されます。ストレージアレイで異常を検出すると、その問題に関する情報をイベントログに書き込みます。これには、バッテリの障害、最適からオフラインへのコンポーネントの状態の変化、コントローラの冗長性の問題などが含まれます。イベントが「アラート対象」であると判断した場合、イベントモニタは設定されているアラート方法（Eメール、SNMP、syslog）を使用して通知を送信します。重大イベントはすべて「アラート対象」とみなされるほか、一部の警告イベントと情報イベントも「アラート対象」とみなされます。



 a| 
メールサーバ
 a| 
メールサーバはEメールアラートの送受信に使用されます。サーバはSMTP（簡易メール転送プロトコル）を使用します。



 a| 
SNMP
 a| 
簡易ネットワーク管理プロトコル（SNMP）は、IPネットワーク上のデバイス間で情報を管理および共有するために使用されるインターネット標準プロトコルです。



 a| 
SNMPトラップ
 a| 
SNMPトラップは、SNMPサーバに送信される通知です。トラップには、ストレージアレイの重要な問題に関する情報が含まれています。



 a| 
SNMP トラップの送信先
 a| 
SNMPトラップの送信先は、SNMPサービスを実行しているサーバのIPv4またはIPv6アドレスです。



 a| 
コミュニティ名
 a| 
コミュニティ名は、SNMP環境内のネットワークサーバのパスワードのような役割を果たす文字列です。



 a| 
MIBファイル
 a| 
管理情報ベース（MIB）ファイルは、ストレージアレイ内で監視および管理されているデータを定義します。SNMPサービスアプリケーションがインストールされたサーバにコピーしてコンパイルする必要があります。このMIBファイルは、サポートサイトのSystem Managerソフトウェアで入手できます。



 a| 
MIB変数
 a| 
管理情報ベース（MIB）変数は、SNMP GetRequestsへの応答として、ストレージアレイ名、アレイの場所、担当者などの値を返すことができます。



 a| 
syslog
 a| 
syslogは、ネットワークデバイスがイベントメッセージをロギングサーバに送信するために使用するプロトコルです。



 a| 
UDP
 a| 
User Datagram Protocol（UDP）は、パケットヘッダーで送信元と送信先のポート番号を指定するトランスポートレイヤプロトコルです。

|===