---
permalink: sm-settings/automatic-load-balancing-overview.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, automatic, load, balancing, 
summary: 自動ロードバランシングを使用すると、負荷の変化に動的に対応してボリュームのコントローラ所有権が自動的に調整されるため、コントローラ間でワークロードが移動する際の負荷の不均衡が解消され、I/Oリソースの管理が強化されます。 
---
= 自動ロードバランシングの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
自動ロードバランシングを使用すると、負荷の変化に動的に対応してボリュームのコントローラ所有権が自動的に調整されるため、コントローラ間でワークロードが移動する際の負荷の不均衡が解消され、I/Oリソースの管理が強化されます。

各コントローラのワークロードは継続的に監視され、ホストにインストールされたマルチパスドライバとの連携により、必要に応じて自動的に負荷を分散できます。ワークロードがコントローラ間で自動的に再分散されるため、ストレージアレイの負荷の変化に合わせてボリュームのコントローラ所有権を手動で調整する必要がなくなり、ストレージ管理者の負担が軽減されます。

自動ロードバランシングを有効にすると、次の機能が実行されます。

* コントローラのリソース利用率を自動的に監視して負荷を分散します。
* ボリュームのコントローラ所有権が必要に応じて自動的に調整され、ホストとストレージアレイの間のI/O帯域幅が最適化されます。




== 自動ロードバランシングの有効化と無効化

自動ロードバランシングは、すべてのストレージアレイでデフォルトで有効になっています。

自動ロードバランシングは、ストレージアレイの状況に応じて無効にすることができます。たとえば、次のような場合です。

* 特定のボリュームのコントローラ所有権については、ワークロードを分散するために自動的に変更されないようにする場合。
* 高度に調整された環境で、コントローラ間の負荷分散が特定の要件を満たすように意図的に設定されている。




== 自動ロードバランシング機能をサポートするホストタイプ

自動ロードバランシングを有効にするのはストレージアレイレベルですが、ホストまたはホストクラスタに選択したホストタイプがこの機能の動作に直接影響します。

ストレージアレイのワークロードをコントローラ間で分散する際、自動ロードバランシング機能は、両方のコントローラからアクセスでき、自動ロードバランシング機能をサポートするホストまたはホストクラスタにのみマッピングされたボリュームの移動を試みます。

これにより、ロードバランシングプロセスによってホストがボリュームにアクセスできなくなることはありませんが、自動ロードバランシングをサポートしていないホストにマッピングされたボリュームがあると、ストレージアレイはワークロードを分散できなくなります。自動ロードバランシングがワークロードを分散するためには、マルチパスドライバがTPGSをサポートしていることと、ホストタイプが次の表に含まれていることが必要です。

[NOTE]
====
ホストクラスタが自動ロードバランシングに対応しているとみなされるのは、そのグループ内のすべてのホストが自動ロードバランシングをサポートしている場合です。

====
[cols="1a,1a"]
|===
| 自動ロードバランシングをサポートするホストタイプ | マルチパスドライバ 


 a| 
WindowsまたはWindowsクラスタ
 a| 
MPIOとNetApp EシリーズDSM



 a| 
Linux DM-MP（カーネル3.10以降）
 a| 
DM-MPと'scsi_dh_aluaデバイス・ハンドラ



 a| 
VMware
 a| 
Native Multipathing Plugin（NMP）と'VMW_SATP_ALUA Storage Array Type'プラグイン

|===
[NOTE]
====
一部の例外を除き、自動ロードバランシングをサポートしていないホストタイプは、この機能が有効になっているかどうかに関係なく正常に動作し続けます。例外の1つがシステムのフェイルオーバーです。データパスが復旧すると、ストレージアレイはマッピングされていないボリュームまたは割り当てられていないボリュームを所有権を持つコントローラに戻しますが、自動ロードバランシングをサポートしていないホストにマッピングまたは割り当てられているボリュームは移動されません。

====
を参照してください https://mysupport.netapp.com/matrix["Interoperability Matrix Tool で確認してください"^] サポートされるマルチパスドライバ、OSレベル、コントローラドライブトレイの互換性情報については、を参照してください。



== 自動ロードバランシング機能とOSの互換性の確認

新しいシステムを設定（または既存のシステムを移行）する前に、自動ロードバランシング機能とOSの互換性を確認します。

. にアクセスします https://mysupport.netapp.com/matrix["Interoperability Matrix Tool で確認してください"^] をクリックして解決策 を検索し、サポートを確認してください。
+
Red Hat Enterprise Linux 6またはSUSE Linux Enterprise Server 11を実行しているシステムの場合は、テクニカルサポートにお問い合わせください。

. /etc/multipath.confファイルを更新して構成します
. 該当するベンダーおよび製品の「retain_attached_device_handler」と「detect_prio」の両方が「yes」に設定されていることを確認するか、デフォルトの設定を使用します。

