---
permalink: sm-settings/cache-settings-and-performance.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, cache, settings, performance, 
summary: キャッシュメモリは、ドライブメディアよりも速くアクセスできる、コントローラ上の一時的な揮発性ストレージ領域です。 
---
= キャッシュの設定とパフォーマンス
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
キャッシュメモリは、ドライブメディアよりも速くアクセスできる、コントローラ上の一時的な揮発性ストレージ領域です。

キャッシュを使用すると、全体的なI/Oパフォーマンスを次のように向上させることができます。

* 読み取り用にホストから要求されたデータが以前の処理からすでにキャッシュに格納されている可能性があるため、ドライブへのアクセスが不要になります。
* 書き込みデータは最初にキャッシュに書き込まれるため、データがドライブに書き込まれるのを待つことなくアプリケーションが処理を続行できます。


デフォルトのキャッシュ設定はほとんどの環境の要件を満たしていますが、必要に応じて設定を変更できます。



== ストレージアレイキャッシュの設定

ストレージアレイ内のすべてのボリュームについて、Systemページで次の値を指定できます。

* *フラッシュの開始値*--キャッシュフラッシュ（ディスクへの書き込み）をトリガーするキャッシュ内の書き込み前のデータの割合。指定した開始の割合の書き込み前のデータがキャッシュに格納されると、フラッシュがトリガーされます。デフォルトでは、キャッシュが80%フルに達すると、コントローラがキャッシュのフラッシュを開始します。
* *キャッシュブロックサイズ*--キャッシュ管理の組織単位である各キャッシュブロックの最大サイズ。キャッシュブロックサイズはデフォルトで8KiBですが、4、8、16、32KiBに設定できます。アプリケーションの一般的なI/Oサイズにキャッシュブロックサイズを設定するのが理想的です。ファイルシステムやデータベースアプリケーションでは一般に小さいサイズを使用し、大規模なデータ転送やシーケンシャルI/Oを必要とするアプリケーションには大きいサイズが適しています




== ボリュームキャッシュの設定

ストレージアレイ内の個々のボリュームについて、Volumes（ボリューム）ページで次の値を指定できます（メニュー：Storage [Volumes]）。

* *読み取りキャッシュ*--読み取りキャッシュは'ドライブから読み取られたデータを格納するバッファです読み取り処理の対象となるデータが以前の処理ですでにキャッシュに格納されていれば、ドライブにアクセスする必要はありません。読み取りキャッシュのデータは、フラッシュされるまで保持されます。
+
** *動的キャッシュ読み取りプリフェッチ*--動的キャッシュ読み取りプリフェッチにより'コントローラは'ドライブからキャッシュにデータ・ブロックを読み取っているときに'追加のシーケンシャル・データ・ブロックをキャッシュにコピーすることができますこのキャッシングにより、以降のデータ要求にキャッシュから対応できる可能性が高まります。動的キャッシュ読み取りプリフェッチは、シーケンシャルI/Oを使用するマルチメディアアプリケーションで重要ですデータがキャッシュにプリフェッチされる速度と量は、ホスト読み取りの速度と要求サイズに基づいて自動で調整されます。ランダムアクセスの場合、原因 データがキャッシュにプリフェッチされることはありません。この機能は、読み取りキャッシュが無効になっている場合は適用されません。


* *書き込みキャッシュ*--書き込みキャッシュは'まだドライブに書き込まれていないホストからのデータを格納するバッファです書き込みキャッシュ内のデータは、ドライブに書き込まれるまで保持されます。書き込みキャッシュにより、I/Oパフォーマンスを向上させることができます。
+
[CAUTION]
====
*データ損失の可能性*--バッテリなしの書き込みキャッシュ*オプションを有効にして保護用のユニバーサル電源装置を持たないと、データが失われる可能性があります。また、コントローラのバッテリがない場合に*バッテリなしの書き込みキャッシュ*オプションを有効にすると、データが失われる可能性があります。

====
+
** *バッテリなしの書き込みキャッシュ*--バッテリなしの書き込みキャッシュ設定により、バッテリがない、故障している、完全に放電されている、またはフル充電されていない場合でも書き込みキャッシュを続行できます。バッテリなしの書き込みキャッシュを選択すると電源の喪失時にデータが失われる可能性があるため、一般には推奨されません。通常、書き込みキャッシュは、バッテリが充電されるか障害が発生したバッテリが交換されるまで、コントローラによって一時的にオフにされます。
** *ミラーリングありの書き込みキャッシュ*--ミラーリングありの書き込みキャッシュは'一方のコントローラのキャッシュ・メモリに書き込まれたデータがもう一方のコントローラのキャッシュ・メモリにも書き込まれたときに発生しますそのため、一方のコントローラで障害が発生した場合、もう一方のコントローラで未処理の書き込み処理をすべて完了できます。書き込みキャッシュのミラーリングは、書き込みキャッシュが有効で、2台のコントローラが配置されている場合にのみ使用できます。ミラーリングありの書き込みキャッシュは、ボリュームの作成時にデフォルトで設定されます。



