---
permalink: sm-settings/change-default-host-type.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, change, default, host, type, 
summary: デフォルトのホストオペレーティングシステムの変更設定を使用して、ストレージアレイレベルでデフォルトのホストタイプを変更します。一般に、デフォルトのホストタイプは、ストレージアレイにホストを接続する前、または追加のホストを接続するときに変更します。 
---
= デフォルトのホストタイプを変更
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
デフォルトのホストオペレーティングシステムの変更設定を使用して、ストレージアレイレベルでデフォルトのホストタイプを変更します。一般に、デフォルトのホストタイプは、ストレージアレイにホストを接続する前、または追加のホストを接続するときに変更します。

.このタスクについて
次のガイドラインに注意してください。

* ストレージアレイに接続するホストのオペレーティングシステムがすべて同じ場合は（同機種ホスト環境）、オペレーティングシステムに一致するホストタイプに変更します。
* ストレージアレイに接続するホストに異なるオペレーティングシステムのホストが混在している場合は（異機種ホスト環境）、ホストのオペレーティングシステムの大部分に一致するホストタイプに変更します。
+
たとえば、8つの異なるホストをストレージアレイに接続し、そのうち6つでWindowsオペレーティングシステムを実行している場合は、Windowsをデフォルトのホストオペレーティングシステムタイプとして選択する必要があります。

* ほとんどの接続ホストでオペレーティングシステムが異なる場合は、ホストタイプを工場出荷時のデフォルトに変更します。
+
たとえば、8つの異なるホストをストレージアレイに接続し、そのうち2つでWindowsオペレーティングシステムを実行している場合、3つでVMwareオペレーティングシステムを実行しています。 さらに、別の3つのOSでLinuxオペレーティングシステムを実行している場合は、デフォルトのホストオペレーティングシステムタイプとしてFactory Defaultを選択する必要があります。



.手順
. メニューを選択します。[設定][システム]。
. 下にスクロールして「その他の設定」を選択し、「デフォルトのホストOSタイプの変更」をクリックします。
. デフォルトとして使用するホストオペレーティングシステムのタイプを選択します。
. [ 変更（ Change ） ] をクリックします。

