---
permalink: sm-settings/change-local-user-passwords-settings.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, change, local, user, password, settings, 
summary: ストレージアレイで新規または更新されるローカルユーザパスワードの最小文字数を設定できます。また、ローカルユーザがパスワードを入力せずにストレージアレイにアクセスできるようにすることもできます。 
---
= ローカルユーザパスワードの設定を変更します
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイで新規または更新されるローカルユーザパスワードの最小文字数を設定できます。また、ローカルユーザがパスワードを入力せずにストレージアレイにアクセスできるようにすることもできます。

.作業を開始する前に
Root Adminの権限が割り当てられたローカル管理者としてログインする必要があります。

.このタスクについて
ローカルユーザパスワードの最小文字数を設定する際には、次のガイドラインに注意してください。

* 設定を変更しても既存のローカルユーザパスワードには影響しません。
* ローカルユーザパスワードの最小文字数は、0~30文字にする必要があります。
* 新しいローカルユーザパスワードは、現在の最小文字数の設定以上にする必要があります。
* ローカルユーザがパスワードを入力せずにストレージアレイにアクセスできるようにする場合は、パスワードの最小文字数を設定しないでください。


.手順
. メニューを選択します。Settings [Access Management]。
. [ローカルユーザー役割*（Local User Roles *）]タブを選択します。
. 「*表示/設定の編集*」ボタンを選択します。
+
[ローカルユーザーパスワードの設定]ダイアログボックスが開きます。

. 次のいずれかを実行します。
+
** ローカルユーザがパスワードを入力せずにストレージアレイにアクセスできるようにするには、「すべてのローカルユーザパスワードを少なくとも必要とする」チェックボックスをオフにします。
** すべてのローカルユーザパスワードの最小文字数を設定するには、「すべてのローカルユーザパスワードを少なくとも必要とする」チェックボックスをオンにしてから、スピンボックスを使用してすべてのローカルユーザパスワードの最小文字数を設定します。
+
新しいローカルユーザパスワードは、現在の設定以上の長さにする必要があります。



. [ 保存（ Save ） ] をクリックします。

