---
permalink: sm-settings/change-passwords.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, change, passwords, user, passwords, 
summary: アクセス管理で各ユーザプロファイルのユーザパスワードを変更できます。 
---
= パスワードを変更します
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アクセス管理で各ユーザプロファイルのユーザパスワードを変更できます。

.作業を開始する前に
* Root Adminの権限が割り当てられたローカル管理者としてログインする必要があります。
* ローカル管理者のパスワードを確認しておく必要があります。


.このタスクについて
パスワードを選択する際は、次のガイドラインに注意してください。

* 新しいローカルユーザパスワードは、最小パスワードの現在の設定（[表示/編集の設定]）以上である必要があります。
* パスワードは大文字と小文字を区別します。
* パスワードの末尾のスペースは削除されません。パスワードにスペースが含まれている場合は、スペースを含めるようにしてください。
* セキュリティを強化するために、パスワードには15文字以上の英数字を使用し、頻繁に変更してください。


[NOTE]
====
System Managerでパスワードを変更すると、コマンドラインインターフェイス（CLI）のパスワードも変更されます。また、パスワードは、ユーザのアクティブなセッションを終了するために原因 を変更します。

====
.手順
. メニューを選択します。Settings [Access Management]。
. [ローカルユーザー役割*（Local User Roles *）]タブを選択します。
. 表からユーザを選択します。
+
[パスワードの変更]ボタンが使用可能になります。

. [ パスワードの変更 *] を選択します。
+
[パスワードの変更]ダイアログボックスが開きます。

. ローカルユーザパスワードの最低文字数が設定されていない場合は、選択したユーザがパスワードを入力しないとストレージアレイにアクセスできないようにするオプションのチェックボックスをオンにし、そのユーザの新しいパスワードを入力します。
. ローカル管理者パスワードを入力し、* Change *をクリックします。


.結果
ユーザが現在ログインしている場合、パスワードを変更するとユーザのアクティブなセッションが終了します。
