---
permalink: sm-settings/change-security-key.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, change, security, key, 
summary: セキュリティキーは、いつでも新しいキーに置き換えることができます。セキュリティキーの変更が必要になるのは、会社でセキュリティ侵害が発生する可能性があり、権限のない担当者がドライブのデータにアクセスできないようにする場合です。 
---
= セキュリティキーを変更する
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
セキュリティキーは、いつでも新しいキーに置き換えることができます。社内でセキュリティ侵害の可能性があり、ドライブデータへの不正アクセスを防ぎたい場合は、セキュリティキーの変更が必要になることがあります。

.手順
. メニューを選択します。[設定][システム]。
. セキュリティキー管理*で、*キーの変更*を選択します。
+
[セキュリティキーの変更]ダイアログボックスが開きます。

. 次のフィールドに情報を入力します。
+
** *セキュリティキー識別子を定義*--(内部セキュリティキーの場合のみ) デフォルト値（コントローラファームウェアで生成されたストレージアレイ名とタイムスタンプ）をそのまま使用するか、独自の値を入力します。入力できる文字数は最大189文字です。使用できるのは英数字のみで、スペース、句読点、記号は使用できません。
+
[NOTE]
====
入力した文字列の前後に追加の文字が自動的に生成されて付加されます。文字が追加されることで識別子が一意であることが保証されます。

====
** *パスフレーズを定義/パスフレーズを再入力*--これらの各フィールドにパスフレーズを入力します8~32文字で指定し、以下の文字をそれぞれ1文字以上含める必要があります。
+
*** 大文字のアルファベット（1文字以上）。パスフレーズでは大文字と小文字が区別されることに注意してください。
*** 数字（1文字以上）。
*** 英数字以外の、！、*、@などの文字（1文字以上）。




. 外部セキュリティキーの場合に新しいセキュリティキーの作成時に古いセキュリティキーを削除するには、ダイアログの下部にある[Delete current security key...]チェックボックスをオンにします。
+
[CAUTION]
====
*後で使用するためにエントリを記録しておいてください*--セキュリティ有効ドライブをストレージアレイから移動する必要がある場合、ドライブデータのロックを解除するために識別子とパスフレーズを知っておく必要があります。

====
. [ 変更（ Change ） ] をクリックします。
+
前のキーが新しいセキュリティキーで上書きされ、無効になります。

+
[NOTE]
====
ダウンロードファイルのパスは、ブラウザのデフォルトのダウンロード先によって異なる場合があります。

====
. キー識別子、パスフレーズ、ダウンロードしたキーファイルの場所を記録し、*閉じる*をクリックします。


.完了後
セキュリティキーを検証して、キーファイルが破損していないことを確認します。
