---
permalink: sm-settings/change-saml-role-mappings.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, change, saml, role, mappings, 
summary: アクセス管理にSAMLを設定している場合は、IdPグループとストレージアレイの事前定義されたロールとの間のロールマッピングを変更できます。 
---
= SAMLのロールマッピングを変更する
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アクセス管理にSAMLを設定している場合、IdPグループとストレージアレイの事前定義されたロールとの間のロールマッピングを変更できます。

.作業を開始する前に
* Security Adminの権限を含むユーザプロファイルでログインする必要があります。そうしないと、アクセス管理機能は表示されません。
* IdP管理者が、IdPシステムでユーザ属性とグループメンバーシップを設定しておく必要があります。
* SAMLを設定して有効にします。


.手順
. メニューを選択します。Settings [Access Management]。
. SAML *タブを選択します。
. [*役割のマッピング*]を選択します。
+
ロールマッピング(Role Mapping)ダイアログボックスが開きます

. IdPユーザの属性とグループを事前定義されたロールに割り当てます。1つのグループに複数のロールを割り当てることができます。
+
[CAUTION]
====
SAMLが有効になっているときは権限を削除しないように注意してください。削除すると、System Managerにアクセスできなくなります。

====
+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 説明 


 a| 
*マッピング*



 a| 
ユーザー属性
 a| 
マッピングするSAMLグループの属性（「member of」など）を指定します。



 a| 
属性値
 a| 
マッピングするグループの属性値を指定します。



 a| 
ロール
 a| 
フィールド内をクリックし、属性にマッピングするストレージアレイのロールを選択します。このグループに含めるロールを個別に選択する必要があります。MonitorロールはSystem Managerにログインするため必要なロールであり、他のロールと一緒に指定する必要があります。少なくとも1つのグループにSecurity Adminロールを割り当てる必要があります。各ロールの権限は次のとおりです。

** * Storage admin *--ストレージ・オブジェクト（ボリュームやディスク・プールなど）への読み取り/書き込みのフル・アクセス。セキュリティ構成へのアクセスはありません。
** * Security admin *--アクセス管理、証明書管理、監査ログ管理のセキュリティ構成へのアクセス、および従来の管理インターフェイス（SYMbol）のオン/オフの切り替え機能。
** * Support admin *--ストレージアレイのすべてのハードウェアリソース、障害データ、MELイベント、およびコントローラファームウェアアップグレードへのアクセス。ストレージオブジェクトやセキュリティ設定にはアクセスできません。
** *Monitor *--すべてのストレージオブジェクトへの読み取り専用アクセスが可能ですが、セキュリティ設定へのアクセスはありません。


|===
====
+

NOTE: Monitorロールは、管理者を含むすべてのユーザに必要です。Monitorロールがないユーザの場合、System Managerは正常に動作しません。

. 必要に応じて、* Add another mapping *をクリックして、グループとロールのマッピングをさらに入力します。
. [ 保存（ Save ） ] をクリックします。


.結果
このタスクを完了すると、アクティブなユーザセッションはすべて終了します。現在のユーザセッションのみが保持されます。
