---
permalink: sm-settings/change-cache-settings-for-storage-array.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, change, cache, settings, 
summary: ストレージアレイ内のすべてのボリュームでは、フラッシュおよびブロックサイズについてキャッシュメモリの設定を調整できます。 
---
= ストレージアレイのキャッシュ設定を変更します
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイ内のすべてのボリュームでは、フラッシュおよびブロックサイズについてキャッシュメモリの設定を調整できます。

.このタスクについて
キャッシュメモリは、ドライブメディアよりも速くアクセスできる、コントローラ上の一時的な揮発性ストレージ領域です。キャッシュのパフォーマンスを調整するには、次の設定を調整します。

[cols="25h,~"]
|===
| キャッシュ設定 | 説明 


 a| 
デマンドキャッシュフラッシュを開始します
 a| 
キャッシュに格納された書き込み前のデータが何パーセントに達したらキャッシュフラッシュ（ディスクへの書き込み）を開始するかを指定します。デフォルトでは、書き込み前のデータが容量の80%に達するとキャッシュフラッシュが開始されます。書き込み処理が中心の環境では、この割合を高くすると、新しい書き込み要求をディスクにアクセスせずにキャッシュで処理できるため便利です。I/Oが不規則でデータのバーストがある環境では、この割合を低くして、バーストとバーストの間に頻繁にキャッシュがフラッシュされるようにすると効果的です。ただし、80%より小さいパーセントの開始パーセント値を指定すると、原因 のパフォーマンスが低下する可能性があります。



 a| 
キャッシュブロックサイズ
 a| 
キャッシュブロックサイズは、各キャッシュブロックの最大サイズであり、キャッシュを管理する際の単位となります。デフォルトのブロックサイズは32KiBです。システムでは、4、8、16、または32KiBのキャッシュブロックサイズを選択できます。使用するブロックサイズはアプリケーションによって異なり、ストレージのパフォーマンスに影響します。ファイルシステムやデータベースアプリケーションには小さいサイズが適しています。マルチメディアなどのシーケンシャルI/Oを生成するアプリケーションには、大きいサイズが適しています。

|===
.手順
. メニューを選択します。[設定][システム]。
. 下にスクロールして「その他の設定」を選択し、「キャッシュ設定の変更」をクリックします。
+
[キャッシュ設定の変更]ダイアログボックスが開きます。

. 次の値を調整します。
+
** *デマンド・キャッシュ・フラッシュを開始*--ご使用の環境で使用されるI/Oに適した割合を選択します80%未満の値を選択すると、パフォーマンスが低下する可能性があります。
** **キャッシュブロックサイズ--**アプリケーションに適したサイズを選択してください。


. [ 保存（ Save ） ] をクリックします。

