---
permalink: sm-settings/clear-storage-array-configuration.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, clear, storage, array, configuration, 
summary: ストレージアレイからすべてのプール、ボリュームグループ、ボリューム、ホストの定義、およびホストの割り当てを削除する場合は、設定のクリア処理を使用します。 
---
= ストレージアレイの構成のクリア
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイからすべてのプール、ボリュームグループ、ボリューム、ホストの定義、およびホストの割り当てを削除する場合は、設定のクリア処理を使用します。

.作業を開始する前に
ストレージアレイ構成をクリアする前に、データのバックアップを作成します。

.このタスクについて
ストレージアレイ構成のクリアオプションは2つあります。

* *ボリューム*--通常、テスト用ストレージアレイを本番ストレージアレイとして再構成するために、ボリュームオプションを使用します。たとえば、テスト用にストレージアレイを構成し、テストが完了したらテスト構成を削除し、本番環境用にストレージアレイをセットアップする場合があります。
* *ストレージ・アレイ*--通常'ストレージ・アレイを別の部門またはグループに移動するには'ストレージ・アレイ・オプションを使用しますたとえば、エンジニアリング部門が新しいストレージアレイを導入することになり、現在使用しているストレージアレイを管理部門に移動する場合などです。
+
ストレージアレイオプションを選択すると、追加の設定がいくつか削除されます。



[cols="1a,1a,1a"]
|===
|  | ボリューム | ストレージアレイ 


 a| 
プールとボリュームグループを削除します
 a| 
X
 a| 
X



 a| 
ボリュームを削除します
 a| 
X
 a| 
X



 a| 
ホストとホストクラスタを削除します
 a| 
X
 a| 
X



 a| 
ホスト割り当てを削除します
 a| 
X
 a| 
X



 a| 
ストレージアレイ名を削除します
 a| 
 a| 
X



 a| 
ストレージアレイのキャッシュ設定をデフォルトにリセットします
 a| 
 a| 
X

|===
[CAUTION]
====
*データ損失のリスク*-この処理を実行すると、ストレージアレイからすべてのデータが削除されます。（完全消去は実行されません）。 この処理は開始後にキャンセルすることはできません。この処理は、テクニカルサポートから指示があった場合にのみ実行してください。

====
.手順
. メニューを選択します。[設定][システム]。
. 「ストレージアレイ構成のクリア」を選択します。
. ドロップダウンリストで、* Volume *または* Storage Array *のいずれかを選択します。
. *オプション：*（データではなく）設定を保存する場合は、ダイアログボックス内のリンクを使用します。
. 処理を確定します。


.結果
* 現在の構成が削除され、ストレージアレイ上の既存のデータがすべて破棄されます。
* すべてのドライブの割り当てが解除されます。

