---
permalink: sm-settings/configure-iscsi-authentication.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, iscsi, authentication, 
summary: iSCSIネットワークのセキュリティを強化するために、コントローラ（ターゲット）とホスト（イニシエータ）の間に認証を設定できます。 
---
= iSCSI認証を設定
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
iSCSIネットワークのセキュリティを強化するために、コントローラ（ターゲット）とホスト（イニシエータ）の間に認証を設定できます。

System Managerは、チャレンジハンドシェイク認証プロトコル（CHAP）方式を使用します。CHAPは初回のリンク確立時にターゲットとイニシエータのIDを検証します。認証は、a_chap secret_という共有セキュリティキーに基づいて行われます。

.作業を開始する前に
イニシエータ（iSCSIホスト）のCHAPシークレットは、ターゲット（コントローラ）のCHAPシークレットを設定する前でもあとでも設定できます。このタスクの手順を実行する前に、ホストがiSCSI接続を確立するのを待ってから、個々のホストでCHAPシークレットを設定する必要があります。接続が確立されると、iSCSI認証のダイアログボックス（このタスクで説明）にホストのIQN名とCHAPシークレットが表示され、手動で入力する必要はありません。

.このタスクについて
次のいずれかの認証方法を選択できます。

* *一方向認証*--コントローラがiSCSIホストの識別情報を認証できるようにするには'この設定を使用します(一方向認証)
* *双方向認証*--コントローラとiSCSIホストの両方が認証(双方向認証)を実行できるようにするには'この設定を使用しますこの設定は、コントローラがiSCSIホストの識別情報を認証できるようにし、さらにiSCSIホストがコントローラの識別情報を認証できるようにすることで、二次的なセキュリティを提供します。


[NOTE]
====
iSCSIの設定と機能は、ストレージアレイがiSCSIをサポートしている場合にのみ、設定ページに表示されます。

====
.手順
. メニューを選択します。[設定][システム]。
. [iSCSI設定]で、[*認証の設定*]をクリックします。
+
Configure Authentication（認証の設定）ダイアログボックスが表示され、現在設定されている方式が示されます。CHAPシークレットが設定されているホストがあるかどうかも表示されます。

. 次のいずれかを選択します。
+
** *認証なし*--コントローラがiSCSIホストのIDを認証しないようにするには'このオプションを選択して'完了*をクリックしますダイアログボックスが閉じ、設定が完了します。
** *一方向認証*--コントローラがiSCSIホストのIDを認証できるようにするには'このオプションを選択して'次へをクリックします*ターゲットCHAPの構成ダイアログ・ボックスを表示します
** *双方向認証*--コントローラとiSCSIホストの両方が認証を実行できるようにするには'このオプションを選択して'次へ*をクリックし'ターゲットCHAPの構成ダイアログ・ボックスを表示します


. 一方向認証または双方向認証について、コントローラ（ターゲット）のCHAPシークレットを入力または確認します。CHAPシークレットは、12~57文字の印刷可能なASCII文字で指定する必要があります。
+
[NOTE]
====
コントローラのCHAPシークレットがすでに設定されている場合は、フィールド内の文字は表示されません。必要に応じて、既存の文字を置き換えることができます（新しい文字はマスクされません）。

====
. 次のいずれかを実行します。
+
** 一方向認証を設定する場合は、*完了*をクリックします。ダイアログボックスが閉じ、設定が完了します。
** _2Way _authenticationを設定する場合は、* Next *をクリックしてConfigure Initiator CHAPダイアログボックスを表示します。


. 双方向認証について、任意のiSCSIホスト（イニシエータ）のCHAPシークレット（12~57文字の印刷可能なASCII文字）を入力または確認します。特定のホストに双方向認証を設定しない場合は、Initiator CHAP Secretフィールドを空白のままにします。
+
[NOTE]
====
ホストのCHAPシークレットがすでに設定されている場合は、フィールド内の文字は表示されません。必要に応じて、既存の文字を置き換えることができます（新しい文字はマスクされません）。

====
. [ 完了 ] をクリックします。


.結果
認証なしを指定した場合を除き、iSCSIログインシーケンス中にコントローラとiSCSIホストの間で認証が行われます。
