---
permalink: sm-settings/configure-snmp-alerts.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, snmp, alerts, 
summary: 簡易ネットワーク管理プロトコル（SNMP）アラートを設定するには、ストレージアレイのイベントモニタからSNMPトラップを送信できるサーバを少なくとも1つ指定する必要があります。この設定には、コミュニティ名またはユーザ名、およびサーバのIPアドレスが必要です。 
---
= SNMPアラートを設定する
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
簡易ネットワーク管理プロトコル（SNMP）アラートを設定するには、ストレージアレイのイベントモニタからSNMPトラップを送信できるサーバを少なくとも1つ指定する必要があります。この設定には、コミュニティ名またはユーザ名、およびサーバのIPアドレスが必要です。

.作業を開始する前に
* ネットワークサーバにSNMPサービスアプリケーションが設定されている必要があります。イベントモニタからトラップメッセージを送信するためには、このサーバのネットワークアドレス（IPv4アドレスまたはIPv6アドレス）が必要です。複数のサーバを使用できます（最大10台のサーバを使用できます）。
* SNMPサービスアプリケーションがインストールされたサーバに管理情報ベース（MIB）ファイルをコピーしてコンパイルしておきます。このMIBファイルは、監視および管理されるデータを定義します。
+
MIBファイルがない場合は、ネットアップサポートサイトから入手できます。

+
** に進みます https://mysupport.netapp.com/site/global/dashboard["ネットアップサポート"^]。
** [*ダウンロード]タブをクリックし、[*ダウンロード]を選択します。
** EシリーズSANtricity OSコントローラソフトウェア*をクリックします。
** [最新リリースのダウンロード]を選択します。
** ログインします。
** 注意事項および使用許諾契約に同意します。
** コントローラタイプのMIBファイルが表示されるまで下にスクロールし、リンクをクリックしてファイルをダウンロードします。




このタスクでは、トラップの送信先となるSNMPサーバを指定し、設定をテストする方法について説明します。

.手順
. メニューを選択します。Settings [Alerts]（設定[Alerts]）。
. [*SNMP*]タブを選択します。
+
初めて設定するときは、SNMPタブに「コミュニティ/ユーザの設定」と表示されます。

. コミュニティ/ユーザーの設定*を選択します。
+
Select SNMP versionダイアログボックスが開きます。

. アラートのSNMPバージョンとして、* SNMPv2c *または* SNMPv3 *のいずれかを選択します。
+
選択内容に応じて、コミュニティの設定ダイアログボックスまたはSNMPv3ユーザーの設定ダイアログボックスが開きます。

. SNMPv2c（コミュニティ）またはSNMPv3（ユーザ）の適切な手順に従います。
+
** *SNMPv2c (communities)*--コミュニティの設定ダイアログで、ネットワークサーバーのコミュニティストリングを1つ以上入力します。コミュニティ名は、既知の一連の管理ステーションを識別する文字列で、通常はネットワーク管理者が作成します。印刷可能なASCII文字だけで構成されます。コミュニティは最大で256個追加できます。完了したら、*保存*をクリックします。
** *SNMPv3(Users)*-- SNMPv3ユーザーの設定ダイアログで、*Add*をクリックし、次の情報を入力します。
+
*** *ユーザー名*--ユーザーを識別するための名前を入力します最大31文字まで入力できます
*** *エンジンID *--メッセージの認証キーと暗号化キーを生成するために使用されるエンジンIDを選択します管理ドメイン上で一意である必要がありますほとんどの場合、*ローカル*を選択してください。標準以外の設定を使用している場合は、「*カスタム*」を選択します。別のフィールドが表示され、10～32文字の範囲で、正規のエンジンIDを16進数の文字列で入力する必要があります。
*** *認証資格情報*--ユーザーの識別を保証する認証プロトコルを選択します次に、認証プロトコルの設定時または変更時に必要となる認証パスワードを入力します。パスワードは8~128文字で指定する必要があります。
*** *プライバシー資格情報*--メッセージの内容を暗号化するために使用するプライバシープロトコルを選択します次に、プライバシープロトコルを設定または変更するときに必要なプライバシーパスワードを入力します。パスワードは8~128文字で指定する必要があります。完了したら、[*追加]をクリックし、[*閉じる]をクリックします。




. [SNMP]タブが選択されている[Alerts]ページで、[Add Trap Destinations*]をクリックします。
+
トラップ送信先の追加ダイアログボックスが開きます。

. 1つ以上のトラップ送信先を入力し、関連付けられているコミュニティ名またはユーザ名を選択して、* Add *をクリックします。
+
** *Trap Destination*-- SNMPサービスを実行しているサーバーのIPv4またはIPv6アドレスを入力します
** *コミュニティ名またはユーザー名*--ドロップダウンから、このトラップの送信先のコミュニティ名（SNMPv2c）またはユーザー名（SNMPv3）を選択します。（定義したのが1つだけの場合は、このフィールドにはすでに名前が表示されます）。
** *認証失敗トラップを送信*--コミュニティ名またはユーザ名が認識されないためにSNMP要求が拒否された場合にトラップの送信先にアラートを送信するには、このオプション（チェックボックス）を選択します。[Add（追加）]をクリックすると、[* Alerts]ページの[* SNMP]タブにトラップの送信先と関連する名前が表示されます。


. トラップが有効であることを確認するには、テーブルからトラップの送信先を選択し、*トラップの送信先のテスト*をクリックして、設定したアドレスにテストトラップを送信します。


アラート対象のイベントが発生するたびに、イベントモニタからサーバにSNMPトラップが送信されます。
