---
permalink: sm-settings/configure-syslog-server-for-alerts.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, syslog, server, alerts, 
summary: syslogアラートを設定するには、syslogサーバのアドレスとUDPポートを入力する必要があります。最大5台のsyslogサーバを指定できます。 
---
= アラート用のsyslogサーバを設定します
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
syslogアラートを設定するには、syslogサーバのアドレスとUDPポートを入力する必要があります。最大5台のsyslogサーバを指定できます。

.作業を開始する前に
* syslogサーバのアドレスを確認しておく必要があります。このアドレスは、完全修飾ドメイン名、IPv4アドレス、またはIPv6アドレスのいずれかで指定できます。
* syslogサーバのUDPポート番号を確認しておく必要があります。通常は514です。


.このタスクについて
このタスクでは、syslogサーバのアドレスとポートを入力し、入力したアドレスをテストする方法について説明します。

.手順
. メニューを選択します。Settings [Alerts]（設定[Alerts]）。
. *Syslog *タブを選択します。
+
syslogサーバがまだ定義されていない場合は、[Alerts]ページに[Add Syslog Servers]と表示されます。

. [Add Syslog Servers]をクリックします。
+
[Add Syslog Server]ダイアログボックスが開きます。

. 1つ以上のsyslogサーバ（最大5つ）の情報を入力し、* Add *をクリックします。
+
** *サーバーアドレス*--完全修飾ドメイン名、IPv4アドレス、またはIPv6アドレスを入力します。
** *UDPポート*-- syslogのUDPポートは通常514です。設定されているsyslogサーバが表に表示されます。


. サーバーアドレスにテストアラートを送信するには、*すべてのSyslogサーバーをテスト*を選択します。


.結果
アラート対象のイベントが発生するたびに、イベントモニタからsyslogサーバにアラートが送信されます。
