---
permalink: sm-settings/configure-nvme-over-roce-ports-system.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, nvme, roce, ports, 
summary: コントローラにNVMe over RoCE（RDMA over Converged Ethernet）用の接続が含まれている場合は、システムページからNVMeポートを設定できます。 
---
= SANtricity System ManagerでNVMe over RoCEポートを構成する
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コントローラにNVMe over RoCE（RDMA over Converged Ethernet）用の接続が含まれている場合は、システムページからNVMeポートを設定できます。

.作業を開始する前に
* コントローラにNVMe over RoCEホストポートが搭載されている必要があります。そうでないと、System ManagerでNVMe over RoCE設定を使用できません。
* ホスト接続のIPアドレスを確認しておく必要があります。


.手順
. メニューを選択します。[設定][システム]。
. [* NVMe over ROCE SETTINGS *（NVMe over ROCE設定*）]で、[* Configure NVMe over ROCE Ports]を選択します。
. NVMe over RoCEポートを設定するコントローラを選択します。「 * 次へ * 」をクリックします。
. 設定するHICポートをドロップダウンリストから選択します。「 * 次へ * 」をクリックします。
. ポートを設定します。
+
すべてのポート設定を表示するには、ダイアログボックスの右側にある * Show more port settings * リンクをクリックします。

+
.フィールドの詳細
[%collapsible]
====
[cols="1a,1a"]
|===
| ポートの設定 | 説明 


 a| 
イーサネットポート速度の設定
 a| 
ポートのSFPの速度と同じ速度を選択します。



 a| 
IPv4 を有効にする / IPv6 を有効にする
 a| 
一方または両方のオプションを選択して、 IPv4 ネットワークと IPv6 ネットワークのサポートを有効にします。


NOTE: ポートへのアクセスを無効にする場合は、両方のチェックボックスを選択解除します。



 a| 
MTU サイズ（ * Show more port settings* をクリックすると使用可能）
 a| 
必要に応じて、 Maximum Transmission Unit （ MTU ；最大伝送ユニット）の新しいサイズをバイト単位で入力します。

デフォルトの Maximum Transmission Unit （ MTU ；最大転送単位）サイズは 1500 バイト / フレームです。1500~9000 の値を入力する必要があります。

|===
====
+
[*IPv4 を有効にする *] を選択した場合は、 [ 次へ *] をクリックすると、 IPv4 設定を選択するためのダイアログボックスが開きます。[*IPv6 を有効にする *] を選択した場合、 [ 次へ *] をクリックすると、 IPv6 設定を選択するためのダイアログボックスが開きます。両方のオプションを選択した場合は、 IPv4 設定のダイアログボックスが最初に開き、 * 次へ * をクリックすると、 IPv6 設定のダイアログボックスが開きます。

. IPv4 と IPv6 、またはその両方を自動または手動で設定します。
+
.フィールドの詳細
[%collapsible]
====
[cols="1a,1a"]
|===
| ポートの設定 | 説明 


 a| 
自動的に設定を取得します
 a| 
設定を自動的に取得するには、このオプションを選択します。



 a| 
静的な設定を手動で指定します
 a| 
このオプションを選択した場合は、フィールドに静的アドレスを入力します。（必要に応じて、住所をカットアンドペーストしてフィールドに貼り付けることもできます）。 IPv4の場合は、ネットワークのサブネットマスクとゲートウェイも指定します。IPv6 の場合は、ルーティング可能な IP アドレスとルータの IP アドレスも指定します。200Gb対応のHICを使用してEF600ストレージアレイを設定する場合、このダイアログボックスには、ネットワークパラメータの2セットのフィールドが表示されます。1つは物理ポート（外部）用のフィールドで、もう1つは仮想ポート（内部）用のフィールドです。両方のポートに一意のパラメータを割り当てる必要があります。これらの設定により、ホストは各ポート間のパスを確立し、HICのパフォーマンスを最大限に高めることができます。仮想ポートにIPアドレスを割り当てない場合、HICの実行速度は約半分になります。

|===
====
. [ 完了 ] をクリックします。

