---
permalink: sm-settings/configure-syslog-server-for-audit-logs.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, syslog, server, audit, logs, 
summary: 監査ログを外部のsyslogサーバにアーカイブする場合は、そのサーバとストレージアレイの間の通信を設定できます。接続が確立されると、監査ログは自動的にsyslogサーバに保存されます。 
---
= SANtricity System Managerで監査ログ用のSyslogサーバーを構成する
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
監査ログを外部のsyslogサーバにアーカイブする場合は、そのサーバとストレージアレイの間の通信を設定できます。接続が確立されると、監査ログは自動的にsyslogサーバに保存されます。

.作業を開始する前に
* Security Adminの権限を含むユーザプロファイルでログインする必要があります。そうしないと、アクセス管理機能は表示されません。
* syslogサーバのアドレス、プロトコル、およびポート番号を確認しておく必要があります。サーバアドレスは、完全修飾ドメイン名、IPv4アドレス、またはIPv6アドレスのいずれかで指定できます。
* サーバがセキュアなプロトコル（TLSなど）を使用している場合は、ローカルシステムに認証局（CA）証明書が配置されている必要があります。CA証明書がWebサイトの所有者を識別することにより、サーバとクライアントの間のセキュアな接続が確立さ


.手順
. 左側のパネルからメニュー：監視［監査ログ］を選択し、*syslogサーバの設定*を選択します。
+
Configure Syslog Serversダイアログボックスが開きます。

. [ 追加（ Add ） ] をクリックします。
+
[Add Syslog Server]ダイアログボックスが開きます。

. サーバーの情報を入力し、*追加*をクリックします。
+
** *サーバーアドレス*--完全修飾ドメイン名、IPv4アドレス、またはIPv6アドレスを入力します。
** *Protocol*--ドロップダウンリストからプロトコル(TLS、UDP、TCPなど)を選択します。
** *証明書のアップロード（オプション）*-- TLSプロトコルを選択して署名済みCA証明書をまだアップロードしていない場合は、[*参照]をクリックして証明書ファイルをアップロードします。監査ログは、信頼された証明書がないとsyslogサーバにアーカイブされません。
+
[NOTE]
====
証明書が後から無効になった場合、TLSハンドシェイクは失敗します。その結果、監査ログにエラーメッセージが記録され、メッセージはsyslogサーバに送信されなくなります。この問題を解決するには、syslogサーバの証明書を修正してから、menu:Monitoring[Audit log > Configure Syslog Servers > Test All]に移動してください。

====
** *ポート*-- syslogレシーバーのポート番号を入力します。[Add *]をクリックすると、[Configure Syslog Servers]ダイアログボックスが開き、設定したsyslogサーバがページに表示されます。


. ストレージアレイとのサーバ接続をテストするには、「*すべてテスト」を選択します。


.結果
設定が完了すると、以降すべての監査ログがsyslogサーバに送信されるようになります。以前のログは転送されません。アラートのsyslog設定の詳細については、を参照してください。 https://docs.netapp.com/us-en/e-series-santricity/sm-settings/configure-syslog-server-for-alerts.html["アラート用のsyslogサーバを設定します"]。

 NOTE: If multiple syslog servers are configured, all configured syslog servers will receive an audit log.