---
permalink: sm-settings/configure-iscsi-authentication.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, iscsi, authentication, 
summary: iSCSIネットワークのセキュリティを強化するために、コントローラ（ターゲット）とホスト（イニシエータ）の間に認証を設定できます。 
---
= SANtricity System ManagerでiSCSI認証を構成する
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
iSCSIネットワークのセキュリティを強化するために、コントローラ（ターゲット）とホスト（イニシエータ）の間に認証を設定できます。

System Managerは、チャレンジハンドシェイク認証プロトコル（CHAP）方式を使用します。CHAPは初回のリンク確立時にターゲットとイニシエータのIDを検証します。認証は、a_chap secret_という共有セキュリティキーに基づいて行われます。

.作業を開始する前に
イニシエータ（iSCSIホスト）のCHAPシークレットは、ターゲット（コントローラ）のCHAPシークレットを設定する前でもあとでも設定できます。このタスクの手順を実行する前に、ホストがiSCSI接続を確立するのを待ってから、個々のホストでCHAPシークレットを設定する必要があります。接続が確立されると、iSCSI認証のダイアログボックス（このタスクで説明）にホストのIQN名とCHAPシークレットが表示され、手動で入力する必要はありません。

.このタスクについて
CHAP認証を有効にして、一方向認証用のターゲットCHAPシークレットを指定することも、コントローラとiSCSIホスト間の双方向認証用のイニシエータCHAPシークレットの両方を指定することもできます。

一方向認証では、コントローラがiSCSIホストのIDを認証できます（単方向認証）。

双方向認証では、コントローラとiSCSIホストの両方が認証を実行できます（双方向認証）。このオプションは、コントローラがiSCSIホストの身元を認証し、さらにiSCSIホストがコントローラの身元を認証できるようにすることで、セキュリティを2段階に強化します。

.手順
. 左側のパネルから*システム*を選択してください。
. 「iSCSI設定」で、「iSCSI認証の設定」をクリックします。
+
「認証設定」ウィンドウが表示されます。

. 認証を有効にするには、「CHAP認証を有効にする」チェックボックスを選択してください。
+
CHAP認証を有効にしたくない場合は、チェックボックスをオフにしてください。

. 一方向認証を有効にした場合は、ターゲットに接続するイニシエータの認証に使用する*ターゲット CHAP シークレット*を入力してください。CHAPシークレットは、12～57文字の印刷可能なASCII文字で指定する必要があります。
+
「ターゲットCHAPシークレットの確認」フィールドに、同じCHAPシークレットを再度入力して確認してください。

. コントローラとiSCSIホスト間の双方向認証を有効にする場合は、イニシエータによるコントローラの認証に使用する*イニシエータCHAPシークレット*を入力してください。CHAPシークレットは、12文字から57文字までの印刷可能なASCII文字でなければなりません。
. [ 保存（ Save ） ] をクリックします。


.結果
認証なしを指定した場合を除き、iSCSIログインシーケンス中にコントローラとiSCSIホストの間で認証が行われます。
