---
permalink: sm-settings/configure-mail-server-and-recipients-for-alerts.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, mail, server, recipients, alerts, 
summary: Eメールアラートを設定するには、メールサーバのアドレスとアラート受信者のEメールアドレスを指定する必要があります。Eメールアドレスは20個まで指定できます。 
---
= メールサーバとアラートの受信者を設定
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Eメールアラートを設定するには、メールサーバのアドレスとアラート受信者のEメールアドレスを指定する必要があります。Eメールアドレスは20個まで指定できます。

.作業を開始する前に
* メールサーバのアドレスを確認しておく必要があります。アドレスには、IPv4アドレス、IPv6アドレス、または完全修飾ドメイン名を使用できます。
+
[NOTE]
====
完全修飾ドメイン名を使用するには、両方のコントローラにDNSサーバを設定する必要があります。DNSサーバはハードウェアページから設定できます。

====
* アラート送信者として使用するEメールアドレスを確認しておく必要があります。これは、アラートメッセージの「送信元」フィールドに表示されるアドレスです。SMTPプロトコルでは送信者アドレスが必要です。ない場合はエラーになります。
* アラート受信者のEメールアドレスを確認しておく必要があります。通常、受信者には、ネットワーク管理者またはストレージ管理者のアドレスを指定します。Eメールアドレスは20個まで入力できます。


.このタスクについて
このタスクでは、メールサーバの設定方法、送信者と受信者のEメールアドレスの入力方法、および[Alerts]ページから入力したすべてのEメールアドレスのテスト方法について説明します。

[NOTE]
====
Eメールアラートは初期セットアップウィザードから設定することもできます。

====
.手順
. メニューを選択します。Settings [Alerts]（設定[Alerts]）。
. [*Email*]タブを選択します。
+
Eメールサーバがまだ設定されていない場合は、［Eメール］タブに［メールサーバの設定］と表示されます。

. ［*メールサーバーの設定*］を選択します。
+
メールサーバーの設定ダイアログボックスが開きます。

. メールサーバの情報を入力し、[保存]をクリックします。
+
** *メールサーバーアドレス*--メールサーバーの完全修飾ドメイン名、IPv4アドレス、またはIPv6アドレスを入力します。
+
[NOTE]
====
完全修飾ドメイン名を使用するには、両方のコントローラにDNSサーバを設定する必要があります。DNSサーバはハードウェアページから設定できます。

====
** *Email sender address *--電子メールの送信者として使用する有効な電子メールアドレスを入力しますこのアドレスは、電子メールメッセージの「送信元」フィールドに表示されます。
** *Encryption*--メッセージを暗号化する場合は、暗号化タイプとして*SMTPS*または*STARTTLS *を選択し、暗号化されたメッセージのポート番号を選択します。それ以外の場合は、*なし*を選択します。
** *ユーザー名とパスワード*--必要に応じて、送信側とメールサーバーで認証を行うためのユーザー名とパスワードを入力します。
** *電子メールに連絡先情報を含める*--送信者の連絡先情報を警告メッセージに含めるには、このオプションを選択し、名前と電話番号を入力します。
+
[保存]をクリックすると、[アラート]ページの[電子メール]タブに電子メールアドレスが表示されます。



. [電子メールの追加]を選択します。
+
[電子メールの追加]ダイアログボックスが開きます。

. アラート受信者のEメールアドレスを1つ以上入力し、*追加*をクリックします。
+
EメールアドレスがAlerts（アラート）ページに表示されます。

. メールアドレスが有効であることを確認するには、「*すべてのメールをテスト*」をクリックして、テストメッセージを受信者に送信します。


.結果
Eメールアラートを設定すると、アラート対象のイベントが発生するたびにイベントモニタから指定した受信者にEメールメッセージが送信されます。
