---
permalink: sm-settings/create-internal-security-key.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, internal, security, key, 
summary: ドライブセキュリティ機能を使用するために、ストレージアレイのコントローラとセキュリティ対応ドライブで共有される内部セキュリティキーを作成できます。内部キーは、コントローラの永続的メモリに保持されます。 
---
= 内部セキュリティキーを作成します
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ドライブセキュリティ機能を使用するために、ストレージアレイのコントローラとセキュリティ対応ドライブで共有される内部セキュリティキーを作成できます。内部キーは、コントローラの永続的メモリに保持されます。

.作業を開始する前に
* ストレージアレイにセキュリティ対応ドライブが搭載されている必要があります。対応するドライブには、Full Disk Encryption（FDE）ドライブと連邦情報処理標準（FIPS）ドライブがあります。
* ドライブセキュリティ機能を有効にする必要があります。そうしないと、このタスクの実行中に[セキュリティキーを作成できません]ダイアログボックスが開きます。ドライブセキュリティ機能を有効にする手順については、必要に応じてストレージベンダーに問い合わせてください。


[NOTE]
====
ストレージアレイにFDEドライブとFIPSドライブの両方が搭載されている場合、すべてのドライブで同じセキュリティキーが共有されます。

====
.このタスクについて
このタスクでは、内部セキュリティキーに関連付ける識別子とパスフレーズを定義します。

[NOTE]
====
ドライブセキュリティのパスフレーズは、ストレージアレイの管理者パスワードとは無関係です。

====
.手順
. メニューを選択します。[設定][システム]。
. セキュリティキー管理*で、*内部キーの作成*を選択します。
+
まだセキュリティキーを生成していない場合は、セキュリティキーの作成ダイアログボックスが開きます。

. 次のフィールドに情報を入力します。
+
** *セキュリティキー識別子を定義*--デフォルト値(コントローラファームウェアによって生成されたストレージアレイ名とタイムスタンプ)をそのまま使用するか'独自の値を入力することができます入力できる文字数は最大189文字です。使用できるのは英数字のみで、スペース、句読点、記号は使用できません。
+
[NOTE]
====
入力した文字列の前後に追加の文字が自動的に生成されて付加されます。文字が追加されることで識別子が一意であることが保証されます。

====
** *パスフレーズを定義/パスフレーズを再入力*--パスフレーズを入力して確認します8~32文字で指定し、以下の文字をそれぞれ1文字以上含める必要があります。
+
*** 大文字のアルファベット（1文字以上）。パスフレーズでは大文字と小文字が区別されることに注意してください。
*** 数字（1文字以上）。
*** 英数字以外の、！、*、@などの文字（1文字以上）。




+
[CAUTION]
====
*後で使用するために、必ず入力を記録しておいてください*。セキュリティ有効ドライブをストレージアレイから移動する必要がある場合、ドライブデータのロックを解除するために識別子とパスフレーズが必要になります。

====
. [ 作成（ Create ） ] をクリックします。
+
セキュリティキーは、コントローラ上のアクセスできない場所に格納されます。実際のキーとともに、ブラウザからダウンロードされた暗号化されたキーファイルも格納されます。

+
[NOTE]
====
ダウンロードファイルのパスは、ブラウザのデフォルトのダウンロード先によって異なる場合があります。

====
. キー識別子、パスフレーズ、ダウンロードしたキーファイルの場所を記録し、*閉じる*をクリックします。


.結果
これで、セキュリティ有効のボリュームグループまたはプールを作成したり、既存のボリュームグループまたはプールでセキュリティを有効にしたりできます。

[NOTE]
====
ドライブの電源をオフにしてオンにするたびに、すべてのセキュリティ有効ドライブがセキュリティロック状態になります。この状態のドライブのデータには、ドライブの初期化時にコントローラによって正しいセキュリティキーが適用されるまでアクセスできません。第三者がロックされたドライブを物理的に取り外して別のシステムに取り付けた場合でも、データへの不正アクセスを防止することができます。

====
.完了後
セキュリティキーを検証して、キーファイルが破損していないことを確認します。
