---
permalink: sm-settings/default-host-operating-system-type.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, default, host, operating, system, 
summary: デフォルトのホストタイプは、ホストの最初の接続時にストレージアレイで使用されます。ボリュームがアクセスされたときに、ストレージアレイ内のコントローラがホストのオペレーティングシステムとどのように連携するかを定義します。 
---
= デフォルトのホストオペレーティングシステムタイプ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
デフォルトのホストタイプは、ホストの最初の接続時にストレージアレイで使用されます。ボリュームがアクセスされたときに、ストレージアレイのコントローラがホストのオペレーティングシステムとどのように連携するかを定義します。

接続されたホストを基準にストレージアレイの動作を変更する必要がある場合は、ホストタイプを変更できます。一般に、デフォルトのホストタイプは、ストレージアレイにホストを接続する前、または追加のホストを接続するときに変更します。

次のガイドラインに注意してください。

* ストレージアレイに接続するホストのオペレーティングシステムがすべて同じ場合は（同機種ホスト環境）、オペレーティングシステムに一致するホストタイプに変更します。
* ストレージアレイに接続するホストに異なるオペレーティングシステムのホストが混在している場合は（異機種ホスト環境）、ホストのオペレーティングシステムの大部分に一致するホストタイプに変更します。
+
たとえば、8つの異なるホストをストレージアレイに接続し、そのうち6つでWindowsオペレーティングシステムを実行している場合は、Windowsをデフォルトのホストオペレーティングシステムタイプとして選択する必要があります。

* ほとんどの接続ホストでオペレーティングシステムが異なる場合は、ホストタイプを工場出荷時のデフォルトに変更します。
+
たとえば、8つの異なるホストをストレージアレイに接続し、そのうち2つでWindowsオペレーティングシステムを実行している場合、3つでVMwareオペレーティングシステムを実行しています。 さらに、別の3つのOSでLinuxオペレーティングシステムを実行している場合は、デフォルトのホストオペレーティングシステムタイプとしてFactory Defaultを選択する必要があります。



[]
====

====