---
permalink: sm-settings/define-log-policies.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, define, audit, log, policies, 
summary: 上書きポリシーや監査ログに記録するイベントのタイプを変更することができます。 
---
= 監査ログポリシーを定義する
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
上書きポリシーや監査ログに記録するイベントのタイプを変更することができます。

.作業を開始する前に
Security Adminの権限を含むユーザプロファイルでログインする必要があります。そうしないと、アクセス管理機能は表示されません。

.このタスクについて
このタスクでは、監査ログの設定を変更する方法について説明します。古いイベントの上書きに関するポリシーや記録するイベントタイプに関するポリシーなどが含まれます。

.手順
. メニューを選択します。Settings [Access Management]。
. [*監査ログ*]タブを選択します。
. 「*表示/設定の編集*」を選択します。
+
[監査ログの設定]ダイアログボックスが開きます。

. 上書きポリシーや記録するイベントのタイプを変更します。
+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 説明 


 a| 
上書きポリシー
 a| 
最大容量に達したときに古いイベントを上書きするポリシーを指定します。

** *監査ログがいっぱいになったらイベントを古いものから上書きする*-監査ログが50、000レコードに達したときに古いイベントを上書きします。
** *監査ログのイベントを手動で削除する必要があります*-イベントが自動的に削除されないように指定します。設定した割合に達した場合、しきい値の警告が表示されます。イベントは手動で削除する必要があります。
+

NOTE: 上書きポリシーを無効にした場合、監査ログのエントリが上限に達すると、Security Adminの権限がないユーザによるSystem Managerへのアクセスは拒否されます。Security Adminの権限がないユーザが再びシステムにアクセスできるようにするには、Security Adminロールが割り当てられているユーザが古いイベントレコードを削除する必要があります。

+

NOTE: 上書きポリシーは、監査ログをsyslogサーバにアーカイブするように設定されている場合は適用されません。





 a| 
ログに記録するアクションのレベル
 a| 
ログに記録するイベントのタイプを指定します。

** *変更イベントのみを記録する*--ユーザーの操作によってシステムに変更が発生するイベントのみを記録します
** *すべての変更イベントと読み取り専用イベントを記録する*--情報の読み取りまたはダウンロードを伴うユーザー操作を含むすべてのイベントを記録します


|===
====
. [ 保存（ Save ） ] をクリックします。

