---
permalink: sm-settings/edit-user-names-for-snmp-traps.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, edit, user, settings, snmpv3, traps, 
summary: SNMPv3トラップのユーザ定義を編集できます。 
---
= SNMPv3トラップのユーザ設定を編集します
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SNMPv3トラップのユーザ定義を編集できます。

.作業を開始する前に
SNMPv3トラップのユーザを作成する必要があります。

.手順
. メニューを選択します。Settings [Alerts]（設定[Alerts]）。
. [*SNMP*]タブを選択します。
+
トラップの送信先とユーザ名が表に表示されます。

. ユーザー定義を編集するには、テーブルでユーザーを選択し、*ユーザーの設定*をクリックします。
. ダイアログで、*表示/設定の編集*をクリックします。
. 次の情報を編集します。
+
** *ユーザー名*--ユーザーを識別する名前を変更します最大31文字まで入力できます
** *エンジンID *--メッセージの認証キーと暗号化キーを生成するために使用されるエンジンIDを選択します管理ドメイン上で一意である必要がありますほとんどの場合、*ローカル*を選択してください。標準以外の設定を使用している場合は、「*カスタム*」を選択します。別のフィールドが表示され、10～32文字の範囲で、正規のエンジンIDを16進数の文字列で入力する必要があります。
** *認証資格情報*--ユーザーの識別を保証する認証プロトコルを選択します次に、認証プロトコルの設定時または変更時に必要となる認証パスワードを入力します。パスワードは8~128文字で指定する必要があります。
** *プライバシー資格情報*--メッセージの内容を暗号化するために使用するプライバシープロトコルを選択します次に、プライバシープロトコルを設定または変更するときに必要なプライバシーパスワードを入力します。パスワードは8~128文字で指定する必要があります。




.結果
Alerts（アラート）ページのSNMP（SNMP）タブに、更新された設定が表示されます。
