---
permalink: sm-settings/enable-iscsi-discovery-settings.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, enable, iscsi, discovery, settings, 
summary: iSCSIネットワーク内のストレージデバイスの検出に関連する設定を有効にすることができます。 
---
= SANtricity System ManagerでiSCSI検出設定を有効にする
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
iSCSIネットワーク内のストレージデバイスの検出に関連する設定を有効にすることができます。

ターゲット検出設定では、Internet Storage Name Service（iSNS）プロトコルを使用してストレージアレイのiSCSI情報を登録し、名前のない検出セッションを許可するかどうかを設定できます。

.作業を開始する前に
iSNSサーバで静的IPアドレスが使用されている場合は、そのアドレスをiSNSの登録に使用できる必要があります。IPv4とIPv6の両方がサポートされています。

.このタスクについて
iSCSI検出に関連する次の設定を有効にすることができます。

* * iSNSサーバによるターゲットの登録を有効にする*--有効にすると'ストレージ・アレイはiSNSサーバからiSCSI Qualified Name（IQN）とポート情報を登録しますこの設定は、イニシエータがiSNSサーバからIQNとポート情報を取得できるように、iSNS検出を許可します。
* *名前のない検出セッションを有効にする*--名前のない検出セッションを有効にすると'イニシエータ（iSCSIホスト）は'検出タイプ接続のログインシーケンス中にターゲットのIQN（コントローラ）を指定する必要はありません無効な場合、ホストはIQNを指定してコントローラへの検出セッションを確立する必要があります。ただし、通常の（I/Oベアリング）セッションでは常にターゲットIQNが必要です。この設定を無効にすると、権限のないiSCSIホストがIPアドレスのみを使用してコントローラに接続することを防止できます。


[NOTE]
====
iSCSIの設定と機能は、ストレージアレイがiSCSIをサポートしている場合にのみ、設定ページに表示されます。

====
.手順
. メニューを選択します。[設定][システム]。
. [* iSCSI settings]で、[*ターゲット検出設定の表示/編集]をクリックします。
+
Target Discovery Settings（ターゲット検出設定）ダイアログボックスが表示されます。[Enable iSNS server*...]フィールドの下に、コントローラがすでに登録されているかどうかを示すダイアログボックスが表示されます。

. コントローラを登録するには、[iSNSサーバーを有効にしてターゲットを登録する*]を選択し、次のいずれかを選択します。
+
** * DHCPサーバから自動的に設定を取得*--動的ホスト構成プロトコル(DHCP)サーバを使用してiSNSサーバを設定する場合は'このオプションを選択しますこのオプションを使用する場合は、コントローラのすべてのiSCSIポートでDHCPを使用するように設定する必要があります。必要に応じて、コントローラのiSCSIポートの設定を更新して、このオプションを有効にします。
+
[NOTE]
====
DHCPサーバでiSNSサーバのアドレスを指定するには'オプション43のベンダー固有の情報を使用するようにDHCPサーバを設定する必要があります このオプションでは、iSNSサーバのIPv4アドレスをデータバイト0xa-0xd（10-13）に含める必要があります。

====
** *静的な設定を手動で指定*-- iSNSサーバの静的IPアドレスを入力する場合は'このオプションを選択します（必要に応じて、住所をカットアンドペーストしてフィールドに貼り付けることもできます）。 フィールドに、IPv4アドレスまたはIPv6アドレスを入力します。両方を設定した場合は、IPv4がデフォルトです。また、TCPリスニングポートを入力します（デフォルトの3205を使用するか、49152~65535の値を入力）。


. ストレージアレイを名前のない検出セッションの対象にするには、*名前のない検出セッションを有効にする*を選択します。
+
** 有効にすると、iSCSIイニシエータは、コントローラの情報を取得するためにターゲットIQNを指定する必要はありません。
** 無効にすると、イニシエータがターゲットIQNを指定しないかぎり、検出セッションは実行されません。名前のない検出セッションを無効にすると、セキュリティが向上します。


. [ 保存（ Save ） ] をクリックします。


.結果
System ManagerがコントローラをiSNSサーバに登録しようとする間、進捗状況バーが表示されます。この処理には最大5分かかることがあります。
