---
permalink: sm-settings/enable-feature-pack.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, enable, feature, pack, 
summary: 機能パックは、ストレージアレイの属性を変更する（プロトコルをFibre ChannelからiSCSIに変更するなど）バンドルです。機能パックを有効にするには特別なキーが必要です。 
---
= SANtricity System Managerで機能パックを有効にする
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
機能パックは、ストレージアレイの属性を変更する（プロトコルをFibre ChannelからiSCSIに変更するなど）バンドルです。機能パックを有効にするには特別なキーが必要です。

.作業を開始する前に
* 新しいストレージアレイ属性の変換と準備について説明した適切な手順を実行しておきます。ホストプロトコルの変更手順については、使用しているコントローラモデルのハードウェアメンテナンスガイドを参照してください。
* ストレージアレイがオフラインであり、ホストやアプリケーションからのアクセスがないことを確認します。
* すべてのデータがバックアップされます。
* 機能パックファイルを入手しておきます。
+
機能パックファイルは管理クライアント（System Managerにアクセスするためのブラウザを備えたシステム）上にロードされます。



[NOTE]
====
システムを停止するメンテナンス時間をスケジュールして、ホストとコントローラの間のすべてのI/O処理を停止する必要があります。また、変更が完了するまではストレージアレイのデータにアクセスできないことに注意してください。

====
.このタスクについて
このタスクでは、System Managerを使用して機能パックを有効にする方法について説明します。完了したら、ストレージアレイを再起動する必要があります。

.手順
. メニューを選択します。[設定][システム]。
. [ * アドオン * ] で、 [ * 機能パックの変更 * ] を選択します。
. [*Browse*](参照)をクリックし、キーファイルを選択します。
+
ファイル名がダイアログボックスに表示されます。

. フィールドに「CHANGE」と入力します。
. [ 変更（ Change ） ] をクリックします。
+
機能パックの移行が開始され、コントローラがリブートします。I/Oアクティビティをなくすために、書き込み前のキャッシュデータが削除されます。両方のコントローラが自動的にリブートし、新しい機能パックが有効になります。リブートが完了すると、ストレージアレイは応答可能な状態に戻ります。


