---
permalink: sm-settings/enable-or-disable-resource-provisioning-for-new-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, enable, disable, resource, provisioning, 
summary: 以前にリソースプロビジョニングのデフォルト機能を無効にしていた場合は、設定に移動して、作成した新しいSSDボリュームグループまたはプールに対して再度有効にすることができます。この設定を再度無効にすることもできます。 
---
= 新しいボリュームグループまたはプールのリソースプロビジョニングを有効または無効にします
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
リソースプロビジョニングのデフォルト機能を無効にしていた場合は、新しく作成するSSDボリュームグループまたはプールに対して再度有効にすることができます。この設定を再度無効にすることもできます。

リソースプロビジョニングは、EF300およびEF600ストレージアレイで使用できる機能です。これにより、バックグラウンドの初期化プロセスを実行せずに、ボリュームをただちに使用できます。ボリュームに割り当てられているすべてのドライブブロックの割り当てが解除され（マッピング解除）、SSDの寿命が延び、書き込みパフォーマンスが最大化されます。


NOTE: デフォルトでは、ドライブがDULBEをサポートするシステムでリソースプロビジョニングが有効になっています。

.作業を開始する前に
* EF300またはEF600ストレージアレイが必要です。
* SSDボリュームグループまたはプールが必要です。このプールでは、すべてのドライブがNVMe Deallocated or Unwritten Logical Block Error（DULBE）エラーリカバリ機能をサポートしています。


.このタスクについて
新しいボリュームグループまたはプールのリソースプロビジョニングを再度有効にすると、新しく作成したボリュームグループとプールのみに影響します。リソースプロビジョニングが有効になっている既存のボリュームグループおよびプールは変更されません。

.手順
. メニューを選択します。[設定][システム]。
. 下にスクロールして「* Additional Settings *」(追加設定*)を選択し、「*リソースプロビジョニングボリュームの有効化/無効化」をクリックします。
+
この設定の概要 は、リソースプロビジョニングが現在有効か無効かを示します。

. ダイアログボックスで、処理を確認します。


.結果
リソースプロビジョニングを有効または無効にすると、新しく作成するSSDプールまたはボリュームグループにのみ影響します。既存のプールまたはボリュームグループは変更されません。
