---
permalink: sm-settings/export-saml-service-provider-files.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, export, saml, Service Provider, files, 
summary: 必要に応じて、ストレージアレイのサービスプロバイダのメタデータをエクスポートして、ファイルをアイデンティティプロバイダ（IdP）システムに再インポートすることができます。 
---
= SAMLサービスプロバイダファイルをエクスポートする
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
必要に応じて、ストレージアレイのサービスプロバイダのメタデータをエクスポートして、ファイルをアイデンティティプロバイダ（IdP）システムに再インポートすることができます。

.作業を開始する前に
* Security Adminの権限を含むユーザプロファイルでログインする必要があります。そうしないと、アクセス管理機能は表示されません。
* SAMLを設定して有効にします。


.このタスクについて
このタスクでは、コントローラからメタデータ（コントローラごとに1ファイル）をエクスポートします。このメタデータは、IdPがコントローラとの間の信頼関係を確立し、認証要求を処理するために必要になります。このファイルには、コントローラのドメイン名やIPアドレスなど、IdPで要求の送信に使用できる情報が含まれています。

.手順
. メニューを選択します。Settings [Access Management]。
. SAML *タブを選択します。
. 「*書き出し*」を選択します。
+
[Export Service Provider Files]ダイアログボックスが開きます。

. 各コントローラについて、* Export（エクスポート）*をクリックしてメタデータファイルをローカルシステムに保存します。
+
[NOTE]
====
各コントローラのドメイン名フィールドは読み取り専用です。

====
+
ファイルの保存先をメモします。

. ローカルシステムで、エクスポートしたサービスプロバイダのメタデータファイルを探します。
+
コントローラごとにXML形式のファイルが1つあります。

. IdPサーバから、サービスプロバイダのメタデータファイルをインポートします。ファイルを直接インポートすることも、ファイルからコントローラの情報を手動で入力することもできます。
. [* 閉じる * ] をクリックします。

