---
permalink: sm-settings/faq-storage-system-alerts.html 
sidebar: sidebar 
keywords:  
summary: この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。 
---
= SANtricity System Managerのストレージシステムアラートに関するFAQ
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。



[[what-if-alerts-are-disabled]]
== アラートが無効になっている場合

ストレージアレイで発生する重要なイベントに関する通知を管理者が受信できるようにするには、アラート方法を設定する必要があります。

SANtricity System Managerで管理されるストレージアレイの場合は、アラートページからアラートを設定します。アラート通知は、Eメール、SNMPトラップ、またはsyslogメッセージを介して送信できます。また、初期セットアップウィザードからEメールアラートを設定することもできます。



[[how-do-i-configure-snmp-or-syslog-alerts]]
== SNMPまたはsyslogのアラートを設定するにはどうすればよいですか？

Eメールアラートに加えて、アラートが簡易ネットワーク管理プロトコル（SNMP）トラップまたはsyslogメッセージで送信されるように設定できます。

SNMP またはsyslogアラートを設定するには、メニュー：Alerts[]に移動します。



[[why-are-timestamps-inconsistent-between-the-array-and-alerts]]
== アレイとアラートでタイムスタンプが異なるのはなぜですか？

ストレージアレイは、アラートの送信時にアラートを受信するターゲットサーバまたはホストのタイムゾーンに合わせて修正を行いません。代わりに、ローカル時間（GMT）を使用してアラートの記録に使用されるタイムスタンプを作成します。そのため、ストレージアレイのタイムスタンプと、アラートを受信するサーバまたはホストのタイムスタンプが一致しないことがあります。

ストレージアレイはアラートの送信時にタイムゾーンを修正しないため、アラートのタイムスタンプはGMTであり、タイムゾーンオフセットはゼロです。タイムスタンプをローカルのタイムゾーンに換算するには、GMTからのオフセットを特定し、タイムスタンプにその値を加算するか減算します。
