---
permalink: sm-settings/how-alerts-work.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, alarm, alerts, 
summary: アラートは、ストレージアレイで発生した重要なイベントについて管理者に通知します。アラートは E メール、 SNMP トラップ、 syslog を通じて送信できます。 
---
= SANtricity System Manager でのアラートの仕組み
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アラートは、ストレージアレイで発生した重要なイベントについて管理者に通知します。アラートは E メール、 SNMP トラップ、 syslog を通じて送信できます。

アラートプロセスは次のように機能します。

. 管理者がSystem Managerで、次のうち1つ以上のアラート方法を設定します。
+
** *電子メール*--電子メールアドレスにメッセージが送信されます。
** *snmp *-- SNMPトラップがSNMPサーバに送信されます。
** *syslog *--メッセージがsyslogサーバに送信される。


. ストレージアレイのイベントモニターが問題を検出すると、その問題に関する情報をイベントログに書き込みます（menu:Monitoring[Event log]からアクセスできます）。例えば、問題としては、バッテリーの故障、コンポーネントが最適状態からオフライン状態に移行する、コントローラーの冗長性エラーなどが挙げられます。
. イベントが「アラート対象」であると判断した場合、イベントモニタは設定されているアラート方法（Eメール、SNMP、syslog）を使用して通知を送信します。重大イベントはすべて「アラート対象」とみなされるほか、一部の警告イベントと情報イベントも「アラート対象」とみなされます。




[[alerts-configuration]]
== アラートの設定

アラートは、初期設定ウィザード（メールアラートのみ）またはアラートページから設定できます。アラートページにアクセスするには、左側のパネルからmenu:Alerts[]を選択してください。



[[alerts-information]]
== アラート情報

アラートには次の種類の情報を含めることができます。

* ストレージアレイの名前。
* イベントログエントリに関連するイベントエラータイプ。
* イベントが発生した日時。
* イベントの短い概要 。


[NOTE]
====
syslogアラートは、RFC 5424のメッセージング標準に準拠しています。

====