---
permalink: sm-settings/obtain-a-feature-key-file.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, obtain, feature, key, file, 
summary: ストレージアレイでプレミアム機能または機能パックを有効にするには、まず機能キーファイルを取得する必要があります。キーは1つのストレージアレイにのみ関連付けられます。 
---
= 機能キーファイルを取得します
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイでプレミアム機能または機能パックを有効にするには、まず機能キーファイルを取得する必要があります。キーは1つのストレージアレイにのみ関連付けられます。

.このタスクについて
このタスクでは、機能の必要な情報を収集し、機能キーファイルの要求を送信する方法について説明します。必要な情報は次のとおりです。

* シャーシのシリアル番号
* 機能有効識別子
* Feature Activation Code （機能アクティベーションコード）


.手順
. System Managerで、シャーシのシリアル番号を確認して記録します。このシリアル番号は、サポートセンターのタイルにマウスを合わせると表示されます。
. System Manager で、機能有効識別子を確認します。[設定]、[システム]の順に移動し、下にスクロールして*アドオン*を表示します。機能有効識別子*を探します。機能有効識別子の番号を記録します。
. 機能を有効にするコードを探して記録します。機能パックの場合、このコードは変換を実行するための適切な手順で提供されます。
+
プレミアム機能の場合は、サポートサイトから次の手順でアクティベーションコードにアクセスできます。

+
.. にログインします https://mysupport.netapp.com/site/global/dashboard["ネットアップサポート"^]。
.. お使いの製品の「*ソフトウェアライセンス*」にアクセスします。
.. ストレージアレイシャーシのシリアル番号を入力し、* Go *をクリックします。
.. [*License Key*]列で、Feature Activation Codeを探します。
.. 必要な機能のFeature Activation Codeを記録します。


. シャーシのシリアル番号、有効化ID、機能のアクティブ化のコードなどの情報を記載したEメールまたはテキストドキュメントをストレージサプライヤに送信して、機能キーファイルを要求します。
+
に進むこともできます http://partnerspfk.netapp.com["ネットアップライセンスのアクティブ化：ストレージアレイプレミアム機能のアクティブ化"^] 機能または機能パックを入手するために必要な情報を入力します。（このサイトの手順はプレミアム機能用であり、機能パック用ではありません）。



.完了後
機能キーファイルを取得したら、プレミアム機能または機能パックを有効にすることができます。
