---
permalink: sm-settings/save-storage-array-configuration.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, save, storage array, configuration, 
summary: ストレージアレイの構成情報をスクリプトファイルに保存すると、追加のストレージアレイをセットアップする時間を同じ構成で節約できます。 
---
= SANtricity System Managerでストレージアレイ構成を保存する
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイの構成情報をスクリプトファイルに保存すると、追加のストレージアレイをセットアップする際に同じ構成を使用するための時間を節約できます。

.作業を開始する前に
論理構成の設定を変更する処理がストレージアレイで行われていないことを確認してください。このような処理の例としては、ボリュームの作成または削除、コントローラファームウェアのダウンロード、ホットスペアドライブの割り当てまたは変更、ボリュームグループへの容量（ドライブ）の追加などがあります。

.このタスクについて
ストレージアレイの構成を保存すると、ストレージアレイの設定、ボリュームの構成、ホストの構成、またはストレージアレイに対するホストとボリュームの割り当てを含むコマンドラインインターフェイス（CLI）スクリプトが生成されます。生成されたこのCLIスクリプトを使用して、ハードウェア構成がまったく同じ別のストレージアレイに構成をレプリケートできます。

ただし、ディザスタリカバリにはこのCLIスクリプトを使用しないでください。システムをリストアするには、代わりに、手動で作成する構成データベースのバックアップファイルを使用するか、テクニカルサポートに問い合わせて最新のAutoSupportデータからこのデータを取得してください。

この操作では、次の設定は保存されません。

* バッテリの寿命です
* コントローラの時刻
* 不揮発性静的ランダムアクセスメモリ（NVSRAM）の設定
* すべてのプレミアム機能
* ストレージアレイのパスワード
* ハードウェアコンポーネントの動作ステータスと状態
* ボリュームグループの動作ステータス（最適を除く）と状態
* ミラーリング、ボリュームコピーなどのコピーサービス


[CAUTION]
====
*アプリケーションエラーのリスク*-論理構成の設定を変更する処理をストレージアレイで実行中の場合は、このオプションを使用しないでください。このような処理の例としては、ボリュームの作成または削除、コントローラファームウェアのダウンロード、ホットスペアドライブの割り当てまたは変更、ボリュームグループへの容量（ドライブ）の追加などがあります。

====
.手順
. メニューを選択します。[設定][システム]。
. 「ストレージアレイ構成の保存」を選択します。
. 保存する構成の項目を選択します。
+
** ストレージアレイの設定
** ボリューム構成
** ホストの設定
** ホスト/ボリューム間の割り当て


+
[NOTE]
====
［*ホスト/ボリューム間の割り当て*］項目を選択した場合、［*ボリューム構成*］項目と［*ホスト構成*］項目もデフォルトで選択されます。「ボリューム構成」と「ホスト構成」も保存しないと、「ホストとボリュームの割り当て」を保存できません。

====
. [ 保存（ Save ） ] をクリックします。
+
ファイルは'storagearray-configuration.cfgという名前でブラウザのDownloadsフォルダに保存されます



.完了後
保存したストレージ・アレイの構成を別のストレージ・アレイにロードするには'-fオプションを指定したSANtricity コマンド・ライン・インターフェイス（SMcli）を使用して'.cfgファイルを適用します

[NOTE]
====
Unified Managerインターフェイスを使用して、ストレージアレイの構成を他のストレージアレイにロードすることもできます（選択メニュー：管理[設定のインポート]）。

====