---
permalink: sm-settings/set-automatic-load-balancing.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, set, automatic, load, balancing, 
summary: 自動ロードバランシング機能を使用すると、ホストからの受信I/Oトラフィックが動的に管理され、両方のコントローラに分散されます。この機能はデフォルトで有効になっていますが、System Managerから無効にすることもできます。 
---
= 自動ロードバランシングを設定する
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
自動ロードバランシング機能を使用すると、ホストからの受信I/Oトラフィックが動的に管理され、両方のコントローラに分散されます。この機能はデフォルトで有効になっていますが、System Managerから無効にすることもできます。

.このタスクについて
自動ロードバランシングを有効にすると、次の機能が実行されます。

* コントローラのリソース利用率を自動的に監視して負荷を分散します。
* ボリュームのコントローラ所有権が必要に応じて自動的に調整され、ホストとストレージアレイの間のI/O帯域幅が最適化されます。


自動ロードバランシングは、ストレージアレイの状況に応じて無効にすることができます。たとえば、次のような場合です。

* 特定のボリュームのコントローラ所有権については、ワークロードを分散するために自動的に変更されないようにする場合。
* 高度に調整された環境で、コントローラ間の負荷分散が特定の要件を満たすように意図的に設定されている。


.手順
. メニューを選択します。[設定][システム]。
. 下にスクロールして「その他の設定」を選択し、「*自動ロードバランシングの有効化/無効化*」をクリックします。
+
この機能が現在有効か無効かを示すテキストがこのオプションの下に表示されます。

+
確認のダイアログボックスが開きます。

. 続行するには、[はい]をクリックして確定します。
+
このオプションを選択すると、機能の有効と無効を切り替えることができます。

+
[NOTE]
====
この機能を無効から有効に切り替えると、ホスト接続レポート機能も自動的に有効になります。

====

