---
permalink: sm-settings/switch-from-external-to-internal-key-management.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, switch, external, internal, key, management, 
summary: ドライブセキュリティの管理方法を外部キーサーバからストレージアレイで使用される内部の方法に変更することができます。以前に外部キー管理用に定義されたセキュリティキーが内部キー管理に使用されます。 
---
= 外部キー管理から内部キー管理に切り替えます
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ドライブセキュリティの管理方法を外部キーサーバからストレージアレイで使用される内部の方法に変更することができます。以前に外部キー管理用に定義されたセキュリティキーが内部キー管理に使用されます。

.このタスクについて
このタスクでは、外部キー管理を無効にして、新しいバックアップコピーをローカルホストにダウンロードします。既存のキーは引き続きドライブセキュリティに使用されますが、ストレージアレイで内部的に管理されます。

.手順
. メニューを選択します。[設定][システム]。
. [*セキュリティキー管理*]で、[*外部キー管理を無効にする*]を選択します。
+
[外部キー管理の無効化]ダイアログボックスが開きます。

. 「*パスフレーズを定義/パスフレーズを再入力*」で、キーのバックアップに使用するパスフレーズを入力して確認します。8~32文字で指定し、以下の文字をそれぞれ1文字以上含める必要があります。
+
** 大文字のアルファベット（1文字以上）。パスフレーズでは大文字と小文字が区別されることに注意してください。
** 数字（1文字以上）。
** 英数字以外の、！、*、@などの文字（1文字以上）。


+
[CAUTION]
====
_後で使用するために、必ずエントリを記録しておいてください。セキュリティ有効ドライブをストレージアレイから移動する必要がある場合、ドライブデータのロックを解除するために識別子とパスフレーズが必要になります。

====
. [*Disable*] をクリックします。
+
バックアップキーがローカルホストにダウンロードされます。

. キー識別子、パスフレーズ、ダウンロードしたキーファイルの場所を記録し、*閉じる*をクリックします。


.結果
ドライブセキュリティがストレージアレイを使用して内部的に管理されるようになりました。

.完了後
セキュリティキーを検証して、キーファイルが破損していないことを確認します。
