---
permalink: sm-settings/synchronize-storage-array-clocks.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, synchronize, storage, array, clocks, 
summary: ネットワークタイムプロトコル（NTP）が無効な場合は、コントローラのクロックを手動で設定して、管理クライアント（SANtricity System Managerにアクセスするブラウザの実行に使用されるシステム）と同期されるようにすることができます。 
---
= ストレージアレイのクロックを同期する
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ネットワークタイムプロトコル（NTP）が無効な場合は、コントローラのクロックを手動で設定して、管理クライアント（System Managerにアクセスするブラウザの実行に使用されるシステム）と同期されるようにすることができます。

.このタスクについて
同期によって、イベントログ内のイベントのタイムスタンプがホストログファイルに書き込まれるタイムスタンプと一致します。同期プロセスの実行中も、コントローラを引き続き使用できます。

[NOTE]
====
System ManagerでNTPが有効になっている場合は、このオプションを使用してクロックを同期しないでください。代わりに、NTPではシンプルネットワークタイムプロトコル（SNTP）を使用してクロックを自動的に同期します。

====
[NOTE]
====
同期後に、パフォーマンス統計が失われたり精度が低下したりする可能性があります。また、スケジュールに影響が生じたり（ASUP、Snapshotなど）、ログデータ内のタイムスタンプが不正確になる可能性もあります。NTPを使用すると、この問題を回避できます。

====
.手順
. メニューを選択します。[設定][システム]。
. [*General]で'[*ストレージ・アレイ・クロックの同期化*]をクリックします
+
ストレージアレイクロックの同期ダイアログボックスが開きます。このダイアログには、コントローラおよび管理クライアントとして使用されているコンピュータの現在の日時が表示されます。

+
[NOTE]
====
シンプレックスストレージアレイの場合、表示されるコントローラは1台だけです。

====
. ダイアログボックスに表示された時間が一致しない場合は、*同期化*をクリックします。


.結果
同期が成功すると、イベントのタイムスタンプはイベントログとホストログで同じになります。
