---
permalink: sm-settings/view-nvme-over-fabrics-statistics-system.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, nvme, fabrics, statistics, 
summary: ストレージアレイへのNVMe over Fabrics接続に関するデータを表示できます。 
---
= SANtricity System ManagerでNVMe over Fabricsの統計情報を表示する
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイへのNVMe over Fabrics接続に関するデータを表示できます。

.このタスクについて
System Managerには、次のタイプのNVMe over Fabrics統計が表示されます。統計はすべて読み取り専用で、設定することはできません。

* *NVMeサブシステム* -- NVMeコントローラとそのキューの統計情報を表示します。NVMeコントローラは、ホストとストレージアレイ内の名前空間との間のアクセスパスを提供します。NVMeサブシステムの統計情報を確認することで、接続障害、リセット、シャットダウンなどの項目を把握できます。
* *RDMA統計* -- RDMAインターフェイス上のすべてのNVMe over Fabricsポートの統計情報を提供します。これには、各スイッチ ポートに関連付けられたパフォーマンス統計情報とリンクエラー情報が含まれます。このタブは、NVMe over Fabricsポートが利用可能な場合にのみ表示されます。


これらの統計はそれぞれ、統計の生データまたはベースライン統計として表示できます。統計の生データは、コントローラの起動以降に収集されたすべての統計です。ベースライン統計は、ベースライン時間の設定以降に収集されたポイントインタイムの統計です。

.手順
. 左側のパネルから*システム*を選択してください。
. 「NVMe over Fabrics の統計情報を表示」を選択します。
. *オプション：*ベースラインを設定するには、*新しいベースラインの設定*をクリックします。
+
ベースラインを設定すると、統計を収集するための新しい開始ポイントが設定されます。すべてのNVMe統計に同じベースラインが使用されます。


