---
permalink: sm-settings/view-iscsi-sessions-system.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, iscsi, sessions, 
summary: ストレージアレイへのiSCSI接続に関する詳細情報を表示できます。iSCSIセッションは、非同期ミラー関係にあるホストまたはリモートストレージアレイとの間で確立できます。 
---
= iSCSI セッションを表示します
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイへのiSCSI接続に関する詳細情報を表示できます。iSCSIセッションは、非同期ミラー関係にあるホストまたはリモートストレージアレイとの間で確立できます。

.手順
. メニューを選択します。[設定][システム]。
. 「* iSCSIセッションの表示/終了*」を選択します。
+
現在のiSCSIセッションのリストが表示されます。

. *オプション：特定のiSCSIセッションに関する追加情報 を表示するには、セッションを選択し、*詳細の表示*をクリックします。
+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| 項目 | 説明 


 a| 
セッション識別子（SSID）
 a| 
iSCSIイニシエータとiSCSIターゲット間のセッションを識別する16進数の文字列。SSIDは、ISIDとTPGTで構成されます。



 a| 
イニシエータセッションID（ISID）
 a| 
セッション識別子のイニシエータの部分。イニシエータはログイン時にISIDを指定します。



 a| 
ターゲットポータルグループ
 a| 
iSCSIターゲット。



 a| 
ターゲットポータルグループタグ（TPGT）
 a| 
セッション識別子のターゲットの部分。iSCSIターゲットポータルグループの16ビットの数値識別子。



 a| 
イニシエータのiSCSI名
 a| 
世界規模で一意なイニシエータの名前。



 a| 
イニシエータのiSCSIラベル
 a| 
System Managerで設定されたユーザラベル。



 a| 
イニシエータのiSCSIエイリアス
 a| 
iSCSIノードにも関連付けることができる名前。エイリアスを使用すると、組織がユーザにわかりやすい文字列をiSCSI名に関連付けることができます。ただし、エイリアスはiSCSI名に代わるものではありません。イニシエータのiSCSIエイリアスは、System Managerではなく、ホストでのみ設定できます



 a| 
ホスト
 a| 
ストレージアレイに入出力を送信するサーバ。



 a| 
接続ID（CID）
 a| 
イニシエータとターゲット間のセッション内における接続の一意の名前。イニシエータがこのIDを生成し、ログイン要求の際にターゲットに提供します。接続IDは、接続を閉じるログアウト時にも表示されます。



 a| 
イーサネットポート識別子
 a| 
接続に関連付けられているコントローラポート。



 a| 
イニシエータのIPアドレス
 a| 
イニシエータのIPアドレス。



 a| 
ネゴシエーション済みのログインパラメータ
 a| 
iSCSIセッションのログイン時に処理されるパラメータ。



 a| 
認証方式
 a| 
iSCSIネットワークへのアクセスを必要とするユーザを認証する手法。有効な値は* chap *および* None *です。



 a| 
ヘッダーダイジェスト方式
 a| 
iSCSIセッションに有効なヘッダー値を表示する手法。HeaderDigestおよびDataDigestには、* None *または* CRC32C *を使用できます。両方のデフォルト値は* None *です。



 a| 
データダイジェスト方式
 a| 
iSCSIセッションに有効なデータ値を表示する手法。HeaderDigestおよびDataDigestには、* None *または* CRC32C *を使用できます。両方のデフォルト値は* None *です。



 a| 
最大接続数
 a| 
iSCSIセッションに許可される接続の最大数。1~4を接続の最大数として指定できます。デフォルト値は* 1 *です。



 a| 
ターゲットエイリアス
 a| 
ターゲットに関連付けられているラベル。



 a| 
イニシエータのエイリアス
 a| 
イニシエータに関連付けられているラベル。



 a| 
ターゲットのIPアドレス
 a| 
iSCSIセッションのターゲットのIPアドレス。DNS名はサポートされません。



 a| 
初期R2T
 a| 
最初の転送準備完了ステータス。ステータスは「* Yes *」または「* No *」のいずれかになります。



 a| 
最大バースト長
 a| 
このiSCSIセッションの最大SCSIペイロード（バイト）。512~262、144（256KB）を最大バースト長として指定できます。デフォルト値は* 262,144（256KB）*です。



 a| 
第1バースト長
 a| 
このiSCSIセッションの未承諾データのSCSIペイロード（バイト単位）。512~131、072（128KB）を第1バースト長として指定できます。デフォルト値は*65,536（64KB）*です。



 a| 
デフォルトの待機時間
 a| 
接続の終了または接続のリセット後に接続を試行するまでの最小秒数。0~3600をデフォルトの待機時間の値として指定できます。デフォルトは* 2 *です。



 a| 
デフォルトの保持時間です
 a| 
接続の終了または接続のリセット後も接続が可能な最大秒数。0~3600をデフォルトの保持時間として指定できます。デフォルト値は*20*です。



 a| 
最大未処理R2T
 a| 
このiSCSIセッションの未処理の「準備が完了した転送」の最大数。1~16を未処理の「準備が完了した転送」の最大値として指定できます。デフォルトは* 1 *です。



 a| 
エラーリカバリレベル
 a| 
このiSCSIセッションのエラーリカバリのレベル。エラーリカバリレベルの値は常に* 0 *に設定されています。



 a| 
受信データ最大セグメント長
 a| 
イニシエータまたはターゲットがペイロードデータユニット（PDU）で受信できる最大データ量。



 a| 
ターゲット名
 a| 
ターゲットの正式名（エイリアスではありません）。iqn形式のターゲット名です。



 a| 
イニシエータ名
 a| 
イニシエータの正式名（エイリアスではありません）。iqn形式または_eui_formatを使用するイニシエータ名です。

|===
====
. *オプション：*レポートをファイルに保存するには、*保存*をクリックします。
+
ブラウザのDownloadsフォルダに'iscsi-session-connections.txt'というファイル名でファイルが保存されます


