---
permalink: sm-settings/view-imported-certificates.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, imported, certificate, information, 
summary: 「証明書」カテゴリでは、ストレージ アレイの証明書の種類、発行機関、および有効な日付範囲を確認できます。 
---
= SANtricity System Managerでインポートされた証明書情報を表示する
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「証明書」カテゴリでは、ストレージ アレイの証明書の種類、発行機関、および有効な日付範囲を確認できます。

.作業を開始する前に
Security Adminの権限を含むユーザプロファイルでログインする必要があります。そうしないと、証明書の機能は表示されません。

.手順
. 左側のパネルから*証明書*を選択してください。
. 証明書に関する情報をご覧になるには、以下のページからいずれかを選択してください。
+
[cols="25h,~"]
|===
| ページ | 説明 


 a| 
menu:Certificates[アレイ管理証明書]
 a| 
ルートファイル、中間ファイル、サーバファイルなど、各コントローラ用にインポートしたCA署名証明書に関する情報が表示されます。



 a| 
メニュー：［信頼された証明書］
 a| 
コントローラ用にインポートしたその他すべてのタイプの証明書に関する情報が表示されます。[Show certificates that are ...]の下のフィルタフィールドを使用して、ユーザがインストールした証明書または事前にインストールされた証明書を表示します。

** *ユーザーがインストールした証明書*--ユーザーがストレージアレイにアップロードした証明書。これには、コントローラがサーバーではなくクライアントとして機能する場合に信頼された証明書、LDAPS証明書、アイデンティティフェデレーション証明書が含まれます。
** *プリインストール*--ストレージアレイに含まれている自己署名証明書。




 a| 
メニュー：［証明書］-［鍵管理証明書］
 a| 
外部キー管理サーバ用にインポートしたCA署名証明書に関する情報が表示されます。

|===

