---
permalink: sm-settings/view-nvme-over-fabrics-statistics-system.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, nvme, fabrics, statistics, 
summary: ストレージアレイへのNVMe over Fabrics接続に関するデータを表示できます。 
---
= NVMe over Fabricsの統計を表示します
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイへのNVMe over Fabrics接続に関するデータを表示できます。

.このタスクについて
System Managerには、次のタイプのNVMe over Fabrics統計が表示されます。統計はすべて読み取り専用で、設定することはできません。

* * nvmeサブシステム統計*- NVMeコントローラとそのキューの統計が表示されます。NVMeコントローラは、ストレージアレイ内のネームスペースとホストの間のアクセスパスを提供します。NVMeサブシステム統計では、接続障害、リセット、シャットダウンなどの項目を確認できます。
* * rdma Interface statistics *-- RDMAインターフェイス上のすべてのNVMe over Fabricsポートの統計を提供します。各スイッチポートに関連付けられているパフォーマンス統計とリンクエラー情報が含まれます。このタブは、NVMe over Fabricsポートが使用可能な場合にのみ表示されます。


これらの統計はそれぞれ、統計の生データまたはベースライン統計として表示できます。統計の生データは、コントローラの起動以降に収集されたすべての統計です。ベースライン統計は、ベースライン時間の設定以降に収集されたポイントインタイムの統計です。

.手順
. メニューを選択します。[設定][システム]。
. View NVMe over Fabrics Statistics *を選択します。
. *オプション：*ベースラインを設定するには、*新しいベースラインの設定*をクリックします。
+
ベースラインを設定すると、統計を収集するための新しい開始ポイントが設定されます。すべてのNVMe統計に同じベースラインが使用されます。


