---
permalink: sm-settings/what-is-controller-cache.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, controller, cache, 
summary: コントローラキャッシュは、コントローラとホストの間、およびコントローラとディスクの間の2種類のI/O（入出力）処理をスムーズに行うための物理メモリスペースです。 
---
= コントローラキャッシュとは何ですか？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コントローラキャッシュは、コントローラとホストの間、およびコントローラとディスクの間の2種類のI/O（入出力）処理をスムーズに行うための物理メモリスペースです。

読み取りおよび書き込みのデータ転送では、ホストとコントローラは高速な接続を介して通信します。ただし、ディスクは比較的低速なデバイスであるため、コントローラのバックエンドからディスクへの通信は低速になります。

コントローラキャッシュがデータを受信すると、コントローラはデータを保持していることをホストアプリケーションに通知します。これにより、ホストアプリケーションはI/Oがディスクに書き込まれるのを待たずに代わりに、アプリケーションは処理を続行できます。また、サーバアプリケーションはキャッシュされたデータにアクセスできるため、データにアクセスするためにディスクを読み取る必要がなくなります。

コントローラキャッシュは、ストレージアレイの全体的なパフォーマンスに次のように影響します。

* キャッシュはバッファとして機能するため、ホストとディスクのデータ転送を同期する必要がありません。
* ホストからの読み取り/書き込み処理の対象となるデータが以前の処理ですでにキャッシュに格納されていれば、ディスクにアクセスする必要はありません。
* 書き込みキャッシュを使用している場合、ホストは以前の書き込み処理がディスクに書き込まれる前に後続の書き込みコマンドを送信できます。
* キャッシュプリフェッチを有効にすると、シーケンシャルリードアクセスが最適化されます。読み取り処理ではデータがディスクから読み取られるのではなく、キャッシュ内のデータが使用される可能性が高くなります。


[CAUTION]
====
*データ損失の可能性*--バッテリなしの書き込みキャッシュ*オプションを有効にして保護用のユニバーサル電源装置を持たないと、データが失われる可能性があります。また、コントローラのバッテリがない場合に*バッテリなしの書き込みキャッシュ*オプションを有効にすると、データが失われる可能性があります。

====