---
permalink: sm-support/activate-controller-software-and-firmware.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, activate, controller, software, firmware 
summary: アップグレードファイルはただちにアクティブ化することも、都合のいいタイミングでアクティブ化することもできます。 
---
= コントローラソフトウェアとファームウェアをアクティブ化します
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アップグレードファイルはただちにアクティブ化することも、都合のいいタイミングでアクティブ化することもできます。

.このタスクについて
ファイルは、アクティブ化せずにダウンロードおよび転送できます。あとでアクティブ化する理由は次のとおりです。

* *時間帯*--ソフトウェアとファームウェアのアクティブ化には時間がかかることがあるため、I/O負荷の低い時間帯に実行できます。アクティブ化の際にはコントローラがフェイルオーバーするため、アップグレードが完了するまではパフォーマンスが通常よりも低下する可能性があります。
* * パッケージのタイプ * -- 他のストレージアレイ上のファイルをアップグレードする前に ' 新しいソフトウェアとファームウェアを 1 つのストレージアレイでテストすることをお勧めします


ソフトウェアまたはファームウェアの転送は完了していてもアクティブ化されていない場合は、System Managerのホームページの通知領域とアップグレードセンターのページに通知が表示されます。

[CAUTION]
====
起動後にアクティブ化プロセスを停止することはできません。

====
.手順
. メニューを選択します。Support [Upgrade Center]を選択します。
. SANtricity OS Controller Software upgrade（OSコントローラソフトウェアのアップグレード）というラベルの付いた領域で、* Activate（アクティブ化）*をクリックし、操作を実行することを確認します。
+
アップグレード前の健常性チェックの段階で処理をキャンセルすることはできますが、アクティブ化の実行中はキャンセルできません。

+
アップグレード前の健常性チェックが開始されます。アップグレード前の健常性チェックにパスすると、アップグレードプロセスはファイルのアクティブ化に進みます。アップグレード前の健常性チェックに失敗した場合は、 Recovery Guru を使用するか、テクニカルサポートに問い合わせて問題を解決してください。一部の種類の条件では、*アップグレードを許可*チェックボックスを選択してエラーが発生しても、テクニカルサポートからアップグレードを続行するようにアドバイスされる場合があります。

+
アップグレード前の健常性チェックが正常に完了すると、アクティブ化が実行されます。アクティブ化にかかる時間は、ストレージアレイの構成とアクティブ化しているコンポーネントによって異なります。

. *オプション：*アップグレードされた内容のリストを表示するには、*ログの保存*をクリックします。
+
ブラウザの Downloads フォルダに、「 drive upgrade_log-timestamp.txt 」という名前でファイルが保存されます。



.完了後
* ハードウェアページにすべてのコンポーネントが表示されていることを確認します。
* [Software and Firmware Inventory] ダイアログボックスをチェックして、新しいソフトウェアとファームウェアのバージョンを確認します（ [Menu] ： [Upgrade Center] を選択し、 [* Software and Firmware Inventory] のリンクをクリックします）。
* コントローラ NVSRAM をアップグレードした場合、既存の NVSRAM に適用されていたカスタム設定はアクティブ化のプロセスで失われます。カスタム設定については、アクティブ化のプロセスの完了後に NVSRAM に再度適用する必要があります。

