---
permalink: sm-support/autosupport-feature-overview.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, autosupport, ASUP 
summary: AutoSupport 機能は、ストレージアレイの健常性を監視し、テクニカルサポートに自動ディスパッチを送信します。 
---
= AutoSupport 機能の概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AutoSupport 機能は、ストレージアレイの健常性を監視し、テクニカルサポートに自動ディスパッチを送信します。

テクニカルサポートは、AutoSupport データを事後対応として使用してお客様の問題の診断と解決を迅速に行い、潜在的な問題をプロアクティブに検出および回避します。

AutoSupport データには、ストレージアレイの構成、ステータス、パフォーマンス、およびシステムイベントに関する情報が含まれます。AutoSupport データにユーザデータが含まれることはありません。ディスパッチはただちに送信することも、スケジュール（毎日または毎週）に基づいて送信することもできます。



== 主なメリット

AutoSupport 機能の主な利点は次のとおりです。

* ケースの解決時間の短縮
* 高度な監視でインシデント管理を迅速化
* スケジュールに従って自動レポートを作成し、重要なイベントに関する自動レポートも作成できます
* ドライブなどの選択したコンポーネントのハードウェア交換要求の自動化
* 問題発生時に、お客様の妨げにならない形で通知し、修正措置を講じるための情報をテクニカルサポートに伝えます
* 設定に関する既知の問題がないかどうか、ディスパッチを監視するAutoSupport 分析ツール




== 個々のAutoSupport 機能

AutoSupport 機能は、個別に有効にする3つの機能で構成されています。

* *Basic AutoSupport *--ストレージ・アレイが自動的にデータを収集してテクニカル・サポートに送信することを可能にします
* * AutoSupport OnDemand*--問題 のトラブルシューティングに必要なときに、テクニカルサポートが以前のAutoSupport ディスパッチの再送信を要求できるようにします。送信はすべて、AutoSupport サーバではなくストレージアレイから開始されます。ストレージアレイはAutoSupport サーバに定期的にコンタクトし、保留中の再送信要求がないかどうかをチェックし、適切に応答します。
* *リモート診断*--問題 のトラブルシューティングに必要な場合に、テクニカルサポートが最新のAutoSupport ディスパッチをリクエストできるようにします。送信はすべて、AutoSupport サーバではなくストレージアレイから開始されます。ストレージアレイはAutoSupport サーバに定期的にコンタクトし、保留中の新規要求がないかどうかをチェックし、適切に応答します。




== AutoSupport とサポートデータ収集の違い

ストレージアレイでは、次の2つの方法でサポートデータを収集できます。

* * AutoSupport 機能*--データが自動的に収集されます。
* *サポートデータの収集オプション*--データを収集して手動で送信する必要があります。


データが自動的に収集および送信されるため、AutoSupport 機能の方が使いやすくなります。AutoSupport データをプロアクティブに使用すると、発生前に問題を防ぐことができます。テクニカルサポートはすでにデータにアクセスできるため、AutoSupport 機能を使用した方がトラブルシューティングにかかる時間が短縮されます。これらの理由から、AutoSupport 機能がデータ収集方法として推奨されます。
