---
permalink: sm-support/clear-recovery-mode.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, clear, recovery, mode 
summary: ストレージアレイ構成をリストアしたら、リカバリモードのクリア処理を使用してストレージアレイでのI/Oを再開し、通常動作に戻します。 
---
= リカバリモードをクリアします
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイ構成をリストアしたら、リカバリモードのクリア処理を使用してストレージアレイでのI/Oを再開し、通常動作に戻します。

.作業を開始する前に
* ストレージアレイを以前の構成に戻す場合は、リカバリモードをクリアする前にバックアップから設定をリストアする必要があります。
* リストアが正常に完了したことを確認するには、検証チェックを実行するか、テクニカルサポートに確認する必要があります。リストアが正常に完了したことを確認したら、リカバリモードをクリアできます。


.このタスクについて
ストレージアレイには、その論理構成（プール、ボリュームグループ、ボリュームなど）が記録された構成データベースが含まれています。ストレージアレイ構成を意図的にクリアした場合、または構成データベースが破損した場合、ストレージアレイはリカバリモードになります。リカバリモードではI/Oが停止され、構成データベースがフリーズされるため、その間に次のいずれかの作業を実行できます。

* コントローラのフラッシュデバイスに保存されている自動バックアップから設定をリストアする。この作業を行う場合は、テクニカルサポートにお問い合わせください。
* 前回の構成データベース保存処理から構成をリストアします。構成データベース保存処理は、コマンドラインインターフェイス（CLI）を使用して実行されます。
* ストレージアレイを一から再構成する。


ストレージアレイの構成がリストアまたは再定義され、すべて問題がないことを確認したら、リカバリモードを手動でクリアする必要があります。

[NOTE]
====
リカバリモードのクリアは一度開始するとキャンセルできません。リカバリモードのクリアには時間がかかることがあります。この処理は、テクニカルサポートから指示があった場合にのみ実行してください。

====
.手順
. メニューを選択します。Support（サポートセンター）> Diagnostics（診断）タブ。
. リカバリモードのクリア*を選択し、この処理を実行することを確認します。
+
このオプションは、ストレージアレイがリカバリモードの場合にのみ表示されます。


