---
permalink: sm-support/enable-or-disable-autosupport-features.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, enable, disable, autosupport, 
summary: AutoSupport 機能およびAutoSupport の個々の機能は、初期セットアップ時に有効にするか、あとから有効または無効にすることができます。 
---
= AutoSupport 機能を有効または無効にします
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AutoSupport 機能およびAutoSupport の個々の機能は、初期セットアップ時に有効にするか、あとから有効または無効にすることができます。

.作業を開始する前に
AutoSupport OnDemandまたはRemote Diagnosticsを有効にする場合は、AutoSupport の配信方法をHTTPSに設定する必要があります。

.このタスクについて
AutoSupport 機能はいつでも無効にできますが、有効なままにしておくことを強く推奨します。AutoSupport 機能を有効にしておくと、ストレージアレイに問題が発生したときに、迅速に原因を判断して解決できます。

AutoSupport 機能は、個別に有効にする3つの機能で構成されています。

* *Basic AutoSupport *--ストレージ・アレイが自動的にデータを収集してテクニカル・サポートに送信することを可能にします
* * AutoSupport OnDemand*--問題 のトラブルシューティングに必要なときに、テクニカルサポートが以前のAutoSupport ディスパッチの再送信を要求できるようにします。送信はすべて、AutoSupport サーバではなくストレージアレイから開始されます。ストレージアレイはAutoSupport サーバに定期的にコンタクトし、保留中の再送信要求がないかどうかをチェックし、適切に応答します。
* *リモート診断*--問題 のトラブルシューティングに必要な場合に、テクニカルサポートが最新のAutoSupport ディスパッチをリクエストできるようにします。送信はすべて、AutoSupport サーバではなくストレージアレイから開始されます。ストレージアレイはAutoSupport サーバに定期的にコンタクトし、保留中の新規要求がないかどうかをチェックし、適切に応答します。


.手順
. メニューを選択AutoSupport します。[Support Center]>[Support]（サポートセンター）タブ。
. AutoSupport 機能の有効化/無効化*を選択します。
. 有効にするAutoSupport 機能の横にあるチェックボックスをオンにします。
+
ダイアログボックス内の項目のレイアウトからわかるように、機能は相互に依存しています。たとえば、Remote Diagnosticsを有効にするには、まずAutoSupport OnDemandを有効にする必要があります。

. [ 保存（ Save ） ] をクリックします。
+
AutoSupport を無効にすると、ホームページに通知が表示されます。[*無視*]をクリックすると、通知を閉じることができます。


