---
permalink: sm-support/how-do-i-configure-the-delivery-method-for-autosupport.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, delivery, method, autosupport, 
summary: AutoSupport 機能は、テクニカルサポートへのAutoSupport ディスパッチの配信にHTTPS、HTTP、SMTPのプロトコルをサポートしています。 
---
= AutoSupport 機能の配信方法を設定するにはどうすればよいですか？
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AutoSupport 機能は、テクニカルサポートへのAutoSupport ディスパッチの配信にHTTPS、HTTP、SMTPのプロトコルをサポートしています。

.作業を開始する前に
* AutoSupport 機能を有効にする必要があります。有効になっているかどうかは、AutoSupport ページで確認できます。
* ネットワークにDNSサーバをインストールし、設定する必要があります。DNSサーバのアドレスはSystem Managerで設定する必要があります（このタスクはハードウェアページから実行できます）。


.このタスクについて
各プロトコルを確認します。

* * HTTPS *-- HTTPSを使用して、テクニカル・サポート・サーバーに直接接続できます。AutoSupport OnDemandまたはRemote Diagnosticsを有効にする場合は、AutoSupport の配信方法をHTTPSに設定する必要があります。
* * HTTP *-- HTTPを使用して、テクニカルサポートの宛先サーバーに直接接続できます。
* *Email*-- AutoSupport ディスパッチの配信方法として電子メールサーバーを使用できます


[NOTE]
====
* HTTPS / HTTPとEメールの配信方法*の違い。SMTPを使用するEメール配信方法とHTTPSおよびHTTP配信方法の間には、重要な違いがいくつかあります。まず、Eメールではディスパッチのサイズが5MBに制限されるため、ASUPデータ収集の一部はディスパッチされません。次に、AutoSupport OnDemand機能はHTPPおよびHTTPSメソッドでのみ使用できます。

====
.手順
. メニューを選択AutoSupport します。[Support Center]>[Support]（サポートセンター）タブ。
. AutoSupport 配信方法の設定 * を選択します。
+
ディスパッチの配信方法を示すダイアログボックスが表示されます。

. 目的の配信方法を選択し、その配信方法のパラメータを選択します。次のいずれかを実行します。
+
** HTTPSまたはHTTPを選択した場合は、次のいずれかの配信パラメータを選択します。
+
*** * direct*--このデリバリパラメータはデフォルトで選択されています。このオプションを選択すると、HTTPSまたはHTTPプロトコルを使用して、テクニカルサポートのデスティネーションシステムに直接接続できます。
*** *プロキシ・サーバ経由*--このオプションを選択すると'テクニカル・サポート・システムとの接続を確立するために必要なHTTPプロキシ・サーバの詳細を指定できますホストアドレスとポート番号を指定する必要があります。ただし、ホスト認証の詳細（ユーザ名とパスワード）は必要な場合にのみ入力します。
*** *プロキシ自動設定（PAC）スクリプト経由*-- Proxy Auto-Configuration（PAC）スクリプトファイルの場所を指定します。PACファイルを使用すると、テクニカルサポートのデスティネーションシステムとの接続の確立に適したプロキシサーバをシステムで自動的に選択できます。


** [電子メール]を選択した場合は、次の情報を入力します。
+
*** メールサーバのアドレス。完全修飾ドメイン名、IPv4アドレス、またはIPv6アドレスを指定します。
*** AutoSupport ディスパッチのEメールの送信元フィールドに表示されるEメールアドレスです。
*** *オプション：設定テストを実行する場合。* AutoSupport システムがテストディスパッチを受信したときに確認が送信されるEメールアドレス。
*** メッセージを暗号化する場合は、暗号化タイプとして*SMTPS*または*STARTTLS *を選択し、暗号化されたメッセージのポート番号を選択します。それ以外の場合は、*なし*を選択します。
*** 必要に応じて、送信元とメールサーバとの認証用のユーザ名とパスワードを入力します。




. Test Configuration *をクリックして、指定された配信パラメータを使用してテクニカルサポートサーバーへの接続をテストします。AutoSupport On-Demand機能を有効にした場合は、AutoSupport OnDemandディスパッチの配信のための接続もシステムでテストされます。
+
設定テストに失敗した場合は、設定を確認してから、もう一度テストを実行してください。テストが引き続き失敗する場合は、テクニカルサポートにお問い合わせください。

. [ 保存（ Save ） ] をクリックします。

