---
permalink: sm-support/how-do-i-choose-which-type-of-upgrade-to-perform.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, upgrade, perform 
summary: ドライブ上で実行するアップグレードのタイプは、プールまたはボリュームグループの状態に応じて選択します。 
---
= 実行するアップグレードのタイプを選択するにはどうすればよいですか？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ドライブ上で実行するアップグレードのタイプは、プールまたはボリュームグループの状態に応じて選択します。

* * オンライン *
+
プールまたはボリュームグループで冗長性がサポートされていて、ステータスが最適の場合は、オンライン方式を使用してドライブのファームウェアをアップグレードできます。オンライン方式では、ドライブを使用している関連付けられたボリュームにストレージアレイがI/Oを処理している間に、ファームウェアがダウンロードされます。ドライブを使用している関連付けられたボリュームへのI/Oを停止する必要はありません。ドライブは、ドライブに関連付けられているボリュームに対して一度に1つずつアップグレードされます。プールまたはボリュームグループに割り当てられていないドライブのファームウェアは、オンライン方式でもオフライン方式でも更新できます。オンライン方式を使用してドライブファームウェアをアップグレードすると、システムのパフォーマンスに影響が出る場合があります。

* * オフライン *
+
プールまたはボリュームグループで冗長性がサポートされていない（RAID 0）か、デグレード状態の場合は、オフライン方式を使用してドライブのファームウェアをアップグレードする必要があります。オフライン方式では、すべてのI/Oアクティビティが停止している間にファームウェアのみがアップグレードされ、ドライブを使用している関連付けられたボリュームにアップグレードされます。ドライブを使用している関連付けられたボリュームへのI/Oをすべて停止する必要があります。プールまたはボリュームグループに割り当てられていないドライブのファームウェアは、オンライン方式でもオフライン方式でも更新できます。


