---
permalink: sm-support/review-the-possible-software-and-firmware-upgrade-errors.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, software, firmware, upgrade, errors 
summary: コントローラソフトウェアのアップグレード中またはドライブファームウェアのアップグレード中にエラーが発生する可能性があります。 
---
= ソフトウェアとファームウェアのアップグレードエラーの可能性を確認します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コントローラソフトウェアのアップグレード中またはドライブファームウェアのアップグレード中にエラーが発生する可能性があります。

[cols="25h,~,~"]
|===
| ファームウェアのダウンロードエラーです | 説明 | 推奨される対処方法 


 a| 
割り当てられたドライブで障害が発生し
 a| 
ストレージアレイに割り当てられているドライブをアップグレードできませんでした。
 a| 
エラーの理由の 1 つとして、ドライブに適切な署名がない可能性があります。該当するドライブが認定済みのドライブであることを確認します。詳細については、テクニカルサポートにお問い合わせください。

ドライブを交換する場合は、交換用ドライブの容量が交換する障害ドライブと同じかそれよりも大きいことを確認してください。

障害が発生したドライブの交換は、ストレージアレイで I/O を受信中に実行できます



 a| 
統合ホットスペアドライブ
 a| 
ホットスペアとしてマークされているドライブがボリュームグループに使用されている場合は、ファームウェアのアップグレードプロセスが失敗します。
 a| 
ファームウェアをアップグレードする前に、このエラーを修正する必要があります。System Manager を起動し、 Recovery Guru を使用して問題を解決します。



 a| 
不完全なボリュームグループです
 a| 
ボリュームグループに含まれるドライブが迂回された、削除された、または応答しない場合、そのボリュームグループは不完全なボリュームグループとみなされます。ボリュームグループが不完全な場合は、ファームウェアをアップグレードできなくなります。
 a| 
1 つ以上のボリュームグループまたはディスクプールが不完全な場合は、ファームウェアをアップグレードする前に、このエラーを修正する必要があります。System Manager を起動し、 Recovery Guru を使用して問題を解決します。



 a| 
すべてのボリュームグループで実行中の排他的処理（バックグラウンドメディア / パリティスキャン以外）
 a| 
ボリュームで排他的な処理を実行中の場合は、ファームウェアをアップグレードできません。
 a| 
1 つ以上の排他的な処理を実行中の場合は、その処理を完了してからファームウェアをアップグレードする必要があります。System Manager で処理の進捗状況を監視します。



 a| 
ボリュームが見つからない
 a| 
いずれかのボリュームが見つからない場合は、ファームウェアをアップグレードできません。
 a| 
ファームウェアをアップグレードする前に、ボリュームが見つからない状態を修正する必要があります。System Manager を起動し、 Recovery Guru を使用して問題を解決します。



 a| 
いずれかのコントローラの状態が最適以外である必要があります
 a| 
いずれかのコントローラの状態が最適以外の場合は、ファームウェアをアップグレードできません。
 a| 
いずれかのストレージアレイコントローラを確認する必要があります。ファームウェアをアップグレードする前に、この状態を修正する必要があります。System Manager を起動し、 Recovery Guru を使用して問題を解決します。



 a| 
SPM の検証でデータベースコントローラのチェックが失敗する
 a| 
ストレージパーティションマッピングデータベースが破損しているため、ファームウェアをアップグレードできません。
 a| 
コントローラでストレージパーティションマッピングデータベースのエラーが発生しました。この問題を解決するには、テクニカルサポートにお問い合わせください。



 a| 
構成データベースの検証（ストレージアレイのコントローラのバージョンでサポートされている場合）
 a| 
構成データベースが破損しているため、ファームウェアをアップグレードできません。
 a| 
コントローラで構成データベースのエラーが発生しました。この問題を解決するには、テクニカルサポートにお問い合わせください。



 a| 
MEL 関連のチェック
 a| 
イベントログにエラーが含まれているため、ファームウェアをアップグレードできません。
 a| 
この問題を解決するには、テクニカルサポートにお問い合わせください。



 a| 
過去 7 日間に 10 個を超える DDE 情報または重大 MEL イベントが報告されました
 a| 
10個を超えるDDE情報または重大MELイベントが過去7日以内に報告されたため、ファームウェアをアップグレードできません。
 a| 
この問題を解決するには、テクニカルサポートにお問い合わせください。



 a| 
2 個を超えるページ 2C 重大 MEL イベントが過去 7 日以内に報告されました
 a| 
2個を超えるページ2C重大MELイベントが過去7日以内に報告されたため、ファームウェアをアップグレードできません。
 a| 
この問題を解決するには、テクニカルサポートにお問い合わせください。



 a| 
2 個を超えるデグレードドライブチャネル重大 MEL イベントが過去 7 日以内に報告されました
 a| 
2個を超えるデグレードドライブチャネル重大MELイベントが過去7日以内に報告されたため、ファームウェアをアップグレードできません。
 a| 
この問題を解決するには、テクニカルサポートにお問い合わせください。



 a| 
過去 7 日間に 4 個を超える重大 MEL エントリが生成されます
 a| 
4個を超える重大イベントログエントリが過去7日以内に報告されたため、ファームウェアをアップグレードできません。
 a| 
この問題を解決するには、テクニカルサポートにお問い合わせください。



 a| 
有効な管理IPアドレスを指定してください。
 a| 
この処理を実行するには、有効なコントローラIPアドレスが必要です。
 a| 
この問題を解決するには、テクニカルサポートにお問い合わせください。



 a| 
このコマンドでは、各コントローラにアクティブな管理IPアドレスを指定する必要があります。
 a| 
この処理には、ストレージアレイに関連付けられている各コントローラのIPアドレスが必要です。
 a| 
この問題を解決するには、テクニカルサポートにお問い合わせください。



 a| 
未処理のダウンロードファイルタイプが返されました。
 a| 
指定したダウンロードファイルはサポートされていません。
 a| 
この問題を解決するには、テクニカルサポートにお問い合わせください。



 a| 
ファームウェアのダウンロード中にエラーが発生しました。手順 のアップロード。
 a| 
コントローラが要求を処理できないため、ファームウェアのダウンロードに失敗しました。ストレージアレイが最適lであることを確認してから、処理を再試行してください。
 a| 
ストレージアレイが最適な状態であることを確認したあともこのエラーが再び発生する場合は、テクニカルサポートに連絡してこの問題 を解決してください。



 a| 
ファームウェアアクティベーション手順 の実行中にエラーが発生しました。
 a| 
コントローラが要求を処理できないため、ファームウェアのアクティブ化に失敗しました。ストレージアレイが最適lであることを確認してから、処理を再試行してください。
 a| 
ストレージアレイが最適な状態であることを確認したあともこのエラーが再び発生する場合は、テクニカルサポートに連絡してこの問題 を解決してください。



 a| 
コントローラ｛0｝のリブートを待機中にタイムアウトしました。
 a| 
リブート後に管理ソフトウェアがコントローラ\{0\}に再接続できません。ストレージアレイへの動作中の接続パスがあることを確認し、処理が正常に完了しなかった場合は再試行してください。
 a| 
ストレージアレイが最適な状態であることを確認したあともこのエラーが再び発生する場合は、テクニカルサポートに連絡してこの問題 を解決してください。

|===
System ManagerのRecovery Guruを使用して、上記の一部の状態を修正できます。ただし、一部の状況については、テクニカルサポートへの連絡が必要な場合があります。最新のコントローラファームウェアのダウンロードに関する情報は、ストレージアレイから入手できます。この情報は、ファームウェアのアップグレードやダウンロードを妨げているエラーの状態をテクニカルサポートが把握するために役立ちます。
