---
permalink: sm-support/upgrade-controller-software-and-firmware.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, upgrade, software, firmware 
summary: ストレージアレイのソフトウェア、およびオプションでIOMファームウェアと不揮発性ランダムアクセスメモリ（NVSRAM）をアップグレードして、最新の機能とバグ修正をすべて適用できます。 
---
= SANtricity System Managerでコントローラのソフトウェアとファームウェアをアップグレードする
:allow-uri-read: 


[role="lead"]
ストレージアレイのソフトウェア、および必要に応じてIOMファームウェアと不揮発性静的ランダムアクセスメモリ（NVSRAM）をアップグレードして、最新の機能とバグ修正をすべて適用できます。

.作業を開始する前に
* IOMファームウェアをアップグレードするかどうかを決めます。
+
通常は、すべてのコンポーネントを同時にアップグレードする必要があります。ただし、 IOM ファームウェアを SANtricity OS ソフトウェアアップグレードの一部としてアップグレードしない場合や、テクニカルサポートから IOM ファームウェアをダウングレードするよう依頼された場合は（ファームウェアのダウングレードにはコマンドラインインターフェイスを使用する必要があります）、アップグレードを中止することもできます。

* コントローラNVSRAMファイルをアップグレードするかどうかを決めます。
+
通常は、すべてのコンポーネントを同時にアップグレードする必要があります。ただし、パッチを適用していたり、カスタムバージョンのコントローラ NVSRAM ファイルを使用していて、上書きしたくない場合は、アップグレードを中止することもできます。

* OSのアップグレードを今すぐアクティブ化するか、あとでアクティブ化するかを決めます。
+
あとでアクティブ化する理由には、次のものがあります

+
** *時間帯*--ソフトウェアとファームウェアのアクティブ化には時間がかかることがあるため、I/O負荷の低い時間帯に実行できます。アクティブ化の際にはコントローラがフェイルオーバーするため、アップグレードが完了するまではパフォーマンスが通常よりも低下する可能性があります。
** * パッケージのタイプ * -- 他のストレージアレイ上のファイルをアップグレードする前に ' 新しいソフトウェアとファームウェアを 1 つのストレージアレイでテストすることをお勧めします


* セキュリティ保護されていないドライブから切り替えるか、内部でセキュリティ保護されているドライブから切り替えるか、ドライブのセキュリティを確保するために外部キー管理サーバ（KMS）を使用するかを確認します。
* ストレージアレイでロールベースアクセス制御を使用するかどうかを決めます。


.このタスクについて
OSのソフトウェアファイルまたはコントローラのNVSRAMファイルのどちらかのみをアップグレードすることも、両方のファイルをアップグレードすることもできます。

この処理は、テクニカルサポートから指示があった場合にのみ実行してください。

[CAUTION]
====
* データ損失のリスク、ストレージアレイの損傷のリスク * -- アップグレードの実行中にストレージアレイを変更しないでください。ストレージアレイの電源は切らないでください。

====
.手順
. ストレージアレイにコントローラが 1 台しかない場合やマルチパスドライバがインストールされていない場合は、アプリケーションエラーを回避するためにストレージアレイへの I/O アクティビティを停止します。ストレージアレイにコントローラが 2 台あり、マルチパスドライバがインストールされている場合は、 I/O アクティビティを停止する必要はありません。
. 左側のパネルから、メニュー：サポート［アップグレードセンター］を選択します。
. 新しいファイルをサポートサイトから管理クライアントにダウンロードします。
+
.. ネットアップサポートをクリックして、サポートWebサイトを起動します。
.. サポートWebサイトで、* Downloads *（ダウンロード）タブをクリックし、* Downloads *（ダウンロード）を選択します。
.. EシリーズSANtricity OSコントローラソフトウェア*を選択します。
.. 残りの手順に従います。


+
[NOTE]
====
バージョン 8.42 以降のデジタル署名されたファームウェアが必要です。署名のないファームウェアをダウンロードしようとすると、エラーが表示されてダウンロードが中止されます。

====
. 現時点でIOMファームウェアの動作を変更する必要がある場合は、*IOM自動同期の設定*をクリックしてください。
+
ストレージアレイにコントローラが 1 台しかない場合、 IOM ファームウェアはアップグレードされません。

. SANtricity OS ソフトウェアのアップグレードで、*SANtricity OS ソフトウェアのアップグレードを開始する*をクリックします。
+
SANtricity OS ソフトウェアのアップグレードページが表示されます。

. アップグレードプロセスを開始するファイルを 1 つ以上選択します。
+
.. *参照*をクリックし、サポート Web サイトからダウンロードした OS ソフトウェア ファイルに移動して、SANtricity OS ソフトウェア ファイルを選択してください。
.. 参照 * をクリックし、サポートサイトからダウンロードした NVSRAM ファイルに移動して、コントローラ NVSRAM ファイルを選択します。コントローラ NVSRAM ファイルの名前は 'N2800-830000-000.dll' のようになります


+
次の処理が行われます。

+
** デフォルトでは、現在のストレージアレイ構成と互換性のあるファイルだけが表示されます。
** アップグレードするファイルを選択すると、ファイルの名前とサイズが表示されます。


. *オプション：* アップグレードする SANtricity OS ソフトウェア ファイルを選択した場合、*「今すぐファイルを転送するが、アップグレードは開始しない（後でアクティブ化する）」* チェックボックスを選択することで、ファイルをアクティブ化せずにコントローラーに転送できます。
. [ * スタート * ] をクリックし、操作を確定します。
+
アップグレード前の健常性チェックの間は処理をキャンセルできますが、転送またはアクティブ化の実行中はキャンセルできません。

. *オプション：* アップグレードされた項目の一覧を表示するには、*ログを保存*をクリックします。
+
ブラウザの Downloads フォルダに、「 drive upgrade_log-timestamp.txt 」という名前でファイルが保存されます。



.完了後
* ハードウェアページにすべてのコンポーネントが表示されていることを確認します。
* ソフトウェアとファームウェアのインベントリページを確認することで、新しいソフトウェアとファームウェアのバージョンを確認できます（menu：Support[Upgrade center]に移動し、*software and firmware inventory*のリンクをクリックしてください）。
* コントローラ NVSRAM をアップグレードした場合、既存の NVSRAM に適用されていたカスタム設定はアクティブ化のプロセスで失われます。カスタム設定については、アクティブ化のプロセスの完了後に NVSRAM に再度適用する必要があります。

