---
permalink: sm-support/upgrade-drive-firmware.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, upgrade, drive, firmware 
summary: ドライブのファームウェアをアップグレードして、最新の機能とバグ修正をすべて利用できます。 
---
= ドライブファームウェアをアップグレードします
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ドライブファームウェアをアップグレードして、最新の機能やバグ修正をすべて適用することができます。

.作業を開始する前に
* ディスクツーディスクバックアップ、（計画的なファームウェアアップグレードの影響を受けないボリュームグループへの）ボリュームコピー、またはリモートミラーを使用してデータをバックアップしておきます。
* ストレージアレイのステータスが「最適」であることを確認します。
* すべてのドライブのステータスが最適な状態である必要があります
* ストレージアレイで構成の変更が実行されていないことを確認します。
* ドライブのオフラインアップグレードのみが可能な場合は、ドライブに関連付けられているすべてのボリュームへのI/Oアクティビティを停止します。


.手順
. メニューを選択します。Support [Upgrade Center]を選択します。
. 新しいファイルをサポートサイトから管理クライアントにダウンロードします。
+
.. Drive Firmware upgrade（ドライブファームウェアのアップグレード）で、*NetApp Support*（ネットアップサポート）をクリック
.. ネットアップサポートWebサイトで、「* Downloads *」タブをクリックします。
.. 「* Disk Drive & Firmware Matrix *」を選択します。
.. 残りの手順に従います。


. ドライブファームウェアのアップグレードで、*アップグレードの開始*をクリックします。
+
使用中のドライブファームウェアファイルを示すダイアログボックスが表示されます。

. サポートサイトからダウンロードしたファイルを展開（解凍）します。
. [* Browse] をクリックし、サポートサイトからダウンロードした新しいドライブファームウェアファイルを選択します。
+
ドライブファームウェアファイルのファイル名は、「 .dhUC101212CSS600_30602291_MS01_2800_0002 」のようになります。拡張子は「 .dlp 」です。

+
ドライブファームウェアファイルは一度に 1 つずつ、最大 4 つまで選択できます。同じドライブに複数のドライブファームウェアファイルが対応している場合は、ファイル競合エラーが発生します。アップグレードに使用するドライブファームウェアファイルを決定し、それ以外のファイルは削除します。

. 「 * 次へ * 」をクリックします。
+
ドライブの選択*（* Select Drives *）ダイアログボックスが表示され、選択したファイルでアップグレードできるドライブがリストされます。

+
対応しているドライブのみが表示されます。

+
ドライブに対して選択したファームウェアが、推奨されるファームウェア情報領域に表示されます。ファームウェアを変更する必要がある場合は、 ［ * 戻る ］ をクリックして前のダイアログに戻ります。

. 実行するアップグレードのタイプを選択します。
+
** * オンライン（デフォルト） * - ストレージ・アレイが I/O を処理している間に ' ファームウェア・ダウンロードをサポートできるドライブを表示しますこのアップグレード方式を選択した場合は、これらのドライブを使用している関連付けられたボリュームへの I/O を停止する必要はありません。これらのドライブは、ストレージアレイによるドライブへの I/O の処理中に 1 つずつアップグレードされます。
** * オフライン（並行処理） * -- ドライブを使用するすべてのボリュームですべての I/O アクティビティが停止されている間に ' ファームウェアのダウンロードのみをサポートできるドライブを表示しますこのアップグレード方式を選択すると、アップグレード対象のドライブを使用するすべてのボリュームで I/O アクティビティをすべて停止する必要があります。冗長性がないドライブはオフラインで処理する必要があります。この要件には、 SSD キャッシュ、 RAID 0 ボリュームグループ、またはデグレード状態のプールやボリュームグループに関連付けられているドライブが含まれます。オフライン（並行）アップグレードは、通常、オンライン（デフォルト）方式よりも高速です。


. テーブルの最初の列で、アップグレードするドライブを選択します。
. [ * スタート * ] をクリックし、操作を確定します。
+
アップグレードを停止する必要がある場合は、 * 停止 * をクリックします。実行中のファームウェアのダウンロードは完了します。開始されていないファームウェアのダウンロードはキャンセルされます。

+
[CAUTION]
====
ドライブファームウェアのアップグレードを停止すると、データが失われたり、ドライブを使用できなくなったりする可能性があります。

====
. *オプション：*アップグレードされた内容のリストを表示するには、*ログの保存*をクリックします。
+
ブラウザの Downloads フォルダに、「 drive upgrade_log-timestamp.txt 」という名前でファイルが保存されます。

. 手順のアップグレード中に次のいずれかのエラーが発生した場合は、推奨される対処方法を実行してください。


.エラーと推奨される対処方法
[%collapsible]
====
[cols="40h,~"]
|===
| ファームウェアのダウンロードエラー | 対処方法 


 a| 
割り当てられたドライブで障害が発生し
 a| 
エラーの理由の 1 つとして、ドライブに適切な署名がない可能性があります。該当するドライブが認定済みのドライブであることを確認します。詳細については、テクニカルサポートにお問い合わせください。

ドライブを交換する場合は、交換用ドライブの容量が交換する障害ドライブと同じかそれよりも大きいことを確認してください。

障害が発生したドライブの交換は、ストレージアレイで I/O を受信中に実行できます



 a| 
ストレージアレイをチェックしてください
 a| 
* 各コントローラに IP アドレスが割り当てられていることを確認します。
* コントローラに接続されているすべてのケーブルが破損していないことを確認します。
* すべてのケーブルがしっかりと接続されていることを確認します。




 a| 
統合ホットスペアドライブ
 a| 
ファームウェアをアップグレードする前に、このエラーを修正する必要があります。System Manager を起動し、 Recovery Guru を使用して問題を解決します。



 a| 
不完全なボリュームグループです
 a| 
1 つ以上のボリュームグループまたはディスクプールが不完全な場合は、ファームウェアをアップグレードする前に、このエラーを修正する必要があります。System Manager を起動し、 Recovery Guru を使用して問題を解決します。



 a| 
すべてのボリュームグループで実行中の排他的な処理（バックグラウンドメディア/パリティスキャン以外）
 a| 
1 つ以上の排他的な処理を実行中の場合は、その処理を完了してからファームウェアをアップグレードする必要があります。System Manager で処理の進捗状況を監視します。



 a| 
ボリュームが見つからない
 a| 
ファームウェアをアップグレードする前に、ボリュームが見つからない状態を修正する必要があります。System Manager を起動し、 Recovery Guru を使用して問題を解決します。



 a| 
いずれかのコントローラの状態が最適以外である必要があります
 a| 
いずれかのストレージアレイコントローラを確認する必要があります。ファームウェアをアップグレードする前に、この状態を修正する必要があります。System Manager を起動し、 Recovery Guru を使用して問題を解決します。



 a| 
コントローラオブジェクトグラフ間でストレージパーティション情報が一致しません
 a| 
コントローラ上のデータの検証中にエラーが発生しました。この問題を解決するには、テクニカルサポートにお問い合わせください。



 a| 
SPM の検証でデータベースコントローラのチェックが失敗する
 a| 
コントローラでストレージパーティションマッピングデータベースのエラーが発生しました。この問題を解決するには、テクニカルサポートにお問い合わせください。



 a| 
構成データベースの検証（ストレージアレイのコントローラバージョンでサポートされている場合）
 a| 
コントローラで構成データベースのエラーが発生しました。この問題を解決するには、テクニカルサポートにお問い合わせください。



 a| 
MEL 関連のチェック
 a| 
この問題を解決するには、テクニカルサポートにお問い合わせください。



 a| 
過去 7 日間に 10 個を超える DDE 情報または重大 MEL イベントが報告されました
 a| 
この問題を解決するには、テクニカルサポートにお問い合わせください。



 a| 
2 個を超えるページ 2C 重大 MEL イベントが過去 7 日以内に報告されました
 a| 
この問題を解決するには、テクニカルサポートにお問い合わせください。



 a| 
2 個を超えるデグレードドライブチャネル重大 MEL イベントが過去 7 日以内に報告されました
 a| 
この問題を解決するには、テクニカルサポートにお問い合わせください。



 a| 
過去 7 日間に 4 個を超える重大 MEL エントリが生成されます
 a| 
この問題を解決するには、テクニカルサポートにお問い合わせください。

|===
====
.完了後
これでドライブファームウェアのアップグレードは完了です。通常の運用を再開することができます。
