---
permalink: sm-support/use-script-editor.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, script editor, script file, execute script 
summary: スクリプト エディタを使用して、スクリプト ファイルを作成または編集したり、スクリプト ファイルをストレージ管理ステーションのローカル ディスクに保存したり、ディスクからスクリプト ファイルをロードしたりできます。 
---
= スクリプト エディタを使用する
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
スクリプト エディタを使用して、スクリプト ファイルを作成または編集したり、スクリプト ファイルをストレージ管理ステーションのローカル ディスクに保存したり、ディスクからスクリプト ファイルをロードしたりできます。

.作業を開始する前に
スクリプトエディタはストレージアレイと通信し、スクリプトの構文チェックとコマンド実行を可能にします。スクリプトエディタに入力されたスクリプトコマンドは、通常、ストレージアレイ上で実行されます。

スクリプトエディタのウィンドウには、次の2つのビューが表示されます：

* エディター ペイン – スクリプト コマンドを入力または編集するための領域を提供します。
* 出力ペイン – 検証結果または実行結果を表示します。分割バーは、ウィンドウをエディタ ペインと出力ペインに分割します。
* スクリプト エディタは、コントローラ ファームウェア、NVSRAM、またはドライブ ファームウェアのアップグレードなど、入力ファイルを必要とするコマンドをサポートしていません。
* Script editor は、出力ファイルを生成するコマンドをサポートしています。
* クライアント側で実行する必要があるコマンドがいくつかあります（クライアント側コマンド）。
+
** このリリースでサポートされている唯一のクライアント側コマンドは、 `on error stop`と `on error continue`です。
** スクリプトエディタは、他のクライアント側コマンドを実行しようとするとエラーを生成します。






== スクリプト エディタを開く

.手順
. 左側のパネルから、menu:Support[Script editor]を選択します。
+
以下の表は、スクリプトエディタで使用できるファイルオプションの一覧です：

+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| Task | アクション 


 a| 
新しいスクリプトを開く
 a| 
.. *Load script file* をクリックすると、既存のスクリプトファイルを Script editor にアップロードできます。
+
Script editorは、選択したスクリプトファイルをエディタペインで開きます。





 a| 
スクリプトコマンドの構文を確認します
 a| 
.. *構文チェック*をクリックして、エディタペインで現在のスクリプトの構文を確認します。
+
スクリプトエディタは、スクリプトファイル内のステートメントを1行ずつ解析し、構文が正しいかどうかを検証します。構文エラーが発生した場合は、出力ペインにエラーが発生した行番号とエラーの説明が表示されます。

+
スクリプト エディタで構文エラーが検出された場合、スクリプトに対するそれ以上の構文検証は実行されません。

+
構文エラーを修正し、*構文チェック* を再実行してエラー修正を検証し、スクリプト内の残りのステートメントをチェックしてください。





 a| 
スクリプトの実行
 a| 
.. *Execute Script*をクリックすると、エディタペインに表示されている現在のスクリプトが実行されます。
+
スクリプトエディタは構文チェック処理を開始し、その後、入力ファイル内の各スクリプトコマンドに対して、ストレージアレイコントローラ上でコマンド実行が実行されます。

+
スクリプトエディタは構文エラーを検出すると、実行を停止し、エラーメッセージを表示します。

+
エラーを修正し、*構文チェック*を再実行してエラー修正を検証します。

+

NOTE: 実行エラーが発生した場合、含まれている `On Error`スクリプト ステートメントによっては、スクリプトの実行が継続されない可能性があります。 `On Error Stop`ステートメントは、実行エラーが発生した場合にスクリプトを停止します。 `On Error
Continue`ステートメントは、実行エラーが発生した後でもスクリプトの実行を続行します。このステートメントはデフォルト設定です。





 a| 
既存のスクリプトを編集する
 a| 
.. *Load script file* をクリックすると、既存のスクリプトファイルを Script editor にアップロードできます。
.. エディタペインで、スクリプトに必要な変更を加えます。




 a| 
スクリプトをローカルファイルに保存します
 a| 
.. *Save script file*をクリックすると、スクリプトペインでの変更内容が新しいスクリプトファイルとしてダウンロードされます。




 a| 
スクリプト エディタのエディタ ペインのテキストをクリアします。
 a| 
.. エディタペイン内のテキストをクリアするには、*エディタをクリア*をクリックします。




 a| 
出力結果をローカルファイルに保存する
 a| 
.. *結果を保存*をクリックすると、出力ペインの内容を新しいファイルとしてダウンロードできます。


|===
====




=== Script editorでスクリプトを作成します

.作業を開始する前に
スクリプト エディタを使用してスクリプト コマンドを記述する場合は、次のガイドラインに従ってください：* すべてのステートメントをセミコロン（;）で終了します。* 各基本コマンドと、それに関連付けられた主要パラメータおよび補助パラメータは、スペースで区切ってください。* スクリプト エディタに入力するパラメータは、大文字と小文字を区別しません。* 各文は別々の行に書いてください。* スクリプトにコメントを追加することで、あなた自身や将来のユーザーがコマンド ステートメントの目的を理解しやすくなります。

.手順
. 複数行のコメントは、文字 `/*`と `*/`で囲みます。
+
スクリプト エンジンが開始コメント表記と終了コメント表記の両方を見つけられない場合、エラー メッセージが表示され、スクリプトの実行が終了します。

. 単一行コメントは、スラッシュ2つ(`//`で始まり、改行文字で終わります。改行文字は、*Enter* を押すことで挿入できます。
+
スクリプト エンジンがコメント処理後にスクリプト内に改行文字を見つけられなかった場合、エラー メッセージが表示され、スクリプトの実行が終了します。

+
このエラーは、スクリプトの最後にコメントを追加した際に、*Enter*キーを押すのを忘れた場合によく発生します。

.  `show`ステートメントを使用して、スクリプト実行中にエディタペインに表示されるコメントをスクリプトに埋め込みます。
+
 `show`ステートメントはスクリプトのデバッグに役立ちます。

+
スクリプトに `show setting controller mode`ステートメントを含めると、スクリプトの実行中にこの行が処理されるときに、出力ペインに次の行が表示されます：

+
[listing]
----
setting controller mode
----




=== スクリプト実行結果を解釈する

スクリプトの実行中、出力ペインには次で始まるメッセージが表示されます：

[listing]
----
Executing script...
----
解析フェーズ中にエラーが発生した場合、出力ペインにエラーが表示され、行番号、列番号、および構文エラーの説明が表示されます。以下は構文エラー メッセージの例です。

スクリプトに次のステートメントを入力した場合：

`set controller[a] mod = passive;`

出力ペインには、結果として生じた構文エラーが次のように表示されます：

[listing]
----
Encountered "mod" at line 2, column 19
Was expecting one of...
"mode"...
"availability"...
"NVSRAMbyte"...
----
スクリプトの実行中にエラーが発生した場合、出力ペインにメッセージが表示され、コマンドが失敗したこととエラーの説明が示されます。

例えば、スクリプトに次のステートメントを入力した場合：

`set volume [three] userLabel="OneOne";`

発生したエラーは、次の出力ペインに表示されます。ストレージアレイが応答不能状態だったため、コマンドを送信できませんでした。

[listing]
----
Unable to change the volume user label using the Set Volume command at line 1
Error - 1 - Could not communicate with the storage array to complete this request.
----

NOTE: ストレージアレイとの通信不能など、特定の実行エラーが発生すると、必ずスクリプトの実行が停止します。これらの場合、 `On Error Continue`ステートメントを使用しても、実行は停止します。

.結果
スクリプトを実行した後、出力ペインを確認して、成功したかエラーが発生したかを確認してください。
