---
permalink: sm-support/view-unreadable-sectors-log.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, unreadable, sectors, log 
summary: 読み取り不能セクターのログを保存して、分析用のファイルをテクニカルサポートに送信できます。 
---
= 読み取り不能セクターのログを表示します
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
読み取り不能セクターのログを保存して、分析用のファイルをテクニカルサポートに送信できます。

.このタスクについて
読み取り不能セクターのログには、リカバリ不能なメディアエラーが報告されたドライブが原因で発生した読み取り不能セクターの詳細なレコードが含まれます。読み取り不能セクターは、通常のI/O処理中、および再構築などの変更処理中に検出されます。読み取り不能セクターが検出されたストレージアレイに対しては、要注意アラートが表示されます。Recovery Guruでは、注意すべき読み取り不能セクターの状態を識別します。読み取り不能セクターに格納されているデータはリカバリできないため、失われたとみなされます。

読み取り不能セクターのログには、最大1、000個の読み取り不能セクターを格納できます。読み取り不能セクターのログが1、000個のエントリに達すると、次の条件が適用されます。

* 再構築中に読み取り不能セクターが新しく検出された場合は、再構築が失敗し、エントリがログに記録されません。
* I/O中に読み取り不能セクターが新しく検出された場合は、I/Oが失敗し、エントリがログに記録されません。
+
[NOTE]
====
これらのアクションには、オーバーフロー前に成功したRAID 5の書き込みとRAID 6の書き込みが含まれます。

====


[CAUTION]
====
*データが失われる可能性*--読み取り不能セクターからのリカバリは複雑な手順 であり、さまざまな方法を使用する可能性があります。この処理は、テクニカルサポートから指示があった場合にのみ実行してください。

====
.手順
. メニューを選択します。Support（サポートセンター）> Diagnostics（診断）タブ。
. 読み取り不能セクターの表示/消去*を選択します。
. 読み取り不能セクターログを保存するには、次の手順を実行
+
.. テーブルの最初の列で、読み取り不能セクターのログを保存するボリュームを個別に選択する（各ボリュームの横にあるチェックボックスをオンにする）か、テーブルのヘッダーにあるチェックボックスをオンにしてすべてのボリュームを選択できます。
+
特定のボリュームを検索するには、任意の列をソートしたり、* Filter *ボックスに文字を入力したりできます。

.. [ 保存（ Save ） ] をクリックします。


+
ブラウザのDownloadsフォルダに、「unreadable-sectors.txt」という名前でファイルが保存されます。

. テクニカルサポートから読み取り不能セクターのログを消去するよう依頼があった場合は、次の手順を実行します。
+
.. テーブルの最初の列で、読み取り不能セクターのログを消去するボリュームを個別に選択する（各ボリュームの横にあるチェックボックスをオンにする）か、テーブルのヘッダーにあるチェックボックスをオンにしてすべてのボリュームを選択できます。
.. [* Clear*](クリア)をクリックし'操作を実行することを確認します



