---
permalink: sm-support/view-iser-over-infiniband-statistics-support.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, iser, over, infiniband, statistics 
summary: ストレージアレイのコントローラにiSER over InfiniBandポートが搭載されている場合は、ホスト接続に関するデータを表示できます。 
---
= iSER over InfiniBandの統計を表示します
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイのコントローラにiSER over InfiniBandポートが搭載されている場合は、ホスト接続に関するデータを表示できます。

.このタスクについて
System Managerには、次のタイプのiSER over InfiniBand統計が表示されます。統計はすべて読み取り専用で、設定することはできません。

* *ローカルターゲット（プロトコル）統計*- iSER over InfiniBandターゲットの統計を提供し、ストレージメディアへのブロックレベルのアクセスが表示されます。
* * iSER over InfiniBandインターフェイス統計*- InfiniBandインターフェイス上のすべてのiSERポートの統計が提供され、各スイッチポートに関連付けられているパフォーマンス統計とリンクエラー情報が含まれます。


これらの統計はそれぞれ、統計の生データまたはベースライン統計として表示できます。統計の生データは、コントローラの起動以降に収集されたすべての統計です。ベースライン統計は、ベースライン時間の設定以降に収集されたポイントインタイムの統計です。

.手順
. メニューを選択します。Support（サポートセンター）> Diagnostics（診断）タブ。
. View iSER over InfiniBand Statistics *を選択します。
. タブをクリックして、さまざまな統計を表示します。
. ベースラインを設定するには、*新しいベースラインを設定*をクリックします。
+
ベースラインを設定すると、統計を収集するための新しい開始ポイントが設定されます。すべてのiSER over InfiniBand統計に同じベースラインが使用されます。


