---
permalink: sm-support/view-events-using-the-event-log.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, events, 
summary: ストレージアレイで発生したイベントの履歴レコードを提供するイベントログを表示できます。 
---
= イベントログを使用してイベントを表示します
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイで発生したイベントの履歴レコードを提供するイベントログを表示できます。

.手順
. メニューを選択します。サポート[イベントログ]。
+
[Event Log]ページが表示されます。

+
.ページの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| 項目 | 説明 


 a| 
すべてのフィールドを表示します
 a| 
すべてのイベントを表示するか、重大/警告イベントだけを表示するかを切り替えます。



 a| 
フィルタフィールド
 a| 
イベントをフィルタします。特定のコンポーネントや特定のイベントなどに関連するイベントだけを表示する場合に便利です



 a| 
列アイコンを選択します。
 a| 
表示する他の列を選択できます。他の列には、イベントに関する追加情報 が表示されます。



 a| 
チェックボックスを選択します
 a| 
保存するイベントを選択できます。テーブルのヘッダーにあるチェックボックスをオンにすると、すべてのイベントが選択されます。



 a| 
[日付/時刻]列
 a| 
コントローラクロックに応じたイベントの日付と時刻のタイムスタンプ。


NOTE: イベントログでは、最初にシーケンス番号に基づいてイベントをソートします。通常、このシーケンスは日付と時刻に対応します。ただし、ストレージアレイ内の2つのコントローラクロックは同期されない可能性があります。この場合、イベントログに表示されるイベントと日時に不整合が生じる可能性があります。



 a| 
[優先度]列
 a| 
優先度の値は次のとおりです。

** *クリティカル*--ストレージアレイに問題がありますただし、すぐに対処すれば、データにアクセスできなくなる状況を回避できる可能性があります。重大イベントはアラート通知に使用されます。すべての重大イベントは、SNMPトラップを使用してネットワーク管理クライアントに送信されるか、設定したEメール受信者に送信されます。
** *警告*--ストレージアレイのパフォーマンスと機能を低下させて別のエラーから回復するエラーが発生しました
** *情報*--ストレージアレイに関連する重要でない情報。




 a| 
[コンポーネントタイプ]列
 a| 
イベントの影響を受けるコンポーネント。コンポーネントには、ドライブやコントローラなどのハードウェアや、コントローラファームウェアなどのソフトウェアがあります。



 a| 
コンポーネントの場所列
 a| 
ストレージアレイ内のコンポーネントの物理的な場所。



 a| 
概要 列
 a| 
イベントの概要 。

*例*-- Drive write failure-retries exhausted



 a| 
シーケンス番号列
 a| 
ストレージアレイの特定のログエントリを一意に識別する64ビットの番号。この数は、新しいイベントログエントリが生成されるたびに1ずつ増えます。この情報を表示するには、列の選択*アイコンをクリックします。



 a| 
[イベントタイプ]列
 a| 
ログに記録される各タイプのイベントを識別する4桁の番号。この情報を表示するには、列の選択*アイコンをクリックします。



 a| 
[イベント固有のコード]列
 a| 
この情報はテクニカルサポートが使用します。この情報を表示するには、列の選択*アイコンをクリックします。



 a| 
[イベントカテゴリ]列
 a| 
** **障害**：ドライブ障害やバッテリ障害など'ストレージアレイのコンポーネントに障害が発生した
** **状態の変更**–状態が変更されたストレージアレイの要素。たとえば、ボリュームが最適ステータスに移行した場合や、コントローラがオフラインステータスに移行した場合などです。
** ** Internal **：ユーザの操作を必要としない内部コントローラ操作。たとえば、コントローラが一日の開始を完了した場合など。
** **コマンド**–ホットスペアが割り当てられているなど、ストレージアレイに対して発行されたコマンド。
** **エラー**–ストレージアレイでエラー状態が検出されました。たとえば、コントローラがキャッシュを同期およびパージできない、ストレージアレイで冗長性エラーが検出されたなどです。
** **一般**–他のカテゴリには適していないイベント。この情報を表示するには'[**列の選択**]アイコンをクリックします




 a| 
ログ元列
 a| 
イベントをログに記録したコントローラの名前。この情報を表示するには'[**列の選択**]アイコンをクリックします

|===
====
. ストレージアレイから新しいイベントを取得するには'[**更新**]をクリックします
+
イベントがログに記録され、[イベントログ]ページに表示されるまでに数分かかる場合があります。

. イベントログをファイルに保存するには、次の手順を実行します。
+
.. 保存する各イベントの横にあるチェックボックスをオンにします。
.. [ 保存（ Save ） ] をクリックします。
+
ブラウザのDownloadsフォルダに'major-event-log-timestamp.log'という名前でファイルが保存されます



. イベントログからイベントをクリアするには、次の手順を実行します
+
イベントログに約8、000個のイベントが格納されると、1つのイベントが新しいイベントに置き換えられます。イベントを保持する場合は、イベントを保存してイベントログからクリアできます。

+
.. まず、イベントログを保存します。
.. [すべてクリア]をクリックし、操作を実行することを確認します。



