---
permalink: sm-support/view-storage-array-profile.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, storage, array, profile 
summary: ストレージアレイプロファイルは、ストレージアレイのすべてのコンポーネントとプロパティの概要 を提供します。 
---
= SANtricity System Managerでストレージアレイのプロファイルを表示する
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイプロファイルは、ストレージアレイのすべてのコンポーネントとプロパティの概要 を提供します。

.このタスクについて
ストレージアレイプロファイルは、リカバリ時の補助として、またはストレージアレイの現在の構成の概要として使用できます。管理クライアントにストレージアレイプロファイルのコピーを保存して、ストレージアレイプロファイルのハードコピーをストレージアレイとともに保管することができます。構成を変更した場合は、ストレージアレイプロファイルの新しいコピーを作成してください。

.手順
. メニューを選択します。Support [サポートセンター]>[サポートリソース]タブ。
. 下にスクロールして「 Launch detailed storage array information 」 * と進み、「 * Storage Array Profile 」を選択します。
+
レポートが画面に表示されます。

+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| セクション | 説明 


 a| 
ストレージアレイ
 a| 
ストレージアレイについて設定可能なすべてのオプションとシステムの静的オプションが表示されます。コントローラ数、ドライブシェルフ数、ドライブ数、ディスクプール数、ボリュームグループ数などを指定できます。 ボリューム、およびホットスペアドライブ、使用可能なドライブシェルフ、ドライブ、ソリッドステートディスク（SSD）、およびボリュームの最大数、Snapshotグループ、Snapshotイメージ、Snapshotボリュームおよび整合性グループの数、機能に関する情報、ファームウェアバージョンに関する情報、シャーシのシリアル番号に関する情報、AutoSupport ステータスおよびAutoSupport スケジュール情報。 サポートデータの自動収集とサポートデータのスケジュール収集、ストレージアレイのWorld-Wide Identifier（WWID）、およびメディアスキャンとキャッシュの設定。



 a| 
ストレージ
 a| 
ストレージアレイ内のすべてのストレージデバイスのリストが表示されます。ストレージアレイの構成によっては、Storageセクションにこれらのサブセクションが表示される場合があります。

** *ディスク・プール*--ストレージ・アレイ内のすべてのディスク・プールのリストを表示します
** *ボリュームグループ*--ストレージアレイ内のすべてのボリュームグループのリストを表示しますボリュームと空き容量は作成順に表示されます。
** * Volumes *--ストレージアレイ内のすべてのボリュームのリストを表示します表示される情報には、ボリューム名、ボリュームステータス、容量、RAIDレベル、ボリュームグループまたはディスクプール、ドライブタイプ、およびその他の詳細があります。
** *見つからないボリューム*--ストレージアレイ内で現在ステータスが不明なすべてのボリュームのリストを表示します表示される情報には、見つからない各ボリュームのWorld Wide Identifier（WWID）があります。




 a| 
コピーサービス
 a| 
ストレージアレイに使用されるすべてのコピーサービスのリストが表示されます。ストレージアレイの構成によっては、Copy Servicesセクションに次のサブセクションが表示される場合があります。

** *ボリュームコピー*--ストレージアレイ内のすべてのコピーペアのリストを表示します表示される情報には、コピーの数、コピーペア名、ステータス、開始のタイムスタンプ、およびその他の詳細があります。
** *スナップショット・グループ*--ストレージ・アレイ内のすべてのスナップショット・グループのリストを表示します
** *スナップショット・イメージ*--ストレージ・アレイ内のすべてのスナップショットのリストを表示します
** *スナップショット・ボリューム*--ストレージ・アレイ内のすべてのスナップショット・ボリュームのリストを表示します
** *コンシステンシ・グループ*--ストレージ・アレイ内のすべてのコンシステンシ・グループのリストを表示します
** *メンバーボリューム*--ストレージアレイ内のすべてのコンシステンシグループメンバーボリュームのリストを表示します
** *ミラーグループ*--すべてのミラーボリュームのリストを表示します
** *リザーブ容量*-ストレージアレイ内のすべてのリザーブ容量ボリュームのリストが表示されます




 a| 
ホストの割り当て
 a| 
ストレージアレイにおけるホスト割り当てのリストが表示されます。表示される情報には、ボリューム名、論理ユニット番号（LUN）、コントローラID、ホスト名またはホストクラスタ名、およびボリュームステータスがあります。追加情報 の一覧には、トポロジの定義とホストタイプの定義が含まれています。



 a| 
ハードウェア
 a| 
ストレージアレイ内のすべてのハードウェアのリストが表示されます。ストレージアレイの構成によっては、「ハードウェア」セクションにこれらのサブセクションが表示される場合があります。

** *コントローラ*--ストレージアレイ内のすべてのコントローラのリストを表示しますコントローラの場所'ステータス'構成が含まれますまた、ドライブチャネル情報、ホストチャネル情報、イーサネットポート情報も含まれます。
** *ドライブ*--ストレージアレイ内のすべてのドライブのリストを表示しますドライブは、シェルフID、ドロワーID、スロットIDの順に表示されます。表示される情報には、シェルフID、ドロワーID、スロットID、ステータス、物理容量、 メディアタイプ、インターフェイスタイプ、現在のデータ速度、製品ID、および各ドライブのファームウェアバージョン。ドライブのセクションには、ドライブチャネル情報、ホットスペアの適用範囲情報、および摩耗度に関する情報も含まれます（SSDドライブの場合のみ）。寿命情報には、使用済み寿命の割合（これまでにSSDドライブに書き込まれたデータの量）と、ドライブの理論上の合計書き込み制限値を合わせた値が含まれます。
** *ドライブチャネル*--ストレージアレイ内のすべてのドライブチャネルの情報を表示します表示される情報には、チャネルステータス、リンクステータス（該当する場合）、ドライブの本数、および累積エラー数があります。
** * shelves *--ストレージアレイ内のすべてのシェルフの情報を表示します。表示される情報には、ドライブタイプおよびシェルフの各コンポーネントのステータス情報があります。シェルフコンポーネントには、バッテリパック、Small Form-factor Pluggable（SFP）トランシーバ、電源/ファンキャニスター、または入出力モジュール（IOM）キャニスターなどが含まれます。ストレージアレイでセキュリティキーを使用している場合は、Hardware（ハードウェア）セクションにセキュリティキー識別子も表示されます。




 a| 
の機能
 a| 
インストールされている機能パックのリスト、および1つのホストまたはホストクラスタで許可されているSnapshotグループ、Snapshot（従来のもの）、ボリュームの最大数が表示されます。機能セクションには、ドライブセキュリティ、つまりストレージアレイがセキュリティ有効かセキュリティ無効かについても記載されています。

|===
====
. ストレージアレイプロファイルを検索するには、検索キーワードを*検索*テキストボックスに入力し、*検索*をクリックします。
+
一致するすべてのキーワードが強調表示されます。すべての結果を一度に 1 つずつスクロールするには、 * 検索 * をクリックします。

. ストレージアレイプロファイルを保存するには、* Save *をクリックします。
+
ブラウザのDownloadsフォルダに「storage-array-profile.txt」という名前でファイルが保存されます。


