---
permalink: sm-support/what-type-of-data-is-collected-through-autosupport.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, data, collected, autosupport, ASUP 
summary: AutoSupport 機能には、標準のディスパッチタイプとして、イベントディスパッチ、スケジュールディスパッチ、オンデマンドディスパッチ、リモート診断ディスパッチの3つがあります。 
---
= AutoSupport 機能ではどのような種類のデータが収集されますか。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AutoSupport 機能には、標準のディスパッチタイプとして、イベントディスパッチ、スケジュールディスパッチ、オンデマンドディスパッチ、リモート診断ディスパッチの3つがあります。

AutoSupport データにユーザデータが含まれることはありません。

* *イベントディスパッチ*
+
テクニカルサポートへのプロアクティブな通知が設定されているシステムでイベントが発生すると、AutoSupport 機能によってイベントトリガー型ディスパッチが自動的に送信されます。

+
** 管理対象のストレージアレイでサポートイベントが発生したときに送信されます。
** イベント発生時のストレージアレイの状況を包括的に記録した情報が含まれます。


* *スケジュールディスパッチ*
+
AutoSupport 機能によって、複数のディスパッチが定期的に送信されます。

+
** *日次ディスパッチ*--ユーザーが設定可能な時間間隔内に毎日1回送信されます現在のシステムイベントログとパフォーマンスデータが含まれます。
** *週次ディスパッチ*--ユーザーが設定可能な時間間隔と日の間に毎週1回送信されます構成とシステムの状態の情報が含まれます。


* * AutoSupport OnDemandおよびRemote Diagnosticsディスパッチ*
+
** * AutoSupport OnDemand*--問題 のトラブルシューティングに必要なときに、テクニカルサポートが以前のAutoSupport ディスパッチの再送信を要求できるようにします。送信はすべて、AutoSupport サーバではなくストレージアレイから開始されます。ストレージアレイはAutoSupport サーバに定期的にコンタクトし、保留中の再送信要求がないかどうかをチェックし、適切に応答します。
** *リモート診断*--問題 のトラブルシューティングに必要な場合に、テクニカルサポートが最新のAutoSupport ディスパッチをリクエストできるようにします。送信はすべて、AutoSupport サーバではなくストレージアレイから開始されます。ストレージアレイはAutoSupport サーバに定期的にコンタクトし、保留中の新規要求がないかどうかをチェックし、適切に応答します。



