---
permalink: sm-support/what-does-unreadable-sectors-data-show-me.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, unreadable, sectors, 
summary: ストレージアレイのドライブで検出された読み取り不能セクターに関する詳細なデータを表示できます。 
---
= 読み取り不能セクターについて、どのようなデータが表示されますか？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイのドライブで検出された読み取り不能セクターに関する詳細なデータを表示できます。

読み取り不能セクターのログでは、最後に検出された読み取り不能セクターが最初に表示されます。ログには、読み取り不能セクターを含むボリュームに関する次の情報が記録されます。これらのフィールドはソートできます。

[cols="25h,~"]
|===
| フィールド | 説明 


 a| 
影響を受けるボリューム
 a| 
ボリュームのラベルが表示されます。見つからないボリュームに読み取り不能セクターが含まれている場合は、ボリュームのWorld Wide Identifierが表示されます。



 a| 
論理ユニット番号（LUN）
 a| 
ボリュームのLUNが表示されます。ボリュームにLUNがない場合は、「NA」と表示されます。



 a| 
割り当て先
 a| 
ボリュームにアクセスできるホストまたはホストクラスタが表示されます。ホスト、ホストクラスタ、またはデフォルトクラスタからボリュームにアクセスできない場合は、「NA」と表示されます。

|===
読み取り不能セクターに関する追加情報 を表示するには、ボリュームの横にあるプラス（+）記号をクリックします。

[cols="25h,~"]
|===
| フィールド | 説明 


 a| 
日付/時刻
 a| 
読み取り不能セクターが検出された日付と時刻が表示されます。



 a| 
ボリュームの論理ブロックアドレス
 a| 
ボリュームの論理ブロックアドレス（LBA）が表示されます。



 a| 
ドライブの場所
 a| 
ドライブシェルフ、ドロワー（ドライブシェルフにドロワーが搭載されている場合）、およびベイの場所が表示されます。



 a| 
ドライブの論理ブロックアドレス
 a| 
ドライブのLBAが表示されます。



 a| 
障害タイプ
 a| 
次のいずれかの障害タイプが表示されます。

* * Physical *--物理的なメディアエラー。
* *論理*--ストライプ内のどこかで読み取りエラーが発生し'データが読み取り不能になっていますたとえば、ボリューム内のどこかで発生したメディアエラーに起因する読み取り不能セクターなど。
* *不整合*--整合性のない冗長性データ。
* * Data Assurance *-- Data Assuranceエラー。


|===