---
permalink: um-certificates/access-management-with-saml.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, access management, saml 
summary: 管理者は、アレイに組み込みのSecurity Assertion Markup Language（SAML）2.0の機能をアクセス管理に使用できます。 
---
= SAMLを使用したアクセス管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
管理者は、アレイに組み込みのSecurity Assertion Markup Language（SAML）2.0の機能をアクセス管理に使用できます。



== 設定ワークフロー

SAMLの設定は次のように行います。

. Security Adminの権限を含むユーザプロファイルでUnified Managerにログインします。
+
[NOTE]
====
adminユーザはSystem Managerのすべての機能にフル・アクセスできます

====
. 管理者は、[アクセス管理]の下の[*SAML *]タブに移動します。
. アイデンティティプロバイダ（IdP）との通信を設定します。IdPは、ユーザにクレデンシャルを要求して認証されたユーザかどうかを確認するための外部システムです。ストレージアレイとの通信を設定するには、IdPシステムからIdPメタデータファイルをダウンロードし、Unified Managerを使用してそのファイルをストレージアレイにアップロードします。
. サービスプロバイダとIdP間の信頼関係を確立します。サービスプロバイダはユーザ権限を制御します。このケースでは、ストレージアレイ内のコントローラがサービスプロバイダの役割を果たします。通信を設定するために、管理者はUnified Managerを使用してコントローラのサービスプロバイダメタデータファイルをエクスポートします。次に、IdPシステムからメタデータファイルをIdPにインポートします。
+
[NOTE]
====
また、認証時に名前IDを返す機能がIdPでサポートされていることを確認しておく必要があります。

====
. ストレージアレイのロールをIdPで定義されているユーザ属性にマッピングします。そのためには、管理者はUnified Managerを使用してマッピングを作成します。
. IdP URLへのSSOログインをテストします。このテストで、ストレージアレイとIdPが通信できることを確認します。
+
[CAUTION]
====
SAMLを有効にすると、ユーザインターフェイスで無効にしたり、IdP設定を編集したりすることはできなくなります。SAMLの設定を無効にしたり編集したりする必要がある場合は、テクニカルサポートにお問い合わせください。

====
. Unified Managerで、ストレージアレイのSAMLを有効にします。
. ユーザが自身のSSOクレデンシャルを使用してシステムにログインします。




== 管理

認証にSAMLを使用している場合、管理者は次の管理タスクを実行できます。

* 新しいロールマッピングを変更または作成します
* サービスプロバイダファイルをエクスポート




== アクセス制限

SAMLが有効な場合、ユーザは従来のStorage Managerインターフェイスからそのアレイのストレージを検出または管理できません。

また、次のクライアントはストレージアレイのサービスとリソースにアクセスできません。

* Enterprise Management Window（EMW）
* コマンドラインインターフェイス（ CLI ）
* ソフトウェア開発キット（SDK）クライアント
* インバンドクライアント
* HTTPベーシック認証REST APIクライアント
* 標準のREST APIエンドポイントを使用してログインします

