---
permalink: um-certificates/change-local-user-passwords-settings-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, change, local, user, password, settings 
summary: すべての新規または更新されるローカルユーザパスワードの最小文字数を設定できます。また、ローカルユーザがパスワードを入力せずにシステムにアクセスできるようにすることもできます。 
---
= ローカルユーザパスワードの設定を変更します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
すべての新規または更新されるローカルユーザパスワードの最小文字数を設定できます。また、ローカルユーザがパスワードを入力せずにシステムにアクセスできるようにすることもできます。

.作業を開始する前に
Root Adminの権限が割り当てられたローカル管理者としてログインする必要があります。

.このタスクについて
ローカルユーザパスワードの最小文字数を設定する際には、次のガイドラインに注意してください。

* 設定を変更しても既存のローカルユーザパスワードには影響しません。
* ローカルユーザパスワードの最小文字数は、0~30文字にする必要があります。
* 新しいローカルユーザパスワードは、現在の最小文字数の設定以上にする必要があります。
* ローカルユーザがパスワードを入力せずにシステムにアクセスできるようにする場合は、パスワードの最小文字数を設定しないでください。


.手順
. アクセス管理*を選択します。
. [ローカルユーザー役割*（Local User Roles *）]タブを選択します。
. 「*表示/設定の編集*」を選択します。
+
[ローカルユーザーパスワードの設定]ダイアログボックスが開きます。

. 次のいずれかを実行します。
+
** ローカルユーザがパスワードを入力せずにsystem_に アクセスできるようにするには、「すべてのローカルユーザパスワードを最低必要とする」チェックボックスをオフにします。
** すべてのローカルユーザパスワードの最小文字数を設定するには、「すべてのローカルユーザパスワードを少なくとも必要とする」チェックボックスを選択し、スピンボックスを使用してすべてのローカルユーザパスワードの最小文字数を設定します。
+
新しいローカルユーザパスワードは、現在の設定以上の長さにする必要があります。



. [ 保存（ Save ） ] をクリックします。

