---
permalink: um-certificates/edit-directory-server-settings-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, edit, directory, server, settings, role, mappings 
summary: アクセス管理でディレクトリサーバを設定済みの場合は、いつでも設定を変更できます。設定には、サーバ接続情報とグループとロールのマッピングが含まれます。 
---
= ディレクトリサーバ設定とロールマッピングを編集します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アクセス管理でディレクトリサーバを設定済みの場合は、いつでも設定を変更できます。設定には、サーバ接続情報とグループとロールのマッピングが含まれます。

.作業を開始する前に
* Security Adminの権限を含むユーザプロファイルでログインする必要があります。そうしないと、アクセス管理機能は表示されません。
* ディレクトリサーバが定義されている必要があります。


.手順
. アクセス管理*を選択します。
. [*ディレクトリサービス*]タブを選択します。
. 複数のサーバが定義されている場合は、編集するサーバを表から選択します。
. 「*表示/設定の編集*」を選択します。
+
[ディレクトリサーバーの設定]ダイアログボックスが開きます。

. サーバー設定*タブで、必要な設定を変更します。
+
.フィールドの詳細
====
[cols="25h,~"]
|===
| 設定 | 説明 


 a| 
*構成設定*



 a| 
ドメイン
 a| 
LDAPサーバのドメイン名。ドメインを複数入力する場合は、カンマで区切って入力します。ドメイン名は、ログイン（_username_@_domain_）で、認証するディレクトリサーバを指定するために使用されます。



 a| 
サーバURL
 a| 
LDAPサーバにアクセスするためのURL。形式はです `ldap[s]://host:port`。



 a| 
バインドアカウント（オプション）
 a| 
LDAPサーバに対する検索クエリやグループ内の検索で使用する読み取り専用のユーザアカウント。



 a| 
バインドパスワード（オプション）
 a| 
バインドアカウントのパスワード（このフィールドはバインドアカウントを入力した場合に表示されます）。



 a| 
保存する前にサーバ接続をテストします
 a| 
システムがLDAPサーバの設定と通信できることを確認します。[保存（Save）]をクリックすると、テストが実行されます。このチェックボックスをオンにした場合、テストに失敗すると設定は変更されません。設定を編集するには、エラーを解決するか、チェックボックスを選択解除してテストをスキップする必要があります。



 a| 
*権限の設定*



 a| 
検索ベースDN
 a| 
ユーザを検索するLDAPコンテキスト。通常は、の形式です `CN=Users, DC=cpoc, DC=local`。



 a| 
ユーザー名属性
 a| 
認証用のユーザIDにバインドされた属性。例:「sAMAccountName」。



 a| 
グループ属性
 a| 
グループとロールのマッピングに使用される、ユーザのグループ属性のリスト。例: memberOf, managedObjects`

|===
====
. [*役割マッピング*]タブで、目的のマッピングを変更します。
+
.フィールドの詳細
====
[cols="25h,~"]
|===
| 設定 | 説明 


 a| 
*マッピング*



 a| 
グループDN
 a| 
マッピングするLDAPユーザグループのドメイン名。正規表現がサポートされます。正規表現パターンに含まれていない特殊な正規表現文字は、バックスラッシュ（\）でエスケープする必要があります。

\.[]{}()<>*+-=！？^$|



 a| 
ロール
 a| 
グループDNにマッピングするロール。このグループに含めるロールを個別に選択する必要があります。MonitorロールはSANtricity Unified Managerにログインするため必要なロールであり、他のロールと一緒に指定する必要があります。ロールには次のものがあります。

** * Storage admin *--アレイ上のストレージ・オブジェクトへの読み取り/書き込みのフル・アクセスを提供しますが'セキュリティ構成へのアクセスはありません
** * Security admin *--アクセス管理と証明書管理のセキュリティ設定へのアクセス。
** * Support admin *--ストレージアレイ上のすべてのハードウェアリソース、障害データ、およびMELイベントへのアクセス。ストレージオブジェクトやセキュリティ設定にはアクセスできません。
** *Monitor *--すべてのストレージオブジェクトへの読み取り専用アクセスが可能ですが、セキュリティ設定へのアクセスはありません。


|===
====
+

NOTE: Monitorロールは、管理者を含むすべてのユーザに必要です。

. 必要に応じて、*別のマッピングを追加*をクリックして、グループとロールのマッピングをさらに入力します。
. [ 保存（ Save ） ] をクリックします。


このタスクを完了すると、アクティブなユーザセッションはすべて終了します。現在のユーザセッションのみが保持されます。
