---
permalink: um-certificates/how-access-management-works-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, authentication, users, roles, access management 
summary: アクセス管理を使用してSANtricity Unified Managerでのユーザ認証を確立する。 
---
= アクセス管理の仕組み
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アクセス管理を使用してSANtricity Unified Managerでのユーザ認証を確立する。



== 設定ワークフロー

アクセス管理の設定は次のように行います。

. Security Adminの権限を含むユーザプロファイルでUnified Managerにログインします。
+
[NOTE]
====
初めてのログインでは'ユーザ名adminが自動的に表示され'変更することはできませんadminユーザは'システムのすべての機能にフル・アクセスできます初回ログイン時にパスワードを設定する必要があります。

====
. ユーザインターフェイスでアクセス管理に移動します。事前に設定されているローカルユーザロールが表示されます。これらのロールはRBAC（ロールベースアクセス制御）機能の実装です。
. 管理者は、次の認証方式を1つ以上設定します。
+
** *ローカルユーザーの役割*-- RBAC機能を使用して認証を管理しますローカルユーザロールには、事前定義されたユーザと、特定のアクセス権限を持つロールが含まれます。管理者は、これらのローカルユーザロールを単一の認証方式として使用することも、ディレクトリサービスと組み合わせて使用することもできます。ユーザのパスワードを設定する以外に必要な設定はありません。
** *ディレクトリサービス*-- LDAP (Lightweight Directory Access Protocol)サーバとディレクトリサービス(MicrosoftのActive Directoryなど)を介して認証を管理します管理者がLDAPサーバに接続し、ローカルユーザロールにLDAPユーザをマッピングします。
** *saml *-- Security Assertion Markup Language（SAML）2.0を使用してアイデンティティプロバイダ（IdP）を介して認証を管理します。管理者がIdPシステムとストレージアレイの間の通信を確立し、ストレージアレイに組み込まれているローカルユーザロールにIdPユーザをマッピングします。


. Unified Managerのログインクレデンシャルをユーザに割り当てます。
. ユーザが自身のクレデンシャルを入力してシステムにログインします。ログイン時には、次のバックグラウンドタスクが実行されます。
+
** ユーザ名とパスワードをユーザアカウントと照合して認証します。
** 割り当てられたロールに基づいてユーザの権限が決まります。
** ユーザインターフェイスの機能にユーザがアクセスできるようにします。
** 上部のバナーにユーザ名が表示されます。






== Unified Managerで使用できる機能

機能へのアクセスは、ユーザに割り当てられたロールによって次のように異なります。

* * Storage admin *--アレイ上のストレージ・オブジェクトへの読み取り/書き込みのフル・アクセスを提供しますが'セキュリティ構成へのアクセスはありません
* * Security admin *--アクセス管理と証明書管理のセキュリティ設定へのアクセス。
* * Support admin *--ストレージアレイ上のすべてのハードウェアリソース、障害データ、およびMELイベントへのアクセス。ストレージオブジェクトやセキュリティ設定にはアクセスできません。
* *Monitor *--すべてのストレージオブジェクトへの読み取り専用アクセスが可能ですが、セキュリティ設定へのアクセスはありません。


使用できない機能は、ユーザインターフェイスではグレー表示されるか、非表示になります。
