---
permalink: um-certificates/overview-access-management-um.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, access management, authentication 
summary: アクセス管理では、SANtricity Unified Managerでユーザ認証を設定することができます。 
---
= アクセス管理の概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アクセス管理では、Unified Managerでユーザ認証を設定することができます。



== どのような認証方式を使用できますか。

次の認証方式を使用できます。

* *ローカルユーザーの役割*-- RBAC（役割ベースのアクセス制御）機能を使用して認証を管理しますローカルユーザロールには、事前定義されたユーザプロファイルと、特定のアクセス権限を持つロールが含まれます。
* *ディレクトリサービス*-- LDAP (Lightweight Directory Access Protocol)サーバとディレクトリサービス(MicrosoftのActive Directoryなど)を介して認証を管理します


詳細はこちら。

* link:how-access-management-works-unified.html["アクセス管理の仕組み"]
* link:access-management-terminology-unified.html["アクセス管理の用語"]
* link:permissions-for-mapped-roles-unified.html["マッピングされたロールの権限"]




== アクセス管理を設定するにはどうすればよいですか。

SANtricity ソフトウェアは、ローカルユーザロールを使用するように事前に設定されています。LDAPを使用する場合は、[Access Management]ページでLDAPを設定できます。

詳細はこちら。

* link:access-management-with-local-user-roles-unified.html["ローカルユーザロールを使用したアクセス管理"]
* link:access-management-with-directory-services-unified.html["ディレクトリサービスを使用したアクセス管理"]

