---
permalink: um-certificates/use-ca-signed-certificate-um.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, ca-signed, certificates 
summary: Unified Managerをホストする管理システムへのセキュアなアクセスを確立するために、CA署名証明書を取得してインポートできます。 
---
= 管理システムのCA署名証明書を使用します
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Managerをホストする管理システムへのセキュアなアクセスを確立するために、CA署名証明書を取得してインポートできます。

Security Adminの権限を含むユーザプロファイルでログインする必要があります。そうしないと、証明書の機能は表示されません。

CA署名証明書の使用は、3つの手順で構成される手順 です。



== 手順1：CSRファイルを作成します

最初に証明書署名要求（CSR）ファイルを生成する必要があります。これにより、Web Services ProxyとUnified Managerがインストールされている組織とホストシステムが特定されます。

[NOTE]
====
または、OpenSSLなどのツールを使用してCSRファイルを生成し、に進みます  2: Submit CSR file。

====
.手順
. [証明書管理]を選択します。
. [管理]タブで、[* CSR全体*]を選択します。
. 次の情報を入力し、[次へ*]をクリックします。
+
** *組織*--会社または組織の正式名称。Inc.やCorp.などの接尾辞も含めて入力してください
** *組織単位（オプション）*--証明書を処理している組織の部門。
** *市区町村*--ホストシステムまたは事業の所在地である市区町村。
** *都道府県(オプション)*--ホストシステムまたは事業の所在地である都道府県。
** *国のISOコード*--自国を表す2桁のISO（国際標準化機構）コード（USなど）。


. Web Services Proxyがインストールされているホストシステムに関する次の情報を入力します。
+
** *共通名*-- WebサービスプロキシがインストールされているホストシステムのIPアドレスまたはDNS名。このアドレスが正しいことを確認してください。ブラウザでUnified Managerにアクセスする際に入力したアドレスと正確に一致している必要があります。http：//またはhttps：//を含めないでください。DNS名の先頭にワイルドカードを使用することはできません。
** *代替IPアドレス*--共通名がIPアドレスの場合は'オプションでホストシステムの追加のIPアドレスまたはエイリアスを入力できます複数指定する場合は、カンマで区切って入力します。
** *代替DNS名*--共通名がDNS名の場合は'ホストシステムの追加のDNS名を入力します複数指定する場合は、カンマで区切って入力します。代替DNS名がない場合は、最初のフィールドに入力したDNS名をここにコピーします。DNS名の先頭にワイルドカードを使用することはできません。


. ホスト情報が正しいことを確認します。証明書が含まれていないと、CAから返された証明書をインポートしようとしたときに失敗します。
. [ 完了 ] をクリックします。
. に進みます  2: Submit CSR file。




== 手順2：CSRファイルを送信する

証明書署名要求（CSR）ファイルを作成したら、そのファイルを認証局（CA）に送信して、Unified ManagerとWebサービスプロキシをホストするシステムの署名付き管理証明書を受け取ります。


NOTE: Eシリーズシステムには、署名済み証明書用のPEM形式（Base64 ASCIIエンコード）が必要です。これには、.pem、.crt、.cer、.keyのいずれかのファイルタイプが含まれます。

.手順
. ダウンロードしたCSRファイルの場所を確認します。
+
ダウンロードフォルダの場所は、ブラウザによって異なります。

. CSRファイルをCA（VerisignやDigiCertなど）に送信し、PEM形式の署名付き証明書を要求します。
+
[CAUTION]
====
* CSRファイルをCAに送信した後、別のCSRファイルを再生成しないでください。* CSRを生成するたびに、システムは秘密鍵と公開鍵のペアを作成します。公開鍵はCSRの一部であり、秘密鍵はシステムのキーストアに保持されます。署名済み証明書を受け取ってインポートすると、秘密鍵と公開鍵の両方が元のペアになります。キーが一致しないと署名済み証明書は機能せず、CAに新しい証明書を要求する必要があります。

====
. CAから返された署名済み証明書については、を参照してください  3: Import management certificates。




== 手順3：管理証明書をインポートする

認証局（CA）から署名入りの証明書を受け取ったら、Web Services ProxyとUnified Managerインターフェイスがインストールされているホストシステムに証明書をインポートします。

.作業を開始する前に
* 署名済みの証明書をCAから受け取っておきます。これらのファイルには、ルート証明書、1つ以上の中間証明書、およびサーバ証明書が含まれます。
* CAからチェーン証明書ファイル（たとえば、.p7bファイル）が提供された場合は、チェーンファイルを個々のファイル（ルート証明書、1つ以上の中間証明書、サーバ証明書）に展開する必要があります。Windowsのcertmgrユーティリティーを使用して'ファイルを展開できます(右クリックしてメニューを選択しますすべてのタスク[エクスポート])base-64エンコーディングが推奨されます。エクスポートが完了すると、チェーン内の証明書ファイルごとに1つのCERファイルが表示されます。
* 証明書ファイルをWebサービスプロキシが実行されているホストシステムにコピーしておきます。


.手順
. [証明書管理]を選択します。
. [管理（Management）]タブで、[*インポート（* Import）]を選択する
+
証明書ファイルをインポートするためのダイアログボックスが表示されます。

. [*Browse*]をクリックして、最初にルート証明書ファイルと中間証明書ファイルを選択し、次にサーバ証明書を選択します。外部ツールからCSRを生成した場合は、CSRと一緒に作成された秘密鍵ファイルもインポートする必要があります。
+
ファイル名がダイアログボックスに表示されます。

. [* インポート * ] をクリックします。


ファイルがアップロードされて検証されます。証明書の情報は、証明書の管理ページに表示されます。
