---
permalink: um-admin/administrator-password-protection-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, administrator, password, protection 
summary: SANtricity Unified Managerには、不正なアクセスを防ぐために管理者パスワードを設定する必要があります。 
---
= 管理者パスワード保護を設定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SANtricity Unified Managerには、不正なアクセスを防ぐために管理者パスワードを設定する必要があります。



== 管理パスワードとユーザプロファイル

Unified Managerを初めて起動したときは、管理者パスワードの設定を求めるプロンプトが表示されます。管理者パスワードを持つユーザは、ストレージアレイの設定を変更できます。

Unified Managerインターフェイスには、adminパスワードのほかに、1つ以上のロールがマッピングされたユーザプロファイルが事前に設定されています。詳細については、を参照してください link:../um-certificates/how-access-management-works-unified.html["アクセス管理の仕組み"]。

ユーザとマッピングは変更できません。変更できるのはパスワードだけです。パスワードを変更するには、以下を参照してください

* link:change-admin-password-unified.html["adminパスワードを変更"]
* link:../um-certificates/change-passwords-unified.html["ローカルユーザプロファイルのパスワードを変更します"]




== セッションタイムアウト

1つの管理セッションでパスワードの入力を求められるのは1回のみです。デフォルトでは操作がない状態が30分続くとセッションがタイムアウトし、パスワードをもう一度入力する必要があります。セッション中に別の管理クライアントから同じソフトウェアにアクセスしている別のユーザがパスワードを変更した場合は、次回の設定処理や表示処理でパスワードの入力を求められます。

セキュリティ上の理由から、パスワードの入力を試行できるのは5回までとなっており、この回数を超えると、ソフトウェアは「ロックアウト」状態になります。この状態では、ソフトウェアはその後のパスワード入力を拒否します。パスワードを再度入力するには、「通常」状態にリセットされるまで10分待つ必要があります。

セッションタイムアウトを調整したり、セッションタイムアウトを無効にしたりできます。詳細については、を参照してください link:manage-session-timeouts-unified.html["セッションタイムアウトの管理"]。
