---
permalink: um-admin/overview-interface-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, interface, GUI 
summary: Unified ManagerはWebベースのインターフェイスであり、1つのビューで複数のストレージアレイを管理することができます。 
---
= SANtricity Unified Managerについて学ぶ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SANtricity Unified Managerは、複数のストレージアレイを1つのビューで管理できるWebベースのインターフェイスです。



== メインページ

Unified Managerにログインすると、メインページが開き、* Manage-All *が表示されます。このページから、ネットワーク内で検出されたストレージアレイのリストをスクロールして、そのステータスを表示し、1つのアレイまたはアレイグループに対して処理を実行できます。



== ナビゲーションサイドバー

Unified Managerの機能には、ナビゲーションサイドバーからアクセスできます。

[cols="25h,~"]
|===
| 面積（ Area ） | 説明 


 a| 
管理
 a| 
ネットワーク内のストレージアレイを検出し、アレイのSANtricity System Managerを起動し、1つのアレイから複数のアレイに設定をインポートし、アレイグループを管理します。アレイ名の横にあるチェックボックスを選択すると、設定のインポートやアレイグループの作成など、アレイに対して操作を実行できます。各行の末尾にある省略記号は、名前変更など、単一のアレイに対する操作を行うためのインラインメニューです。



 a| 
処理
 a| 
あるアレイから別のアレイへの設定のインポートなど、バッチ処理の進捗状況を表示します。

[NOTE]
====
ストレージアレイのステータスが最適でない場合は、一部の処理は使用できません。

====


 a| 
証明書管理
 a| 
ブラウザとクライアントの間で認証する証明書を管理します。



 a| 
アクセス管理
 a| 
Unified Managerインターフェイスのユーザ認証を確立します。



 a| 
サポート
 a| 
テクニカルサポートのオプション、リソース、および連絡先を表示します。

|===


== インターフェイスの設定とヘルプ

インターフェイスの右上にあるヘルプやその他のドキュメントにアクセスできます。ログイン名の横にあるドロップダウンから管理オプションにアクセスすることもできます。



== ユーザログインとパスワード

現在システムにログインしているユーザーは、ユーザー設定に表示されます。

ユーザとパスワードの詳細については、次の項を参照してください。

* link:administrator-password-protection-unified.html["管理者パスワード保護を設定します"]
* link:change-admin-password-unified.html["adminパスワードを変更"]
* link:../um-certificates/change-passwords-unified.html["ローカルユーザプロファイルのパスワードを変更します"]

